### ISSUE TITLE
Drop 32-bit builds on Windows?

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#1002]
* gevent version: 1.3
* Python version: All
* Operating System: Windows

We've never provided 32-bit manylinux wheels. Our OS X wheels have been a mix of universal and 64-bit only (depending on whether there was a working python.org installer available).

Are 32-bit wheels still relevant on Windows in late 2017?

**Comment by schlenk** [comment]
Yes. Unlike Linux and OS X that aggressively removed 32-Bit runtimes from the default installation, it is still quite common to have 32-Bit processes on windows. Even VisualStudio is still a 32-Bit application...
