### ISSUE TITLE
AssertionError: assert tlock is not None

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#1004]
* gevent version: 1.3
* Python version: PyPy3 5.8.0
* Operating System: OS X

### Description:

Under the noted version of Python, I can sometimes get the described error. In particular, test_threading_2 can produce it:
```
test_3_join_in_forked_from_thread (__main__.ThreadJoinOnShutdown) ... Exception ignored in: threading._shutdown()
Traceback (most recent call last):
  File "/pypy3-v5.8.0-src/lib-python/3/threading.py", line 1282, in _shutdown
    assert tlock is not None
AssertionError
```

CPython 3.5 has identical code in `_shutdown` so I'm not entirely clear on what the difference might be. I know we started expecting callbacks from the VM in CPython 3.4, and I also know that PyPy2 has needed more sensitive handling of existing threads at monkey-patch time.

I'm not super worried about this since it's done during interpreter shutdown, and it's also being done by a beta of PyPy. I can look into it more if there's an actual issue reported, and/or when PyPy3 reaches a final state.

**Comment by thedrow** [comment]
FYI PyPy3 is not GA.

**Comment by jamadden** [comment]
I haven't been able to reproduce this with pypy3 5.10.1.
