### ISSUE TITLE
Redis blocked after patch_socket

### ISSUE THREAD

**Issue by Yougoss** [gevent/gevent#1010]
* gevent version: 1.2.1
* Python version: 2.7.10
* Operating System: Linux

### Description:

After I run patch_socket, I want to import Redis object from aother module which I use info() method to confirm redis connection. But it's blocking at redis build a connection to  socket. I don't know why.

main.py

```
from gevent.monkey import patch_socket; patch_socket()
from test import r
print r.info()
print 'main end'
````
test.py
```
import redis
r = redis.StrictRedis(host='127.0.0.1', port=2301, db=0)
print r.info()   # <==block here 
print 'import end'
```

**Comment by jamadden** [comment]
I can't produce any "block" with this code running a local redis server with the current versions of redis (server and client) and gevent:
```
$ python main.py
{'redis_git_dirty':...}
import end
{'redis_git_dirty':...}
main end
```

Can you be more specific about what you're seeing? What traceback do you get if you interrupt the process while it's hung?

**Comment by Yougoss** [comment]
I'm sorry to reply so late. 
I use pycharm5.0.4 as my IDE.
I found when I run the code, it seems ok.But when I debug the code, it blocks.
The console only shows:
`
pydev debugger: process 27041 is connecting

Connected to pydev debugger (build 143.1919)
`

**Comment by jamadden** [comment]
In general, this is not the place to ask for help with your IDE. You might try your IDE's support or the mailing list.

However, in this particular case, someone already posted a comment related to this that you'll find if you search the issues: [make sure the 'gevent' box is checked in the debugger settings](https://github.com/gevent/gevent/issues/804#issuecomment-294375907).

**Comment by Yougoss** [comment]
Thank you very much. At first, I didn't find this problem is related to IDE. I will check the problem more carefully next time
