### ISSUE TITLE
SSLContext infinite recursion in Python 3.6

### ISSUE THREAD

**Issue by Teyras** [gevent/gevent#1016]
On Python 3.6.2 and gevent 1.2.2, I encounter the problem described in #903 . I do not have the rights to reopen the issue, which is why I'm making a duplicate.

**Comment by jamadden** [comment]
Can you please post a failing example and its output?

**Comment by Teyras** [comment]
The code:

```
import gevent
from gevent import monkey
import requests

monkey.patch_all()
from requests.packages.urllib3.util.ssl_ import create_urllib3_context
create_urllib3_context()
```
The output:
```
Traceback (most recent call last):                                                        
  File "gevent_requests.py", line 7, in <module>                                          
    create_urllib3_context()
  File "/usr/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 269, in create_urllib
3_context             
    context.options |= options
  File "/usr/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)                            
  File "/usr/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 329 more times]    
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by jamadden** [comment]
Thanks. The problem is that you're importing `requests` *before* you monkey patch. [You must monkey patch](http://www.gevent.org/gevent.monkey.html#patching) before [importing anything else](http://www.gevent.org/intro.html#monkey-patching). I can reproduce this if I patch in the incorrect order, but if I patch in the correct order it works as expected:
```pycon
Python 3.6.2 (default, Jul 18 2017, 14:08:57)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent.monkey
>>> gevent.monkey.patch_all()
>>> from requests.packages.urllib3.util.ssl_ import create_urllib3_context
>>> create_urllib3_context()
<gevent._ssl3.SSLContext object at 0x1013c2228>
```

**Comment by Teyras** [comment]
Yes, that seems to be the problem - after fixing the order, everything is fine. I'm sorry for bothering you with this, I just googled the exception, found the issue I referenced and thought this must be the problem.

**Comment by jamadden** [comment]
No worries. I will add a warning to gevent to make this more clear.

**Comment by wumpus** [comment]
Thank you for the warning! Excellent way to point out coding errors.

**Comment by garyo** [comment]
Is there a recommended way to initialize gevent with gunicorn to avoid this warning? I'm using Flask with gunicorn as server and gevent with websockets. I tried doing `monkey.patch_all()` in the gunicorn.conf.py in `post_fork`, but still get the warning.

**Comment by jamadden** [comment]
I feel this has been said other places, but I personally monkey-patch before using gunicorn, in the initial boot script.

**Comment by garyo** [comment]
So, you suggest starting gunicorn not on the command line but from a python module? And do the monkey-patching there? (Sorry to be obtuse, I'm just learning gunicorn -- only need to use it because I'm doing websockets in flask.)

**Comment by jamadden** [comment]
Well, no. We use a setuptools entry point that wraps th gunicorn entry point. But it’s application specific.

**Comment by aventurella** [comment]
Is there anywhere else I could look that might cause this?

This here are the first few lines of my main.py:
```
1 print("Main Loading!")
2 import gevent
3 from gevent import monkey
4 monkey.patch_all()
5 print("Gevent Patched!")
6
7 from typing import Iterable, Optional, List
```

Here's what I see in my logs:

```
/var/task/main.py:4: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016
```

I am running this on the AWS Lambda `python3.6` runtime

I cannot for the life of me understand how I can possibly import and patch any earlier than lines 2-4 (effectively line 1-3 as I dropped those `print's` in to see where it was happening)

**Comment by yw94** [comment]
14/5000
You can try to swap the import order of the modules.

**Comment by yw94** [comment]
You can try to swap the import order of the modules.

**Comment by dvf** [comment]
Any chance we can re-open this?
