### ISSUE TITLE
get data from gevent queue raise empty error occasionally, in fact there is one item left in the queue

### ISSUE THREAD

**Issue by yinzhixin** [gevent/gevent#1017]
* gevent version: 1.2.1
* Python version: 2.7.13
* Operating System: centOS6.5

### Description:
First of all，sorry for my terrible english！

I made a queue with maxsize and the same count greent to get data, but when greenlet get the last item in the queue, an empty error raised. I have checked the queue size by using qszie() method, the queue size is 1. I have made a 3 times retry, but the same result I got. 
Is the method I used wrong or anything else，please help me ，much appreciate！

### What I've run:
The code：

```python

        try:
            data = self.queue.get_nowait()
        except:
            retry = 0
            while retry < 3:
                try:
                    retry += 1
                    data = self.queue.get(timeout=5)
                    return data
                except:
                    if retry == 3:
                        data = None
                        self.logger.error("Get data error after 3 times retry:", exc_info=True)
        return data
```
The traceback：
```
2017-09-14 15:34:27,666 ERROR  Get data error after 3 times retry:
Traceback (most recent call last):
  File "/path/to/the/file.py", line 215, in get_data
    data = self.queue.get(timeout=5)
  File "//python2.7/site-packages/gevent/queue.py", line 284, in get
    return self.__get_or_peek(self._get, block, timeout)
  File "/python2.7/site-packages/gevent/queue.py", line 261, in __get_or_peek
    result = waiter.get()
  File "//python2.7/site-packages/gevent/hub.py", line 899, in get
    return self.hub.switch()
  File "//python2.7/site-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
Empty
```

**Comment by jamadden** [comment]
In the traceback, we can see `queue.get` calling into `queue.__get_or_peek`, meaning that at the time of the call the queue was *definitely* empty. If no other greenlet added data to the queue while this one was sleeping, we would expect that exception. We would also expect that exception if a greenlet added data but some other greenlet *also* called `queue.get` or `queue.get_nowait` while this greenlet was sleeping---in other words, a race condition. Do you have multiple greenlets operating on this queue like this? If so, that's likely the problem.

If that doesn't answer your question, then can you post a complete, minimal, runnable example? This snippet is not enough to tell me what's going on.

**Comment by yinzhixin** [comment]
I have multiple greenlets operating on the queue，my situation is that the main process put all data into the queue，when finished，I will start multiple greenlets to get data from the queue.Most of time, the program run properly, errors are rare. when error occured,  it's always meet the Empty error for the last data in the queue, that's wierd. Maybe it's a race condition as you said，I will check and optimiz my program again and Do you have any good idea about how to avoid this problem?

**Comment by jamadden** [comment]
That sure sounds like a race condition to me.

> Do you have any good idea about how to avoid this problem?
If, as you say all the data is in the queue before you ever begin consuming it, it should be very easy to avoid.  You know no data is ever going to be arriving, so as soon as the queue is empty, you're done.
