### ISSUE TITLE
Can't debug in py3.6 with Pycharm

### ISSUE THREAD

**Issue by 631068264** [gevent/gevent#1026]
* gevent version:1.2.2
* Python version:3.6
* Operating System: OSX

### Description:

```
/Users/wyx/bitcoin_workspace/fibo-web-data/.env/bin/python3.6 /Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 61532 --file /Users/wyx/bitcoin_workspace/fibo-web-data/test/t_tele.py
pydev debugger: process 18611 is connecting

Connected to pydev debugger (build 172.3968.37)
Exception ignored in: '_pydevd_frame_eval.pydevd_frame_evaluator.get_bytecode_while_frame_eval'
RecursionError: maximum recursion depth exceeded while calling a Python object

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

### What I've run:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-


from gevent import monkey

monkey.patch_all()


some other code have been annotation
```

When I **just** run the code I **without** any about gevent it can run smoothly.So I think it has some bug in gevent.

**Comment by jamadden** [comment]
Thanks for your report, but I don't see how this could be a gevent bug. gevent knows nothing about debuggers of any kind, and that exception is coming from pycharm's cython code for its debugger. I know that code was newly changed to take advantage of new APIs in CPython 3.6, so perhaps it's not well tested with greenlets or gevent.

There is [a special setting](https://github.com/gevent/gevent/issues/804#issuecomment-294375907) you have to turn on in pycharm to work with gevent.  Please make sure that's on, and if you still have problems, please contact pycharm support. In the meantime, there's always `pdb`.
