### ISSUE TITLE
Command "/usr/local/bin/python2.7 -c "import setuptools, tokenize;__file__='/root/src/gevent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code -9 in /root/src/gevent/

### ISSUE THREAD

**Issue by hd999ljh** [gevent/gevent#1027]
* gevent version:
* Python version:2.7.14
* Operating System:Centos 6 32Bit

### Description:

I am trying to install gevent.then this error appears:
```
Command "/usr/local/bin/python2.7 -c "import setuptools, tokenize;__file__='/root/src/gevent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code -9 in /root/src/gevent/

```

### What I've run:

```
pip install cython -e git://github.com/surfly/gevent.git@1.0rc2#egg=gevent
```

**Comment by jamadden** [comment]
1.0rc2 is a very old version and it is not supported. Please install something more recent.

**Comment by hd999ljh** [comment]
thanks! i'll have a try.

**Comment by jamadden** [comment]
Unless you specifically want a development version, 'pip install gevent' should get the latest pre-built wheel from PyPI. If you are trying to install a development version, you should [follow the instructions under 'Development'](https://pypi.python.org/pypi/gevent).

**Comment by hd999ljh** [comment]
Thank you again for the rapid response! But I used easy_install to install it successfully.
