### ISSUE TITLE
Gevent hangs while launching a process using subprocess

### ISSUE THREAD

**Issue by kandrumounika** [gevent/gevent#1031]
* gevent version: 1.2
* Python version: 2.7
* Operating System: Ubuntu 16.04

### Description:

I have a dictionary with 2000 key value pair key as URL of application and value as command to execute test case of application.

I need to execute those in parallel by using gevent threads and launching test cases command by using sub-process module

After running some of threads and getting output in std out, the subsequent threads are getting stuck and are failing.

I tried by checking with slicing out 500 queue items in my code. It's not get struck and also got mail with report of test cases output.

Have to run the script without any hanging issues
```python
sample dictionary: 
{u'http://n22-r5.w2v.servers.nferx.com:10001': u'config_file="test_adagram_conf.json" domain_name="http://n4-r25.w2v.servers.nferx.com:10001" python -m unittest discover -v -p testing_adagram.py', u'http://n2-r25.w2v.servers.nferx.com:10001': u'config_file="test_adagram_conf.json" domain_name="http://n2-r25.w2v.servers.nferx.com:10001" python -m unittest discover -v -p testing_adagram.py'}
- Like above dictionary we have 2000 key, value pair
```

### What I've run:
```python
import subprocess
import gevent
import gevent.queue
from gevent import monkey; monkey.patch_all()


TOTAL_OUTPUT = []
q_items = []
counter = 0
threads = []
_queue = gevent.queue.Queue()
import os
os.environ["GEVENT_RESOLVER"] = "ares"
for server, command in server_commands.iteritems():
    _data = dict(counter=counter,server=server, command=command, server_commands=server_commands, total_output=total_output)
    _queue.put(_data)
    counter += 1

for i in xrange(50):
    threads.append(gevent.spawn(_run_function, _queue, server_commands, total_output))
gevent.joinall(threads)
def _run_function(_queue, server_commands, total_output):
    while 1:
        try:
            args = _queue.get_nowait()
        except gevent.queue.Empty:
            break
        server = args.get('server')
        command = args.get('command')
        server_commands = args.get('server_commands')
        total_output = args.get('total_output')
        process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=True)
        output, error = process.communicate()
        print "The thread number is %s" % args.get('counter')
        SERVER_COMMANDS[server] = output
        TOTAL_OUTPUT.append(output)
```
Script is hanging and not exiting. But when I see that command in htop and kill that command manually I am getting the mail with report of test cases output.
I am trying to skip the hanged threads and move to next one automatically to avoid hanging.
- Please advice me how could I solve that?

**Comment by jamadden** [comment]
You probably want to specify the [`timeout`](http://www.gevent.org/gevent.subprocess.html#gevent.subprocess.Popen.communicate) parameter to `process.communicate()` to avoid problems when the child processes hang.

Your example doesn't show how you imported `subprocess`. Make sure you monkey-patched the standard library at the top of your script if you wrote `import subprocess`, or write `from gevent import subprocess`. Otherwise your Popen objects will not be cooperating with gevent like you expect.

Setting `GEVENT_RESOLVER` within the script won't affect the current process, but it should affect the children processes.

You may want to use `sys.executable` instead of hardcoding `python` in your commands. 

Try to avoid using `shell=True` if you can. It's slower and doubles the number of processes that get started.

You can avoid a queue and the race conditions that go with it, but still limit concurrency, if you simply use a [`Pool`](http://www.gevent.org/gevent.pool.html#gevent.pool.Pool).

```python
pool = Pool(50)
datas = []
for server, command in server_commands.items():
   data = ...
   datas.append(data)
TOTAL_OUTPUT = pool.imap(_run_function, data)

def _run_function(args):
   server = args.get("server")
   ...
   output, error = process.communicate(timeout=TIMEOUT)
   ...
   return output
```

**Comment by kandrumounika** [comment]
Thanks for your reply. Earlier I imported subprocess like ```import subprocess``` .
Now I tried the process you explained. But unfortunately, I am getting IO error.
Kindly suggest me how could I resolve the same?
```
SERVER_COMMANDS = {}
from gevent.subprocess import Popen, PIPE
pool = Pool(50)  
process = []  
counter = 0  
for server, command in server_commands.iteritems():  
    _data = dict(counter=counter,server=server, command=command, server_commands=server_commands, total_output=total_output)
    process.append(_data)  
    counter += 1  
TOTAL_OUTPUT = pool.imap(_run_function, process)

def _run_function(args):  
        server = args.get('server')  
        command = args.get('command')  
        server_commands = args.get('server_commands')  
        total_output = args.get('total_output')  
        import pdb;pdb.set_trace()  
        process = Popen(command, stdout=PIPE, stderr=PIPE)  
        output, error = process.communicate(timeout=15)  
        print "The thread number is %s" % args.get('counter')  
        SERVER_COMMANDS[server] = output  
        return output  
```
screen shot
![error1](https://user-images.githubusercontent.com/11472099/32236304-c6841368-be87-11e7-9528-88e397954a3f.png)

**Comment by jamadden** [comment]
That appears to be a normal error that you would get when the command cannot be found. If you're *not* using the shell, you need to be explicit with the path to the command (you can't just say "python" and expect it to work); that's why I suggested using `sys.executable`.

**Comment by kandrumounika** [comment]
Thanks.  As per your first comment. By specifying the timeout parameter to _queue.get(timeout=10) I overcome the hanging issue.
