### ISSUE TITLE
custom headers considered as bad (WSGIHandler)

### ISSUE THREAD

**Issue by pavlodvornikov** [gevent/gevent#1041]
* gevent: 1.2.2
* Flask: 0.12.2
* Python: 3.5.2

**Description:**
Using gevent in conjunction with flask I'm facing problem with custom HTTP headers naming. gevent just drop any HTTP header containing "_". 

Does it have some background idea ? Line in code responsible for my case: https://github.com/gevent/gevent/blob/be54060470d192c9d5f131b5fcdd2f3ff88afd6b/src/gevent/pywsgi.py#L1044

**Comment by jamadden** [comment]
IIUC, that’s a very deliberate security feature implemented by many servers. See #819. 

Thanks for the report. Feel free to reopen if I misunderstood what you meant.
