### ISSUE TITLE
gevent.spawn not working

### ISSUE THREAD

**Issue by SyedNawaz** [gevent/gevent#1042]
* gevent version:gevent-1.1rc1.dist-info
* Python version:2.7
* Operating System:ubuntu

### Description:
Hi All,
I am new to python and gevent, i was trying to spawn the gevent but i found the below error, please help me to debug this further and also gevent.joinall or sleep is not working too

 from gevent import spawn
ImportError: cannot import name 'spawn'

Process finished with exit code 1

I have run below program :- 

import gevent
def main():
    coroutines = []
    def rmq_init():
        global connection, channel
        connection = pika.BlockingConnection(pika.ConnectionParameters(
           host='15.184.8.165', port= 5672))
        channel = connection.channel()
        print ("Connected to RMQ.........!")
        #channel.exchange_declare(exchange='AG_CPPM_AUTH', exchange_type='topic', durable= True)
        result = channel.queue_declare(queue="test1", exclusive=False, durable=False, auto_delete=True)
        cppm_queue = result.method.queue
        channel.queue_bind(exchange='AG_CPPM_AUTH', queue=cppm_queue, routing_key="#")

        def on_response(ch, method, props, body):
            global channel, username, password, response
            response = body
            #log.info('on_response response %s', response)
            username = response
            password = response
            print (username)
        #   except Exception as e:
                #log.error("exception: %s", e)

        channel.basic_consume(on_response, no_ack=True,
                                   queue=cppm_queue)
        try:
            channel.start_consuming()
        except KeyboardInterrupt:
            channel.stop_consuming()
            channel.queue_delete()
            channel.close()
            connection.close()
        gevent.sleep(5)
    def hello(a, b):
        print ("here")
        gevent.sleep(5)

    gevent.spawn(rmq_init)
    gevent.spawn(hello)
if __name__ == '__main__':
    main()

**Comment by arcivanov** [comment]
> gevent-1.1rc1.dist-info

That's an incredibly old version. You might want to upgrade to ~=1.2.

**Comment by jamadden** [comment]
Based on a post to the mailing list, It looks to me like you named your file “gevent.py”. That would shadow the library. Try naming it something else.

**Comment by SyedNawaz** [comment]
Thanks for the help, it worked :)
