### ISSUE TITLE
SSLEOFError in gevent's WSGIServer when using Google Chrome

### ISSUE THREAD

**Issue by juja256** [gevent/gevent#1046]
* gevent version: 1.2.2
* Python version: 2.7.13
* Operating System: Windows 10 / 17.03
* Browser: Google Chrome 62.0.3202.94
* OpenSSL version: 1.0.2j  26 Sep 2016

### Description:

I am trying to run SSL web server based on Flask app using gevent's WSGIServer. My page requests described above server with XMLHttpRequest when document.ready is occured. 
When I use Google Chrome browser all is ok except strange messages in console:
```
127.0.0.1 - - [2017-12-05 16:44:17] "GET / HTTP/1.1" 200 128 0.001000
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 174, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 695, in wrap_socket
    ciphers=ciphers)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 270, in __init__
    raise x
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:661)
Tue Dec 05 16:44:36 2017 <Greenlet at 0x3844440: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x37659d0 fileno=[Errno 9] Bad file de)> failed with SSLEOFError
```
This message occur after mostly all of requests in Google Chrome.
This error is not appeared when I use Mozilla Firefox.
Sometimes my web server hangs after lots of this messages, not responding to any request until I print something like Ctrl+C in console. When I insert Ctrl+C server quickly answers to all pending requests and prints those strange errors.

### What I've run:
Code of example web server:
```python
from flask import Flask

from gevent import monkey
from gevent import pywsgi

monkey.patch_all()

import ssl

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret'


@app.route('/')
def index():
    return "Hello World!"

if __name__ == '__main__':

    wsgi_server = pywsgi.WSGIServer(
        ('localhost', 8443), app,
        certfile='server.crt', keyfile='server.key')

    wsgi_server.serve_forever()
```

Code of requesting Java Script:
```
$(document).ready(function() {
    var xhttp = new XMLHttpRequest();
    xhttp.open("GET", "https://localhost:8443", true);
    xhttp.send();
}

```

**Comment by jamadden** [comment]
Since you only see this with chrome, it seems like the browser is closing the connection prematurely, probably as part of an "optimization". I'm not sure what you expect gevent to do about that.

FWIW, for any production usage, I recommend *not* using Python to handle SSL. Instead use something like stunnel or even an nginx reverse proxy to handle SSL.

**Comment by juja256** [comment]
I expect to get my server working despite this errors because I write local web-server based util. So that using ngingx or whatever else is not an option. I checked this case on Ubuntu, so Google Chrome works with my app without any errors on Linux. Could this error be Windows-specific?

**Comment by jamadden** [comment]
Yes, it's possible this could be Windows-specific. Windows is supported for development only, it is not recommended for production.

**Comment by juja256** [comment]
This errors are not the scariest things in this situation since web-server continues working for some time, but getting not responding web-server after some time handling chrome requests is not a good thing..
Okay, If you say that gevent is not supposed to be used in production on Windows this issue might be closed.
