### ISSUE TITLE
ImportError: cannot import name '_NONE'

### ISSUE THREAD

**Issue by 623059008** [gevent/gevent#1052]
* gevent version:1.2.2
* Python version:3.5.2
* Operating System:Linux 4.4.0-62-generic #83-Ubuntu

### Description:
I'm trying to import gevent.And it shows me an ImportError.
It says cannot import name '_NONE'.
and I look up the gevent._util, it indeed has the _NONE.
I don't know why this happened.But I guess there may be something wrong in the version.
How can I solve this problem?
### What I've run:

```
>>> import gevent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/gevent/__init__.py", line 51, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/usr/local/lib/python3.5/dist-packages/gevent/hub.py", line 31, in <module>
    from gevent._util import _NONE
ImportError: cannot import name '_NONE'
>>>
```

**Comment by jamadden** [comment]
It looks like you've installed your operating system's package for gevent. Can you instead install it from PyPI or the source tarball (probably into a virtual environment)? There's not much I can do about problems with a linux distributions packaging. Something like:
```
$ python -m venv env
$ . env/bin/activate
$ pip install -U setuptools pip greenlet wheel
$ pip install -U gevent
$ python -c 'import gevent'
```

To attempt to debug the problem with the system package, you could try looking at the output of `python -vv -c 'import gevent'`.
