### ISSUE TITLE
Review gevent socket code in light of bpo-27456

### ISSUE THREAD

**Issue by arcivanov** [gevent/gevent#1059]
This is not a bug report but rather a note to review gevent socket/file code in light of findings in [bpo-27456](https://bugs.python.org/issue27456) wrt checking for socket non-blocking status.
 
Specifically the changes introduced there are:

https://github.com/python/cpython/commit/e796b2fe26f220107ac50667de6cc86c82b465e3#diff-08afa52ab2b1511bee8527814ad44d80R87

```
       # Linux's socket.type is a bitmask that can include extra info
       # about socket (like SOCK_NONBLOCK bit), therefore we can't do simple
       # `sock_type == socket.SOCK_STREAM`, see
       # https://github.com/torvalds/linux/blob/v4.13/include/linux/net.h#L77
       # for more details.
```

**Comment by jamadden** [comment]
Thanks! As far as I can see, we don't introspect a socket's type anywhere.  There's only one hit that looks like that in the socket code, and (a) it's in a Win32-only block, and (b) `type` is a constant passed in by the user that should by SOCK_STREAM or SOCK_DGRAM:
```
$  ack '= SOCK' src/gevent/*socket*py
src/gevent/_socket3.py
697:        if type != SOCK_STREAM:
```

Broading the search to all files shows a few more hits, but they're benign:
```
$ ack '= SOCK' src/gevent/*py
src/gevent/_socket3.py
697:        if type != SOCK_STREAM:

src/gevent/_ssl3.py
175:        if sock.getsockopt(SOL_SOCKET, SO_TYPE) != SOCK_STREAM:

src/gevent/_sslgte279.py
211:        if sock.getsockopt(SOL_SOCKET, SO_TYPE) != SOCK_STREAM:

src/gevent/resolver_ares.py
153:                    elif socktype == SOCK_STREAM:
155:                    elif socktype == SOCK_DGRAM:
```

The `resolver_ares.py` hits are again on a user-specified parameter. And the hits in the SSL code show that gevent has actually been aware of this issue for some time. From _ssl3.py:

```
        # Can't use sock.type as other flags (such as SOCK_NONBLOCK) get
        # mixed in.
        if sock.getsockopt(SOL_SOCKET, SO_TYPE) != SOCK_STREAM:
            raise NotImplementedError("only stream sockets are supported")
```

Feel free to reopen if there's anything I missed.
