### ISSUE TITLE
Can/Should `gevent.sleep` be smarter?

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#1072]
See #1071 for a concise explanation of the current behaviour (with reference to #1068 for some more discussion). It allows the programmer to tune the system, but it can sometimes be surprising. There are also changes coming with libuv where it enforces a 1ms minimum sleep time that make this a more important issue to address: old idioms like `time.sleep(0.00000001)` to cycle the event loop will not work as expected under libuv.

One possibility is to have a hybrid approach to the number of callbacks we run per event loop iteration, periodically checking for how long we've run and cycling the loop if some threshold is exceeded. Presumably that threshold, and really the count, should be configurable.

libev offers a way to set a minimum blocking time in its select call that may sometimes also be useful (though not directly related to this). Not sure if libuv has anything similar.

**Comment by arcivanov** [comment]
> One possibility is to have a hybrid approach to the number of callbacks we run per event loop iteration, periodically checking for how long we've run and cycling the loop if some threshold is exceeded. Presumably that threshold, and really the count, should be configurable.

I think this is actually amazing as it will allow for "thread" greenlets to switch regularly without one grabbing all the time in a tight loop. 50 to 250 loops for one greenlet in a row seems like a reasonable threshold (old CPython thread switching limit was 100 instructions?)

**Comment by jamadden** [comment]
It's tricky because callbacks are used so heavily. Acquiring a lock is a callback, for example, so locks can be handed back and forth without requiring trips through the event loop. Overhead is crucial.

>  50 to 250 iterations for one greenlet in a row seems like a reasonable default threshold 

I wasn't proposing anything about specific greenlets (we have no way to detect that anyway), just changing the condition from `if number_of_callbacks_run > 1000: cycle_event_loop()` to `if number_of_callbacks_run > 1000 or total_time_running_callbacks > some_threshold: cycle_event_loop()`.

> (old CPython thread switching limit was 100 instructions?)

Yeah, `sys.setcheckinterval` determined the number of bytecode instructions that would be allowed between checking for thread switches. But bytecode instructions, much like callbacks, are highly variable in the amount of time they take---some instructions can go into C and spend arbitrary amounts of time---so the interval, while low-overhead, ended up being highly variable in terms of actual time. That's why Python 3.2 changed to `sys.setswitchinterval`, which is based on the amount of time spent running, not the amount of instructions executed. It's still variable because the check only occurs at certain parts of the eval loop, but it generally provides a tighter bound. (See [this message](https://mail.python.org/pipermail/python-dev/2009-October/093321.html)). That's basically what I'm talking about here: not perfect, and adds overhead, but maybe provides better latency overall.

**Comment by arcivanov** [comment]
I think it would be great.
