### ISSUE TITLE
wait operation on multiple Queues/Events

### ISSUE THREAD

**Issue by ArunMj** [gevent/gevent#1074]
Is it possible to do some sort of blocking wait operation on multiples Queues/Events.
In my case there will be a queue, which is used for sending some messages to a greenlet. That greenlet will be waiting for messages using Queue.get(). At the same time, it should aware of another event set by different greenlet.  How can use Queue.get and Event.wait together in one greenlet?

**Comment by jamadden** [comment]
Only if it's documented 😄 

greenlets are cheap. Usually one would just use a greenlet per queue.

**Comment by ArunMj** [comment]
Oh!, that was not i meant, i have edited my question, can look into it again :-|

**Comment by jamadden** [comment]
> How can use Queue.get and Event.wait together in one greenlet?

I don't think you can. Use two greenlets that feed a third greenlet.

**Comment by ArunMj** [comment]
okay got it. thank u. (y)
