### ISSUE TITLE
Remove Py2 Source Files from Py3 sdist + wheel

### ISSUE THREAD

**Issue by cooperlees** [gevent/gevent#1091]
* gevent version: 1.2.2
* Python version: Python 3.6.3
* Operating System: CentOS Linux release 7.4.1708 (Core)
Linux devbox 4.6.7 #69 SMP Tue Nov 14 16:47:15 PST 2017 x86_64 x86_64 x86_64 GNU/Linux

### Description:

Can we separate out the Python 2 only .py files so they don't get included into the Py3 wheel / src dists? I compile all .py files before adding them to PEX's for production release, so this fails with gevent. Happy to do the PR, how would you like to do it?

```
error: unable to compile "gevent/_socket3.py": invalid syntax (_socket3.py, line 195)

error: unable to compile "gevent/_util_py2.py": invalid syntax (_util_py2.py, line 7)

Build failed: Command failed with exit code 1.
stderr: error: unable to compile "gevent/_util_py2.py": invalid syntax (_util_py2.py, line 7)
```

### What I've run:

```python
python3.6 -m compileall .
```

**Comment by jamadden** [comment]
No. There is only one sdist, and as such it must work for all versions. See previous threads on this forum for working around shortcomings in tools that fail to handle that.

**Comment by cooperlees** [comment]
Any chance of a link or keywords to search for? Not having much luck searching for these threads.

**Comment by Ivoz** [comment]
It may be possible to reorganise the code such that 2/3 specific code are in 2/3 specific folders, and then for your tool ignore one of those folders?
