### ISSUE TITLE
Can a single imap target yield multiple results?

### ISSUE THREAD

**Issue by RonRothman** [gevent/gevent#1095]
* gevent version: 1.2.2

I'd like to do something like this:

```
pool = gevent.pool.Pool(max_concurrency)
result_iter = pool.imap(myfunc, some_list_of_inputs)
```

But, rather than a 1-1-1 correspondence between the number of items in `some_list_of_inputs`, the number of calls to `myfunc`, and the number of items in `result_iter`, I'd like to have `myfunc` yield 1 *or more* results per invocation.

Here's a simple contrived example that I hope will make clear what I'm asking:

```
def yield_images(url):
    """Fetch the text of ``url`` and yield all of the <img src> tags found therein."""
    for img_tag in parse(fetch(url)):
        yield img_tag.src

pool = gevent.pool.Pool(100)
img_src_iter = pool.imap(yield_images, url_list)

# We can now iterate over all the img srcs returned by yield_images, which there are presumably
# many more of than there are urls in url_list.
```

Is such a pattern supported? (I'm quite familiar with gevent already, and have looked through the docs, but haven't been able to find a solution there.) .Would welcome any advice or pointers. Thanks!

**Comment by RonRothman** [comment]
FWIW, the closest I've come is to use `chain.from_iterable` to flatten the results from `Pool.imap`.

Adding to the example above,
```
for img_src in itertools.chain.from_iterable(img_src_iter):
    print img_src
```

That seems to do the trick. It's not a bad solution at all, but if anyone can think of a better way, that'd be great.

**Comment by jamadden** [comment]
I think the itertools solution is about the best that can be done.

There hasn't been any activity on this issue in quite a while, so I'm closing it. Feel free to re-open if there is additional information to add.
