### ISSUE TITLE
Sleep in a threading.Timer freezes execution

### ISSUE THREAD

**Issue by kamac** [gevent/gevent#1097]
* gevent version: 1.2.2
* Python version: 3.5.3 anaconda
* Operating System: Windows 10 Home, version 1709

### Description:

I've been trying to call time.sleep from within threading.Timer from within a gevent Pool process, but execution halts without ever going through time.sleep.

A side note, but if you set threading.Timer to execute after more than 0.0 seconds, it halts without ever running the function behind the timer.

This issue does not exist when using threading.Thread in stead of threading.Timer

Expected behavior: process sleeps for given time and continues execution.

### What I've run:

```python
from gevent import monkey
from gevent.pool import Pool

import threading
import time

monkey.patch_all()

def wrapped():
    def example():
        print("sleeping")
        time.sleep(1)
        print("end sleeping")
    t = threading.Timer(0.0, example)
    print("threading timer start")
    t.start()
    t.join()

pool = Pool()
pool.spawn(wrapped)
pool.join()
```

**Comment by jamadden** [comment]
Thanks for the report! `threading.Timer` is not monkey-patched on Python 3.4 and above when using gevent 1.2. Please use gevent 1.3a1.
