### ISSUE TITLE
linux gevent for python

### ISSUE THREAD

**Issue by daxiabiluo** [gevent/gevent#1114]
I want to know how to use gevent in linux version of python, you need to cross compiler?

**Comment by jamadden** [comment]
In general, you use gevent on Linux exactly the same way you use it on other platforms, and exactly the same as you install other Python packages. For example, you may simply `pip install gevent`. No cross compiling is necessary.

**Comment by daxiabiluo** [comment]
I would like to ask under the use of gevent arm need to cross-compiler?

**Comment by jamadden** [comment]
Again, no, you don't need to use a cross compiler. I regularly build gevent directly on a Raspberry Pi. It takes awhile, but it saves me the effort of setting up a cross compiling tool chain. With appropriate options, you could probably make such a cross compilation setup work, but that's beyond the scope of gevent---that's a general compiler/setuptools/python issue at that point.
