### ISSUE TITLE
Wait for a socket and an event

### ISSUE THREAD

**Issue by ralt** [gevent/gevent#1140]
Hi,

Is it possible to wait for both a socket and an event? Something like this:

```python
s = socket.socket()
e = gevent.event.Event()

gevent.wait([s, e])
# Either the socket or the event is ready
```

This code is obviously not valid, but I wonder if there's some trick or workaround to make it work.

**Comment by ralt** [comment]
My use case is a read loop on the socket that needs to properly exit when an event occurs (a "stop event"), and my only way to do that right now is using a timeout on `select`. Which means I need to wait for the full timeout to check if the event was set, which can be slow, depending on the timeout.

**Comment by jamadden** [comment]
The simplest thing I can think of is to just have one greenlet waiting on the event, and when the event is set, raise an exception in the second greenlet handling the `read` loop.

**Comment by ralt** [comment]
Err, how do you raise an exception in the second greenlet?

**Comment by jamadden** [comment]
[Greenlet.kill](http://www.gevent.org/gevent.html#gevent.Greenlet.kill)

**Comment by ralt** [comment]
Thanks! I'll play with that.
