### ISSUE TITLE
gevent 1.3a2 with libuv use too much cpu times

### ISSUE THREAD

**Issue by wwqgtxx** [gevent/gevent#1144]
* gevent version: gevent1.3a2 downloaded from pypi (and cffi==1.11.5)
* Python version: cPython 3.6.2 downloaded from python.org
* Operating System: windows10 1703

### Description:

I write a simply code to test gevent1.3a2 with libuv, and that I found both the client and server use 20% cpu time on `socket.recv()` and when I switch back to libev it used almost 0% cpu time by the same code.

server:
```python
import gevent

gevent.config.loop = 'libuv'
gevent.config.resolver = 'ares'

import gevent.monkey

gevent.monkey.patch_all()

from gevent.server import StreamServer

import sys
import logging

logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s{%(name)s}%(filename)s[line:%(lineno)d]<%(funcName)s> pid:%(process)d %(threadName)s %(levelname)s : %(message)s',
                    datefmt='%H:%M:%S', stream=sys.stdout)

logger = logging.getLogger("TEST")


class TI:
    i = 0


def socket_handle(socket, address):
    TI.i += 1
    logger.info("new %d client<%s> connect" % (TI.i, str(address)))
    socket.settimeout(60 * 60 * 60 * 60)
    socket.recv(2048)
    logger.info("client<%s> disconnect" % (str(address)))


if __name__ == '__main__':
    server = StreamServer(('0.0.0.0', 11111), socket_handle)
    server.serve_forever()

```

client:
```python
import gevent

gevent.config.loop = 'libuv'
gevent.config.resolver = 'ares'

import gevent.monkey

gevent.monkey.patch_all()

import socket
import threading
import time


def client():
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.connect(('localhost', 11111))
        s.settimeout(60*60*60)
        # time.sleep(5000)
        s.recv(2048)


if __name__ == '__main__':
    for _ in range(1000):
        threading.Thread(target=client).start()
        time.sleep(0.001)

```

**Comment by jamadden** [comment]
Thanks for the report! What's happening is that libuv is spinning the CPU reporting over and over that the sockets are *writable* when all we really want to know is if they are *readable*.  This is because libuv doesn't allow multiple watchers for the same file descriptor, unlike libev, so gevent emulates that behaviour at the Python level, and it turns out that there was a bug doing so (when a Python watcher was stopped, it didn't properly update the events libuv was watching for).

**Comment by wwqgtxx** [comment]
A other question is how do `node.js` use `libuv` to solve this problem.I think in `node.js` also had to watch a socket to know it's writable and readable and why `node.js`'s implement not cause the spinning the CPU.Can we simulate the `node.js`'s implement in gevent to solve this.

**Comment by jamadden** [comment]
It's easily solved. This was just a simple bug. Test cases didn't catch it because it only has a side-effect, not a primary effect.

**Comment by wwqgtxx** [comment]
Thanks,I had test that pr and it solved my problem very well.
