### ISSUE TITLE
Remove calls to _dbg

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#1146]
* gevent version: 1.3

Before final release. Even when they're disabled, they add overhead of a function call, and some of them are in hot code paths. I suspect that the level of debugging they output is of interest only to myself.

**Comment by arcivanov** [comment]
Can `assert` be used?

**Comment by jamadden** [comment]
Not to produce debugging output :) (`_dbg` is a set of printing wrappers.)

**Comment by arcivanov** [comment]
I meant to call `_dbg` as part of the `assert` statement so it goes away unless __debug__ is set on the interpreter level.

**Comment by jamadden** [comment]
Oh, I see. Yes, that would work, but I have two concerns:

1) Side-effects of `assert` are generally considered a bad thing precisely *because* they can be turned off.
2) In my experience, relatively few people/deployments actually turn assertions *off*. I've even came across code that actually broke if they were turned off (because it depended on side-effects). So I'm not sure it would have the benefit I'd like to have. (Of course this whole thing could be a case of premature optimization--I haven't actually *measured* proof that the `_dbg` calls add overhead when they're not enabled, so at this point the main benefit would be cleanup up the code, as the `_dbg` calls tend to be long and unwieldy looking.)

**Comment by arcivanov** [comment]
Makes sense, but that's the only way to achieve `#ifdef` or `private static final` performance equivalent of instruction elision.
