### ISSUE TITLE
are the monkey.patch_* methods idempotent? i.e. what are the implications of calling monkey.patch_all() twice in the same program?

### ISSUE THREAD

**Issue by sulphide0** [gevent/gevent#1149]
* gevent version: 1.0.2
* Python version: cpython 2.7.9
* Operating System: Please be as specific as possible: "amazon linux"

for example, what is the behavior of monkey.get_original after calling patch_all twice?

**Comment by jamadden** [comment]
Their idempotency is not currently documented and is subject to change in the future. What [is documented](http://www.gevent.org/gevent.monkey.html#gevent.monkey.patch_all) is that calling `patch_all` multiple times with different arguments issues a warning.

Implementation wise, there has been some work around this recently-ish (i.e., the aforementioned warning). 1.0.2 is very old and I don't remember how it behaved, you'd have to check the code (But I'd recommend upgrading.)

**Comment by sulphide0** [comment]
thanks!

**Comment by jamadden** [comment]
As an implementation note, the internal function `patch_item`, used by the internal function `patch_module` actually uses `dict.setdefault` when it's recording the items to be returned by `get_original`. So even back in 1.0.2 the original item is still the original item after multiple calls to `patch_subprocess`, say. 1.3 actually contains a test for this...

**Comment by sulphide0** [comment]
ah ok, i didn't realize that. thanks
