### ISSUE TITLE
select on windows can't handle more 512 sockets

### ISSUE THREAD

**Issue by wwqgtxx** [gevent/gevent#1151]
* gevent version: gevent version: gevent1.3a2 downloaded from pypi (and cffi==1.11.5)
* Python version: cPython 3.6.2 downloaded from python.org
* Operating System: Operating System: windows10 1703

### Description:

Because of the code in gevent/select.py#137
```python
    # First, do a poll with the original select system call. This
    # is the most efficient way to check to see if any of the file descriptors
    # have previously been closed and raise the correct corresponding exception.
    # (Because libev tends to just return them as ready...)
    # We accept the *xlist* here even though we can't below because this is all about
    # error handling.
    sel_results = ((), (), ())
    try:
        sel_results = _original_select(rlist, wlist, xlist, 0)
    except error as e:
        enumber = getattr(e, 'errno', None) or e.args[0]
        if enumber != EINTR:
            # Ignore interrupted syscalls
            raise
```
It call original select before libev or libuv, but the original select on windows can't handle more than 512 sockets and can't handle the file object. If I drop those code, the program can handle more than 512 sockets good on windows. Of course that it not a good way to solve this problem because of the comments in that code. So I come to ask a good way to let gevent's select work better and more like it on linux or bsd operating systems.

simply test code:

```python
# import os
# os.environ['GEVENT_DEBUG'] = 'TRACE'
import gevent

gevent.config.loop = 'libuv'
gevent.config.resolver = 'ares'

import gevent.monkey

gevent.monkey.patch_all()
import socket
import select

if __name__ == '__main__':
    sockets = [socket.socket(socket.AF_INET, socket.SOCK_DGRAM) for _ in range(2048)]
    print(select.select(sockets, [], []))

```

**Comment by jamadden** [comment]
Why are you trying to use that many sockets? gevent on windows is not supported for production, only local development and testing.

**Comment by wwqgtxx** [comment]
Some times use that on some simple tools which write by myself.

**Comment by wwqgtxx** [comment]
I think a method which can solve this problem it is split the `rlist`, `wlist` and `xlist` when it lager than 512 only on windows. The call to original select is only for a check, so if first we check a part of them and then check the other part would have the same result.

**Comment by jamadden** [comment]
> Some times use that on some simple tools which write by myself.

So that's cool! Then you would presumably understand both the limitations of Windows and the gevent API. You'd need to workaround the Windows limitations under any other circumstances, so you could probably do the same here (i.e., don't make big `select` calls as you suggested). 

I don't think it's reasonable to expect that a call to `select` that would usually fail would happen to work if `select` had been monkey-patched (it's generally the other way around that's reasonable).

**Comment by wwqgtxx** [comment]
If change the monkey-patched `select` is not reasonable, could gevent provide a interface to replace `select` .I had read almost all gevent docs and not found a way can wait many sockets in a greenlet.

**Comment by jamadden** [comment]
It seems to me you may already have the answer to that, based on the code sample you’ve seen.

**Comment by wwqgtxx** [comment]
But this way can't handle more than 512 sockets on Windows(some times we don't care about performance only need to realize this feature). And I read the code found `gevent.select.SelectResult` is a nopublic class however can solve my problem. `SelectResult.select` is use `libev` or `libuv` to watch the sockets' event so it unneed care about the python stdlib's limits of `select`.
By my suggest can `gevent` provide a api which can call `gevent.Select` or other name call `SelectResult.select` directly to use `libev` or `libuv`'s `select` or `iocp` without monkey-patched.

**Comment by jamadden** [comment]
To be clear, I am not interested in providing such a public API right now. The building blocks are there if you wish to use them, but I don't see it as part of gevent's mission at this time.

**Comment by arcivanov** [comment]
Just out of curiosity, is the 512 limit a winsock2 problem or Python Windows implementation problem?

**Comment by wwqgtxx** [comment]
@arcivanov It's Python Windows implementation problem
https://github.com/python/cpython/blob/master/Modules/selectmodule.c#L36
