### ISSUE TITLE
Make libuv the default Windows loop for 1.3?

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#1163]
* gevent version: 1.3
* Python version: All
* Operating System: Windows

I'd like to make the libuv backend the default on Windows for 1.3 for all supported Python implementations (currently it's the default for PyPy). This would benefit Windows users by granting access to more sockets by avoiding libev's use of the C runtime functions that have a fixed size cap, and potentially being more efficient (although since Windows is currently not recommended for production, those may be only nominal benefits). It would benefit the gevent project by (very slightly) increasing the number of testers of the libuv backend.

Windows is currently 14th in download stats for the last 90 days with an order of magnitude fewer downloads than first place.

Our Linux wheels cannot be tested with libuv at all because manylinux1 doesn't support libuv. We'll have to wait for manylinux2010, which PEP is expected to be approved about April 9th, and then see how long it takes to get support for that across the ecosystem.

 rank | Version | File | system | download_count 
------|--------|-----|--------|----------------- 
| 1 | 1.2.2 | gevent-1.2.2-cp27-cp27mu-manylinux1_x86_64.whl | Linux | 632080 |  
| 2 | 1.2.2 | gevent-1.2.2-cp35-cp35m-manylinux1_x86_64.whl | Linux | 131471 |  
| 3 | 1.2.2 | gevent-1.2.2-cp36-cp36m-manylinux1_x86_64.whl | Linux | 129704 |  
| 4 | 1.2.2 | gevent-1.2.2.tar.gz | Linux | 95025 |  
| 5 | 1.2.1 | gevent-1.2.1-cp27-cp27mu-manylinux1_x86_64.whl | Linux | 42103 |  
|6 | 1.2.1 | gevent-1.2.1.tar.gz | Linux | 29716 |  
| 7 | 1.2.2 | gevent-1.2.2-cp34-cp34m-manylinux1_x86_64.whl | Linux | 13935 |  
| 8 | 1.2.2 | gevent-1.2.2.tar.gz | null | 11906 |  
| 9 | 1.2.1 | gevent-1.2.1-cp36-cp36m-manylinux1_x86_64.whl | Linux | 11860 |  
| 10 | 1.2.2 | gevent-1.2.2-cp27-cp27m-macosx_10_6_intel.whl | Darwin | 11405 |  
| 11 | 1.3a1 | gevent-1.3a1.tar.gz | null | 9215 |  
| 12 | 1.2.2 | gevent-1.2.2-cp36-cp36m-macosx_10_6_intel.whl | Darwin | 6554 |  
| 13 | 1.2.1 | gevent-1.2.1-cp35-cp35m-manylinux1_x86_64.whl | Linux | 6290 |  
| 14 | 1.2.2 | gevent-1.2.2-cp27-cp27m-win32.whl | Windows | 6281 |  
| 15 | 1.2.2 | gevent-1.2.2-cp36-cp36m-win_amd64.whl | Windows | 5800 |  
| 16 | 1.2.2 | gevent-1.2.2-cp27-cp27m-manylinux1_x86_64.whl | Linux | 5291 |  
| 17 | 1.2.2 | gevent-1.2.2-cp27-cp27mu-manylinux1_x86_64.whl | null | 4980 |  
| 18 | 1.2.0 | gevent-1.2.0-cp34-cp34m-manylinux1_x86_64.whl | Linux | 3882 |  
| 19 | 1.2.2 | gevent-1.2.2-cp36-cp36m-win32.whl | Windows | 3702 |  
| 20 | 1.2.2 | gevent-1.2.2-cp27-cp27m-win_amd64.whl | Windows | 3471 |  

Any reason not to do that?

**Comment by arcivanov** [comment]
Just curious, how did you pull the stats? I was under the impression pypi no longer had the download counters. Also, do you know if these include replication?

**Comment by jamadden** [comment]
[The PyPI data](https://bigquery.cloud.google.com/dataset/the-psf:pypi?pli=1) is a [public dataset in Google's BigQuery](https://kirankoduru.github.io/python/pypi-stats.html). I don't think it includes replication outside the CDN, but I can't find the original post announcing the data.

**Comment by wwqgtxx** [comment]
A small suggest is would we need add the cffi to depends on setup.py when run in Windows to let more people tedt the libuv backend.

**Comment by jamadden** [comment]
Good point.
