### ISSUE TITLE
Fix outstanding test failures

### ISSUE THREAD

**Issue by arcivanov** [gevent/gevent#1167]
```
 - GEVENT_DEBUG=debug GEVENT_RESOLVER=thread GEVENT_RESOLVER_NAMESERVERS=8.8.8.8 /home/travis/.runtimes/snakepit/python3.5.4 -u test__local.py
 - GEVENT_DEBUG=error GEVENT_RESOLVER=thread GEVENT_RESOLVER_NAMESERVERS=8.8.8.8 /home/travis/.runtimes/snakepit/python3.4.7 -u -W ignore -mgreentest.monkey_test test_threading.py
 - GEVENT_DEBUG=debug GEVENT_RESOLVER=thread GEVENT_RESOLVER_NAMESERVERS=8.8.8.8 /home/travis/.runtimes/snakepit/python3.4.7 -u test__local.py
```

**Comment by jamadden** [comment]
Hmm, I don't see what you're talking about. The most recent master builds on travis [are green](https://travis-ci.org/gevent/gevent/builds/361189474) as was Appveyor for Python 3. I don't reproduce any failures with 3.5 locally on master either.

**Comment by arcivanov** [comment]
I reproduced ` - GEVENT_DEBUG=debug GEVENT_RESOLVER=thread GEVENT_RESOLVER_NAMESERVERS=8.8.8.8 /home/travis/.runtimes/snakepit/python3.5.4 -u test__local.py` consistently on  my machine with Python 3.6. My MP PR also fails consistently with those completely unrelated issues.

**Comment by arcivanov** [comment]
Couldn't get the threading to reproduce consistently though.

**Comment by jamadden** [comment]
So you're seeing extra objects in the list?

Assuming that's the case, then a better test would be to use a new greenlet that holds only the one local and ask for its locals. That should be deterministic, even on pypy. (I don't know why I didn't do that in the first place, probably just lazy).
```python
def test_local_dicts_for_greenlet(self):
         import gevent
         from gevent.local import all_local_dicts_for_greenlet
        test = self
         class Greenlet(gevent.Greenlet):
             def _run(self):
                x = MyLocal()
                x.foo = 42
              results = all_local_dicts_for_greenlet(gevent.getcurrent())
             test.assertEqual(results,
                         [((MyLocal, id(x)), {'foo': 42})])

     g = Greenlet.spawn()
     g.join()
     self.assertTrue(g.successful)
```
