### ISSUE TITLE
_threading.RLock is missing in 1.3

### ISSUE THREAD

**Issue by vmalloc** [gevent/gevent#1171]
in Logbook (the logging library) we import gevent._threading to get to the actual _threading primitives even for installations that perform monkey patching. It seems that gevent 1.3 chose to remove _threading.RLock for some reason. Is there any chance to bring it back, or otherwise supply an alternative way to get to it?

(Originated by https://github.com/getlogbook/logbook/issues/258)

Thanks in advance!

**Comment by jamadden** [comment]
The supported way to get unpatched primitives is with `gevent.monkey.get_original`. `threading.Lock` is available there; depending on your needs that may be enough. If you do expect recursion, then you'll need to implement your own wrapper around the basic `threading.Lock`---the implementations of `acquire`/`__enter__` and `release`/`__exit__` are pretty simple. (Alternatively, you can try `gevent.monkey.get_original('threading', '_CRLock')` to get the C accelerated version directly from the stdlib, which is unaffected by monkey patching.)

The internals of `_threading` weren't used or tested by gevent and had some bitrot. Being an underscore prefixed module not publicly documented, we felt free to refactor them for 1.3 to improve speed for the parts that gevent *did* use and ensure everything was tested.

**Comment by vmalloc** [comment]
@jamadden of course, I wasn't criticising you for removing it... I was aware that it might break. I opened this issue because I was unclear about what had to be done since I don't use gevent myself and needed a direction for solving it.

I will look into using `get_original` for the solution. Thanks!
