### ISSUE TITLE
_close_fds on linux takes relatively long time on Python 3 

### ISSUE THREAD

**Issue by koreno** [gevent/gevent#1172]
https://github.com/gevent/gevent/blob/e3e555e2309120a488bbbc8b4f965791a5f15eed/src/gevent/subprocess.py#L1148

This is true especially when the host has a high limit of file-descriptors (`MAXFD`), which seems to be the case inside docker containers. This implementation leads to a lot (~2^20 in my case) of unnecessary calls to the `close` syscall, which slows down any subprocess invocation.
In contrast, the native python implementation uses `_posixsubprocess.fork_exec` [which in turn uses](https://github.com/python/cpython/blob/master/Modules/_posixsubprocess.c#L273) `/dev/fd` to identify fds that are indeed open.

**Comment by jamadden** [comment]
Yep, that's all true. The CPython version is written in C and is Linux specific, of course, and even it maintains the ["brute force"](https://github.com/python/cpython/blob/master/Modules/_posixsubprocess.c#L216) looping implementation as a fallback.

**Comment by koreno** [comment]
Is it not possible to implement something similar in the gevent version?
I.e use `/dev/fd` if available?

**Comment by jamadden** [comment]
Pull requests welcome; I don’t expect to implement any changes here myself, I don’t have a workload that bottlenecks on this. Note that there are a number of corner cases that must be handled, and the bar for test coverage is fairly high.

**Comment by jamadden** [comment]
I took a closer look at this and discovered a real regression on Python 3 for the close_fds=False case. Details in commit https://github.com/gevent/gevent/commit/b166aaf8cc6505716af1e87f9defee0a6d9a31fc; PR forthcoming.

**Comment by koreno** [comment]
Great! Lucky :)
