### ISSUE TITLE
pypi whl file missing

### ISSUE THREAD

**Issue by wwqgtxx** [gevent/gevent#1173]
* gevent version:1.3b1

### Description:

On the pypi's page [https://pypi.python.org/pypi/gevent/1.3b1](https://pypi.python.org/pypi/gevent/1.3b1)
 It was missing some windows `whl` files like `gevent-1.3b1-cp35-cp35m-win_amd64.whl` and `gevent-1.3b1-cp36-cp36m-win32.whl`.

**Comment by jamadden** [comment]
Thanks, I had issues uploading those two wheels the first time but they are there now.

**Comment by jamadden** [comment]
They will be part of the next gevent maintenance release. Python 3.7 has not been tested on Windows yet, it will take a PR to update the appveyor configuration.
