### ISSUE TITLE
Patched subprocess.call 10x slower on Python3 

### ISSUE THREAD

**Issue by stefano-maggiolo** [gevent/gevent#1188]
* gevent version: 1.1b5 up to 1.3b1, not in 1.1a1 (introduced between 1.1a2 and 1.1b5, testing versions in between gave me a `NameError: name 'MAXFD' is not defined`) 
* Python version: cPython 3.5.2, in a virtualenv
* Operating System: Ubuntu 16.04

### Description:

subprocess (at least subprocess,call()) looks much slower in Python 3 in the versions described above.

Here are some numbers (the second system is a debian derivative with python 3.6.2).

```
System     | Python 3, gevent 1.1a1 | Python3, gevent 1.2.2 | Python2, gevent 1.2.2
As above   | ~3.5 ms/call           | ~13.5 ms/call         | ~3.9 ms/call
~debian    | ~1.3 ms/call           | ~24.0 ms/call         | ~1.7 ms/call
```

### What I've run:

```python
from gevent import subprocess
from time import time

N = 1000
start = time()
for i in range(N):
    subprocess.call("/bin/true")
end = time()
print("%.3f ms/call" % (1000.0 * (end - start) / N))
```

**Comment by jamadden** [comment]
Yup :) This was addressed in https://github.com/gevent/gevent/pull/1176 and will be part of 1.3b2.

Thanks for the report.
