### ISSUE TITLE
Question about changing environment variable before monkey patching

### ISSUE THREAD

**Issue by carsonip** [gevent/gevent#1192]
* gevent version: 1.2.2
* Python version: 2.7.6
* Operating System: Ubuntu 14.04

### Description:
This is a question. I need to change environment variable `GEVENT_RESOLVER` to `ares` before importing anything about gevent otherwise `gevent.hub.Hub.resolver_class` will not be ares. I am asking this because I am not certain whether importing os before monkey patching will cause any problems. At least in my case patching os after importing os is still successful.

The wrong way to do:
```
>>> from gevent import monkey
>>> monkey.patch_all()
>>> import os
>>> os.environ['GEVENT_RESOLVER'] = 'ares'
>>> import gevent
>>> gevent.hub.Hub.resolver_class
['gevent.resolver_thread.Resolver', 'gevent.resolver_ares.Resolver', 'gevent.socket.BlockingResolver']
```

What I intend to do:
```
>>> import os
>>> os.environ['GEVENT_RESOLVER']='ares'
>>> from gevent import monkey
>>> monkey.patch_all()
>>> import gevent
>>> gevent.hub.Hub.resolver_class
['gevent.resolver_ares.Resolver']
```

1. Please confirm what I intend to do will not cause any problems.
2. Is this the best way to achieve what I want to do? Or should I simply forcefully set `gevent.hub.Hub.resolver_class = ['gevent.resolver_ares.Resolver']`?
3. Also, out of curiosity, under what circumstances will late monkey patching mess up imports?

Thank you very much.

**Comment by jamadden** [comment]
Your proposed code should be fine. `os` is typically imported as part of the startup of the interpreter anyway.

There is a nicer way to do this under gevent 1.3 (`import gevent; gevent.config.resolver = 'ares'`), but what you have is portable between both versions. (Under 1.3 I would suggest using 'dnspython' instead, though.)

Monkey-patching too late can break in all kinds of circumstances. Here's one trivial example:
```python
from socket import socket # This could be in any module imported before patching
from gevent.monkey import patch_all; patch_all()
sock = socket(...)  # Whoops, will not be cooperative
```

**Comment by carsonip** [comment]
Got it. Many thanks.
