### ISSUE TITLE
Add testing on PyPy2/3 6.0

### ISSUE THREAD

**Issue by arcivanov** [gevent/gevent#1195]
> We updated the cffi module included in PyPy to version 1.11.5, and the cppyy backend to 0.6.0. Please use these to wrap your C and C++ code, respectively, for a JIT friendly experience.

https://morepypy.blogspot.com/2018/04/pypy27-and-pypy35-v60-dual-release.html

**Comment by jamadden** [comment]
Fixed in 10c56fb6
