### ISSUE TITLE
Installation failed with endless loop

### ISSUE THREAD

**Issue by raririn** [gevent/gevent#1198]
* gevent version: 1.2.2
* Python version: 3.4.3
* Operating System: Ubuntu 14.04.5 LTS on Windows 10

Either installing gevent with ` pip install gevent` or `python setup.py build` after unzipping fails when the installation comes to run `\deps\c-ares\configure` and `conftest.c` `conftest.err` `conftest.er1` emerge and vanish endlessly.

The installation with pip works fine on windows 10, and direct installation seems to be okay on my vps running ubuntu 16.04.

**Comment by jamadden** [comment]
Thanks for the report. I don't support the Windows Subsystem for Linux directly, but if you can supply the full log I can take a look for any obvious problems. I also suggest you try installing 1.3b2 (or git master) as the build system has been updated.

**Comment by jamadden** [comment]
Also, based on what you've said, it appears to be an issue with c-ares. Does c-ares support WSL? You might try raising the issue over there.

You can disable building c-ares by setting a particular environment variable, IIRC (EMBED_CARES?), see setup.py for more info.

**Comment by raririn** [comment]
1.Thanks for quick reply! I tried to reproduce the log. It took very long time to reach the point it stuck (it took ~10 min running the command `running build_ext` (which I guess is dealing with libev? but no compiling error on the log though).

Not exactly the same as I encountered the last time. I bet it stopped on the next line of the compiling command and was something including running the configure file; but anyways the appearance is the same. `conftest.*` keeps looping and `config.log` didn't update any more.

Here is the bash log (might be a little long):
[my.log](https://github.com/gevent/gevent/files/1975213/my.log)


2. Installation using git master failed with the following log:
'Traceback (most recent call last):
  File "setup.py", line 403, in <module>
    run_setup(EXT_MODULES, run_make=_BUILDING)
  File "setup.py", line 387, in run_setup
    "signal_os_incompat = gevent.monkey:_subscribe_signal_os",
  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 239, in __init__
    self.fetch_build_eggs(attrs.pop('setup_requires'))
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
    replace_conflicting=True
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 595, in resolve
    requirements = list(requirements)[::-1]  # set up the stack
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2583, in scan_list
    "Expected ',' or end-of-list in",line,"at",line[p:]
ValueError: ("Expected ',' or end-of-list in", "cffi >= 1.11.5 ; sys_platform == 'win32' and platform_python_implementation == 'CPython'", 'at', " ; sys_platform == 'win32' and platform_python_implementation == 'CPython'")'


3. I'm sorry but I didn't find the variable EMBED_CARES anywhere... Did you mean the variable (or something works like that) is in setup.py?


Thank you!

**Comment by jamadden** [comment]
> File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2583, in scan_list
> "Expected ',' or end-of-list in",line,"at",line[p:]
> ValueError: ("Expected ',' or end-of-list in", "cffi >= 1.11.5 ; sys_platform == 'win32' and > platform_python_implementation == 'CPython'", 'at', " ; sys_platform == 'win32' and platform_python_implementation == 'CPython'")'

I would tend to guess that means you have an outdated version of setuptools. Ubuntu/debian is *always* outdated on packaging stuff. You'll need to use a virtual environment (see https://pypi.org/project/gevent/1.3b2/) and be sure to specify `-U` to pip.

> I'm sorry but I didn't find the variable EMBED_CARES anywhere... Did you mean the variable (or something works like that) is in setup.py?

There are a set of environment variables that control how parts of setup.py build extensions. They're undocumented and were added at the request of downstream packagers. I don't remember the exact details.

**Comment by raririn** [comment]
`running build_ext
Running '(cd  "/mnt/c/Users/Anonymous/gevent-master/deps/libev"  && sh ./configure   && cp config.h "$OLDPWD" ) > configure-output.txt' in /mnt/c/Users/Anonymous//gevent-master/build/temp.linux-x86_64-3.4/libev
building 'gevent.libev.corecext' extension
creating build/temp.linux-x86_64-3.4/src
creating build/temp.linux-x86_64-3.4/src/gevent
creating build/temp.linux-x86_64-3.4/src/gevent/libev
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DLIBEV_EMBED=1 -DEV_COMMON= -DEV_CLEANUP_ENABLE=0 -DEV_EMBED_ENABLE=0 -DEV_PERIODIC_ENABLE=0 -Ibuild/temp.linux-x86_64-3.4/libev -Isrc/gevent/libev -I/mnt/c/Users/Anonymous//gevent-master/deps/libev -I/usr/include/python3.4m -c src/gevent/libev/corecext.c -o build/temp.linux-x86_64-3.4/src/gevent/libev/corecext.o
x86_64-linux-gnu-gcc: error: src/gevent/libev/corecext.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 4`
The installation still fails. I suppose the problem is with libev, c-ares or perhaps gcc on my machine. Will try building libev and c-ares alone and will comment if anything new found. Thank you.

**Comment by jamadden** [comment]
`error: src/gevent/libev/corecext.c: No such file or directory` looks like Cython is not installed.

**Comment by raririn** [comment]
I though I have Cython installed... Installed Cython and the installation stops exactly where I first attempted to install it using v1.2.2.
`Running '(cd  "/mnt/c/gevent-master/deps/c-ares"  && if [ -r ares_build.h ]; then cp ares_build.h ares_build.h.orig; fi   && sh ./configure --disable-dependency-tracking CONFIG_COMMANDS=   && cp ares_config.h ares_build.h "$OLDPWD"   && cat ares_build.h   && if [ -r ares_build.h.orig ]; then mv ares_build.h.orig ares_build.h; fi) > configure-output.txt' in /mnt/c/gevent-master/build/temp.linux-x86_64-3.4/c-ares` So it seems to fail when building c-ares.

PS: interrupting the installation gives out `checking types of args and return type for recvfrom...`. It seems something goes wrong on this check and dead loop happens.

**Comment by jamadden** [comment]
>  interrupting the installation gives out checking types of args and return type for recvfrom.... It seems something goes wrong on this check and dead loop happens.

Ok. I don't know how to help with that, since we're just running the bare 'configure' script as shipped from c-ares. You'll probably need to get in touch with them to see if they support WSL.

(It might be that all that's needed is an updated config.guess with additional support for this platform. That's part of autoconf. We've needed to update that in the past for platform support once before. I don't know where to look for such a thing off the top of my head though.)

**Comment by raririn** [comment]
Tried to build c-ares alone and got the same symptom. Confirmed that it's a c-ares issue.
