### ISSUE TITLE
Upgrading from 1.3a1 to 1.3b2 resulted in `TypeError: Expected type, got ABCMeta` on Windows

### ISSUE THREAD

**Issue by bmjjr** [gevent/gevent#1201]
* gevent version: 1.3b2
* Python version: Cpython from miniconda, tried both 3.6.4-0 conda-forge,  3.6.5-1 conda-forge
* Operating System: Windows 10 Pro Version 10.0.16299 Build 16299

### Description:

I'm running a gevent based WSGI server on windows for a flask app. I upgraded from gevent 1.3a1 to 1.3b2 and the server fails to start, receiving a traceback:

```
File "src\gevent\local.py", line 374, in gevent._local.local.__cinit__
File "src\gevent\local.py", line 540, in gevent._local._local_find_descriptors
TypeError: Expected type, got ABCMeta

Process finished with exit code 1
```

### What I've run:

I'm monkey patching at the top of my manage.py file and below is the server code.  Reverting back to 1.3a1 works fine.

```python
def prodserver(host="127.0.0.1", port=8000):
    """Run a gevent-based WSGI server."""
    port = int(port)
    wrapped_app = app
    if app.config.get("DEBUG", True):
        wrapped_app = werkzeug.debug.DebuggedApplication(app)
        logging.basicConfig(filename='error.log', level=logging.DEBUG)
    server = WSGIServer(listener=(host, port), application=wrapped_app,
                        handler_class=WSGIHandler)
    def serve():
        print(" * Running on http://%s:%d/" % (host, port))
        server.serve_forever()

    if app.debug:
        werkzeug.serving.run_with_reloader(
            serve,
            reloader_type="stat" if sys.platform == "win32" else "auto")
    else:
        serve()

```

**Comment by jamadden** [comment]
Is there more to the traceback? In particular, can you pinpoint the (sub)class  of local being instantiated? I'm guessing it's using multiple-inheritance in an unexpected way, but it would be useful to see.

**Comment by bmjjr** [comment]
Here is the full traceback. My flask app uses the common factory pattern to create the app and register extensions and logging. Nothing stands out to me.

````python
C:\ProgramData\Miniconda3\envs\pythonocc\python.exe C:/Users/bjord/repos/aoscrdb_app/manage.py prodserver

Traceback (most recent call last):
  File "C:/Users/bjord/repos/aoscrdb_app/manage.py", line 95, in <module>
    app = create_app(config_obj=CONFIG)
  File "C:\Users\bjord\repos\aoscrdb_app\base\app.py", line 81, in create_app
    register_extensions(app)
  File "C:\Users\bjord\repos\aoscrdb_app\base\app.py", line 129, in register_extensions
    level=logging.ERROR)
  File "C:\ProgramData\Miniconda3\envs\pythonocc\lib\site-packages\raven\contrib\flask.py", line 279, in init_app
    self.client = make_client(self.client_cls, app, self.dsn)
  File "C:\ProgramData\Miniconda3\envs\pythonocc\lib\site-packages\raven\contrib\flask.py", line 52, in make_client
    'app': app,
  File "C:\ProgramData\Miniconda3\envs\pythonocc\lib\site-packages\raven\base.py", line 225, in __init__
    self._context = Context(self)
  File "src\gevent\local.py", line 374, in gevent._local.local.__cinit__
  File "src\gevent\local.py", line 540, in gevent._local._local_find_descriptors
TypeError: Expected type, got ABCMeta

Process finished with exit code 1
````

**Comment by jamadden** [comment]
This is the key line, that's the subclass of local being constructed:

>  self._context = Context(self)

[Chasing that down](https://github.com/getsentry/raven-python/blob/master/raven/context.py#L33) shows the class is declared like this:

```python
from collections import Mapping, Iterable
from threading import local
class Context(local, Mapping, Iterable):
    ...
```

`Mapping` and `Iterable` are, of course, ABCs using a custom metaclass (`ABCMeta`). (I've never seen the combo of `threading.local` and ABCs, but of course its legal.)

`Context` thus has an MRO of:
```pycon
>>> Context.mro()
[Context,
 gevent._local.local,
 collections.abc.Mapping,
 collections.abc.Collection,
 collections.abc.Sized,
 collections.abc.Iterable,
 collections.abc.Container,
 object]
```

And each object in the MRO has a particular type:
```pycon
>>> [type(x) for x in Context.mro()]
[abc.ABCMeta,
 type,
 abc.ABCMeta,
 abc.ABCMeta,
 abc.ABCMeta,
 abc.ABCMeta,
 abc.ABCMeta,
 type]
```

`gevent._local` is compiled as a C extension using Cython so it can perform as fast as the native `threading.local`. The TypeError is coming from a line that's iterating across `Context.mro()`, expecting each object to be a `type`. And apparently that pre-condition is not being met.

What's weird is that `abc.ABCMeta` *is* a kind-of `type`:

```pycon
>>> type(abc.ABCMeta)
type
>>> issubclass(abc.ABCMeta, type)
True
```

So I wouldn't expect this error. I'm wondering if it's a bug in Cython...I'll have to do some digging.

In the meantime, you could set the environment variable `PURE_PYTHON=1` before importing gevent. That will negate many (but not all) of the speed benefits that 1.3b1 and b2 bring, but it should be no worse than 1.3a1.
