### ISSUE TITLE
Cannot install gevent-socket on AWS Linux

### ISSUE THREAD

**Issue by leematthewshome** [gevent/gevent#1202]
* gevent version: 1.2.2
* Python version: 2.7.12
* Operating System: AWS Linux 

I am trying to install gevent-socket on my AWS Linux server. I have gevent installed...see results below if I try to reinstall

    [ec2-user@ip-00-00-00-00 ~]$ pip install gevent
    Requirement already satisfied: gevent in /usr/local/lib64/python2.7/site-packages (1.2.2)
    Requirement already satisfied: greenlet>=0.4.10 in /usr/local/lib64/python2.7/site-packages (from gevent) (0.4.13)

However when I try to install gevent-socket I get the following error:

    [ec2-user@ip-00-00-00-00 ~]$ pip install gevent-socket
    Collecting gevent-socket
      Could not find a version that satisfies the requirement gevent-socket (from versions: )
    No matching distribution found for gevent-socket

I upgraded to pip 10.0.1 when this happened, but that has not helped install gevent-socket as I still get exactly the same error. Can you please suggest what might be the problem.

**Comment by jamadden** [comment]
`gevent-socket` is not maintained by this organization. You'll need to seek out the maintainers of that project.

However, the error message is pretty clear: there is no project named `gevent-socket` on the package index you're installing from (PyPI). Perhaps you meant `gevent-websocket`?

**Comment by leematthewshome** [comment]
Apologies. Was following (faulty) notes I prepared when setting up another server. You are right, it should have been gevent-websocket.
