### ISSUE TITLE
gevent.local.local Doesn't Garbage Collect when the Greenlet Finishes

### ISSUE THREAD

**Issue by icebrick** [gevent/gevent#1206]
* gevent version: 1.3.0
* Python version: cPython3.5
* Operating System: 4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19) x86_64 GNU/Linux

### Description:

It seem the [issue#387](https://github.com/gevent/gevent/issues/387) not fixed yet, I repeated the code in issue#387, and found the local variable was not released when greenlet was dead, it was released only when the current script was finished, see the follow code

### What I've run:

I put the following code in a script file, and run it

```python
from gevent.local import local
import gevent
import time


# The sentinel object will let us know when it gets deleted
class Sentinel(object):
    def __del__(self):
        print("%s deleted" % self)


# A simple subclass of local, which references a Sentinel
class MyLocal(local):
    def __init__(self):
        self.sentinel = Sentinel()

my_local = MyLocal()


def demonstrate_my_local():
    # Get the important parts
    my_local.sentinel

g = gevent.spawn(demonstrate_my_local)
gevent.sleep()

# the greenlet has dead
print(g.dead)

time.sleep(3)
from gevent.local import all_local_dicts_for_greenlet
# but the local variable is still there
loc_var = all_local_dicts_for_greenlet(g)
print(loc_var)
# when this script finished, the local variable is released
print(g.dead)
```
the result is that: 
```
True
[((<class '__main__.MyLocal'>, 140628881588296), {'sentinel': <__main__.Sentinel object at 0x7fe6b5964ef0>})]
True
<__main__.Sentinel object at 0x7fe6b6b63748> deleted
<__main__.Sentinel object at 0x7fe6b5964ef0> deleted

Process finished with exit code 0
```
The the time gap between first output line and second line is 3 seconds.
It seems that the local variable was not garbage collected when the greenlet was dead.

**Comment by jamadden** [comment]
Thanks for the report. What's happening is that you need to yield to the hub for the greenlet to "finish" dying. Various gevent objects, including `gevent.local.local`, schedule cleanup actions using hub callbacks, which run as part of the event loop cycling. Unless you yield to the hub, those actions cannot take place. 

If you replace `time.sleep` with `gevent.sleep`, you'll see the object used in the background greenlet get deleted at that time.

If you don't yield to the hub, 1.2.2 shows the same behaviour as this; if you do, it also collects.

Example output using `gevent.sleep` (prints slightly modified for clarity):

```python
...
print("In", getcurrent(), "Spawned is dead?", g.dead)
print("Yielding to the hub from", getcurrent())

gevent.sleep()

print("Back from the hub in", getcurrent())
...
```

```
MyLocal.__init__: Created <__main__.Sentinel object at 0x106e965d8> in <greenlet.greenlet object at 0x106f8d6d0>
MyLocal.__init__: Created <__main__.Sentinel object at 0x107130268> in <Greenlet "Greenlet-0" at 0x106eec958: demonstrate_my_local>
Running in <Greenlet "Greenlet-0" at 0x106eec958: demonstrate_my_local> <__main__.Sentinel object at 0x107130268>
In <greenlet.greenlet object at 0x106f8d6d0> Spawned is dead? True
Yielding to the hub from <greenlet.greenlet object at 0x106f8d6d0>
<__main__.Sentinel object at 0x107130268> deleted
Back from the hub in <greenlet.greenlet object at 0x106f8d6d0>
Local vars? []
Dead now True
<__main__.Sentinel object at 0x106e965d8> deleted
```

**Comment by icebrick** [comment]
Oh, my fault, I see.
