### ISSUE TITLE
Flask gevent leaks CLOSE_WAIT

### ISSUE THREAD

**Issue by mdsf22** [gevent/gevent#1208]
gevent version: 1.2.2
Python version: 2.7.13
Operating System: centos7.3

Basically, after running for several day, the server will start to accumulate sockets in CLOSE_WAIT state, until things crash (ie. the server is still running, but no one can really connect, it just sits there and waits).

**Comment by jamadden** [comment]
Sockets in the CLOSE_WAIT state are needing the application to close them. Usually this means the application is leaking socket objects (on Python 2, that means having a reference to the socket object or to the results of socket.makefile() that isn't closed). 

What makes you think this is a gevent problem?

**Comment by mdsf22** [comment]
I use WSGIServer  of gevent

**Comment by mdsf22** [comment]
this is the code:

from gevent.wsgi import WSGIServer
from gevent.monkey import patch_all; patch_all() # noqa
from app import app
from app.config import config


if __name__ == '__main__':
    http_server = WSGIServer(
        (config.get('ip', '0.0.0.0'), config.get('port', 5002)), app)
    http_server.serve_forever()

**Comment by jamadden** [comment]
Without knowing what `app` does, the code snippet doesn't tell us much. Perhaps your request handler (`app`) sometimes hangs "forever", thus tying up a socket?

If I was trying to debug this, I would probably start by setting up a USR1 signal handler that called gevent 1.3's [print_run_info](http://www.gevent.org/monitoring.html#visibility) and use it when I saw unclosed sockets start to build up to see what my greenlets are doing. You could also try running under Python 3 with `-W default` or PyPy 2 with `-X trackresources` to look for unclosed sockets. And you could also set a spawn limit for the server to cap the number of greenlets below your number of open files. There may be some further suggestions on https://github.com/gevent/gevent/issues/1021

(Note that `gevent.wsgi` has been deprecated for a long time and was removed in gevent 1.3.)

**Comment by jamadden** [comment]
I'm going to close this since there have been no updates in 3 weeks. Feel free to reopen if there's an update!
