### ISSUE TITLE
Preventing Context Switches on Websocket IO?

### ISSUE THREAD

**Issue by rydamckinney** [gevent/gevent#1216]
* gevent version: 1.2.2
* Python version: 3.6
* Operating System: Mac OS X

### Description:

I am using gevent workers in a monolithic gunicorn server (via gevent-websocket).

I am sending audio through websockets in a real-time conversational system and want to be able to allow multiple user-server conversations in the same gunicorn worker. However, as gevent context switches on every network I/O, when I am sending audio through multiple websockets concurrently I am having issues. 

As I am sending hundreds of frames of audio to multiple websockets at the same time, the context switching between each greenlet (after each ws.send(data) call) causes the audio delivered to a single socket to be interrupted.

This long preamble essentially leads me to one major question: 

**Is it possible to block the gevent event loop (for < 100 ms) so that I can send many frames of data through one websocket without each ws.send(data) yielding to a context switch?**

I need to ensure that a quick for-loop (executes < 50 ms) which includes many ws.send(data) calls is uninterrupted by the typical context switch generated by the websocket data send.

I tried a workaround of creating a python-native thread, however as gunicorn gevent worker monkey patches before any application code, the native Thread has already been monkey patched so it also yields the context switching after each ws.send().

Any ideas on how I can block the context-switching on websocket IOs or achieve that effect with a Macgyver'd workaround?

```python
```

**Comment by jamadden** [comment]
cf #930 Short answer, no, you cannot do that in gevent. *Everything* revolves around the event loop cycling. If you want to block the event loop, you need to use non-gevent APIs. For example, you could use `os.write` on `socket.fileno()` in the threadpool.

**Comment by arcivanov** [comment]
You should have a jitter buffer and have a longer audio frames sent. If you're sending 30ms frames you should be able to switch no problem. Sounds like you're trying to solve your issue in the wrong layer.

**Comment by arcivanov** [comment]
Alternatively, if you really want to do it in Gevent, you can create special function that does exactly what you want by batching/gathering writes: https://github.com/gevent/gevent/blob/master/src/gevent/os.py#L130

Until you get to `hub.wait(event)` in https://github.com/gevent/gevent/blob/master/src/gevent/os.py#L131 the greenlet will not switch.

**Comment by jamadden** [comment]
There hasn't been any activity on this issue in quite a while, so I'm closing it. Feel free to re-open if there is additional information to add.
