### ISSUE TITLE
Cannot make weakref to gevent.queue.Queue object

### ISSUE THREAD

**Issue by githrdw** [gevent/gevent#1217]
* gevent version: 1.3
* Python version: "Python 2.7.12"
* Operating System: "Linux Ubuntu"

### Description:

I was trying to get [Ajenti ](https://github.com/ajenti/ajenti)running, which uses "gevent", but I ran into the following error:
`TypeError: cannot create weak reference to 'gevent._queue.Queue' object`

A week before it worked, with version v1.2.2 installed.

### What I've run:

Ajenti tried to run the following code (in /usr/local/lib/python2.7/dist-packages/aj/util/broadcast_queue.py):
```python
import weakref
from gevent.queue import Queue
class BroadcastQueue(object):
    def __init__(self):
        self._queues = []
    def register(self):
        q = Queue()
        self._queues.append(weakref.ref(q))
        return q
    def broadcast(self, val):
        for q in list(self._queues):
            if q():
                q().put(val)
            else:
                self._queues.remove(q)
```

**Comment by Zimeon-** [comment]
Tried to apply this fix but didn't get it to work, still get the same error. Made the modifications (https://github.com/gevent/gevent/pull/1218) to _queue.pxd and queue.py,  after that i compiled a new  queue.pyc.

Did I miss something?

**Comment by jamadden** [comment]
@Zimeon- If you're talking about the changes in commit 7f403c3, those affect the Cython-compiled modules. You'd need to recompile with Cython plus the C compiler.

The workaround in #1211 about using a trivial Python subclass is simpler.

**Comment by Zimeon-** [comment]
thank you for the reply, I'll check that one out.

**Comment by alexsv** [comment]
I'm getting "ValueError: gevent._queue.Queue has the wrong size, try recompiling. Expected 80, got 72" - is it something related to this change?

**Comment by jamadden** [comment]
@alexsv There was a brief period of time when broken manylinux1 wheels were on PyPI. If you installed one of those, you need to reinstall gevent, which should get the source and compile it. You may need to clear pip caches, I'm not sure. See #1219
