### ISSUE TITLE
Add libuv binaries to manylinux wheels

### ISSUE THREAD

**Issue by kpayson64** [gevent/gevent#1226]
* gevent version: 1.3.2
* Python version: Please be as specific as possible: cPython 2.7.13
* Operating System: Please be as specific as possible: Debian linux x86_64

### Description:
Attempted to use ```libuv``` implementation on linux.  It looks like the manylinux wheels don't have the compiled binaries for libuv.

```
from gevent.libuv import _corecffi # pylint:disable=no-name-in-module,import-error
ImportError: cannot import name _corecffi
```

### What I've run:
```
import gevent
gevent.config.loop = "libuv"
```

**Comment by jamadden** [comment]
Yes, that's a known and [documented issue](http://www.gevent.org/whatsnew_1_3.html#platform-support) issue. The binary wheels for manylinux1 simply *cannot* support libuv. The upcoming manylinux2010  spec should be able to.

That said, I would always recommend compiling all C extensions on the local platform for max performance. Installing generic binaries is likely to involve compromises.
