### ISSUE TITLE
Understanding where to call gevent.monkey.patch_all() when it can't be called at the beginning of the program

### ISSUE THREAD

**Issue by abarik1981** [gevent/gevent#1231]
* gevent version: 1.1.2
* Python version: "cPython 2.7.14 downloaded from python.org"
* Operating System: "Red Hat Enterprise Linux Server release 5.3"

### Description:

I am trying to understand where to call `gevent.monkey.patch_all()` when it can't be called at the beginning of the program?

My problem is that I am writing a python library `myconcurlib` that uses gevent to make concurrent request calls. This library will get imported and used by a external team's python framework (`some_python_framework`) that I don't have much control over (since `some_python_framework` is owned and written by another team, I can only contribute as addons). 

Its very likely that the caller/user/client of `myconcurlib.get_request_data` inside `some_python_framework` will import socket/requests/probably other blocking modules before calling `myconcurlib.get_request_data`

Do you think its safe to just call `gevent.monkey.patch_all()` at the top of `myconcurlib/__init__.py` and no need to patch it anywhere else (or do you think patching inside the function `get_request_data` helps)?

This is a sample code of `myconcurlib`
```python
# myconcurlib/__init__.py
import logging
import gevent.monkey
import datetime
from gevent.pool import Pool
import gevent.monkey
gevent.monkey.patch_all()
import requests

log = logging.getLogger(__name__)


def get_request_data(urls, pool_size=None):
    def _worker(url):
        log.debug("Running get_request_data.worker with url: {}".format(url))
        try:
            return requests.get(url)
        except Exception as e:
            log.exception("Error found in get_nsm_devices_concurrently.worker with url: {}: {}".format(url, e))

    # Patch all for gevent (even though Knits API uses coral in python which is implemented in requests and requests
    # primarily uses socket, there can be some other blocking IO code and its best to patch_all rather than patch_socket
    # http://www.gevent.org/intro.html#monkey-patching
    if not gevent.monkey.is_module_patched('socket'):
        log.debug('Gevent monkey patching socket')
        gevent.monkey.patch_all()


    start_time = datetime.datetime.now()
    pool = Pool(pool_size)
    jobs = urls
    log.debug("Getting request_data concurrently with pool size {} with job size {}".format(pool_size, len(jobs)))
    results = pool.map(_worker, jobs)
    end_time = datetime.datetime.now() - start_time
    log.info("runtime for get_nsm_devices_concurrently: {} result length: {}".format(end_time, len(results)))
    return results
       
```

This is the program that consumes `myconcurlib` which I don't have any control over

```python
# some_python_framework/some_client.py
## I only have control over this file
## Should I patch here, since I have control over this file?
from myconcurlib import get_request_data
import framework_call

@framework_call
def get_requests(urls):
  return get_request_data(urls)


# some_python_framework/main.py
## I don't have control over this main.py at all
import select, os, requests, urllib # and other blocking modules

from some_python_framework.some_client import get_requests

def main():
   call_all_framework_calls() # which will call get_requests

main()

```

**Comment by arcivanov** [comment]
To answer your question more broadly and generally (and there are always caveats and exceptions).
1. `from gevent import monkey` SHOULD be the first import in the main module.
2. `monkey.patch_all()` SHOULD be invoked immediately after the monkey import.

The exceptions are, you can import `gevent.config` and set gevent config prior to monkey patching (like setting DNS provider, type of file objects, gevent profiling and monitoring etc).

You should always think about "by importing a module am I going to open a file, or a socket or import and retain a reference to any object/class/method/function that is going to be patched before monkey-patching is invoked". If the answer is "yes" or even "maybe" you must do monkey-patching before importing such module.

**Comment by jamadden** [comment]
In general, I do not think a *library* should attempt to monkey patch the system (some high-profile examples aside, but those have particular, limited uses, and document their limitations). This goes double for libraries used inside a framework that presumably combines together multiple independent libraries. (But see the bottom for an exception to "general.")

This is in contrast to an *application* which should do the monkey  patching as soon as possible.

A library does not necessarily know the context in which it is being used. Nor does it necessarily know what other libraries are being used. Some of those libraries may break in the presence of monkey-patching. Or perhaps the deployer of the application (framework) wants to have the option of using greenlets or threads (such as gunicorn, which gives you a choice of worker type).

Suppose this library is slow to load, or not always needed, or its use is dynamically configured---all of which would be reasons that the import of this library is delayed well past application startup (e.g., it's imported inside a function call). Monkey-patching then might very well break things badly by having the system in a half-and-half state: some stdlib locks, some gevent locks, some native threads, some greenlets, some cooperative sockets, some uncooperative sockets, etc.

Even if this library is imported immediately, before anything has a chance to get into a half-and-half state, *unless the application is aware* that it's being used in a gevent environment, it's quite possible that it will do things that don't cooperate with gevent and thus break your library. For example, maybe this application/framework talks to a database. If it uses a database driver implemented in C, such as psycopg2, then every time it talks to the database the event loop will hang and concurrency will stop. To fix that, the application must be gevent aware (in this case, it would apply psycogreen)---and if it's gevent aware, then it should be doing the monkey-patching in the first place.

Basically, a library cannot silently monkey-patch itself into gevent heaven as part of a larger process. At the very least, the library *must* document that it uses gevent and that if it is going to work as designed, the calling application/framework must have some passing knowledge of that, if only to be sure not to use any non-cooperative other libraries (at which point, again I would argue, the application should do the monkey-patching).

An option I like is to write the library to use the standard library interfaces: threads, sockets, select/poll, etc. You can test your library with gevent monkey-patches, but it will also work without monkey-patches. You can document that you work best with monkey-patches, but it's up to the application to decide to do that or not. Being able to do it both ways is a lot of the point of monkey-patching.


Now, I said "in general." Maybe in this one case the example you provided is safe:
```python
def main():
   call_all_framework_calls() # which will call get_requests
```

If `call_all_framework_calls` makes calls one after the other, and no call is allowed to leave anything running (e.g., a thread) after it returns, and `main` does nothing after this, and your library is guaranteed to be the very last library to run, you might get lucky and monkey-patching that late might not mess anything up. But that has a lot of "if" statements.

**Comment by jamadden** [comment]
It's not clear to me there's anything more we can add to this. If there is or the OP wants to add more details, feel free to reopen!
