### ISSUE TITLE
MonkeyPatchWarning

### ISSUE THREAD

**Issue by WaspVae** [gevent/gevent#1235]
* gevent version:1.3.0
* Python version: cPython 3.6.5 downloaded from python.org
* Operating System: win 10

### Description:

**REPLACE ME**: At first
```
import socket
import re
import gevent
import gevent.monkey
gevent.monkey.patch_all()
```

### What I've run:

**REPLACE ME**: finally，i want know why ?I just touched python for a month and I was a newbie

```
MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016
  gevent.monkey.patch_all()

```

**Comment by arcivanov** [comment]
The call to `monkey.patch_all()` must precede all other imports. An import is not just symbolic linking, it has state and may create io-related objects.

You should have it as follows:

```python
import gevent.monkey
gevent.monkey.patch_all()

import socket
import re
import gevent
```

**Comment by jamadden** [comment]
@WaspVae Did that solve things for you?

If not, it may also be possible that something in your environment (e.g., sitecustomize.py or pkg_resources) has imported `ssl` before getting to your code. If running `python -c 'import gevent.monkey; gevent.monkey.patch_all()'` produces the warning, but running `python -I -S -c 'import gevent.monkey; gevent.monkey.patch_all()'` (note the `-I` and `-S` flags) *does not*, then that's the case. The task then is to figure out what is causing that import and fix it if possible.

**Comment by reallyquickturtle** [comment]
Try using gevent 1.2.2 and see if that works.

I'm not calling moneky patch anywhere in my project and gunicorn only gives me the monkey patch warning when running version 1.3 or above

**Comment by reallyquickturtle** [comment]
Try using gevent 1.2.2 and see if that works.

I'm not calling moneky patch anywhere in my project and gevent only gives me the monkey patch warning when running version 1.3 or above

**Comment by arcivanov** [comment]
@WaspVae 

The above should happen in the first ever module loaded. When using gevent monkey your entire first ever loaded module should look something like this:

```python
#!/usr/bin/env python3

if __name__ == '__main__':
    from gevent import monkey

    monkey.patch_all()

    # You can put any additional imports here if you need to
    import socket
    import re
    import gevent
    
    from actual_main_module import main

    main()
```

**Comment by WaspVae** [comment]
@arcivanov 
I tried the solution you provided but the problem still exists.
My gevent has been updated to version 1.3.2.post0
Here is my code:
`class WebServer:
    def __init__(self):
        self.server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.server_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, True)
        self.server_socket.bind(('', 8888))
        self.server_socket.listen()

    def handle_request(self, new_socket):
        recv_data = new_socket.recv(1024).decode()
        if not recv_data:
            print("byebye")
            new_socket.close()
            return
        data_list = recv_data.splitlines()
        request_line = data_list[0]
        regex = re.match(r'.* (.*) .*', request_line)
        file_path = regex.group(1)
        if file_path == '/':
            file_path = '/myWeChat.html'
        try:
            with open(f'.{file_path}', 'rb') as f:
                response_body = f.read()
        except Exception as reason:
            response_line = "HTTP/1.1 404 Not Found\r\n"
            response_headers = "Server: WASPVAE/6.6\r\n"
            response_headers += "Connection: Keep_Alive\r\n"
            response_headers += "Content-Type: text/html;charset=utf-8\r\n"
            response_headers += "\r\n"
            response_body = f'<h2>404 {reason}</h2>'.encode()
        else:
            response_line = "HTTP/1.1 200 OK\r\n"
            response_headers = "Server: WASPVAE/6.6\r\n"
            response_headers += "Connection: Keep_Alive\r\n"
            response_headers += "Content-Type: text/html;charset=utf-8\r\n"
            response_headers += "\r\n"
        finally:
            response = response_line + response_headers
            new_socket.send(response.encode() + response_body)
            new_socket.close()

    def run(self):
        while True:
            new_socket, client_addr = self.server_socket.accept()
            gevent.spawn(self.handle_request, new_socket)


def main():
    web_server = WebServer()
    web_server.run()


if __name__ == '__main__':
    from gevent import monkey

    monkey.patch_all()

    # You can put any additional imports here if you need to
    import socket
    import re
    import gevent

    main()
 `

**Comment by WaspVae** [comment]
@arcivanov 
I tried the solution you provided but the problem still exists.
My gevent has been updated to version 1.3.2.post0
Here is my code:
```
class WebServer:
    def __init__(self):
        self.server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.server_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, True)
        self.server_socket.bind(('', 8888))
        self.server_socket.listen()

    def handle_request(self, new_socket):
        recv_data = new_socket.recv(1024).decode()
        if not recv_data:
            print("byebye")
            new_socket.close()
            return
        data_list = recv_data.splitlines()
        request_line = data_list[0]
        regex = re.match(r'.* (.*) .*', request_line)
        file_path = regex.group(1)
        if file_path == '/':
            file_path = '/myWeChat.html'
        try:
            with open(f'.{file_path}', 'rb') as f:
                response_body = f.read()
        except Exception as reason:
            response_line = "HTTP/1.1 404 Not Found\r\n"
            response_headers = "Server: WASPVAE/6.6\r\n"
            response_headers += "Connection: Keep_Alive\r\n"
            response_headers += "Content-Type: text/html;charset=utf-8\r\n"
            response_headers += "\r\n"
            response_body = f'<h2>404 {reason}</h2>'.encode()
        else:
            response_line = "HTTP/1.1 200 OK\r\n"
            response_headers = "Server: WASPVAE/6.6\r\n"
            response_headers += "Connection: Keep_Alive\r\n"
            response_headers += "Content-Type: text/html;charset=utf-8\r\n"
            response_headers += "\r\n"
        finally:
            response = response_line + response_headers
            new_socket.send(response.encode() + response_body)
            new_socket.close()

    def run(self):
        while True:
            new_socket, client_addr = self.server_socket.accept()
            gevent.spawn(self.handle_request, new_socket)

def main():
    web_server = WebServer()
    web_server.run()

if __name__ == '__main__':
    from gevent import monkey

    monkey.patch_all()

    # You can put any additional imports here if you need to
    import socket
    import re
    import gevent

    main()
```

**Comment by arcivanov** [comment]
I just ran your code. I receive no warning. Gevent 1.3.3, Python 3.6.5.

```
(env) [arcivanov@ai-karellen-lap traiana]$ python test.py 
^CKeyboardInterrupt
2018-06-12T03:47:42Z
Traceback (most recent call last):
  File "test.py", line 60, in <module>
    main()
  File "test.py", line 48, in main
    web_server.run()
  File "test.py", line 43, in run
    new_socket, client_addr = self.server_socket.accept()
  File "/home/arcivanov/.pyenv/versions/3.6.5/envs/env/lib/python3.6/site-packages/gevent/_socket3.py", line 212, in accept
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 265, in gevent.__hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 266, in gevent.__hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 252, in gevent.__hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 151, in gevent.__waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
KeyboardInterrupt
(env) [arcivanov@ai-karellen-lap traiana]$ pip show gevent
Name: gevent
Version: 1.3.3
Summary: Coroutine-based network library
Home-page: http://www.gevent.org/
Author: Denis Bilenko
Author-email: denis.bilenko@gmail.com
License: MIT
Location: /home/arcivanov/.pyenv/versions/3.6.5/envs/env/lib/python3.6/site-packages
Requires: greenlet
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(env) [arcivanov@ai-karellen-lap traiana]$ python --version
Python 3.6.5
```

**Comment by arcivanov** [comment]
So this might be a Windows-only problem.

**Comment by WaspVae** [comment]
@arcivanov 
It is a problem with my Pycharm.I didn't have this kind of waring with command or IDLE when I ran my code.And I ran my code on other computer without warning.
Sorry for the inconvenience caused.

**Comment by jamadden** [comment]
I don't use Pycharm or Windows so I can't really investigate further. But #1239 limits the scenarios that the warning is issued in to those that we're pretty sure will cause problems. We'd prefer if all users patched as early as possible, but at least this way if they do have a problem there's a link to more information about it issued before the problem.

**Comment by mikelibg** [comment]
Running my code with gevent==1.3.4 and Python 3.6.5 not on Windows and not using PyCharm and getting similar error:

/Users/uuu/Development/work/venvs/myenv3/lib/python3.6/site-packages/gunicorn/workers/ggevent.py:65: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util (/Users/uuu/Development/work/venvs/myenv3/lib/python3.6/site-packages/urllib3/util/__init__.py)', 'urllib3.util.ssl_ (/Users/uuu/Development/work/venvs/myenv3/lib/python3.6/site-packages/urllib3/util/ssl_.py)'].
  monkey.patch_all(subprocess=True)

This issue was discussed 
https://github.com/urllib3/urllib3/issues/1176
