### ISSUE TITLE
why put/get print different

### ISSUE THREAD

**Issue by LashengRamsey** [gevent/gevent#1243]
* gevent version:1.3.4
* Python version: 2.7.15
* Operating System: windows7

### Description:
why put/get print different

![41708182-736bbb0c-7572-11e8-975c-e8d94be03a4b](https://user-images.githubusercontent.com/7947566/41708691-e0751b7a-7573-11e8-97b4-56be16b83951.png)
![41708241-9f13521a-7572-11e8-8f04-a238e46f46ef](https://user-images.githubusercontent.com/7947566/41708693-e142e6a4-7573-11e8-949d-5eecafe7bd6b.png)

'\x00\x00\x00\x00\x00\x00\x00o\x08\x00\x12\xba\x01\x1a\x10rpcSceneEnterEndB\xa3\x01{"sName":"\xe6\xa3\xb1\xe9\x95\x9c\xe7\xa7\x98\xe5\x9c\xb0","iMapWidth":1102,"iMapHight":1694,"sMapResource":"map_2_1_jpg","iInstMode":5,"iInstType":1,"sMusic":"BGM-10_mp3","iWarMode":2,"iSceneId":3}J\x00'

**Comment by LashengRamsey** [comment]
![6 x5 fx f on5ej0 jkb i](https://user-images.githubusercontent.com/7947566/41710574-97802df6-7578-11e8-97cf-15ea2bfef8c4.png)
![ynkddb ntfwt ue97phn eh](https://user-images.githubusercontent.com/7947566/41710575-97e79626-7578-11e8-8101-3c16bd428430.png)

**Comment by jamadden** [comment]
I'm sorry, I do not understand what you're trying to say. Can you please create a [short, self-contained](http://sscce.org) code example to put here (as actual code, not pictures)?
