### ISSUE TITLE
Add a get_original_module API?

### ISSUE THREAD

**Issue by zhangyangyu** [gevent/gevent#1245]
Is it acceptable to add a `get_original_module` query API to the monkey module? Currently there is only `get_original` to return a specific original function. But it is not easy to use when you want to incorporate it with the import mechanism. Eventlet has a similar `patcher.original` API to do so.

**Comment by jamadden** [comment]
gevent doesn't replace entire modules so `get_original_module` doesn't make sense to me. gevent patches objects in place, inside a module.

**Comment by zhangyangyu** [comment]
I know. Eventlet does the same and uses `patcher.original` to return a not patched copy. For example, see https://github.com/eventlet/eventlet/blob/master/eventlet/hubs/kqueue.py. I don't mean gevent should have what eventlet gets. But I think such an API first is easier to use, don't have to know what functions are actually patched and use `get_original` across the module. Second, it could be incorporated with import mechanism, hooking `__import__` to return an not patched module.

**Comment by jamadden** [comment]
I don't see how that's feasible given the way gevent works.

If you want a "pristine" copy of some module, you can try [import_fresh_module](https://docs.python.org/3/library/test.html#test.support.import_fresh_module).

**Comment by jamadden** [comment]
> It there anything technically wrong with this method?

The answer is either "yes" or a more guarded "it depends on exactly what you're trying to accomplish." Lots of things can go wrong, including unexpected blocking of the event loop, failed `isinstance` or `issubclass` checks, uncaught exceptions, etc. The system is in an undefined state after that (again, depending on what you're trying to accomplish).

I don't want to sign up for the support headaches that go with such a loaded footgun. If you're willing to take the risk and debug through the problems in your particular application, more power too you, though! 😄

**Comment by zhangyangyu** [comment]
Of course if someone uses the original version, no matter the function or the module in a patched environment, the application is highly possible under an undefined state. I don't propose such APIs used in such a way. They should be used with good knowledge and the way frameworks like gevent or eventlet use them. Anyway, I am not proposing any new feature, I just think it could bring more convenience to users who want the original functions.

**Comment by jamadden** [comment]
I appreciate your suggestion, but I explicitly *do not* want to bring "more convenience" to creating undefined states. Easy things should be easy, hard things should be possible, and it is, using existing stdlib APIs, for users who really feel like they need to do something out of the ordinary, and have good enough reason to do so that they put in the effort to understand the options and the drawbacks.

**Comment by zhangyangyu** [comment]
I could understand your point as the framework maintainer. It's not hard to do it myself. Thanks for your feedback. :-) One last thing I wanna know is, all the drawbacks you mentioned apply to `get_original` too, right? if not used properly.

**Comment by jamadden** [comment]
To a much smaller extent, yes, that's true. It exposes a much smaller surface area and the uses are typically more targeted using a single function gevent shadows (e.g., to get the native thread ident).

**Comment by zhangyangyu** [comment]
Thanks. :-)
