### ISSUE TITLE
Add a function to list the stacks for all greenlets with a signal handler to show them ?

### ISSUE THREAD

**Issue by tzickel** [gevent/gevent#1246]
Just like there is the backdoor package, maybe it's worth to add a function that dumps all greenlets with their names and their stack traces.

It could be triggered by an signal handler for example SIGUSR1.

I've seen that docker daemon does it, upon SIGUSR1 it dumps all channel stacks to a file with a timestamp.

This can be helpful to debug live running processes.

**Comment by jamadden** [comment]
Perhaps like [print_run_info()](http://www.gevent.org/monitoring.html#visibility)? It's up to you to connect it to your signal of choice...

**Comment by tzickel** [comment]
1.3 seems to have some nice surprises.
