### ISSUE TITLE
need patch queue.SimpleQueue for py37

### ISSUE THREAD

**Issue by wwqgtxx** [gevent/gevent#1248]
* gevent version: gevent==1.3.4
* Python version: cPython3.7.0 downloaded from python.org
* Operating System: win10 1709

### Description:

The python37 default `SimpleQueue` was implemented with C code, which will cause hang the main thread.
A simple way to solve this problem like that 
```python
from gevent import monkey
monkey.patch_all()
import queue
queue.SimpleQueue = queue._PySimpleQueue
```
but I think this code is so ugly and may be have better way to implements in gevent.

**Comment by wwqgtxx** [comment]
Another interesting question I want to know is why not patch the whole queue module by `gevent.queue` ☺

**Comment by jamadden** [comment]
There are native thread use cases for the original objects.

**Comment by wwqgtxx** [comment]
In my test, combine use the native thread and the monkey patched standard library sometimes will cause deadlock but I can't confirm when and where cause that. So I rewrite that code by use `multiprocessing` but `gevent` will block in some `multiprocessing`'s native code too. Could gevent provide a document to says how to use native thread with gevent correctly and the compatibility with standard library to avoid the users writing the wrong code.
