### ISSUE TITLE
gevent python3.7 + ThreadPoolExecutor block main thread

### ISSUE THREAD

**Issue by ClericPy** [gevent/gevent#1251]
* gevent version: 1.3.4
* Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] downloaded from python.org
* Operating System: Windows-10-10.0.16299-SP0

### Description:

gevent + python3.7 + ThreadPoolExecutor will block main thread forever while running future.result(). seems like something about _thread.allocate_lock.acquire.

**only python3.7 hit that issue**

> python3.6+ubuntu18.04 + gevent 1.3.4 runs ok
> 
> python3.7+ubuntu18.04 + gevent 1.3.4 runs bad

### What I've run:

```python
from gevent import monkey

monkey.patch_all()

from concurrent.futures import ThreadPoolExecutor
import requests

pool = ThreadPoolExecutor()

task = pool.submit(requests.get, "http://python.org")
task.add_done_callback(lambda r: print(r.result(), 'done'))
print(task.result())
```

#### output:

<Response [200]> done
> and then blocking...............

**Comment by wwqgtxx** [comment]
please try #1248

**Comment by ClericPy** [comment]
@wwqgtxx thanks very much, close this issue for duplicate.

**Comment by jamadden** [comment]
Sure enough, on 3.7, `ThreadPoolExecuter` was changed to use `queue.SimpleQueue`; on 3.6 it uses `queue.Queue`.

**Comment by ClericPy** [comment]
@jamadden thank you for answering, will gevent do that trick in the future versions?

**Comment by jamadden** [comment]
@ClericPy See #1253. I was on the fence about having gevent do that patch (it's never patched `queue` before) but this example convinced me that it was the right thing.

**Comment by ClericPy** [comment]
waiting for the wonderful lib's updating ^-^
