### ISSUE TITLE
Greenlet._run attribute resets  after  execution is finished

### ISSUE THREAD

**Issue by ArunMj** [gevent/gevent#1257]
* gevent version: 1.3.4
* Python version: "cPython 2.7.9"
* Operating System: "Ubuntu x64 4.15.0-23-generic"

### Description:
If we pass a callable while instantiating `gevent.Greenlet`, its `_run` attribute gets replaced with the same.
But after greenlet is finished execution, this attribute reset to the original `_run` defined in `gevent.Greenlet`

Sometimes it would be helpful if we could get original callable inside linked callbacks.

### What I've run:

```python
import gevent

def foo():
    print "** [inside foo] gthread._run" , gthread._run

def callback(g):
    assert gthread is g
    print "** [inside callback] g._run" , g._run

gthread = gevent.Greenlet(foo)

gthread.link(callback)
print "** [before_start] gthread._run" , gthread._run
gthread.start()
gthread.join()
print "** [finished] gthread._run" , gthread._run
```

Result
---
** [before_start] gthread._run <function foo at 0x7fa1949bb5f0>
** [inside foo] gthread._run <function foo at 0x7fa1949bb5f0>
** [inside callback] gthread._run **<bound method Greenlet._run of <Greenlet "Greenlet-1" at 0x7fa197c75ec0: _run>>**  
** [finished] gthread._run **<bound method Greenlet._run of <Greenlet "Greenlet-1" at 0x7fa197c75ec0: _run>>**

**Comment by jamadden** [comment]
Thanks for the report.

> But after greenlet is finished execution, this attribute reset to the original _run defined in gevent.Greenlet

That behaviour is very deliberate. The reference is dropped as soon as possible to break potential cycles and allow garbage to be collected as soon as possible. gevent tries to be careful with memory usage and especially avoiding/breaking cycles.

**Comment by ArunMj** [comment]
So, is it possible to get rid of this behaviour by subclassing Greenlet?  I looked into the [source code](https://github.com/gevent/gevent/blob/e6d9991e63a7c7dcc7aef851fbb6c9e95bf4cb8f/src/gevent/greenlet.py) and unfortunately could not find at where the reference is dropped?

**Comment by ArunMj** [comment]
So, Is it possible to get rid of this behaviour by subclassing `Greenlet`?

**Comment by ArunMj** [comment]
So, is it possible to override this behaviour by subclassing `Greenlet`?
I looked into the [sourcecode](https://github.com/gevent/gevent/blob/e6d9991e63a7c7dcc7aef851fbb6c9e95bf4cb8f/src/gevent/greenlet.py) but unfortunately could not find any lines which drop the reference.

**Comment by jamadden** [comment]
The [documented way to subclass Greenlet](http://www.gevent.org/api/gevent.greenlet.html#subclassing-greenlet) is to override its `_run` method. You could have `_run` call some arbitrary callable that you keep in an arbitrary instance variable. Clearly Greenlet can't [pop](https://github.com/gevent/gevent/blob/master/src/gevent/greenlet.py#L722) an ivar it doesn't know about.
