### ISSUE TITLE
Gevent install from pip requirng cython

### ISSUE THREAD

**Issue by rillip3** [gevent/gevent#1259]
* gevent version: 1.3.1
* Python version: Python 2.7.13 from Debian 9 repos inside virtualenv
* Operating System: Debian Linux 9.0 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

### Description:
When installing gevent from pip (at least if it is already installed) an error occurs saying cython not found as it tries to remove itself and readd itself. This doesn't appear to be a problem, because the uninstall is rolled back and I still seem to have gevent at the end of the run, it's just inconvenient to have a failure. When I installed cython and ran again, I got a much longer error message that I didn't feel was worth looking into.

Output from the first run that requires cython below

```
$ pip install -r requirements.txt 
Looking in indexes: https://pypi.raxent.com/simple
...
Installing collected packages: gevent
  Found existing installation: gevent 1.3.1
    Uninstalling gevent-1.3.1:
      Successfully uninstalled gevent-1.3.1
  Running setup.py develop for gevent
    Complete output from command /home/peatheri/ae/siphonenv/bin/python2 -c "import setuptools, tokenize;__file__='/home/peatheri/ae/siphonenv/src/gevent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    /home/peatheri/ae/siphonenv/local/lib/python2.7/site-packages/setuptools/dist.py:398: UserWarning: Normalizing '1.0dev' to '1.0.dev0'
      normalized_version,
    running develop
    running egg_info
    writing requirements to gevent.egg-info/requires.txt
    writing gevent.egg-info/PKG-INFO
    writing top-level names to gevent.egg-info/top_level.txt
    writing dependency_links to gevent.egg-info/dependency_links.txt
    reading manifest file 'gevent.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'Makefile.ext'
    writing manifest file 'gevent.egg-info/SOURCES.txt'
    running build_ext
    /home/peatheri/ae/siphonenv/bin/python2 util/cythonpp.py -o gevent.core.c gevent/core.ppyx
    Running cython -o gevent.core.c gevent/core.pyx  # !EV_USE_SIGNALFD && !defined(LIBEV_EMBED) && !defined(_WIN32)
    sh: 1: cython: not found
    Traceback (most recent call last):
      File "util/cythonpp.py", line 801, in <module>
        process_filename(filename, options.output_file)
      File "util/cythonpp.py", line 85, in process_filename
        output = run_cython(pyx_filename, sourcehash, output_filename, banner, comment)
      File "util/cythonpp.py", line 529, in run_cython
        system(command, comment)
      File "util/cythonpp.py", line 539, in system
        raise AssertionError('%r failed with code %s' % (command, result))
    AssertionError: 'cython -o gevent.core.c gevent/core.pyx' failed with code 32512
    Makefile:10: recipe for target 'gevent/gevent.core.c' failed
    make: *** [gevent/gevent.core.c] Error 1
    
    ----------------------------------------
  Rolling back uninstall of gevent
Command "/home/peatheri/ae/siphonenv/bin/python2 -c "import setuptools, tokenize;__file__='/home/peatheri/ae/siphonenv/src/gevent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/peatheri/ae/siphonenv/src/gevent/
```

### What I've run:

apt-get install cython, pip install gevent

**Comment by jamadden** [comment]
It appears that the contents of `requirements.txt` is resulting in a *very* old version of gevent being installed. I can tell for sure by two lines in the output:

> UserWarning: Normalizing '1.0dev' to '1.0.dev0'

'1.0dev' was only used in the [1.0a1 pre-release](https://github.com/gevent/gevent/blob/1.0a1/gevent/__init__.py#L10) and other early pre-releases.

> cythonpp.py -o gevent.core.c gevent/core.ppyx
    Running cython -o gevent.core.c gevent/core.pyx  # !EV_USE_SIGNALFD && !defined(LIBEV_EMBED) && !defined(_WIN32)

`cythonpp.py` doesn't exist in gevent 1.3. It only existed up through gevent 1.2.2.

I recommend adjusting `requirements.txt` to use the current version of gevent which is 1.3.5.

**Comment by jamadden** [comment]
Note that none of the 1.0 pre-releases appear to [be on PyPI](https://pypi.org/project/gevent/#history), so the use of a custom index server is probably also related. I can't seem to contact that index server to verify.

> Looking in indexes: https://pypi.raxent.com/simple

**Comment by rillip3** [comment]
Thanks for look @jamadden, you're correct that it's hitting an internal cache. Why some previous dev thought this was a good idea, I'll never know. If this isn't reproducible in a sane environment, I think we're good to close this.

**Comment by rillip3** [comment]
I've confirmed in a new virtualenv on the same machine that without the ridiculous pinning to the internal server and an ancient version, this isn't reproducible.
