### ISSUE TITLE
tutorial links on wiki page broken

### ISSUE THREAD

**Issue by vsoch** [gevent/gevent#1263]
hey gevent! This is a tiny issue, but the links to the tutorials on the wiki page seem to be broken -

https://github.com/gevent/gevent/wiki/Projects#tutorials

are there any updates?

**Comment by jamadden** [comment]
TBH, the wiki is not maintained and should probably be closed down unless someone steps up. A search engine is a better bet.

**Comment by vsoch** [comment]
That would work too :) if it's useful to know, I found that page via the main docs (the link to open source projects) and I got there from Google search!

**Comment by jamadden** [comment]
That is useful to know, thanks. The main docs are in git and can be edited that way.

**Comment by vsoch** [comment]
Okay cool. I removed the two sections of dead links (Tutorials and More) on the projects wiki page --> https://github.com/gevent/gevent/wiki/Projects. There are too many potential good links on the wiki so I didn't prune anything away for now - likely a maintainer that knows which are best to share might consolidate (on the main docs page) and then clean up (dispose of?) the wiki. Please let me know if I can be of any help!

**Comment by jamadden** [comment]
Thanks for looking at it!
