### ISSUE TITLE
AttributeError("type object 'socket' has no attribute 'error'")

### ISSUE THREAD

**Issue by Mradr** [gevent/gevent#1264]
Running python 3.7 with the newest gevent build..

from gevent.socket import socket

except socket.error as e:

AttributeError("type object 'socket' has no attribute 'error'")

Any way to fix?

**Comment by Mradr** [comment]
Actually, I am going to expand on this if it helps,

https://pastebin.com/F4wSp390

I have the feeling the problem is with in this model, but I am trying to monkey patch the whole thing, but I seem to have different errors every time:

From my __name__ == '__main__':

#from gevent import monkey; monkey.patch_select()# (seems to stop select from working? At least when I enable this - everything just freezes)

#from gevent import monkey; monkey.patch_socket()# (Gives an error that it can't switch threads)

#from gevent import monkey; monkey.patch_thread()# (same as select, everything just seems like it freezes)

**Comment by jamadden** [comment]
I don't see any monkey-patching being done in that sample code.

Remember that `gevent.monkey.patch_all()` should be [done first](http://www.gevent.org/api/gevent.monkey.html#module-gevent.monkey), before any other imports. Unless your `main()` function is in some other file that does *nothing* but import gevent and monkey patch *before* importing that sample code, you're probably monkey patching too late. 

As for the original question:

```python
from gevent.socket import socket

except socket.error as e:

AttributeError("type object 'socket' has no attribute 'error'")
```

`gevent.socket.socket` is a type, just like `socket.socket` is a type. `error` is a class in the `socket` or `gevent.socket` module, not a member of the `socket.socket` or `gevent.socket.socket` type. That said, in Python 3, `socket.error` is just a deprecated alias of the built-in `OSError` class.

**Comment by Mradr** [comment]
I see. Thank you!
