### ISSUE TITLE
Function Decorators dropped when inheriting from gevent.local.local

### ISSUE THREAD

**Issue by bpowers39** [gevent/gevent#1266]
* gevent version: 1.3.4
* Python version: cPython 3.6.5
* Operating System: Red Hat Enterprise Linux Server release 7.5 (Maipo)

### Description:
Sometime between Gevent 1.1.0 and 1.3.4, decorators on classes inheriting from gevent.local.local are dropped. In the example below, the @staticmethod decorator on the class inheriting from gevent.local.local is missing, but the class inheriting from threading.local works as expected.

### Test Case:

```python
import threading
from gevent.local import local

class ThreadingClass(threading.local):
    @staticmethod
    def test_method(*args):
        print(args)

class GeventClass(local):
    @staticmethod
    def test_method(*args):
        print(args)

print("Thread Local")
t = ThreadingClass()
print("Static:")
ThreadingClass.test_method(1, 2, 3)
print("Instance:")
t.test_method(1, 2, 3)

print()
print()

print("Gevent Local")
g = GeventClass()
print("Static:")
GeventClass.test_method(1, 2, 3)
print("Instance:")
g.test_method(1, 2, 3)
```

### Expected Result
The decorators on both ThreadingClass GeventClass work as intended when instances of each class type are created.
```
Thread Local
Static:
(1, 2, 3)
Instance:
(1, 2, 3)


Gevent Local
Static:
(1, 2, 3)
Instance:
(1, 2, 3)
```

### Actual Result
The ```@staticmethod``` decorator on GeventClass is dropped when an instance of the class is created.
```
Thread Local
Static:
(1, 2, 3)
Instance:
(1, 2, 3)


Gevent Local
Static:
(1, 2, 3)
Instance:
(<__main__.GeventClass object at 0x7f66615a6a98>, 1, 2, 3)
```

**Comment by jamadden** [comment]
Thanks for the report! That's definitely a regression in 1.3. (The cause is that `staticmethod` objects are descriptors, which, when invoked, return a plain function object...which *itself* is also a descriptor that produces method objects when invoked.)
