### ISSUE TITLE
Let system’s c-ares and libev use system’s version instead of building them.

### ISSUE THREAD

**Issue by MCApollo** [gevent/gevent#1270]
Edit: **Let c-ares and libev be used (System’s version) if they’re installed instead if building them.**
>Sorry for the typo.

* gevent version: gevent 1.3.5
* Python version: "Cross-compiled python 3.6.4"
* Operating System: “arm64-apple-darwin17 (Jailbroken, yes it works.)"

### Description:

This is not really a issue, more of a request.

Let setup.py have a option to use system libraries and not be forced to compiled its dependencies.

Yes, I can fix configure to bypass the issue, but already having the libraries makes it redundant.

```
configure: error: /bin/sh ./config.sub arm64-apple-darwin17.5.0 failed
```

### What I've run:

pip3 install gevent —no-clean

Thanks for reading this ticket.

**Comment by jamadden** [comment]
You can set the undocumented, unsupported environment variable `EMBED=0` to disable building c-ares and libev when installing from source; this does not work for libuv. This is not recommended and disables certain features of the libev backend.

**Comment by MCApollo** [comment]
Thank you.
