### ISSUE TITLE
Error during build with python-2.7

### ISSUE THREAD

**Issue by yurivict** [gevent/gevent#1272]
```
writing byte-compilation script '/tmp/tmpx5grU4.py'
/usr/local/bin/python2.7 -O /tmp/tmpx5grU4.py
  File "/usr/local/lib/python2.7/site-packages/gevent/_socket3.py", line 222
    def makefile(self, mode="r", buffering=None, *,
                                                  ^
SyntaxError: invalid syntax
```

Version 1.3.6 in the FreeBSD port.

**Comment by jamadden** [comment]
Thanks, that's expected and harmless, that file is not used under Python 2. There are [several other issues in the archives](https://github.com/gevent/gevent/issues?utf8=✓&q=is%3Aissue+SyntaxError) if you'd like to see more.
