### ISSUE TITLE
Occupy  100% cpu

### ISSUE THREAD

**Issue by monsterxx03** [gevent/gevent#1273]
* gevent version: 1.3.5
* Python version: cpython 3.6.5 (official package with ubuntu 18.04)
* Operating System:  Ubuntu 18.04 Linux 4.15.0-1019-aws  x86_64
 
### Description:

Recently I setup a webservice with gunicorn + gevent (flask).

After running for several hours, process cpu usage bump to 100%, but still can respond to client.

Then I removed it from load balancer, no traffic is going to its port, but cpu usage is still 100%.

Use strace -p {pid}, I got

```
epoll_wait(10, [], 64, 1)               = 0
getpid()                                = 13738
epoll_wait(10, [], 64, 1)               = 0
getpid()                                = 13738
epoll_wait(10, [], 64, 1)               = 0
getpid()                                = 13738
epoll_wait(10, [], 64, 1)               = 0
getpid()                                = 13738
epoll_wait(10, [], 64, 1)               = 0
getpid()                                = 13738
epoll_wait(10, [], 64, 1)               = 0
getpid()                                = 13738
epoll_wait(10, [], 64, 1)               = 0
getpid()                                = 13738
epoll_wait(10, [], 64, 1)               = 0
getpid()                                = 13738
epoll_wait(10, [], 64, 1)               = 0
getpid()                                = 13738
epoll_wait(10, [], 64, 1)               = 0
getpid()                                = 13738
epoll_wait(10, [], 64, 1)               = 0
getpid()                                = 13738
epoll_wait(10, [], 64, 1)               = 0
getpid()                                = 13738
epoll_wait(10, [], 64, 1)               = 0
getpid()                                = 13738
epoll_wait(10, [], 64, 1)               = 0
getpid()                                = 13738
epoll_wait(10, [], 64, 1)               = 0
getpid()                                = 13738
epoll_wait(10, [], 64, 1)               = 0
getpid()                                = 13738
epoll_wait(10, [], 64, 1)               = 0
getpid()                                = 13738
epoll_wait(10, [], 64, 1)               = 0
getpid()                                = 13738
....
```

Process  stuck in this infinite  loop (flushing very quick).

If strace on a normal idle process, get same traceback, but frequency is much lower.

I haven't found way to manually reproduce it. Just let service handle requests for several hours, it will happen (seems cpu bumped in one second, not gradually).

I tried to run service with uwsgi, get the same problem after several hours.

The problem may be not caused by gevent directly, any way I can take for further debug? 

Thanks.

**Comment by jamadden** [comment]
Looping through `epoll_wait` with a minimum timeout suggests that there is an active watcher with a minimum timeout. For example, a started `gevent.Timeout` object, or a loop idle watcher. Make sure none of those are leaking and are always closed when finished.

You might also try [a different loop implementation](http://www.gevent.org/loop_impls.html) in case of a bug in the event loop. The libuv loop, in particular, has a `debug()` method that can be used to print all the active watchers.

**Comment by monsterxx03** [comment]
@jamadden Thank you for your help. Finally I get out it's caused by waiting celery's async task's result without a timeout.  I fix it by add the timeout back. I figured it out with tool https://github.com/uber/pyflame

Wired thing is client request already timeout, but the green thread is not killed.
