### ISSUE TITLE
Reading negative length in pywsgi wsgi.input never returns

### ISSUE THREAD

**Issue by tzickel** [gevent/gevent#1274]
* gevent version: master

### Description:

Python sometimes uses read length -1 for reading all (like in file i/o) and sometimes None (like in http)...

When reading a non chunked body in pywsgi from wsgi.input with negative length (or -1) it gets stuck in the read command, the chunked code path has a check for this:

https://github.com/gevent/gevent/blob/1afdb093edb855f2249f3130966988dadff965fd/src/gevent/pywsgi.py#L270

Maybe it's worth adding it in regular read as well before:

https://github.com/gevent/gevent/blob/1afdb093edb855f2249f3130966988dadff965fd/src/gevent/pywsgi.py#L161

Also a minor nitpick (although it seems other frameworks have this issue as well):

If application already sets a Transfer-Encoding: chunked in the headers in start_response, pywsgi will not check it, and add another one (if it deems to use it), resulting in a Transfer-Encoding: chunked, chunked (Might be the same for Content-Length). Maybe those headers should be removed if they are conflicting (when deciding which headers to send) ?

### What I've run:

```python
from gevent.pywsgi import WSGIServer

def app(env, start_response):
  print env['wsgi.input'].read(-1)
  start_response('204 OK', [])
  return []

WSGIServer(('', 1234), app).serve_forever()
```

**Comment by jamadden** [comment]
> Maybe it's worth adding it in regular read as well before:

Maybe? [The specification](https://www.python.org/dev/peps/pep-3333/#input-and-error-streams) only says that "A server **should** allow `read()` to be called without an argument, and return the remainder of the client's input stream.". It doesn't say anything about what "invalid" argument values mean, but the argument for symmetry is strong.

A PR that moves the check from `_do_chunked_read` up to `read()` should be pretty simple and not reduce test coverage; bonus points if it added a specific test for the non-chunked.

> If application already sets a Transfer-Encoding: chunked in the headers in start_response,

I believe that means the application is buggy. The [specification says](https://www.python.org/dev/peps/pep-3333/#handling-the-content-length-header) " applications and middleware **must not** apply any kind of Transfer-Encoding to their output, such as chunking or gzipping; as "hop-by-hop" operations, these encodings are the province of the actual web server/gateway."

**Comment by tzickel** [comment]
What do you suggest on readline ? The wsgiref validator that wraps Input in the testing framework does not allow for passing arguments to readline

**Comment by jamadden** [comment]
Portable applications cannot rely on `readline` accepting an argument at all. Anything there is implementation defined.

**Comment by jamadden** [comment]
Oh, did you meant for *testing* it? I think there are unit tests for the `Input` class itself that should work, or there's `TestInputReadline` that specifically disables the validator for app level tests.

**Comment by tzickel** [comment]
Just a quick question before this issue is closed (unrelated, but I want to know if to open a new issue or it's a wontfix).

When trying to read from Input using env['wsgi.input'].read(size) where size is a number > 31bit (i.e. 2GB) this will trigger:
https://github.com/gevent/gevent/blob/master/src/gevent/pywsgi.py#L182

Shouldn't we be able to handle reading inputs larger than 2GB ? The comment on OverflowError is wrong btw, because it you read the makefile code, it will in the end do a socket read with that length and bork.

**Comment by tzickel** [comment]
Ok, but the comment is still misleading there " # Expecting to read more than 64 bits of data. Ouch!" for someone who is reading the code.
