### ISSUE TITLE
Documentation website navigation 404s

### ISSUE THREAD

**Issue by BrennenSprimont** [gevent/gevent#1280]
### Summary:
Gevent's documentation website navigation bar can lead to 404s.

### Description:
It looks like the links generated on the navigation bar just have the file names and don't include paths. If you travel to a path that is not the base path (example: `www.gevent.org/api/`) the navigation bar fails to get back to the home page and causes 404s from various navigation bar links.

### Steps to reproduce:
 * Starting at the index (http://www.gevent.org/index.html)
 * Clicking navigation bar item "Docs" (http://www.gevent.org/contents.html)
 * Clicking page link "API reference" (http://www.gevent.org/api/index.html)
 * Clicking navigation bar item "Docs" (http://www.gevent.org/api/contents.html)
    * Returns a 404.

### Suggested Solution
Change the navigation bar links to be paths instead of file names.
```
<a id="title href="index.html">gevent</a>
...
<a href="contents.html">Docs</a>
...
<a href="community.html">Mailing list</a>
...
<a href="sfc.html">Donate</a>
```
To:
```
<a id="title href="/index.html">gevent</a>
...
<a href="/contents.html">Docs</a>
...
<a href="/community.html">Mailing list</a>
...
<a href="/sfc.html">Donate</a>
```

**Comment by jamadden** [comment]
Thanks for pointing that out!
