### ISSUE TITLE
CI for 1.3.6 is failing 

### ISSUE THREAD

**Issue by rbreslow** [gevent/gevent#1281]
See: 

* https://travis-ci.org/gevent
* https://travis-ci.org/gevent/gevent/jobs/428114085

**Comment by jamadden** [comment]
Thanks. The gevent test suite is somewhat sensitive to timing issues, and a loaded container on CI sometimes results in false failures. I have been working to resolve these issues in the test suite itself as they are identified, but in the meantime hitting the 'rebuild' button on CI usually fixes the issues---as it did here; what you point to is now green.

**Comment by rbreslow** [comment]
I appreciate your response! That makes sense.
