### ISSUE TITLE
Allow pywsgi server to return different content types response on errors

### ISSUE THREAD

**Issue by hackaugusto** [gevent/gevent#1285]
* gevent version: 1.3.6
* Python version: `Python 3.7.0 (default, Sep 15 2018, 19:13:07) [GCC 8.2.1 20180831] on linux` package `python 3.7.0-4`
* Operating System: ArchLinux

### Description:

The wsgi server has hard coded responses:

https://github.com/gevent/gevent/blob/85d0dd3dbbfa29e2274059d6bcc0b4f5e0e19b19/src/gevent/pywsgi.py#L67-L72

Which are used by the top-level error handler:

https://github.com/gevent/gevent/blob/85d0dd3dbbfa29e2274059d6bcc0b4f5e0e19b19/src/gevent/pywsgi.py#L1029

An application that wants to propagate unhandled exceptions *and* respect the request's `Accept` header has to either monkey patch the globals or reimplement `_send_error_response_if_possible`. I assume both options are not encouraged.

**Comment by hackaugusto** [comment]
> Why would an app want to do that? By definition, an internal error leaves the response in an undefined state. The client isn't going to be getting what they expect, period.

True, my rationale is to be consistent with the response types and to fulfill this [recommendation](https://tools.ietf.org/html/rfc7231#section-6.6):

> the server SHOULD send a representation containing an explanation of the error situation, and whether it is a temporary or permanent condition

The problem is catching an "inflight" exception and being able to respond to the client.

**Comment by jamadden** [comment]
As far as I can see, we are fulfilling that recommendation, within the bounds of security.

> The problem is catching an "inflight" exception and being able to respond to the client.

Apps that want to do that are able to. Very often they'll use a middleware to do so, or their framework will; often this will be configured differently for development vs production. Letting it bubble all the way up to the actual WSGI server leaves very limited options, and the WSGI server should be very conservative in what it does.

**Comment by jamadden** [comment]
There hasn't been any activity on this issue in quite a while, so I'm closing it. Feel free to re-open if there is additional information to add.
