### ISSUE TITLE
Semaphore does not check and notify callbacks on rawlink()

### ISSUE THREAD

**Issue by danmilon** [gevent/gevent#1287]
* gevent version: 1.3.6
* Python version: 3.7.0 from archlinux repos
* Operating System: Linux 4.18.7-arch1-1-ARCH

### Description:

`gevent.wait([semaphore])` does not yield when the semaphore is already ready.

This raises that it would block forever
```python
import gevent.monkey
gevent.monkey.patch_all()
import gevent
import gevent.lock

s = gevent.lock.Semaphore(1)
gevent.wait([s])
```

This works as expected:
```python
s = gevent.lock.Semaphore(1)
s.acquire()
gevent.spawn_later(1, s.release)
gevent.wait([s])
```

I would expect it to work like `gevent.event.Event`, which will notify links when a new callback is registered. If you agree that the semaphore should behave similarly, I'm happy to work on the fix.

**Comment by jamadden** [comment]
It's not clear to me that it should behave like an `Event`. A Semaphore is *not* an event, it's a special-purpose, low-level primitive.
