### ISSUE TITLE
About libev use select backend in Mac OSX..

### ISSUE THREAD

**Issue by CandyMi** [gevent/gevent#1320]
* gevent version:  gevent/1.3.7
* Python version: Python 2.7.13 [PyPy 6.0.0 with Apple LLVM 9.1.0 (clang-902.0.39.1)]
* Operating System: Mac OSX Sierra 10.13.6

### Description:

**Question**: 

Hello!
        I used  locust to test my website today! When I step by step to adjust the amount of concurrency, Throws the following exception. 
       I am not sure gevent use select backend in Apple (or BSD like), And some people Suggest me Open issues in this Project. So, Can I get some Suggestion in from here?

```bash
(venv) bogon:web-benchmarker candy$ locust -f test.py -H http://localhost
[2018-11-28 14:02:59,759] bogon/INFO/locust.main: Starting web monitor at *:8089
[2018-11-28 14:02:59,760] bogon/INFO/locust.main: Starting Locust 0.9.0
[2018-11-28 14:04:02,545] bogon/INFO/locust.runners: Hatching and swarming 5000 clients at the rate 500 clients/s...
[2018-11-28 14:06:00,154] bogon/ERROR/stderr: SystemError: (libev) select: Invalid argument
[2018-11-28 14:06:00,154] bogon/ERROR/stderr: 2018-11-28T06:06:00Z
(venv) bogon:web-benchmarker candy$
```

```bash
(venv) bogon:web-benchmarker candy$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 10240
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited
(venv) bogon:web-benchmarker candy$ 
```

### What I've run:

**REPLACE ME**:

```python
#coding:utf-8
from locust import HttpLocust, TaskSet, task

class UserBehavior(TaskSet):
     #首页
     @task(1)
     def index(self):
         self.client.get("/")

class WebsiteUser(HttpLocust):
    task_set = UserBehavior
    min_wait = 3000
    max_wait = 6000
```

**Comment by jamadden** [comment]
I don't understand what your question is.

**Comment by jamadden** [comment]
Without seeing the code, I don't know what's going on or how to fix it.

Instead of relying on some complex third-party program, can you produce a [short, self contained, correct example](http://sscce.org) that demonstrates your problem? 

If not, if you want anyone to look into it you'll need to link to the source and ideally provide a traceback.
