### ISSUE TITLE
thread ids are different

### ISSUE THREAD

**Issue by chenyuan53618** [gevent/gevent#1329]
* gevent version: latest version
* Python version: 3.5
* Operating System: Ubuntu 16.04

### Description:

```
from gevent import monkey

# monkey.patch_all()
import gevent
import threading

def printer():
    print(threading.current_thread().ident)

def starter():
    print(threading.current_thread().ident)
    jobs = [gevent.spawn(printer), gevent.spawn(printer), gevent.spawn(printer)]
    gevent.joinall(jobs)
    print("all job done")
```
what I got is:
140141676316416
140141676316416
140141676316416
140141676316416
all job done
this is expected since all of them should be in the same thread. However, after doing monkey_patch(uncomment 'monkey.patch_all()'), all the thread id are different:

140444366575464
140444338640968
140444338641224
140444338641480
all job done

why are all of them different? Should all of them be the same still?

**Comment by jamadden** [comment]
They are expected to be different. When you monkey-patch threading, you monkey-patch `threading.current_thread()` to be based on the current *greenlet*, and of course those are different.

```python
# test.py
import gevent.monkey
gevent.monkey.patch_all()

import gevent
import gevent.thread

import threading

def run():
	print('Thread:', threading.current_thread(),
		  'Greenlet Ident', gevent.thread.get_ident(),
		  'Greenlet ID:', id(gevent.getcurrent()))

glets = [gevent.spawn(run) for _ in range(3)]
gevent.wait(glets)
```

```console
$ python test.py
Thread: <_DummyThread(DummyThread-1, started daemon 4539874968)> Greenlet Ident 4539874968 Greenlet ID: 4539874968
Thread: <_DummyThread(DummyThread-2, started daemon 4545003608)> Greenlet Ident 4545003608 Greenlet ID: 4545003608
Thread: <_DummyThread(DummyThread-3, started daemon 4545003912)> Greenlet Ident 4545003912 Greenlet ID: 4545003912
```
