### ISSUE TITLE
When running in main(), NameError appears and the global variable cannot be read(greenlet is the lates version)，whether it is windows or linux.

### ISSUE THREAD

**Issue by perloliu** [gevent/gevent#1330]
# When running in main(), NameError appears and the global variable cannot be read(greenlet is the lates version,python is also)，whether it is windows or linux（Although this is not a problem with gevent itself, but i want to ask for help）.

> C:\Users\57018\Desktop\nothing\venv\Include>python demo_greenlet.py
> -----test1-----
> Traceback (most recent call last):
> File "demo_greenlet.py", line 26, in 
> main()
> File "demo_greenlet.py", line 23, in main
> g1.switch()
> File "demo_greenlet.py", line 8, in test1
> g2.switch()
> NameError: name 'g2' is not defined

```
from greenlet import greenlet
import time


def test1():
    while True:
        print("-----test1-----")
        g2.switch()
        time.sleep(1)


def test2():
    while True:
        print("-----test2-----")
        g1.switch()
        time.sleep(1)


def main():
    g1 = greenlet(test1)
    g2 = greenlet(test2)
    
    g1.switch()

if __name__ == "__main__":
    main()
```
## But it can run successfully like this:

> C:\Users\57018\Desktop\nothing\venv\Include>python demo_greenlet.py
> -----test1-----
> -----test2-----
> -----test1-----
> -----test2-----
> -----test1-----
> -----test2-----
> -----test1-----
> -----test2-----
> -----test1-----
> -----test2-----
> -----test1-----
> -----test2-----

```
from greenlet import greenlet
import time


def test1():
    while True:
        print("-----test1-----")
        g2.switch()
        time.sleep(1)


def test2():
    while True:
        print("-----test2-----")
        g1.switch()
        time.sleep(1)


g1 = greenlet(test1)
g2 = greenlet(test2)
    
g1.switch()
```
## So I want to know why, or if there is a bug, or if there is a problem with my usage, please advise, thank you.

**Comment by perloliu** [comment]
The same problem with linux.

**Comment by jamadden** [comment]
This is a basic problem with the program. `g1` and `g2` are local variables, not global variables. They are only visible in the `main` function.

**Comment by perloliu** [comment]
> 这是该程序的基本问题。`g1`并且`g2`是局部变量，而不是全局变量。它们仅在`main`函数中可见。

Thank you very much. I discovered this in the near future.
