### ISSUE TITLE
100% cpu when has 1000 greenlets

### ISSUE THREAD

**Issue by beruhan** [gevent/gevent#1332]
I use gevent in a IO intensive task,  one producer,one thousand consumers,and a Queue.I fount the CPU usage has always 100%，Is there any way to reduce the  cpu usage?

env as follows:

- gevent version: 1.3.5, libev
- Python version: cpython 3.6.5 (official package with ubuntu 18.04)
- Operating System: Ubuntu 18.04 Linux 4.15.0-1019-aws x86_64

The code is as follows：

```python
import gevent.monkey

gevent.monkey.patch_all()
gevent.monkey.patch_sys()

import signal
from sys import stdin
from sys import stdout

import gevent
from gevent.queue import Queue


def consumer(queue, config):
    """handle something and write to stdout"""
    for line in queue:
        res = handle_many_io_related_things()
        stdout.write(res + "\n")
        stdout.flush()
        gevent.sleep(0.0001)
    # greenlet stop
    queue.put(StopIteration)


def producer(queue):
    """read from stdin"""
    for line in stdin:
        if not line:
            break
        queue.put(line)
        gevent.sleep(0.0001)
    queue.put(StopIteration)


if __name__ == "__main__":
    gevent.signal(signal.SIGQUIT, gevent.kill)
    senders = 1000
    queue = Queue(maxsize=10000)
    tasks = list()
    tasks.append(gevent.spawn(producer, queue))
    tasks.extend(gevent.spawn(consumer, queue) for i in range(senders))
    gevent.joinall(tasks)

```

**Comment by beruhan** [comment]
can anyone help me?

**Comment by jamadden** [comment]
Have you profiled to see where the time is being spent? Without that, anything anybody said would be (educated) guesses. For example, you seem to be doing a lot of busy waiting loops (calls to `sleep()`); that's often suspicious (forcing greenlets to be scheduled to sleep and wakeup instead of letting them be event driven).

**Comment by tamara-bain** [comment]
What would be the best way to profile something like this? I'm facing the same issue.

**Comment by jamadden** [comment]
(Standard profilers work well to get an overview of what the process as a whole is doing. I currently like py-spy, with native profiling enabled.)

Other than that, there hasn't been any activity on this issue in quite a while, so I'm closing it. Feel free to re-open if there is additional information to add.

**Comment by alok2k5ingh** [comment]
> Have you profiled to see where the time is being spent? Without that, anything anybody said would be (educated) guesses. For example, you seem to be doing a lot of busy waiting loops (calls to `sleep()`); that's often suspicious (forcing greenlets to be scheduled to sleep and wakeup instead of letting them be event driven).

@jamadden I think I'm seeing similar issue of this busy waiting loops in my profile. I using gevent worker class in gunicorn for my django service, which has mysql and redis as well. So in my profile, the cpu time for sleep function increases when there are about 20 to 25 requests on a 4 vcpu aws containers. How can i increase my throuput please guide i'm stuck. 
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/41323382/227717496-fb5fc9f4-3c48-40b1-aa9d-0d7f8b599f63.png">
