### ISSUE TITLE
AttributeError: module 'gevent' has no attribute 'spawn'

### ISSUE THREAD

**Issue by beisimm** [gevent/gevent#1333]
* gevent version:1.3.7
* Python version: Please be as specific as possible: "cPython 3.7.0 downloaded from python.org"
* Operating System: Please be as specific as possible: "windows10"

### Description:

**REPLACE ME**: What are you trying to get done, what has happened, what went wrong, and what did you expect?

```
Remember to put tracebacks in literal blocks
```

### What I've run:

AttributeError: module 'gevent' has no attribute 'spawn'

```python
import gevent

def eat():
    while True:
        print("eat")
        gevent.sleep(1)

def speak():
    while True:
        print('speak')
        gevent.sleep(1)

def main():
    spand_chi = gevent.spawn(eat)
    spand_chi.join()

if __name__ == '__main__':
    main()
```

**Comment by jamadden** [comment]
That attribute definitely exists in the `gevent` module:
```pycon
Python 3.7.1 (default, Oct 21 2018, 09:01:26)
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent
>>> gevent.__version__
'1.3.7'
>>> gevent.spawn
<bound method Greenlet.spawn of <class 'gevent._greenlet.Greenlet'>>
```

So I suspect we're looking at some sort of installation problem. There's not a lot I can do to diagnose that remotely, but some things you can look at include:

- What's the output of `print(gevent)` and `print(dir(gevent))`?

```pycon
>>> print(gevent)
<module 'gevent' from '//tmp-3f64795374346eb9/lib/python3.7/site-packages/gevent/__init__.py'>
None
>>> print(dir(gevent))
['Greenlet', 'GreenletExit', 'Timeout', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__greenlet_primitives', '__hub_local', '__hub_primitives', '__ident', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '__waiter', '_compat', '_config', '_greenlet', '_greenlet_primitives', '_hub_local', '_hub_primitives', '_ident', '_signal_class', '_signal_metaclass', '_signal_module', '_tblib', '_util', '_version_info', '_waiter', 'absolute_import', 'config', 'exceptions', 'fork', 'get_hub', 'getcurrent', 'getswitchinterval', 'greenlet', 'hub', 'idle', 'iwait', 'joinall', 'kill', 'killall', 'libev', 'namedtuple', 'os', 'reinit', 'setswitchinterval', 'signal', 'signal_handler', 'sleep', 'spawn', 'spawn_later', 'spawn_raw', 'timeout', 'version_info', 'wait', 'with_timeout']
```

- Is there anything unusual in the output of `python -vv -c 'import gevent'`?

- Can you reproduce this in a fresh virtual environment? If so, in another fresh virtual environment, is there anything interesting in the output of `pip install -v gevent`?

**Comment by beisimm** [comment]
``>>> import gevent
>>> gevent.spawn
<bound method Greenlet.spawn of <class 'gevent._greenlet.Greenlet'>>
>>> print(gevent)
<module 'gevent' from 'C:\\Users\\Administrator\\PycharmProjects\\untitled\\venv\\lib\\site-packages\\gevent\\__init__.py'>
>>> print(dir(gevent))
['Greenlet', 'GreenletExit', 'Timeout', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__greenlet_primitives', '__hub_local', '__hub_primitives',
'__ident', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '__waiter', '_compat', '_config', '_ffi', '_greenlet', '_greenlet_primiti
ves', '_hub_local', '_hub_primitives', '_ident', '_interfaces', '_signal_class', '_signal_metaclass', '_signal_module', '_tblib', '_util', '_version_info', '_waiter
', 'absolute_import', 'config', 'exceptions', 'get_hub', 'getcurrent', 'getswitchinterval', 'greenlet', 'hub', 'idle', 'iwait', 'joinall', 'kill', 'killall', 'libuv
', 'namedtuple', 'os', 'reinit', 'setswitchinterval', 'signal', 'signal_handler', 'sleep', 'spawn', 'spawn_later', 'spawn_raw', 'timeout', 'version_info', 'wait', '
with_timeout']

**Comment by jamadden** [comment]
OK, so you just demonstrated that your `gevent` module *does* have the `spawn` attribute. If some particular program isn't working, it's something else in your environment. (Try looking in pycharm's settings for 'gevent'.)
