### ISSUE TITLE
What's the relationship between gevent and pypy?

### ISSUE THREAD

**Issue by iamybj** [gevent/gevent#1337]
What's the relationship between gevent and pypy?
I want to use pypy for better performance, and use gevent for better concurrency. Do they can be used  together in a wsgi project?
I searched in google, but don't find solutions that use both gevent and pypy.

**Comment by jamadden** [comment]
Yes, gevent supports PyPy. See the classifiers either in [setup.py](https://github.com/gevent/gevent/blob/master/setup.py#L399) or [on PyPI](https://pypi.org/project/gevent/), or gevent's own documented [supported platforms](http://www.gevent.org/install.html#supported-platforms).
