### ISSUE TITLE
time.sleep change the thread id

### ISSUE THREAD

**Issue by chenyuan53618** [gevent/gevent#1342]
gevent version: latest version
Python version: 3.5
Operating System: Ubuntu 16.04

### Description:

```
import gevent
from gevent import monkey

monkey.patch_all()

import time
import threading


def printer():
    print('Thread:', threading.current_thread(),
          'Greenlet Ident', gevent.thread.get_ident(),
          'Greenlet ID:', id(gevent.getcurrent()))
    # time.sleep(1)


if __name__ == '__main__':
    current_thread = threading.current_thread()
    print(current_thread.ident)
    threading.Thread(target=printer).start()
    threading.Thread(target=printer).start()
    threading.Thread(target=printer).start()
```
and the result is :
```
Thread: <Thread(Thread-1, started 140354195269704)> Greenlet Ident 140354195269704 Greenlet ID: 140354195269704
Thread: <Thread(Thread-2, started 140354195269704)> Greenlet Ident 140354195269704 Greenlet ID: 140354195269704
Thread: <Thread(Thread-3, started 140354195269704)> Greenlet Ident 140354195269704 Greenlet ID: 140354195269704

```
This is expected since gevent monkey patch will transform threading into coroutine which all have the same thread id. However, after uncomment 'time.sleelp', the thread ids all change:

```
import gevent
from gevent import monkey

monkey.patch_all()

import time
import threading


def printer():
    print('Thread:', threading.current_thread(),
          'Greenlet Ident', gevent.thread.get_ident(),
          'Greenlet ID:', id(gevent.getcurrent()))
    time.sleep(1)


if __name__ == '__main__':
    current_thread = threading.current_thread()
    print(current_thread.ident)
    threading.Thread(target=printer).start()
    threading.Thread(target=printer).start()
    threading.Thread(target=printer).start()
```

```

Thread: <Thread(Thread-1, started 140540632344648)> Greenlet Ident 140540632344648 Greenlet ID: 140540632344648
Thread: <Thread(Thread-2, started 140540632344904)> Greenlet Ident 140540632344904 Greenlet ID: 140540632344904
Thread: <Thread(Thread-3, started 140540632345160)> Greenlet Ident 140540632345160 Greenlet ID: 140540632345160
```

Could someone explain me why?

**Comment by jamadden** [comment]
On CPython, `id()` of an object is just its memory address, and a thread identifier is also just a memory address. On CPython, allocating and deleting an object and then allocating another object will tend to have that second object using the same memory address as the first object. (You can imagine it sort of like a stack). 

Without any switches into the hub, (when `sleep()` is commented out), your example is serially allocating and deleting objects and then allocating and deleting objects again. What you're seeing is just the memory addresses getting reused.

Adding the `sleep()` prevents the deallocation from happening before the next allocation needs to happen, so you see separate addresses. 

If you try a Python implementation with a more nuanced allocation pattern, such as PyPy, you'll probably see different results.
