### ISSUE TITLE
UserWarning from libuv on every line from jupyter consoles

### ISSUE THREAD

**Issue by astechow** [gevent/gevent#1347]
* gevent version: 1.4.0
* Python version: Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] using Jupyter QtConsole 4.2.1
* Operating System: Windows 7 64-bit / Windows 10 64-bit

### Description:

After monkey patching when using the Jupyter QtConsole (`gevent.monkey.patch_all()` or more specifically `gevent.monkey.patch_time()`), I receive the following message after every single line I execute:
```
C:\Program Files\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\site-packages\gevent\hub.py:154: UserWarning: libuv only supports millisecond timer resolution; all times less will be set to 1 ms
  with loop.timer(seconds, ref=ref) as t:
```

### What I've run:

```python
from gevent import monkey
monkey.patch_all()
```

This produces no errors in a regular python session started from the command line, but will generate a warning in all Jupyter-related sessions (iPython Qt console, Jupyter notebook, Jupyter lab).
I suspect that these sessions somehow call sleep() with a value of less than 0.001. I don't know if this issue should best be addressed on the gevent side or with jupyter.

**Comment by jamadden** [comment]
There's nothing gevent can do, and I believe the warning is valid; your session isn't going to be behaving as the Jupyter developers intended. If the warning bothers you, suppress it with the PYTHONWARNINGS environment variable or by calling [one of the `warnings` functions](https://docs.python.org/3/library/warnings.html#overriding-the-default-filter).

(Historically, it hasn't been safe to monkey-patch inside a jupyter/ipython session. I'm pleased that at least something seems to be working for you.)

**Comment by astechow** [comment]
It has been performing great (as far as I can tell) in jupyter! I use gevent through grequests fyi.

I agree with gevent not being able to do much here, and am fine with having this issue closed.

For future reference to users with similar issues, the following code called before monkey patching will disable the warning (along with all other `UserWarning`):
```python
import warnings
warnings.simplefilter("ignore", category=UserWarning)
```

**Comment by jamadden** [comment]
Thanks for the report! I wish there was a happier resolution, but at least this will be searchable now.

**Comment by imanojkumar** [comment]
doesn't work on Windows 10, anaconda 3.7 x64 bit

**Comment by fhrt811** [comment]
@imanojkumar Try this

import warnings
warnings.filterwarnings('ignore')
