### ISSUE TITLE
Notes on minor regression on select.select from 1.2a1

### ISSUE THREAD

**Issue by carsonip** [gevent/gevent#1348]
* gevent version: 1.2a1+
* Python version: Python 2.7.12 from Ubuntu apt
* Operating System: Ubuntu 16.04

### Description:

Upgrading from 1.1.2 to 1.3.7, this error is observed:
```
ValueError: filedescriptor out of range in select()
```
traceback:
```
File "venv/local/lib/python2.7/site-packages/imapclient/imapclient.py", line 791, in idle_check
    rs, _, _ = select.select([sock], [], [], timeout)
File "venv/local/lib/python2.7/site-packages/gevent/select.py", line 145, in select
    sel_results = _original_select(rlist, wlist, xlist, 0)
ValueError: filedescriptor out of range in select()\n
```

After some digging around, this is due to the change in gevent `select.select` implementation from 1.2a1. The original `select.select` is used in the update. My application is probably creating too many sockets and the original `select.select` is limited to 1024 fd afaik. The use of `select.select` in imapclient should suffer from this error without gevent, or with gevent 1.2a1+ but not with the older versions of gevent.

It would be nice if this could be added as a note in "Changes for gevent 1.2" or "What’s new in gevent 1.2" in case some users like me rely on the old gevent implementation of `select.select`.

Now I suppose I have to patch imapclient to replace the use of `select.select` by `poll` or something else. (Maybe I can simply read from the socket because it is already monkeypatched?)

Also please let me know if there is anything wrong in my analysis or if there is any smarter workaround.

**Comment by carsonip** [comment]
Just finished changing the imapclient code, might as well run it by you to make sure I don't make any rookie mistakes.

Before:
```
    @require_capability('IDLE')
    def idle_check(self, timeout=None):
        sock = self._sock

        # make the socket non-blocking so the timeout can be
        # implemented for this call
        sock.settimeout(None)
        sock.setblocking(0)
        try:
            resps = []
            rs, _, _ = select.select([sock], [], [], timeout)
            if rs:
                while True:
                    try:
                        line = self._imap._get_line()
                    except (socket.timeout, socket.error):
                        break
                    except IMAPClient.AbortError:
                        # An imaplib.IMAP4.abort with "EOF" is raised
                        # under Python 3
                        err = sys.exc_info()[1]
                        if 'EOF' in err.args[0]:
                            break
                        else:
                            raise
                    else:
                        resps.append(_parse_untagged_response(line))
            return resps
        finally:
            sock.setblocking(1)
            self._set_read_timeout()
```

After:
```
    @require_capability('IDLE')
    def idle_check(self, timeout=None):
        resps = []
        try:
            while True:
                try:
                    self._sock.settimeout(timeout)
                    line = self._imap._get_line()
                    timeout = 0.0
                except (socket.timeout, socket.error):
                    break
                except IMAPClient.AbortError:
                    # An imaplib.IMAP4.abort with "EOF" is raised
                    # under Python 3
                    err = sys.exc_info()[1]
                    if 'EOF' in err.args[0]:
                        break
                    else:
                        raise
                else:
                    resps.append(_parse_untagged_response(line))
        finally:
            self._set_read_timeout()
        return resps
```

**Comment by jamadden** [comment]
Thanks for the report. That's intended to be covered under the "standard library compatibility: select" section of [the release notes](http://www.gevent.org/changelog_1_2.html#select-poll):

> If `gevent.select.select()` is given closed or invalid file descriptors in any of its lists, raise the appropriate EBADF exception *like the standard library does*. Previously, libev would tend to return the descriptor as ready. In the worst case, this adds an extra system call, but may also reduce latency if descriptors are ready at the time of entry.

**Comment by carsonip** [comment]
Right. I didn't relate that paragraph to the fd limit. Thanks.

**Comment by jhatch28** [comment]
@carsonip did your patch to just read from the socket in `imapclient` work? I'm encountering this _exact_ issue right now with `imapclient`

**Comment by carsonip** [comment]
@jhatch28 Yes it works.

But there is an issue with large response regardless of the fix where `self._imap._get_line()` returns `SSLWantReadError` because data flows in too slowly and the next call of get line returns unexpected response (residue of last call). This happens with the original implementation anyway. This can be reproduced when you are using IDLE and read/unread the whole page in gmail.
