### ISSUE TITLE
Allow execution of only offline tests

### ISSUE THREAD

**Issue by scarabeusiv** [gevent/gevent#1349]
* gevent version: 1.4.0
* Python version: 3.7.1 from openSUSE
* Operating System: openSUSE Leap 15.0 x86_64"

### Description:

When distributing gevent in openSUSE we would like to execute the tests for basic sanity checking, yet we do this contained on servers that for security purposes do not have access to the internet.

Gevent testsuite sadly does not account for this and as such some of the tests will fail because there is expectation to query stuff from running servers.

Would it be possible to add switch/enviroment variable that would allow us to skip all the online tests and in turn do at least basic validation of the codebase?

**Comment by jamadden** [comment]
The gevent testrunner (`python -mgevent.tests`) accepts a `--ignore` option. This option is a list of filenames, and each file is a list of test files to skip running. gevent uses this to run various subsets of tests with different options (e.g., 
https://github.com/gevent/gevent/blob/master/src/gevent/tests/tests_that_dont_do_leakchecks.txt). You could use this to pass a list of test files you want to skip in your environment.

**Comment by scarabeusiv** [comment]
That sounds useful for my case indeed, I will try to use it Today and follow up here.

**Comment by scarabeusiv** [comment]
Okay, I've got news; seems that I was able to skip the network tests, now I still have 8 failing tests
[build.log](https://github.com/gevent/gevent/files/2821160/build.log)

Any chance these are flaky or should I dig into them more?

We do build in loops where first we build against python2 and then on python3 as such when I manage to get the python2 tests pass we still might find something more on python3.

**Comment by jamadden** [comment]
Several of the failures are due to missing test dependencies:
```
[   13s] [0m| GEVENT_RESOLVER=thread /usr/bin/python2 -u -mgevent.tests.test__hub
[   13s]   .../home/abuild/rpmbuild/BUILDROOT/python-gevent-1.4.0-0.x86_64/usr/lib64/python2.7/site-packages/gevent/_monitor.py:282: MonitorWarning: Unable to monitor memory usage. Install psutil.
[   13s]     MonitorWarning)
[   13s]   F...........
[   13s]   ======================================================================
[   13s]   FAIL: test_blocking_this_thread (__main__.TestPeriodicMonitoringThread)
[   13s]   ----------------------------------------------------------------------
[   13s]   Traceback (most recent call last):
[   13s]     File "/home/abuild/rpmbuild/BUILDROOT/python-gevent-1.4.0-0.x86_64/usr/lib64/python2.7/site-packages/gevent/testing/errorhandler.py", line 48, in wrapper
[   13s]       return method(self, *args, **kwargs)
[   13s]     File "/home/abuild/rpmbuild/BUILDROOT/python-gevent-1.4.0-0.x86_64/usr/lib64/python2.7/site-packages/gevent/testing/errorhandler.py", line 35, in wrapper
[   13s]       return method(self, *args, **kwargs)
[   13s]     File "/home/abuild/rpmbuild/BUILDROOT/python-gevent-1.4.0-0.x86_64/usr/lib64/python2.7/site-packages/gevent/testing/testcase.py", line 88, in wrapper
[   13s]       return method(self, *args, **kwargs)
[   13s]     File "/home/abuild/rpmbuild/BUILDROOT/python-gevent-1.4.0-0.x86_64/usr/lib64/python2.7/site-packages/gevent/tests/test__hub.py", line 207, in test_blocking_this_thread
[   13s]       self.assertEqual(2, len(monitor.monitoring_functions()))
[   13s]   AssertionError: 2 != 1
[   13s]   
```

Several more of the failures are because this is an incomplete build, missing the CFFI and libuv backends: 
```
[   10s]   ======================================================================
[   10s]   ERROR: test_gevent_libuv_watcher (__main__.TestExec)
[   10s]   ----------------------------------------------------------------------
[   10s]   Traceback (most recent call last):
[   10s]     File "/home/abuild/rpmbuild/BUILDROOT/python-gevent-1.4.0-0.x86_64/usr/lib64/python2.7/site-packages/gevent/tests/test__execmodules.py", line 23, in test
[   10s]       six.exec_(src, {'__file__': path})
[   10s]     File "/home/abuild/rpmbuild/BUILDROOT/python-gevent-1.4.0-0.x86_64/usr/lib64/python2.7/site-packages/gevent/testing/six.py", line 30, in exec_
[   10s]       exec("""exec code in globs, locs""")
[   10s]     File "<string>", line 1, in <module>
[   10s]     File "<string>", line 8, in <module>
[   10s]   ImportError: cannot import name _corecffi
[   10s]   
[   10s]   ----------------------------------------------------------------------
```

The simplest way to rectify those issues is to install the full set of requirements, as specified in `dev-requirements.txt`.

One of the failures is due to a very unusual errno value:
```
   18s] [0m| GEVENT_RESOLVER=thread /usr/bin/python2 -u -mgevent.tests.test__socket
[   18s]   .F.......s............
[   18s]   ======================================================================
[   18s]   FAIL: test_refuses (__main__.TestCreateConnection)
[   18s]   ----------------------------------------------------------------------
[   18s]   Traceback (most recent call last):
[   18s]     File "/home/abuild/rpmbuild/BUILDROOT/python-gevent-1.4.0-0.x86_64/usr/lib64/python2.7/site-packages/gevent/testing/errorhandler.py", line 48, in wrapper
[   18s]       return method(self, *args, **kwargs)
[   18s]     File "/home/abuild/rpmbuild/BUILDROOT/python-gevent-1.4.0-0.x86_64/usr/lib64/python2.7/site-packages/gevent/testing/errorhandler.py", line 35, in wrapper
[   18s]       return method(self, *args, **kwargs)
[   18s]     File "/home/abuild/rpmbuild/BUILDROOT/python-gevent-1.4.0-0.x86_64/usr/lib64/python2.7/site-packages/gevent/testing/testcase.py", line 88, in wrapper
[   18s]       return method(self, *args, **kwargs)
[   18s]     File "/home/abuild/rpmbuild/BUILDROOT/python-gevent-1.4.0-0.x86_64/usr/lib64/python2.7/site-packages/gevent/tests/test__socket.py", line 361, in test_refuses
[   18s]       self.assertIn('refused', str(ex).lower())
[   18s]   AssertionError: 'refused' not found in '[errno -2] name or service not known'
[   18s]   
[   18s]   ----------------------------------------------------------------------
```

I don't know what causes that.

One example finished much faster than expected:
```
[   44s]   ======================================================================
[   44s]   FAIL: test_runs (gevent.testing.testcase.Test_dns_mass_resolve.py)
[   44s]   ----------------------------------------------------------------------
[   44s]   Traceback (most recent call last):
[   44s]     File "/home/abuild/rpmbuild/BUILDROOT/python-gevent-1.4.0-0.x86_64/usr/lib64/python2.7/site-packages/gevent/tests/test__examples.py", line 57, in test_runs
[   44s]       self.assertGreaterEqual(took, min_time)
[   44s]   AssertionError: 0.2311241626739502 not greater than or equal to 2
[   44s]   
[   44s]   ----------------------------------------------------------------------
```

This is using DNS to resolve a bunch of host names. I suppose its possible that you have DNS disabled and so it errored out very quickly?

The remaining failure is in a standard library test, something out of my control:
```
   27s]   ======================================================================
[   27s]   FAIL: test_options (__main__.ContextTests)
[   27s]   ----------------------------------------------------------------------
[   27s]   Traceback (most recent call last):
[   27s]     File "/tmp/test_ssllc6WtN.py", line 750, in test_options
[   27s]       ctx.options)
[   27s]   AssertionError: 2181038164 != 2181169236L
[   27s]   
[   27s]   ----------------------------------------------------------------------
```

Perhaps your distro changes the standard SSL module in a way that's not compatible with the upstream CPython tests?

**Comment by scarabeusiv** [comment]
Oky found out what broke the cffi generation, but now I have different problem :) I compile in libuv as a bundle instead of using system version. Would it be possible to have LIBUV_EMBED variable like with LIBEV and CARES? 
[build.log](https://github.com/gevent/gevent/files/2821988/build.log)


For the rest with the crypto library it seems to be code to skip it on travis testing/patched_tests_setup.py (and it seems I would need this skipped every time as we probably have openssl-1.1 while this check was written against openssl-1.0:

```    if TRAVIS:                                                                 
        disabled_tests += [                                                    
            # When we moved to group:travis_latest and dist:xenial,            
            # this started returning a value (33554432L) != 0; presumably      
            # because of updated SSL library? Only on CPython.                 
            'test_ssl.ContextTests.test_options',     
```

I state dependencies equal to the dev things (except of perf and coverage things); so if I screwed up when I rewrote them let me know, but it seems I have them all:

https://build.opensuse.org/package/view_file/devel:languages:python/python-gevent/python-gevent.spec?expand=1

**Comment by scarabeusiv** [comment]
Also for the socket test there is variable greentest.DEFAULT_LOCAL_HOST_ADDR used in all other tests and this one uses DEFAULT_BIND_ADDR, but I dunno what is the difference between them.

**Comment by jamadden** [comment]
>  I compile in libuv as a bundle instead of using system version. Would it be possible to have LIBUV_EMBED variable like with LIBEV and CARES?

Unfortunately, I haven't been able to make that work 😢  I don't remember the details, it's possible it was mostly a problem on Windows. I would like to offer that as an option. (However, we've also had to apply patches to libuv in the past. Currently we're not doing that on *ix platforms, but we are on Windows.) Maybe I can go through and add some additional skip decorators to avoid those tests for now.

I am hoping to be able to transition to a default libuv/cffi backend and eventually eliminate the Cython libev backend in the future.

**Comment by scarabeusiv** [comment]
While I was vacationing Antonio fixed the two major failing tests:
[fix-tests.txt](https://github.com/gevent/gevent/files/2850728/fix-tests.txt)

And had to remove testCongestion as it timeouted for no aparent reason:
[remove-testCongestion.txt](https://github.com/gevent/gevent/files/2850731/remove-testCongestion.txt)

With this we actually have building and tested package all around.
