### ISSUE TITLE
_socket3.py SyntaxError with python27

### ISSUE THREAD

**Issue by AgainstWind** [gevent/gevent#1353]
* gevent version: 1.3.6
* Python version: Please be as specific as possible: "cPython 2.7.9 downloaded from python.org"
* Operating System: Please be as specific as possible: "Raspbian (Debian Linux 8.0 Linux 4.9.35-v7+  armv7l)"

### Description:
```
/usr/lib/rpm/sepdebugcrcfix: Updated 16 CRC32s, 0 CRC32s did match.
17084 blocks
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 0
Bytecompiling .py files below /root/yuezht/gevent-1.3.6/build/bdist.linux-x86_64/rpm/BUILDROOT/gevent-1.3.6-1.x86_64/usr/lib64/python2.7 using /usr/bin/python2.7
Compiling /root/yuezht/gevent-1.3.6/build/bdist.linux-x86_64/rpm/BUILDROOT/gevent-1.3.6-1.x86_64/usr/lib64/python2.7/site-packages/gevent/_socket3.py ...
  File "/usr/lib64/python2.7/site-packages/gevent/_socket3.py", line 222
    def makefile(self, mode="r", buffering=None, *,
                                                  ^
SyntaxError: invalid syntax

Compiling /root/yuezht/gevent-1.3.6/build/bdist.linux-x86_64/rpm/BUILDROOT/gevent-1.3.6-1.x86_64/usr/lib64/python2.7/site-packages/gevent/_socket3.py ...
  File "/usr/lib64/python2.7/site-packages/gevent/_socket3.py", line 222
    def makefile(self, mode="r", buffering=None, *,
                                                  ^
SyntaxError: invalid syntax
```

and i trt to solve this problem with:
1: add ' %define _python_bytecompile_errors_terminate_build 0' to spec
2. add follow content to spec
 %global __os_install_post /usr/lib/rpm/redhat/brp-compress %{!?__debug_package:/usr/lib/rpm/redhat/brp-strip %{__strip}} /usr/lib/rpm/redhat/brp-strip-static-archive %{__strip} /usr/lib/rpm/redhat/brp-strip-comment-note %{__strip} %{__objdump} /usr/lib/rpm/redhat/brp-python-hardlink

but it does not work

```
Remember to put tracebacks in literal blocks
```

### What I've run:

python setup.py bdist_rpm

```python
"Put python code in python blocks"
```

**Comment by jamadden** [comment]
Thanks for the report. There are other (closed) threads on this tracker about writing specs for RPMs that ignore this, if you search you should be able to find them.
