### ISSUE TITLE
Running blocking operations

### ISSUE THREAD

**Issue by idokoren1** [gevent/gevent#1358]
* gevent version: 1.4.0
* Python version: Please be as specific as possible: "cPython 3.6.1 downloaded from brew"
* Operating System: Please be as specific as possible: "Darwin Kernel Version 16.7.0"

### Description:

In my application I need to have few blocking (non-cooperative) operations from time to time.
This application uses gevent and i'm trying to find elegant way to start OS thread where the blocking operation will run without limiting the other greenlets.

Found this gem in the documentation:

[gevent.hub](http://www.gevent.org/api/gevent.hub.html#gevent.hub.Hub
)
> threadpool
> The threadpool associated with this hub.
> 
> Usually this is a gevent.threadpool.ThreadPool, but you can customize that.
> 
> Use this object to schedule blocking (non-cooperative) operations in a different thread to prevent them from halting the event loop.

I'm not sure how to use threadpool object for this purpose.
can you please give example of such use or any other recommended method to run blocking threads?

is the other native thread can run his own hub and run greenlets himself?

Thanks

**Comment by jamadden** [comment]
See [the documentation](http://www.gevent.org/api/gevent.threadpool.html) for how to use the threadpool. The method you use will vary depending on your use cases; `apply` is perfect for running a single blocking operation such as `os.read`, `imap` and `map` are the simplest to work with multiple data on the same operation, and `spawn` is useful when multplie tasks do different things and are of unbounded length.

You may also consider the [ThreadPoolExecuter](http://www.gevent.org/api/gevent.threadpool.html#gevent.threadpool.ThreadPoolExecutor), or even use `gevent.monkey.get_original('_thread', 'start_new_thread')` to directly access a new native thread. Keep in mind, though, that in a monkey-patched system, `threading.Lock` and other things only work with greenlets on a single thread and do *not* correctly synchronize across hubs.

While you can create secondary hubs in non-main threads, that usually complicates things and I generally don't suggest it.
