### ISSUE TITLE
Error output should use logging module, or at least include time stamps

### ISSUE THREAD

**Issue by denik** [gevent/gevent#137]
When gevent catches most errors, it calles traceback.print_exception and writes to sys.stderr directly. 

It would be better to use the logging module, to give developers and administrators more control.

Absent that, the output should at least have timestamps.
<p><a href="http://code.google.com/p/gevent/issues/detail?id=137">Reported by j1mf4n.</a></p>

**Comment by fletom** [comment]
+1, it seems impossible to stop gevent from polluting stderr and when your tests have dozens of normal/expected "errors" in them it gets quite frustrating indeed

**Comment by dvdotsenko** [comment]
@fletom 

Until the underlying issue is fixed we use:

```python
@contextmanager
def silence_stderr():
    original_stderr = sys.stderr
    sys.stderr = open(os.devnull, 'w')
    yield
    sys.stderr = original_stderr
```

```
with silence_stderr():
    # do noise-producing op here
```

**Comment by fletom** [comment]
@dvdotsenko Thanks for the tip!

**Comment by jamadden** [comment]
See also #106 and (this comment)[https://github.com/gevent/gevent/issues/106#issuecomment-115409644] for a possible reason not to use logging.

**Comment by jamadden** [comment]
In addition to the lock problem in logging (which I think is solved now), an additional problem in using a logger is that many times the error reported is called directly in the hub, so the state of the system is somewhat precarious, and blocking functions aren't allowed. It's not hard to come up with a logging configuration that, when called from the hub's `print_exception` function, raises either `LoopExit` or `AssertionError`. Using the `DatagramHandler` will do it, as will the SysLogHandler. I'm not sure we can allow arbitrary code execution to report errors without substantial overhead (i.e., queuing to a background greenlet, which has its own reliability concerns).
