### ISSUE TITLE
Question: Monkey patching and threading.Lock and threading.RLock

### ISSUE THREAD

**Issue by abdelrahman-t** [gevent/gevent#1381]
I have been looking through the documentation to get some information on the behavior of threading.Lock and threading.RLock after monkey patching. Could you provide some insights on their behavior with greenthreads? 

Thank you, Gevent is awesome btw.

**Comment by jamadden** [comment]
They work just like they would work with threads, except with greenlets?

If there's something specific you want to know, perhaps I can provide a more specific answer.

**Comment by jamadden** [comment]
In short, yes. If you call `gevent.monkey.patch_all()` at the very beginning of your program, then new uses of `threading.[R]Lock` will use cooperative (gevent) locks.
