### ISSUE TITLE
Gevent queue and multiprocessing Process

### ISSUE THREAD

**Issue by SachaLhopital** [gevent/gevent#1383]
* gevent version: 1.1.0
* Python version: Python 2.7.6 downloaded from python.org
* Operating System: Ubuntu 14.04.5 LTS Trusty Tahr

### Description:

I have a gevent.queue writting some data inside an lmdb database. I want to create 4 distinct processes that will fill up this queue and wait until all the data is saved in the database (and therefore the queue is empty). I manage to reproduce my situation with the following code : 

```python

import gevent.queue
import lmdb
import time

from multiprocessing import Process

def populate_queue(queue, process_id):

    print "Queue id :", str(id(queue))

    for x in range(1, 10):
        print "Adding ", (str(x) + str(process_id), x), " to the queue !"
        queue.put((str(x) + str(process_id), x))
        time.sleep(1)

    print "Done adding to the queue for ", str(process_id)


def queue_writer(queue):

    print "Starting ! Queue id :", id(queue)
    env = lmdb.open(path="data/test.db", map_size=2 ** 43, map_async=True, metasync=True, lock=False)

    for key, value in queue:

        try:
            with env.begin(write=True) as txn:

                print "Save 1 entry in the database...- queue size :", str(queue.qsize())
                txn.put(key, value, dupdata=False)
                queue.task_done()

        except Exception as e:
            print "Unable to save some data inside the database :", str(e)

    print "If you see this, it means that the process has ended !"


if __name__ == '__main__':

    queue = gevent.queue.JoinableQueue()
    event = gevent.spawn(queue_writer, queue)
    gevent.sleep(0)

    p1 = Process(target=populate_queue, args=(queue, "A",))
    p1.start()
    p2 = Process(target=populate_queue, args=(queue, "B",))
    p2.start()
    p3 = Process(target=populate_queue, args=(queue, "C",))
    p3.start()
    p4 = Process(target=populate_queue, args=(queue, "D",))
    p4.start()
    p1.join()
    p2.join()
    p3.join()
    p4.join()

    time.sleep(10)

    print "Waiting for the queue to be done ", queue.qsize()
    queue.join()
    print "Queue completed ! ", queue.qsize()
```

This code produce the following output : 

````shell
root@CSXTPDEV:/mnt# python test2.py
Starting ! Queue id : 123601672253072
Queue id : 123601672253072
Adding  ('1A', 1)  to the queue !
Queue id : 123601672253072
Adding  ('1B', 1)  to the queue !
Queue id : 123601672253072
Adding  ('1C', 1)  to the queue !
Queue id : 123601672253072
Adding  ('1D', 1)  to the queue !
Adding  ('2A', 2)  to the queue !
Adding  ('2B', 2)  to the queue !
Adding  ('2C', 2)  to the queue !
Adding  ('2D', 2)  to the queue !
Adding  ('3A', 3)  to the queue !
Adding  ('3B', 3)  to the queue !
Adding  ('3C', 3)  to the queue !
Adding  ('3D', 3)  to the queue !
Adding  ('4A', 4)  to the queue !
Adding  ('4B', 4)  to the queue !
Adding  ('4C', 4)  to the queue !
Adding  ('4D', 4)  to the queue !
Adding  ('5A', 5)  to the queue !
Adding  ('5B', 5)  to the queue !
Adding  ('5C', 5)  to the queue !
Adding  ('5D', 5)  to the queue !
Adding  ('6A', 6)  to the queue !
Adding  ('6B', 6)  to the queue !
Adding  ('6C', 6)  to the queue !
Adding  ('6D', 6)  to the queue !
Adding  ('7A', 7)  to the queue !
Adding  ('7B', 7)  to the queue !
Adding  ('7C', 7)  to the queue !
Adding  ('7D', 7)  to the queue !
Adding  ('8A', 8)  to the queue !
Adding  ('8B', 8)  to the queue !
Adding  ('8C', 8)  to the queue !
Adding  ('8D', 8)  to the queue !
Adding  ('9A', 9)  to the queue !
Adding  ('9B', 9)  to the queue !
Adding  ('9C', 9)  to the queue !
Adding  ('9D', 9)  to the queue !
Done adding to the queue for  A
Done adding to the queue for  B
Done adding to the queue for  C
Done adding to the queue for  D
Waiting for the queue to be done  0
Queue completed !  0
````

It seems that I am able to share the queue between all the processes (because the id of the queue is the same), but for a weird reason, it's like every process is not working with the same queue. Also, the thread unpacks the queue is not doing anything (because the queue is always empty). 

I expect all the processes to update the same queue so that the **event** thread can save everything in the database properly. Is it even possible ? I've heard about incompatibilities between multiprocessing and gevent: is this possible ? 

Maybe it is some weird python behavior ? 

Thank you very much for your help ! 

Sacha

**Comment by jamadden** [comment]
> It seems that I am able to share the queue between all the processes (because the id of the queue is the same), but for a weird reason, it's like every process is not working with the same queue. 

The queue is **not** the same. Simplifying quite a bit, when you create new processes, you get a *copy* of all the objects that are in memory in each new process (you actually get a copy of the *memory*). The objects will have the same ID in each process (because that was part of the copy), but will otherwise be completely unrelated. It takes special effort to actually share data between processes (`multiprocessing.Queue` does this special effort, but is not fully compatible with gevent).

Without understanding more about what it is you're doing I can't be very specific about possible solutions. Assuming your work is CPU bound and you need multiple processes, instead of multiple threads to work around Python's GIL, then all I can suggest is to, look into *general* ways to share data between *unrelated* processes; for example, have the "master" process open a socket server and have the worker processes connect to it and write results. (Or, since you're not really using much of anything gevent provides above, perhaps you just need `multiprocessing.Queue` and not gevent.)

I would also encourage you to update your version of gevent, as 1.1 isn't supported anymore. 

HTH.

**Comment by SachaLhopital** [comment]
Thank you very much for your answer ! It's quite clear now ! 
I will look up for the upgrade ! 

Sacha

**Comment by finefoot** [comment]
@jamadden  To quote from your comment https://github.com/gevent/gevent/issues/1383#issuecomment-479959531

> `multiprocessing.Queue` does this special effort, but is not fully compatible with gevent

I couldn't find anything in the docs about this. In which way is it not fully compatible with gevent?

There is this question https://stackoverflow.com/questions/22162538/passing-a-multiprocessing-queue-dictionary-etc-to-green-threads on StackOverflow about compatibility of `multipprocessing.Queue` with gevent where one answer says

> The benefits would likely be lost, standard threaded queue implements locks where a green thread would likely be slowed down

and another one says

> I would say that it is a thread safe object then it is not dangerous

So is it really only a performance issue and not dangerous in terms of race conditions and data corruption?
