### ISSUE TITLE
[1.4.0] Tests fails on build for python 3.6

### ISSUE THREAD

**Issue by tuxmaster5000** [gevent/gevent#1385]
OS: CentOS 7.6
estrunner (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: testrunner (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testrunner
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'greentest.testrunner'

----------------------------------------------------------------------

**Comment by jamadden** [comment]
You don't provide enough information to try to replicate or explain the problem, but it's true, that module no longer exists. See [this changelog entry](http://www.gevent.org/changelog.html#id1):

> Refactored the gevent test runner and test suite to make them more reusable. In particular, the tests are now run with python -m gevent.tests. See issue #1293.
