### ISSUE TITLE
Incompatible with contextvars.ContextVar

### ISSUE THREAD

**Issue by aberres** [gevent/gevent#1407]
More and more libraries are switching from `threading.local` to `contextvars.ContextVar`.

(So far) gevent does not support `contextvars`. This leads to the situation that libraries need to explicitly check if gevent is used and then select the "old style" implementation. Example: https://github.com/elastic/apm-agent-python/commit/090b938c967469d5833cf41b13b1aba1a2b72464
Alternativbely the libraries are not working properly with gevent at all: https://github.com/census-instrumentation/opencensus-python/issues/628

I could find very few information if there is any chance for gevent to support `contextvars`. I found a claim that it is not feasible due to its C implementation. At the same time PEP 550 at least mentioned gevent - in the final 567 this is no more the case though.

If it should not be possible some words in the docs would be helpful I think.

**Comment by colincadams** [comment]
Any idea when this might get done, or guidance you can provide on the implementation?

**Comment by jamadden** [comment]
I've been heads down on another project, but I'm hoping to have more time for gevent next month.

**Comment by victoraugustolls** [comment]
Any news oh this?

**Comment by colincadams** [comment]
Just want to check in again, any update or guidance you can give so someone else could take it on?
