### ISSUE TITLE
Patched GeventWorker + gunicorn causes calls to `subprocess` to segfault

### ISSUE THREAD

**Issue by jamwalla** [gevent/gevent#1420]
* gevent version: 1.4.0
* Python version: 3.7
* Operating System: Ubuntu
(from docker: `FROM ubuntu:latest` `RUN apt update -y && apt install -y python3.7-dev`)
 

### Description:

Patched GeventWorker + gunicorn causes calls to `subprocess` to segfault.

We run an appengine flex project with gunicorn using a patched gevent worker, so we can make asynchronous calls to the `requests` library. 
```python
from gunicorn.workers.ggevent import GeventWorker
from grpc.experimental import gevent
class GeventGrpcWorker(GeventWorker):
    def patch(self):
        super(GeventGrpcWorker, self).patch()
        gevent.init_gevent()
        self.log.info('patched grpc')
```
We found this issue while trying to use [tabula-py](https://github.com/chezou/tabula-py): all calls to `subprocess` cause a segfault like the following:
```
aef-default-v1--0--28-3573 kernel: [47918.185101] gunicorn[2328]: segfault at 0 ip 00007fbb87466b16 sp 00007ffd63a35630 error 4 in cygrpc.cpython-37m-x86_64-linux-gnu.so[7fbb87376000+3af000]
```

### What I've run:
I've tried unpatching subprocess `import importlib; importlib.reload(subprocess)` and excluding `patch_subprocess` in the original patch; neither prevents the segfault.

**Comment by jamadden** [comment]
`cygrpc.cpython-37m-x86_64-linux-gnu.so` comes from the grpc project. I suspect you're seeing a bug in the experimental part of grpc. Perhaps open an issue in that repository? I don't know what their policy is on support for the experimental modules.

**Comment by jamwalla** [comment]
Thanks, filed this there!
