### ISSUE TITLE
why gevent.socket send do not cause greenlet switch ?

### ISSUE THREAD

**Issue by kaka19ace** [gevent/gevent#1422]
* gevent version: 1.3.5
* Python version: cPython 2.7.9 downloaded from python.org
* Operating System: Debian Linux 8.1 Linux 4..4.0-33 amd64"

### Descsription:
When using opentracing trace the gevent net operation, 
Just find that  there is no interrupt or switch to anther greenlet at socket.send() , but will occur at socket.read() and socket connect

**Comment by jamadden** [comment]
gevent only switches if it is helpful to do so. If sending isn't going to block (because the socket buffer has space), it doesn't need to switch. It can be more efficient that way.

**Comment by SeaHOH** [comment]
This is a trouble when use libuv on win32, it must be switch, otherwise double-operation will be blocked.

CPython 3.5.3 amd64 on Win7 SP1

**Comment by SeaHOH** [comment]
I patch `send` as below, then `sendall` resume works correctly, but the CPU overhead up. 
```py
    def send(self, data, flags=0, timeout=timeout_default):
        num_send = gevent_send(self, data, flags, timeout)
        self._wait(self._write_event)
        return num_send
```

**Comment by jamadden** [comment]
>  it must be switch, otherwise double-operation will be blocked.

You seem to be discussing a different issue. If you'd like to report a bug, please open a new issue with an explanation and demonstration of the problem.

**Comment by SeaHOH** [comment]
I wrote and tested a simple demo, it works well, but the similar codes in my repositroy can not work correctly. I try to find out the reason, not found.
Looks like it's not a gevent bug, no new issue will be open, and I try solve it myself.
