### ISSUE TITLE
installing gevent via pip on travis ci fails with python 3.6 target

### ISSUE THREAD

**Issue by dothebart** [gevent/gevent#1424]
Trying to run a PR test that should install gevent via pip. the 2.7 version works well, 3.[5|6] fails, (3.7 isn't available) 

https://github.com/ArangoDB-Community/pyArango/pull/143

```
gcc: error: src/gevent/queue.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 4
The command "python setup.py install" failed and exited with 1 during .
```

**Comment by jamadden** [comment]
It appears that your versions of [pip](https://travis-ci.org/ArangoDB-Community/pyArango/jobs/536730397#L444) and [setuptools](https://travis-ci.org/ArangoDB-Community/pyArango/jobs/536730397#L549) are very outdated and don't understand manylinux2010 wheels or [PEP517](https://www.python.org/dev/peps/pep-0517/)/[PEP  518](https://www.python.org/dev/peps/pep-0518/). 

I recommend upgrading them both.

**Comment by dothebart** [comment]
but the pip is whatever travis brings? so basically a `.travis.yml` like this is born dead:

```
sudo: required
language: python
python:
  - "3.6"
 
before_script:
  - pip install coverage gevent enum

```
how to fix this?

**Comment by jamadden** [comment]
> but the pip is whatever travis brings

Which is horribly outdated.

> how to fix this?

Upgrade pip. A newer pip should be able to install the binary distributions of gevent, thus saving a lot of build time.

**Comment by dothebart** [comment]
thanks a lot for your advice, getting the right place to upgrade pip was a bit tricky, but got it fixed.
