### ISSUE TITLE
I cannot import gevent after having it installed.

### ISSUE THREAD

**Issue by Alex-Fortin** [gevent/gevent#1425]
**Hi, so this is what I have installed:**

installed the latest event version using pip install gevent
Running Python 3.7.3 downloaded from python.org
I'm running MacOs latest version Mojave 10.14.5
* Operating System: Please be as specific as possible: "Raspbian (Debian Linux 8.0 Linux 4.9.35-v7+  armv7l)"

### Description:

**This is to show I have it installed:**

(venv) (base) Alexandres-MacBook-Pro:HelloWorld alexandrefortin$ pip install gevent
Requirement already satisfied: gevent in ./venv/lib/python3.7/site-packages (1.4.0)
Requirement already satisfied: greenlet>=0.4.14; platform_python_implementation == "CPython" in ./venv/lib/python3.7/site-packages (from gevent) (0.4.15)

**And this is the error message I get when I try to run a .py file that has import gevent in it**

> Traceback (most recent call last):
>   File "/Users/alexandrefortin/PycharmProjects/HelloWorld/geventTEst.py", line 1, in <module>
>     import gevent
>   File "/Users/alexandrefortin/PycharmProjects/HelloWorld/gevent.py", line 2, in <module>
>     from gevent import socket
> ImportError: cannot import name 'socket' from 'gevent' (/Users/alexandrefortin/PycharmProjects/HelloWorld/gevent.py)

Now one problem I see is that even if I try to "import gevent" on a different .py file, it still say it cannot import it from .../gevent.py

I tried running the file directly on the iOS terminal and it still tell me same error: cannot import name 'socket' from 'gevent'

Please advise

**Comment by jamadden** [comment]
Your module named 'gevent' is shadowing (hiding) the gevent package that's been installed. This isn't unique to gevent, it can be a problem with any colliding module names. Observe:

```console
$ python -c 'from socket import gethostbyname'
$ echo 'from socket import gethostbyname' > socket.py
$ python socket.py
Traceback (most recent call last):
  File "socket.py", line 1, in <module>
    from socket import gethostbyname
  File "/private/tmp/socket.py", line 1, in <module>
    from socket import gethostbyname
ImportError: cannot import name 'gethostbyname' from 'socket' (/private/tmp/socket.py)
$ python -c 'from socket import gethostbyname'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/socket.py", line 1, in <module>
    from socket import gethostbyname
ImportError: cannot import name 'gethostbyname' from 'socket' (/private/tmp/socket.py)
```

The solution is to use a different module name (that is, don't have a file named 'gevent.py').
