### ISSUE TITLE
Monkey patching urllib

### ISSUE THREAD

**Issue by vineetrshenoy** [gevent/gevent#1426]
* gevent version: 1.4.0
* Python version: 3.5.2
* Operating System: Ubuntu 16.04 LTS

### Description:

I am trying to use `gevent` with the `urllib.request` library. I am using a monkey patch, but when I print `monkey.is_module_patched('urllib.request')` the code returns `False`.

I am using `urllib.request` version `3.5`
### What I've run:

```python
import gevent
from gevent import monkey

monkey.patch_all()

import urllib.request


print(monkey.is_module_patched('urllib.request'))
```

Is there something I am doing wrong or is `urllib.request` not supported for monkey patches?

**Comment by jamadden** [comment]
There's nothing to patch in `urllib`. `urllib` just *uses* things that are already patched under the covers...eventually, it will talk to the network using the `socket` module, and that is patched.

**Comment by vineetrshenoy** [comment]
Thanks! I'm still a little confused though. I am trying to download images from two different locations, and the images are begin downloaded using the `urllib.request` library as follows:
```
try: #try to download the image
	pth = self.PATH + '/train/' + category_string + '/' + filename
	urllib.request.urlretrieve(url, pth)
	logger.info('Downloaded file: ' + pth)

except urllib.error.HTTPError as e:
	logger.warning('Broken URL: ' + url)
	broken_link = broken_link + 1
```
Since I am downloading from two different locations, I have been using code similar to the following to spawn greenlets:

```
obj1 = MerchantDBDataset(90787)
obj2 = MerchantDBDataset(59227)
gevent.joinall([
		gevent.spawn(obj1.downloadImages()),
		gevent.spawn(obj2.downloadImages())
])
```

However, when I look inside the folder as the images are being downloaded, it appears as though the images are being downloaded serially (obj1 has downloaded thousands of images while obj2 has not downloaded anything yet). Is there something I am doing wrong?

**Comment by jamadden** [comment]
>  Is there something I am doing wrong?

Maybe? `gevent.spawn(obj1.downloadImages()),` sure looks like you're passing the *result* of downloading images to the spawn function, when what you actually want to spawn is the function itself.

**Comment by jamadden** [comment]
Closing since there's been no new info added.
