### ISSUE TITLE
Gevent pywsgi WSGIServer concurrent request are queued

### ISSUE THREAD

**Issue by kleysonr** [gevent/gevent#1428]
* gevent version: 1.4.0
* Python version: 3.6
* Operating System: Ubuntu 18.04.2 LTS

### Description:

I'm using Connexion with Gevent WSGI server to create an API server.
My API is CPU bound.

Concurrent calls to the API are being executed in a serial fashion.

Below the start/end time of the API execution:

```
2019-06-07 10:57:43,219 - ssp.ws.rgvirtual - INFO - Starting api/rgf for requestid 1
2019-06-07 10:57:55,475 - ssp.ws.rgvirtual - INFO - api/rgf ran in 12.26s for requestid 1
2019-06-07 10:57:55,487 - app.main - INFO - 10.x.x.x - - [2019-06-07 10:57:55] "POST /api/rgf?requestid=1&width=1024&widthret=200&rotate=0 HTTP/1.1" 200 84199 12.438735

2019-06-07 10:57:55,511 - ssp.ws.rgvirtual - INFO - Starting api/rgv for requestid 2
2019-06-07 10:58:07,217 - ssp.ws.rgvirtual - INFO - api/rgv ran in 11.71s for requestid 2
2019-06-07 10:58:07,282 - app.main - INFO - 10.x.x.x - - [2019-06-07 10:58:07] "POST /api/rgv?requestid=1&width=1024&widthret=500&rotate=0 HTTP/1.1" 200 541706 24.228940
```

### What I've run:

This is how the WSGIServer is created (https://github.com/zalando/connexion/blob/2.0.2/connexion/apps/flask_app.py#L106-L113):

```python
        elif self.server == 'gevent':
            try:
                import gevent.pywsgi
            except ImportError:
                raise Exception('gevent library not installed')
            http_server = gevent.pywsgi.WSGIServer((self.host, self.port), self.app, **options)
            logger.info('Listening on %s:%s..', self.host, self.port)
            http_server.serve_forever()
```

What is needed to have my CPU bound requests be processed in parallel by the Gevent ?
What are the difference between **'wsgi.multithread'** and **'wsgi.multiprocess'** ?

I tried to enable the **'wsgi.multithread'** and **'wsgi.multiprocess'** parameters but I got the same behavior:

```python
geventOpt = {'GATEWAY_INTERFACE': 'CGI/1.1',
                'SERVER_SOFTWARE': 'gevent/%d.%d Python/%d.%d' % (gevent.version_info[:2] + sys.version_info[:2]),
                'SCRIPT_NAME': '',
                'wsgi.version': (1, 0),
                'wsgi.multithread': True, # XXX: Aren't we really, though?
                'wsgi.multiprocess': True,
                'wsgi.run_once': False}
http_server = gevent.pywsgi.WSGIServer((self.host, self.port), self.app, environ=geventOpt)
```

**Comment by jamadden** [comment]
gevent is for [cooperative multitasking](http://www.gevent.org/intro.html#cooperative-multitasking): if your code is CPU bound and not cooperative, there's no automatic way for gevent to extract concurrency. You can try running your CPU bound code in [a threadpool](http://www.gevent.org/api/gevent.hub.html#gevent.hub.Hub.threadpool) to use multiple threads and extract some level of concurrency and parallelism that way (limited to Python's GIL). (E.g., `result = gevent.get_hub().threadpool.apply(cpu_func, (arg1, arg2))`). Or you can insert calls to `gevent.sleep(0)` into your inner loop to make the loop cooperative.

**Comment by kleysonr** [comment]
@jamadden I saw some examples that it's supposed to work.

For the testing purposes, my func() is basically a time.sleep(10).

Using a sleep function for testing, should the gevent be able to process the next request before finishing the first one ?

**Comment by jamadden** [comment]
It depends on the details. If it's actually `time.sleep(10)` then **unless the system is monkey-patched by gevent** the answer is an emphatic "no!". `time.sleep` is definitely *not* cooperative.

**Comment by kleysonr** [comment]
Applying monkey_patch I am able to process the requests in parallel.

```python
from gevent import monkey
monkey.patch_all()
```

Thanks.

**Comment by jamadden** [comment]
gevent's WSGIServer uses greenlets for concurrency. If your code is cooperative with gevent and greenlets, than it certainly can handle requests concurrently.

**Comment by chrisinmtown** [comment]
Thanks @jamadden for the quick answer! My use case is a single outbound HTTP request to a slow server that takes 100+ seconds to reply. I can add the monkey patch of socket and use gevent.spawn() to launch that single request.  Please tell me if that solution will allow the server to answer other (short) requests while the long request is running.

**Comment by jamadden** [comment]
I always recommend `patch_all()` instead of patching a single module.

Each request is already running in its own greenlet, so if everything is patched (and thus cooperative) you don't need to spawn your own greenlet when you make a (cooperative) blocking call when handling a request. You'd only need to do that if you wanted a single request to make multiple blocking calls in parallel.

**Comment by nofreewill42** [comment]
> ```python
> from gevent import monkey
> monkey.patch_all()
> ```

This worked for me the first time I tried it and now, it doesn't anymore.

**Comment by nofreewill42** [comment]
I might switch to waitress, as I'm searching for a solution for about 4-5 hours now, but nothing seems to work.

Previously:

>from gevent import monkey
>monkey.patch_all()
>from gevent.pywsgi import WSGIServer

>http_server = WSGIServer((host, port), app,environ={'wsgi.multithread': True,'wsgi.multiprocess': True,})
>http_server.serve_forever()

Now

>from waitress import serve
>serve(app, host=host, port=port)

Now it seems to work just fine, without any difficulties. Does anyone know if waitress has its own really bad drawbacks?
