### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#1430]
Now that beta1 is out, it's time to start work on supporting 3.8.

First step is to add it to CI and make sure the generic tests pass.

Then the next step is to add its stdlib unit tests and make them pass.

**Comment by alexprengere** [comment]
Currently on Python3.7b1, I cannot install gevent 1.4 from PyPI (compilation fails with an error related to PyCode_New), but everything works fine when I install from master (I have a test suite using gevent that passes too).
So I guess we are one release away from supporting Python3.8 😄

**Comment by jamadden** [comment]
> Currently on Python3.7b1,  I cannot install gevent 1.4 from PyPI (compilation fails with an error related to PyCode_New)

gevent 1.4 is tested and supported on Python 3.7. Perhaps upgrading to a Python 3.7 final release would help? I do recall breakage in an C API pretty late in the game and Cython had to be updated to workaround it.

**Comment by jamadden** [comment]
3.8b4 support landed in #1456

**Comment by jodal** [comment]
Python 3.8 has now been released. Can we have a gevent release so that libraries depending on gevent can start supporting Python 3.8 too?

**Comment by jamadden** [comment]
gevent 1.5a2 has been released to PyPI. Wheels are still building and will be uploaded when complete. (Note that there will be no Windows wheels for 3.8 as 3.8 is not available on Appveyor yet.)

**Comment by tlolkema** [comment]
> gevent 1.5a2 has been released to PyPI. Wheels are still building and will be uploaded when complete. (Note that there will be no Windows wheels for 3.8 as 3.8 is not available on Appveyor yet.)

It looks like Appveyor supports 3.8 now:
https://github.com/appveyor/ci/issues/3142#issuecomment-552049896

**Comment by filips123** [comment]
@jamadden Will stable 1.5 with support for Python 3.8 be released soon?

**Comment by jamadden** [comment]
There are releases of gevent 1.5 that support Python 3.8 now. Just because it's 1.5a4 doesn't mean "don't use it". gevent never makes a release that isn't suitable for production. 

The 'a' is a strict interpretation of semantic versioning meaning that the new API is still subject to change. I could release the exact same code as 1.5.0, but that's a false signal and we'd burn though numbers pretty quickly (we'd be at something like 1.25 by now).

**Comment by ehmkah** [comment]
I understand that you do not want to burn the release numbers to fast. But 1.5a4 stills seems to be a pre-release. Would it be possible to make it a "real"-release? My company policy says "no prereleases". :-( I am a not a python-expert so I do not know what the implications are if such a release has been delivered.
