### ISSUE TITLE
python standard library http.client is not patched by monkey.patch_all

### ISSUE THREAD

**Issue by baiyueheiyu** [gevent/gevent#1431]
* gevent version: 1.4.0
* Python version:  cPython 3.7.3 downloaded from python.org"
* Operating System: Windows 10

### Description:

I use python standard library http.client to send HTTP request.
I found  when server reply late, whole process hang here. 

I monkey patched all, so socket receiving should not block other code, right?

### What I've run:

```python
from gevent import monkey
monkey.patch_all()

import gevent
import time
 
# class ByHttpClient internally use http.client.HTTPConnection to send message
from lib.ByHttpClient import ByHttpClient

def gfunc(client):    
    for x in range(100):
        # request with url /api/profile,  server will reply very quick
        response = client.request('GET',"/api/profile",wholeDuration=0.1)
        # request with url /api/delay, server will delay 5 second and reply
        # I found it will make whole program hang there !!!
        response = client.request('GET',"/api/delay",wholeDuration=0.1)

gevent.spawn(gfunc,ByHttpClient('192.168.1.102',timeout=3))
time.sleep(10)

```

**Comment by jamadden** [comment]
>  so socket receiving should not block other code, right?

That's correct, `http.client.HTTPConnection` uses the standard socket APIs, and those are monkey-patched to cooperate with gevent.

It's not clear to me what you are saying the problem is. Your example is using code that's not available (`ByHttpClient`) and doesn't actually demonstrate any concurrency, so it's hard to guess.  You might want to look at the [monitoring documentation](http://www.gevent.org/monitoring.html) if you think you have some code that's not gevent cooperative.

**Comment by baiyueheiyu** [comment]
my bad, one http client cannot send out another request before it reciving response.

And it does not block other greenlet code.

I add printing like the following, everything goes well, it could print 1,2,3,4 while greenlet blocked in receiving.

```python
from gevent import monkey
monkey.patch_all()

import gevent
import time
 
# class ByHttpClient internally use http.client.HTTPConnection to send message
from lib.ByHttpClient import ByHttpClient

def gfunc(client):    
    for x in range(100):
        # request with url /api/profile,  server will reply very quick
        response = client.request('GET',"/api/profile",wholeDuration=0.1)
        # request with url /api/delay, server will delay 5 second and reply
        # I found it will make whole program hang there !!!
        response = client.request('GET',"/api/delay",wholeDuration=0.1)

gevent.spawn(gfunc,ByHttpClient('192.168.1.102',timeout=3))
print('1')
time.sleep(1)
print('2')
time.sleep(1)
print('3')
time.sleep(1)
print('4')
time.sleep(1)
```
