### ISSUE TITLE
Request logging doesn't work

### ISSUE THREAD

**Issue by finefoot** [gevent/gevent#1432]
I'm using a Flask app with `gevent.pywsgi.WSGIServer`. According to the docs http://www.gevent.org/api/gevent.pywsgi.html

> - `log` - If given, an object with a write method to which request (access) logs will be written. If not given, defaults to sys.stderr. [...]

In my call, I don't specify the `log` option, so I assume all request logs will be written to `sys.stderr`. However, I don't get any console output at all.

**Environment:**

```
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent
>>> gevent.__version__
'1.4.0'
```

**Minimal example:**
 
```python
from flask import Flask
from gevent import pywsgi
from geventwebsocket.handler import WebSocketHandler

app = Flask(__name__)
@app.route('/')
def hello():
    return 'Hello'

server = pywsgi.WSGIServer(('127.0.0.1', 5000), app, handler_class=WebSocketHandler)
server.serve_forever()
```

I run the app with `python3 server.py`.

**Comment by jamadden** [comment]
You're specifying a custom handler class that's not part of gevent. It appears that that handler class [overrides the way `pywsgi` logs requests](https://gitlab.com/noppo/gevent-websocket/blob/master/geventwebsocket/handler.py#L268).

**Comment by finefoot** [comment]
Sorry, my bad. I should have done better research. I assumed `geventwebsocket` was part of `gevent`.

An issue has already been filed at the respective `geventwebsocket` project homepage: https://gitlab.com/noppo/gevent-websocket/issues/16
