### ISSUE TITLE
Gevent threading module call a missing greenlet method

### ISSUE THREAD

**Issue by sebastien-petitdemange** [gevent/gevent#1435]
* gevent version: 1.4.0
* Python version: Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
* Operating System: Linux Mint 19 Tara x86_64

### Description:

Threading gevent module call **greenlet.greenlet.join** which does't exist when you **join** a Thread object.

```
Traceback (most recent call last):
  File "/tmp/test_thread.py", line 11, in <module>
    t.join()
  File "/home/seb/miniconda3/envs/bliss3/lib/python3.7/site-packages/gevent/threading.py", line 189, in join
    self._greenlet.join(timeout=timeout)
AttributeError: 'greenlet.greenlet' object has no attribute 'join'
Exception ignored in: <module 'threading' from '/home/seb/miniconda3/envs/bliss3/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/home/seb/miniconda3/envs/bliss3/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/home/seb/miniconda3/envs/bliss3/lib/python3.7/site-packages/gevent/threading.py", line 189, in join
    self._greenlet.join(timeout=timeout)
AttributeError: 'greenlet.greenlet' object has no attribute 'join'
```

### What I've run:

```python
import gevent
from gevent import threading

def f():
    print("ENTER f")
    gevent.sleep(1)
    print("LEAVE f")

t =threading.Thread(target=f)
t.start()
t.join()
```

**Comment by jamadden** [comment]
[The documentation](http://www.gevent.org/api/gevent.threading.html) for that module begins with:

> This module is a helper for `gevent.monkey` and is not intended to be used directly

It means it. Do not import or use that module. Either monkeypatch and use the standard `threading` API, or use documented gevent API like `gevent.spawn`

**Comment by sebastien-petitdemange** [comment]
Ok sorry, I didn't read this line in documentation.

Actually I want to monkey patch **threading** only in one module of my project and keep the original threading  for other. Is there an easy way to do it?

I've try this (As I didn't read carefully) :
```python
from gevent import threading
from prompt_toolkit.shortcuts.progress_bar import base
base.threading = threading #patch
```
