### ISSUE TITLE
[FEATURE REQUEST] Add count paramter to JoinableQueue.task_done()

### ISSUE THREAD

**Issue by ulope** [gevent/gevent#1436]
### Description:

Currently `JoinableQueue.task_done()` only marks a single task as done. This is fine if items are handled one at a time. 
However it's also a common use case to process things in batches leading to unnecessary loops only calling `.task_done()`.

Slightly artificial example:
```python
while True:
    batch = [queue.get() for _ in range(5)]

    # do something to process batch here

    for _ in batch:
        queue.task_done()
```
 
It would be useful if `task_done()` were to gain a `count` parameter so multiple tasks can be marked done at the same time.

**Comment by jamadden** [comment]
Thanks for the request!

JoinableQueue's `task_done` is meant to be compatible with the standard library's `task_done`, which doesn't have that parameter. Still, a default argument could be used.

However, it seems to me that wanting to work on tasks in batches, without previously having batched them to put into the queue in the first place, and without looping internally at all such that there's a natural place to call `task_done` is a fairly niche thing to do, so it's not clear that it's worth adding the complexity here.

For those that do have that work pattern, a subclass could pretty easily add such a method/default argument. That has the advantage of also working with the standard library queue.

**Comment by ulope** [comment]
Fair enough, I wasn't aware it mimics the stdlib interface. That is indeed a good argument to not modify the signature.
