### ISSUE TITLE
我的是找不到monkey 

### ISSUE THREAD

**Issue by SharelockSmile** [gevent/gevent#1438]
报错信息如下：
Traceback (most recent call last):
  File "E:/PycharmProjects/document/gevent.py", line 1, in <module>
    import gevent
  File "E:\PycharmProjects\document\gevent.py", line 2, in <module>
    from gevent import monkey; monkey.patch_all()
ImportError: cannot import name 'monkey' from 'gevent' (E:\PycharmProjects\document\gevent.py)

**Comment by jamadden** [comment]
> ImportError: cannot import name 'monkey' from 'gevent' (E:\PycharmProjects\document\gevent.py)

You appear to be using the name `gevent` for your own module. This "hides" a real installation of gevent. Try changing the name of your file.

**Comment by SharelockSmile** [comment]
那需要怎么改呢
