### ISSUE TITLE
In which way is `multiprocessing.Queue` not fully compatible with gevent?

### ISSUE THREAD

**Issue by finefoot** [gevent/gevent#1443]
To quote from a comment https://github.com/gevent/gevent/issues/1383#issuecomment-479959531 from another posted issue:

> It takes special effort to actually share data between processes (`multiprocessing.Queue` does this special effort, but is not fully compatible with gevent).

I couldn't find anything in the docs about this. In which way is it not fully compatible with gevent?

There is this question https://stackoverflow.com/questions/22162538/passing-a-multiprocessing-queue-dictionary-etc-to-green-threads on StackOverflow about compatibility of `multiprocessing.Queue` with gevent where one answer says

> The benefits would likely be lost, standard threaded queue implements locks where a green thread would likely be slowed down

and another one says

> I would say that it is a thread safe object then it is not dangerous

So is it really *only* a performance issue and *not* dangerous in terms of race conditions and data corruption?

**Comment by arcivanov** [comment]
It is dangerous. The `mp.Queue` and other mp data structures utilize things like Semaphores internally: https://github.com/python/cpython/blob/master/Lib/multiprocessing/queues.py#L48

Semaphores under Linux are not fd-based and would require threaded wrappers to unblock the main loop thread. I've done some work to geventize the `mp` package but it's not complete. I may return to it at some point: https://github.com/gevent/gevent/pull/1158/commits/dc4f6055a61722e953d3a1472bd168b2a2dd2faf#diff-0be5ae2c9aa641e019319f01be8d4134R28

**Comment by jgehrcke** [comment]
@finefoot not sure how badly you actually need the queue for inter-process communication in your case. For really simple use cases there is [gipc](https://github.com/jgehrcke/gipc) -- it is a small wrapper around `multiprocessing.Process`. With that, `multiprocessing.Process`-based child processes can safely be created and managed from within your gevent-driven application, and you can also reliably send messages across these processes in a gevent-cooperative fashion.

**Comment by finefoot** [comment]
Thanks for your replies! :) So the answers on that question on StackOverflow are incorrect, yes? :thinking:

I've added a new answer quoting you @arcivanov with a link to this issue.

@jgehrcke Thanks for the link, I'll check it out :+1:

**Comment by finefoot** [comment]
Does this mean that `queue.Queue` is incompatible, too?

**Comment by arcivanov** [comment]
No, why? mp.Queue uses OS-level Semaphore, whereas queue.Queue is actually using process-level locking that has been monkey-patched as with all blocking primitives.

**Comment by finefoot** [comment]
Oh, okay. So `queue.Queue` is fully compatible with `gevent`? What's the advantage of [`gevent.queue.Queue`](http://www.gevent.org/api/gevent.queue.html) over stdlib's `queue.Queue` then? :thinking:

**Comment by jamadden** [comment]
Thanks for your question and the responses!

gevent's Queue is directly implemented in terms of gevent primitives, rather than going through the abstraction of the monkey-patched `threading` libraries like the standard library Queue must do, and gevent's Queue can take advantage of the fact that certain operations cannot be interrupted by other greenlets. This lets it have reduced overhead and better performance. 

gevent's Queue is compatible with gevent and greenlets even if monkey-patching isn't used, whereas the standard library Queue isn't and requires monkey-patching. Not everyone like to monkey-patch.

gevent's Queue also has a slightly richer interface, for example it can be iterated.

**Comment by finefoot** [comment]
@jamadden  :man_facepalming: Of course, that makes sense. Thanks for the explanation.

> Is this something I should have known by reading the gevent docs?

I'm still not sure about this question, though. Regarding the incompatibility with `multiprocessing`, as a gevent end-user, should I have known about that by only reading the docs? Or should I have looked into the `multiprocessing` source code? Like I said, concurrency and parallelism seem to be really hard sometimes. I'm just trying to find out, if gevent is even meant for - more or less - beginners like me or if it'll only lead to more confusion.

**Comment by arcivanov** [comment]
I think the important thing to understand is that `mp.Queue` is distinctly different from both `queue.Queue` and `gevent.queue.Queue`. The `mp.Queue` is based on OS primitives (either pipes, Unix sockets or TCP sockets) and transfers pickled data between the processes. Whereas `queue.Queue` and `gevent.queue.Queue` always were and always will be intra-process data structures only. The distinctions between `mp.Queue` and `queue.Queue` are obvious from the documentation, irrespective of gevent. The particularies of implementation of `gevent.queue.Queue` would require you to look inside.

**Comment by arcivanov** [comment]
Version 0.0.2 of https://github.com/karellen/geventmp released with multiple fixes and extensive testing on Linux.
