### ISSUE TITLE
Cannot run other threads

### ISSUE THREAD

**Issue by TGWC** [gevent/gevent#1444]
When using with gpiozero all background threads do not work, how to solve it?

**Comment by jamadden** [comment]
The C libraries that deal with GPIO on the Rasperry  Pi, such as [RPi.GPIO](https://pypi.org/project/RPi.GPIO/), need to run a native thread to [poll for IO](https://sourceforge.net/p/raspberry-gpio-python/code/ci/default/tree/source/event_gpio.c). Without running in an native thread, they'll block gevent's own event loop. So try `patch_all(thread=False, threading=False)`.

If you uninstall all the C libraries and rely on gpiozero's pure-Python support, *it won't work*. gpiozero is coded to use `select.epoll`, but `select.epoll` is not patched by gevent (#962). Best case scenario, if you've patched early enough, gpiozero will fail with an `AttributeError`. Worst case, it will simply hang the process. 

Good luck!
