### ISSUE TITLE
wheel for alpine without needing gcc?

### ISSUE THREAD

**Issue by tommyjcarpenter** [gevent/gevent#1446]
* gevent version:
Latest (My `setup_requires` does not specify)
* Python version: Please be as specific as possible: "cPython 2.7.9 downloaded from python.org"
3.7.2
* Operating System: Please be as specific as possible: "Raspbian (Debian Linux 8.0 Linux 4.9.35-v7+  armv7l)"
Alpine Linux from Docker python:3.7-alpine

### Description:

I'd like to install gevent from a `setup_requires` in a setup.py WITHOUT needing GCC to be installed. Is there a way to install a precompiled binary so that I don't need the GCC compilation tools to be installed?

```
  Running setup.py install for greenlet: started
    Running setup.py install for greenlet: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wx5wn6fv/greenlet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wx5wn6fv/greenlet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__fi
le__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-dnq81yyw/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-wx5wn6fv/greenlet/
    Complete output (9 lines):
    running install
    running build
    running build_ext
    building 'greenlet' extension
    creating build
    creating build/temp.linux-x86_64-3.7
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.7m -c greenlet.c -o build/temp.linux-x86_64-3.7/greenlet.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wx5wn6fv/greenlet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wx5wn6fv/greenlet/setup.py'"'"';f=getattr(tok
enize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-dnq81yyw/install-record.txt --single-version-externally-managed --compile
Check the logs for full command output.
```

### What I've run:

Here is an insanely minimal example Dockerfile:

```
FROM python:3.7-alpine
RUN pip install gevent
```

then:
```
docker build  --no-cache -t test:latest .
```

**Comment by jamadden** [comment]
[It isn't possible](https://github.com/pypa/manylinux/issues/37) to distribute wheels for Alpine Linux (specifically, anything that uses a libc besides glibc, like musl) on PyPI; the specifications just don't allow it. But you're welcome to build a private wheel and install from that file locally.

**Comment by tommyjcarpenter** [comment]
@jamadden  Interesting; so this isn't actually a problem with gevent not having dont something, it's a problem that pypi ...policy? doesn't allow it? Thanks for the clarification!

**Comment by thedrow** [comment]
See https://github.com/pypa/packaging-problems/issues/69 for details.
