### ISSUE TITLE
why does my gevent run slowly than the normal program ? 

### ISSUE THREAD

**Issue by allwell997** [gevent/gevent#1453]
Python Version  : 3.7.3
IDE : pycharm 
problems : 
I make a speed testing. I am trying to read the local file whihc are more then 2000 ,  it took for 6.5 seconds when i use the gevent moulde, another took for 2.8 seconds when normally i used 'for in'. 
I want to know why does not gevent raise efficiency for I/O.

**Comment by allwell997** [comment]
from gevent import monkey; monkey.patch_all()
import gevent

import time



def read(file):
    with open(file , 'rb') as f:
        import struct
        i = 0
        while True:
            li = f.read(32)
            if not li:
                break
            data = struct.unpack('lllllfll', li)
            # print(data)
            i += 1


if __name__ == '__main__':
    dir = 'D:\\lday\\'
    files = os.walk(dir)
    files_lst = [line for line in files][0][2:][0]
    g_lst = []
    start = time.time()
    for code in files_lst:
        file = ''.join([dir,'\\',code])
        g = gevent.spawn(read, file)
        g_lst.append(g)
    gevent.joinall(g_lst)
    took = time.time() - start
    print(took,len(files_lst))

    start = time.time()
    for code in files_lst:
        file = ''.join([dir, '\\', code])
        read(file)
    took = time.time() - start
    print(took, len(files_lst))

**Comment by allwell997** [comment]
OS : WIN10
could you share the coding ? thanks

**Comment by allwell997** [comment]
appreciated !!

'''
from gevent import monkey; monkey.patch_all()
import gevent
import os
import time



def read(file):
    print(file,end=' ')
    with open(file , 'rb') as f:
        import struct
        i = 0
        while True:
            li = f.read(32)
            if not li:
                break
            data = struct.unpack('lllllfll', li)
            i += 1

if __name__ == '__main__':
    dir = 'D:\\lday\\'
    files = os.walk(dir)
    files_lst = [line for line in files][0][2:][0]
    g_lst = []
    start = time.time()
    for code in files_lst:
        file = ''.join([dir,'\\',code])
        g = gevent.spawn(read, file)
        g_lst.append(g)
    gevent.joinall(g_lst)
    took1 = time.time() - start


    start = time.time()
    for code in files_lst:
        file = ''.join([dir, '\\', code])
        read(file)
    took = time.time() - start
    print(took1,len(files_lst))
    print(took, len(files_lst))
'''

**Comment by allwell997** [comment]
bingo and appreciated.

**Comment by allwell997** [comment]
it still does not work. I dont know why. The program stops when I run it and nothing to show.  
```ruby
from gevent import monkey; monkey.patch_all()
from gevent.fileobject import FileObject
import gevent
import os
import time

def read(file):
    # print(file,end=' ')
    with FileObject(open(file , 'rb')) as f:
        import struct
        i = 0
        while True:
            li = f.read(32)
            if not li:
                break
            data = struct.unpack('lllllfll', li)
            i += 1

def read1(file):
    print(file,end=' ')
    with open(file , 'rb') as f:
        import struct
        i = 0
        while True:
            li = f.read(32)
            if not li:
                break
            data = struct.unpack('lllllfll', li)
            i += 1
        print(i)



if __name__ == '__main__':
    dir = 'D:\\lday\\'
    files = os.walk(dir)
    files_lst = [line for line in files][0][2:][0]
    g_lst = []
    start = time.time()
    for code in files_lst:
        file = ''.join([dir,'\\',code])
        g = gevent.spawn(read, file)
        g_lst.append(g)
    gevent.joinall(g_lst)
    took1 = time.time() - start


    start = time.time()
    for code in files_lst:
        file = ''.join([dir, '\\', code])
        read1(file)
    took = time.time() - start
    print(took1,len(files_lst))
    print(took, len(files_lst))
```

**Comment by allwell997** [comment]
what wrong did me coded ?

**Comment by iamybj** [comment]
Only stupid newbies use windows. Windows is just a third-world commercial production which aims to earn money.

**Comment by arcivanov** [comment]
@iamybj I would 1) watch your tone 2) consider whether this was a constructive comment.

**Comment by allwell997** [comment]
does not work still.

**Comment by arcivanov** [comment]
"Does not work" is not a valid response. Are you getting an error? Is it still not performing the way you want (I would expect it won't)?

**Comment by allwell997** [comment]
could you gime me your email address ? And I would like to send all the file which I am going to read and then you make a testing on these files.  'dose not work still' means the program do nothing for long time although the program read out data from file.

**Comment by arcivanov** [comment]
I don't have Windows to begin with, so I can't help testing. Have you tried debugging through it to see where it gets stuck?

**Comment by allwell997** [comment]
sure. I am trying to migrate to linux os.

**Comment by jamadden** [comment]
The short answer is, this is a CPU bound program. It doesn't do selectable/pollable IO. With no IO to parallelize, gevent and (greenlets in general) has no performance advantage over sequential code: there are no "idle" CPU cycles that can be reclaimed while waiting on IO to happen. 

The `FileObjectThread` version makes things worse by making presumably many very small IO requests across the thread pool; it'd be better to throw the entire CPU-bound function into the threadpool.

The potential advantage gevent can have here is better code organization through improved APIs and communication primitives. But that comes with a cost of overhead, especially on Windows where things like signal handling are emulated with timers. The event loop has to cycle, timers have to fire, etc, none of which is completely free. There's been a lot of work recently to reduce that overhead, so hopefully the penalty is much less than it used to be. Also, #1493 was a pathological case that might have been affecting this particular example.

There hasn't been any activity on this issue in quite a while, so I'm closing it. Feel free to re-open if there is additional information to add.
