### ISSUE TITLE
Broken with OpenSSL 1.1.1c

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#1457]
* gevent version: master
* Python version: 3.7.4 on AppVeyor, 3.7.4 on macOS from macports

Observed in https://github.com/gevent/gevent/pull/1456 that AppVeyor builds started breaking when it upgraded from 3.7.3 to 3.7.4 due to test__ssl.py. Rebuilt local CPython 3.7.4 to use OpenSSL 1.1.c instead of 1.0.?.j and can now produce the same failures.

**Comment by jamadden** [comment]
Fixed in #1460.

**Comment by arcivanov** [comment]
FYI OpenSSL 1.1.1d has landed this week with CVEs. Might want to switch to that.

**Comment by jamadden** [comment]
gevent's not in control of that, it's whatever Python is built with. It just happens that there were recently some switches to build with newer versions and fully implement TLS1.3 that required these changes in gevent.
