### ISSUE TITLE
When resolving DNS hostname fails, errno is different depending on the resolver used

### ISSUE THREAD

**Issue by spellr** [gevent/gevent#1459]
* gevent version: 1.4.0
* Python version: cPython 2.7.15
* Operating System: Ubuntu Linux 18.04 Linux 5.0.0-27-generic x86_64

### Description:

When resolving host to address, and failed to find host, the errno returned is different when using thread-dns or dnspython, and when using ares.
thread-dns returns EAI_NONAME, which makes sense.
dnspython return None, which is a little weird.
ares returns EINTR, which is very weird.

### What I've run:

resolve.py:
```python
from gevent import monkey
monkey.patch_all()

import socket

try:
    print socket.gethostbyname('www.some-non-existing-domain.com')
except socket.gaierror as e:
    print e.errno
```

```bash
$ python resolve.py 
-2
$ GEVENT_RESOLVER=dnspython python resolve.py 
None
$ GEVENT_RESOLVER=ares python resolve.py 
4
```

**Comment by spellr** [comment]
As a side note, this behavior is very bad when using PyMySQL.
When using ares, [this code](https://github.com/PyMySQL/PyMySQL/blob/383c0438fe74464ad65b9850bd13f310de7a878e/pymysql/connections.py#L565-L574) is stuck in an infinite loop.

**Comment by chenyosef-stratoscale** [comment]
:+1:

**Comment by jamadden** [comment]
Different resolvers are different? 🤷‍♂ I'd review PRs that added this fact to the documentation or which got them to behave more like each other in a tested way. There are existing tests for that in `test__socket_dns.py`, and some are skipped if we're not using the system DNS resolver, perhaps that's a starting point.
