### ISSUE TITLE
calling `get` more than once

### ISSUE THREAD

**Issue by uriva** [gevent/gevent#1472]
Some questions that arise from this code:

```
def dedup_requests(f):
    pending = {}

    @functools.wraps(f)
    def wrapped(*args, **kwargs):
        key = _make_call_key(args, kwargs)
        if key not in pending:
            pending[key] = gevent.spawn(f, *args, **kwargs)
        result = pending[key].get()
        if key in pending:
            del pending[key]
        return result

    return wrapped
```

I've tried to run it with threading as well, and getting some kind of a deadlock which I can't reproduce.

1) Can gevent ever cause a deadlock from calling `get` multiple times? Should this be written with `join` instead?
2) Is there any issue with spawning things from spawned functions (in a recursive manner)?
3) Should this code explicitly kill the spawned greenlet or does garbage collection handle that?

**Comment by jamadden** [comment]
> Can gevent ever cause a deadlock from calling get multiple times? 

In gevent, operations that would deadlock raise `LoopExit` instead.

> Should this be written with join instead?

Shouldn't make any difference.

> Is there any issue with spawning things from spawned functions (in a recursive manner)?

You could ultimately exhaust memory if you do so in an unbounded fashion. Other than that it depends on the specifics.

> Should this code explicitly kill the spawned greenlet or does garbage collection handle that?

If you want it to die at a particular time you should kill it. Otherwise don't worry.
