### ISSUE TITLE
Cannot install gevent with Anaconda 2019.10, Python 3.8 @ windows server 2019

### ISSUE THREAD

**Issue by ecc256** [gevent/gevent#1476]
Cannot install gevent with Anaconda 2019.10, Python 3.8 @ windows server 2019.
Detailed report can be found [here](https://github.com/locustio/locust/issues/1131).
Not a big deal as it works fine in Anaconda + Python 3.7 and 3.6 @ windows server 2019.
Works fine in Anaconda 2019.10, Python 3.8 @ Ubuntu 18.04 too.

**Comment by jamadden** [comment]
gevent 1.5 is required for Python 3.8. That was attempting to install gevent 1.4.

**Comment by ecc256** [comment]
Jason,
You are absolutely right,
Found the same already, reported it [here](https://github.com/gwik/geventhttpclient/issues/117#issuecomment-551932239), but didn’t update this issue yet
