### ISSUE TITLE
ImportError: No module named __hub_local

### ISSUE THREAD

**Issue by gabrielmatau79** [gevent/gevent#1477]
* gevent version: gevent-1.4.0.dist-info
* Python version: 2.7.1
* Operating System: Please be as specific as possible: "Raspbian (Debian Linux 8.0 Linux 4.9.35-v7+  armv7l)"

### Description:
i have problem you can help me please

i try import de gevent and throw this
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\Gabriel Mata\.ignition\cache\gw192.168.100.53_80\C0\pylib\site-packages\ari_originate.py", line 5, in <module>
    import gevent
  File "C:\Users\Gabriel Mata\.ignition\cache\gw192.168.100.53_80\C0\pylib\site-packages\gevent\__init__.py", line 87, in <module>
    from gevent._hub_local import get_hub
  File "C:\Users\Gabriel Mata\.ignition\cache\gw192.168.100.53_80\C0\pylib\site-packages\gevent\_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "C:\Users\Gabriel Mata\.ignition\cache\gw192.168.100.53_80\C0\pylib\site-packages\gevent\_util.py", line 105, in import_c_accel
    mod = importlib.import_module(cname)
  File "C:\Users\Gabriel Mata\.ignition\cache\gw192.168.100.53_80\C0\pylib\site-packages\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named __hub_local
```

### What I've run:
```python
#!/usr/bin/env python2.7
# Requirements: pip install ari gevent
import argparse
import ari
import gevent
from gevent.monkey import patch_all; patch_all()
from gevent.event import Event
import logging
from requests.exceptions import HTTPError, ConnectionError
import socket
import time
```

**Comment by jamadden** [comment]
Those paths with drive letters don't look like what I would expect on Raspbian. It looks like Windows.

Python 2.7.1 is *not* supported, so this simply may not work at all. It looks like gevent is not installed correctly. In particular, it looks like the C code was not compiled. You'll need to re-install gevent correctly. If you're on an ARM system, you'll have to do the compiling yourself from the sdist (.tar.gz file) because we could not distribute binary compiled files. To do that you'll have to have a C compiler installed and working to compile Python extensions. That's usually pretty easy and often the default on Linux distributions, but it requires extra downloads on Windows.

**Comment by gabrielmatau79** [comment]
Thank you jamadden , you are rigth the operating system is Centos 7, i installed geven with pip install gevent, the strange thing is that I install and run the program from the console and it works fine now when I try to run from Ignition automation throws that error I guess as you already clarified that python 2.7.1 does not let it work

**Comment by jamadden** [comment]
I don't know what Ignition automation is, but it seems like it doesn't have gevent correctly installed. There's not much I can do to help with that.

Here's a guess: you installed gevent on a Unix system, but you're trying to access it from a Windows system using some sort of sharing or cache (or, you installed it on an x86 system and are trying to use it from an Arm system, or vice versa). That won't work, gevent has to be compiled specifically for the platform and operating system it's being used on. `pip install gevent` is only going to install and compile a version for the system that it was run on.

**Comment by gabrielmatau79** [comment]
Thanks jamadden for you help ..!
