### ISSUE TITLE
Gevent sleep within the group ?

### ISSUE THREAD

**Issue by davit555** [gevent/gevent#1498]
Let's say I have two gevent pools
```
gevent_pool_1 = Pool(2)
gevent_pool_2 = Pool(2)
```

I want to gevent.sleep(10) in gevent_pool_1
which will not block the gevent_pool_2

is there any possibility? 
Couldn't find it from the docs

**Comment by jamadden** [comment]
A greenlet executing `gevent.sleep(some_number)` yields to the event loop and thus lets other greenlets run. Pools don't enter into the discussion at all --- pools are just a way to track a group of greenlets.

**Comment by davit555** [comment]
Thank you for the quick reply.
thought, really would be useful for example for per session rate-limiting or something like that..

**Comment by davit555** [comment]
thanks for the answer and sorry for the late replay
thanks for the answer, just wondered why isn't it supporting? It could be useful on per session rate-limiting or something like that...
