### ISSUE TITLE
BaseServer can accept many more connections than desired.

### ISSUE THREAD

**Issue by fizx** [gevent/gevent#1505]
* gevent version: Github master
* Python version: Any
* Operating System: Any

### Description:

Docs claim that StreamServer/BaseServer will check to see if the Greenlet Pool is full.  In fact, that check is stubbed out.  This has the potential to break people who rely on the concurrency limiting feature, as gevent will accept more connections than the pool is able to service.

https://github.com/gevent/gevent/blob/master/src/gevent/baseserver.py#L64
https://github.com/gevent/gevent/blob/master/src/gevent/baseserver.py#L245

**Comment by jamadden** [comment]
In fact, the pool's `full()` method overwrites the stub method. That's what the comment in the stub method is trying to describe.

https://github.com/gevent/gevent/blob/a67a39f4c452d251940fdd12bc32cf6fead9e4d5/src/gevent/baseserver.py#L155-L156

**Comment by fizx** [comment]
Thanks @jamadden!  That wasn't really clear.

I'll do a better job of extracting my repro case into a gist or something.  It's possible that it's a thing specific to my setup, but I'm definitely getting a server accepting 200 connections on a size = 100 pool (and then hanging 100).

**Comment by jamadden** [comment]
Perhaps you’re encountering an issue with the socket backlog (which is all of OS dependent, silent, and configurable).  Other than that I don’t have any guesses. I ran some tests to confirm that the pool is properly obeyed, and no `accept` calls are made once the pool fills —- this is easily checked by overriding `stop_accepting`

**Comment by jamadden** [comment]
There hasn't been any activity on this issue in quite a while, so I'm closing it. Feel free to re-open if there is additional information to add.
