### ISSUE TITLE
FileObject seek doesn't seem to work

### ISSUE THREAD

**Issue by denik** [gevent/gevent#151]
<b>What steps will reproduce the problem?</b>
1. Createa  file called testfile in the working directory. Fill it with at least 1050 bytes of data.
2. Run the attached script (it will perform a seek then read with basic file operations and then do the same with gevent's fileobject)

<b>What is the expected output? What do you see instead?</b>

Expected:
1024
data: kjasflksajflsajfalskjfsak
1024
data: kjasflksajflsajfalskjfsak

Actual:
1024
data: kjasflksajflsajfalskjfsak
0
data: 

<b>What version of the gevent are you using?</b>
gevent 1.0b3

<b>On what operating system?</b>
Mac OSX 10.7.4

<b>On what Python?</b>
Python 2.7.1

<b>Please provide any additional information below.</b>

<p><a href="http://code.google.com/p/gevent/issues/detail?id=151">Reported by mrkhingston.</a></p><hr/><h2>earlier comments</h2>
<p><strong>Denis.Bilenko said, at 2012-08-30T07:31:46.000Z:</strong></p>
<p>Indeed. seek() works for me on Linux but does crazy things on Mac OS X.</p>

**Comment by jamadden** [comment]
Here was the original script:
```python
#!/usr/bin/env python
from gevent.fileobject import FileObject

f = open('testfile', 'rb')
f.seek(15)
data = f.read(1024)
print len(data)
print 'data: {}'.format(data[0:25])

f_raw = open('testfile', 'rb')
f = FileObject(f_raw, 'rb')
f.seek(15)
data = f.read(1024)
print len(data)
print 'data: {}'.format(data[0:25])
f.close()
```
