### ISSUE TITLE
What are the plans for dropping python2 support

### ISSUE THREAD

**Issue by nom3ad** [gevent/gevent#1518]
Since python2 have reached it's EOL, many projects  already pledged to drop support for python2. Some projects have already made this transition. [sunsetting Python 2 support](https://python3statement.org/)

Do we have any python3 migration plans as of now?

**Comment by jamadden** [comment]
Python 3 is fully supported. Python 2 won't be dropped for at least the next major release of gevent.

**Comment by bluetech** [comment]
Reading through gevent's code, I notice that Python 2 support adds a fair bit of complexity, so I wondered about this as well. Python 2 is now no longer supported. According to [PyPI stats](https://pypistats.org/packages/gevent), gevent Python 2 downloads are around 3% to 5% (and I'm guessing many of them are pinned to older versions anyway). So maybe now is a good time to drop Python 2? I can try to prepare a PR for it if it will help.
