### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by Set4now** [gevent/gevent#1531]
* gevent version:  1.4.0
* Python version: 3.6.9
* Operating System:  Red Hat Enterprise Linux Server release 5.3 (Tikanga)

current setup
nginx-gunicorn-flask
### Description:

Am trying to run flask-socketIO with gevent and gunicorn
gunicorn -k gevent -c $1  app:app

```python
cat app. py
from flask_socketio import SocketIO
app = Flask(__name__)
app.secret_key = """kljclkcdlskcmsdlkcmnyrandomstring"""
socketio = SocketIO(app)

if __name__ == '__main__':
    app.config['DEBUG'] = True

```

Gunicorn starts but throws exception:- 
   ......
   client_cert=new_config.client_cert)
    client_cert=client_cert,
  File "/python3.6/site-packages/botocore/httpsession.py", line 180, in __init__
    self._manager = PoolManager(**self._get_pool_manager_kwargs())
  File "python3.6/site-packages/botocore/httpsession.py", line 188, in _get_pool_manager_kwargs
    'ssl_context': self._get_ssl_context(),
  File "/lib/python3.6/site-packages/botocore/httpsession.py", line 197, in _get_ssl_context
    return create_urllib3_context()
  File "/lib/python3.6/site-packages/botocore/httpsession.py", line 72, in create_urllib3_context
    context.options |= options
  File "/python3.6/lib/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/python3.6/lib/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/python3.6/lib/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 310 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by Set4now** [comment]
I have seen people are talking about monkey patching order. Not sure where exactly i need to insert that

**Comment by jamadden** [comment]
You must monkey-patch before importing anything else. gunicorn's default monkey patching is sometimes not enough and you need to do it sooner. Exactly how you do that will depend on your specific deployment scenario (we use a setuptools entry point). There's more discussion at https://github.com/benoitc/gunicorn/issues/1566

Example entry point
======

Add a module:
```python
# gevent_gunicorn.py
from gevent import monkey; monkey.patch_all()
import sys
from pkg_resources import load_entry_point


def main():
    sys.exit(
        load_entry_point('gunicorn', 'console_scripts', 'gunicorn')()
    )


if __name__ == '__main__':
    sys.exit(main())
```

And add the entry point in setup.py:

```python
setup(…
    entry_points={
        'console_scripts': [
            "my_gunicorn=my.package.gevent_gunicorn:main",
        ],
    },
)
```

Then to launch, specify `my_gunicorn <arguments>` instead of `gunicorn <arguments>`.

**Comment by jamadden** [comment]
Closing since there’s been no response.
