### ISSUE TITLE
Add `gevent.selectors:GeventSelector`

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#1532]
This would be a full featured Selector implementation taking advantage of gevent internals.

Ideally, it would exist on Python 2 with a compatible API to help apps transition (maybe there's a backport library for the base selector?).

See details in https://github.com/gevent/gevent/pull/1523#issuecomment-582494487

**Comment by hashbrowncipher** [comment]
I have this deployed and it's working great. Thanks for doing all of the work to get it merged!

**Comment by jamadden** [comment]
Thanks for the feedback! It's rare to get feedback of any kind, let alone positive.

**Comment by vytas7** [comment]
> It's rare to get feedback of any kind

Oh, c'mon... The only reason for the above I can think of is that gevent works really well, and people are more vocal when things don't. I'm pretty sure the battle tested-gevent is still very widely used.

And you're doing a great job maintaining it :100:
