### ISSUE TITLE
Wheel for Python 3.8 (cp38)

### ISSUE THREAD

**Issue by MartinThoma** [gevent/gevent#1534]
* gevent version: 1.4.0
* Python version: cPython 3.8.x

### Description:

[The latest gevent does not have a wheel on PyPI for Python 3.8](https://pypi.org/project/gevent/#files). Could you please add one? This would prevent me from having to install cffi :-)

**Comment by MartinThoma** [comment]
Currently, I get 

>  /usr/local/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'cffi_modules'

**Comment by jamadden** [comment]
gevent 1.4 does not support Python 3.8. Please use gevent 1.5, which does have the appropriate wheels.

**Comment by MartinThoma** [comment]
So I have to wait: https://github.com/gevent/gevent/milestone/21 😢

**Comment by jamadden** [comment]
No, 1.5a3 is released and used in production. There's just more features to add.
