### ISSUE TITLE
FileObjectBlock: read() should return bytes

### ISSUE THREAD

**Issue by wiggin15** [gevent/gevent#1535]
* gevent version: 1.5a3
* Python version: 3.7.3 on macOS

### Description:

Using `FileObjectBlock` and `FileObjectThread` in Python 3 with gevent 1.5a3 fail to read.

### What I've run:

```python
>>> from gevent.fileobject import FileObjectBlock
>>> f = open("foo", "r")
>>> fo = FileObjectBlock(f, "r")
>>> fo.read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: read() should return bytes
```

**Comment by jamadden** [comment]
You need to pass `"rb"` when you `open` the file. gevent's file objects require a "raw" descriptor that returns bytes.

(Of course this is a silly example, `open` already returns a blocking file object.)

**Comment by wiggin15** [comment]
This used to work - the change is not backwards compatible with gevent 1.4.0 and I couldn't find a note about this in `CHANGES`.

I have a function that looks like this:
````
def fdopen(fd, mode='r', buffering=-1):
    f = os.fdopen(fd, mode, buffering)
    return FileObjectThread(f, mode, buffering)
```
It will be hard to modify it so that `fdopen` always uses `b` but `FileObjectThread` uses the mode requested by the user.

**Comment by jamadden** [comment]
Under gevent 1.4, `FileObjectThread` was *badly* broken on Python 3, and it behaved differently than `FileObjectPosix`. The issue was #1441

**Comment by wiggin15** [comment]
I reported #1441. It was more about the bug about return types. I didn't think it will cause backward-incompatible changes. I understand there is no chance to treat this as something that should be fixed?
