### ISSUE TITLE
Hang when calling `fork()` after `socket.connect()` (“WARNING: Mixing fork() and threads detected; memory leaked.”)

### ISSUE THREAD

**Issue by denik** [gevent/gevent#154]
In testing 1.0b4, I've found that the process will hang when calling `socket.connect()` after a `fork()` if `socket.connect()` was called before the fork. See below and attached for an example.

Some poking around leads me to believe that the cause of this issue is:
- The first call to `connect()` spawns a thread in the default hub's thread pool (to call `getaddrinfo`)
- After the call to `connect()` returns, the thread is left in the pool
- The second call to `connect()` (after `fork()`) tries to re-use the same thread pool
- ??? something breaks ???

Currently I'm solving this problem by manually calling `gevent.hub.get_hub().threadpool.kill()` before calling `fork()`, which prevents the hang, but the WARNING is still issued.

Example (also attached):

<pre>
$ cat gevent_1.0b4_socket_fork_hang.py
from gevent import monkey; monkey.patch_all()
import os
import socket

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((&quot;google.com&quot;, 80))
s.close()

# NOTE: Uncomment this to fix the hang (but the warning is still printed)
# import gevent
# gevent.hub.get_hub().threadpool.kill()

pid = os.fork()
if pid == 0:
    print &quot;Child calling connect...&quot;
    s2 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s2.connect((&quot;google.com&quot;, 80))
    s2.close()
    print &quot;Child done.&quot;
else:
    print &quot;Waiting for child...&quot;
    os.waitpid(-1, 0)
    print &quot;All done.&quot;

$ python gevent_1.0b4_socket_fork_hang.py
Waiting for child...
Child calling connect...
WARNING: Mixing fork() and threads detected; memory leaked.
</pre>

&lt;hang&gt;<p><a href="http://code.google.com/p/gevent/issues/detail?id=154">Reported by wolever.</a></p><hr/><h2>earlier comments</h2>
<p><strong>wolever said, at 2012-09-11T22:26:41.000Z:</strong></p>
<p>After some more tinkering, it seems like calling `gevent.sleep(0)` after `fork()` is sufficient to prevent the hang:

<pre>
$ cat gevent_1.0b4_socket_fork_hang_hacky_fix.py
from gevent import monkey; monkey.patch_all()
import os
import socket

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(("google.com", 80))
s.close()

#
# HACKY FIX
#
import gevent
gevent.hub.get_hub().threadpool.kill()
pid = os.fork()
gevent.sleep(0)
#
# HACKY FIX
#

if pid == 0:
    print "Child calling connect..."
    s2 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s2.connect(("google.com", 80))
    s2.close()
    print "Child done."
else:
    print "Waiting for child..."
    os.waitpid(-1, 0)
    print "All done."

$ python gevent_1.0b4_socket_fork_hang_hacky_fix.py
Waiting for child...
Child calling connect...
Child done.
All done.
</pre>

</p><p><strong>wolever said, at 2012-09-11T22:35:50.000Z:</strong></p>
<p>Here is the “fixed” version of `fork()` that I will be using in my application. The
decision to kill all active threads might not be right for everyone, but it works
nicely for me:

<pre>
def fork():
    tp = get_hub().threadpool
    if len(tp):
        sys.stderr.write("WARNING: calling fork() while threads are active; "
                         "they will be killed.\n")
    tp.kill()
    tp.join()
    result = gevent.fork()
    gevent.sleep(0)
    return result
</pre>

</p>

**Comment by jamadden** [comment]
The original problem is fixed in 103110209cba0d7acd739410899253a3ef5d05b7. The examples I put just above are fixed in 4b59a30450f14dad44c297be0571e94da959eb1a (albeit, because of the way the loop works, it takes a full cycle around the loop for the fork callback to happen. This means that the code has to sleep more than once before the watcher is called.)
