### ISSUE TITLE
gevent.release() return value is 0

### ISSUE THREAD

**Issue by csjy12580** [gevent/gevent#1545]
* gevent version: 1.4.0
* Python version: python2.7.17 downloaded from python.org"
* Operating System: "centos 7.2"

### What I've run:

```python
#-*- coding: utf-8 -*-
from gevent.lock import BoundedSemaphore
sem = BoundedSemaphore(value=10)
print("Counter:",sem.counter)
print("init:",sem._initial_value)
print(sem.acquire())
print("counter:",sem.counter)
print("release return value :",sem.release())
print(sem.counter)
```
The Return Value: 
![image](https://user-images.githubusercontent.com/22486671/77532320-a0021c80-6ecf-11ea-8ec6-03af45ef32dd.png)

accord to API:
```python
    def release(self):
        """
        Release the semaphore, notifying any waiters if needed.
        """
        self.counter += 1
        self._check_and_notify()
        return self.counter
```
The sem.release()'s return value should be 10

**Comment by jamadden** [comment]
> The sem.release()'s return value should be 10

[The documentation](http://www.gevent.org/api/gevent.lock.html#gevent.lock.Semaphore.release) doesn't mention any return value, so the method is free to return whatever it wants, including None (which is what's actually being returned; the 0 is an artifact of Cython). The source code you're looking at —— which is not the same thing as its documentation —— is for a different method.

Also note that `counter` and `_initial_value` are undocumented internal details subject to change.
