### ISSUE TITLE
gevent fails to build on RHEL 5

### ISSUE THREAD

**Issue by wiggin15** [gevent/gevent#1550]
* gevent version: 1.5a4
* Operating System: RHEL 5

### Description:
RHEL 5, although old, is still supported and used to work with gevent 1.4. The latest version fails to compile on it due to the dependencies:

- libev: we get the following error:

        deps/libev/ev.c: In function ‘ev_run’:
        deps/libev/ev.c:4051: internal compiler error: in insert_save, at caller-save.c:725

this seems to be due to a bug in the older gcc that comes with RHEL 5: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=34434
I did not find exactly what causes this and did not report it to libev.

- libuv: see https://github.com/libuv/libuv/issues/2770

It's ok if you decide it's not worth supporting this platform, but we still use it and I wanted to bring this to your attention.

**Comment by jamadden** [comment]
Thanks for the report. [manylinux2010](https://www.python.org/dev/peps/pep-0571/) is the required baseline for gevent 1.5. That's defined to be CentOS 6. The previous baseline, CentOS 5.11, couldn't compile libuv at all and I presume RHEL 5 would have the same issue.
