### ISSUE TITLE
Orphan greenlets still running after I kill them

### ISSUE THREAD

**Issue by atibdialpad** [gevent/gevent#1553]
* gevent version: 1.1rc3
* Python version: Python 2.7.16
* Operating System: Linux worker-node-1 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

### Description:
I have a scenario where :
1. I have a bunch of greenlets.
2. Each greenlet is tracked via a gevent.pool
3. Each greenlet run a set of network tests (liking running a ping/mtr etc to some destination eg 8.8.8.8)
4. The greenlet run until I explicitly kill it 
the implementation looks like this :  

```python
"Put python code in python blocks"
CREATION FLOW : 
greenlet_thread = gevent.spawn(test_function()) 
self.gevent_pool.add(greenlet_thread)  

DELETION FLOW:
self.gevent_pool.killone(greenlet_thread)

TEST FUNCTION LOOKS LIKE THIS
def test_function():
  while True:
    ping 1.1.1.1 > log_file_name
    gevent.sleep(10)
```
Things were working fine. That is to say, the pings were stopped when greenlet was killed in the DELETION FLOW.
Recently I added a bunch of more tests in my test_function, in addition to running ping, now it runs mtr as well. Plus it runs both ipv4 and ipv6 pings and mtrs. Post this I am observing that these tests still running event after the deletion flow is invoked. 
While experimenting when I tried increasing the sleep in test_function() to 120 seconds it started working fine.
The issue is certainly related to how cpu intensive my test_function is VS the sleep timer, but I don't seem to get what exactly is going on here ?

**Comment by atibdialpad** [comment]
@jikamens @jamadden 
is this related to https://github.com/gevent/gevent/issues/330 ?

**Comment by jamadden** [comment]
This seems unlikely to have anything to do with 330.

gevent 1.1rc3 is not supported anymore and implementation details have changed substantially in newer versions such that if you try the current version (1.5) you might find different behaviour. *might* being the operative word, as it depends on exactly what your code is doing. There aren't enough details to say for sure beyond your hunch that your greenlets are performing non-cooperative/non-yielding operations (which is probably correct).

**Comment by atibdialpad** [comment]
thanks @jamadden let me check with 1.5 and get back.
one question on the expected behaviour,
suppose the event queue looks like this 
-----------------------------------------------------------
some op | some op |.....| kill |......|some op| ...... |some op|
-----------------------------------------------------------
where 'some_op' is the test_functio() that is running and then sleeping for 10 second before it begins doing it 'some_op' in while loop
and 'kill' is the gevent.kill() that has been enqueued() by the parent greenlet.
In this case, what is the expected behavior ? the greenlet loop breaks or is the 'kill' going to get ignored since there are some tasks still in the enque after it ?

**Comment by jamadden** [comment]
Once it is running, killing a greenlet just causes it to raise an exception at some point in the future. The greenlet has to choose to ignore that exception. There's no context around that exception, no way for the greenlet to examine this hypothetical "event queue" and discover that…actually, I'm not sure what your example is trying to say; `while` loops are a Python concept independent of gevent's event loop and specifically independent of the callbacks used to respond to events.

"some point in the future" is probably the key. The greenlet (all greenlets!) must be cooperating with the gevent event loop (by periodically giving up control, yielding) or that point in the future may never come.

The [blocking monitoring thread](http://www.gevent.org/monitoring.html) might be helpful to you.

**Comment by atibdialpad** [comment]
thanks @jamadden for the info so far
" I'm not sure what your example is trying to say"

the code that runs in my greenlet is in a python while loop, so my expectation is that it must run endlessly until the greenlet is killed by the kill signal

**MAIN FUNCTION:**
'''
greenlet_thread = gevent.spawn(test_function()) 
self.gevent_pool.add(greenlet_thread) ----> I am managing all greenlets via a pool
'''
**WORKER GREENLET :** 
'''
while True:
   <do something>
   **sleep(10) <----this is the cooperative part**
'''
MAIN FUNCTION:
because of the sleep(10) the control comes out of the WORKER GREENLET. 
Based on some events in  the  MAIN FUNCTION,  gevent_pool.killone(WORKER_GREENLET) is executed which successfully kills the greenlet.

In a recent change, we have increased the work that we do in <do_something> part of the WORKER GREENET post which I see the job still running after a kill. 
However if I increases the sleep time from 10 to 100, it starts working fine, as in the WORKER GREENLET is killed successfully and the  <do_something> workload stops.

What I am not able to understand is what is the dependence with the sleep timer value and kill not working as expected ?
Is your "some point in the future" playing a role here ?

**Comment by jamadden** [comment]
> Is your "some point in the future" playing a role here ?

Possibly. You seem to have a timing issue of some sort and aren't yielding when you think you are, or you have something (this new work) catching and ignoring the exception that's meant to kill the greenlet.

Without actually seeing and stepping through the code (which I don't have the time for), it's impossible to be more precise.

**Comment by atibdialpad** [comment]
awesome....
deep down in my worker greenlet, there was a try and except block which was eating gevent.greenlet.GreenletExit

I fixed that and it works..

thanks a lot @jamadden (Learnt a lot about gevent, debugging this issue and discussing with you)
