### ISSUE TITLE
Make releases easier and more frequent

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#1555]
gevent's yearly major release cadence is too slow, especially with CPython accelerating their release schedule from 18+months down to 12. Since pip and warehouse now conspire to hide "pre-release" versions, they might as well not exist—no one sees them or installs them by default.

We already have the policy of keeping `master` in a release-ready state at all times, so we might as well capitalize on that and make smaller "final" releases more frequently. That comes with its own set of challenges, most of which can be automated out of the way. (Inspiration comes from things like [pip's release process](https://pip.pypa.io/en/latest/development/release-process/).)

- [x] Decide an a release cadence. Every time there's some non-trivial change? Set a schedule? pip does the latter; most other projects I work on do the former, at the discretion of the project (e.g., a bunch of the changes I recently made to zope.interface were part of a theme and so I held of releasing 5.0 until all the PRs were created and merged). It's this faster cadence that drives the next change.
- [x] Switch to [CalVer](https://calver.org) using `YY.0M.Micro`, e.g., the next release would be 20.04.0. This requires some of the other changes below.
- [x] Write a clear deprecation policy based on the cadence. Probably a year, to match CPython's schedule, roughly?
- [x] Figure out how to handle `.. versionadded:` and `.. versionchanged:` in docstrings. I'm thinking `.. versionadded: NEXT` is what's checked in, and at release time a script replaces those with the release version. zest.releaser can probably automate that.
- [x] Maybe use [towncrier](https://github.com/twisted/towncrier) to generate CHANGES.rst. If so, integrate that with zest.releaser.
- [x] Document the release process.
- [x] Let Appveyor and Travis build and upload Windows, Manylinux and Mac wheels for releases. BTrees [is a good](https://github.com/zopefoundation/BTrees/blob/master/.travis.yml) example [of this](https://github.com/zopefoundation/BTrees/blob/master/appveyor.yml).
- [x] Add upper bounds to `python_requires`? Not strictly related but we've had lots of people installing gevent 1.4 on Python 3.8 (because of the no-pre-release thing that pip does), which is not supported. 
- [x] Other documentation improvements: especially about building from source, e.g., alpine linux (#1567, #1562, #1559, #1566). This needs a callout in whatsnew_1_5.html

**Comment by jgehrcke** [comment]
Thank you @jamadden for your continued efforts, and this excellent level of clarity and transparency in your communications on GitHub.
