### ISSUE TITLE
Gevent and python version in requirements.txt

### ISSUE THREAD

**Issue by ghost** [gevent/gevent#1557]
We have a pull request open intended to update the requirements.txt in [ZeroNet](https://github.com/hellozeronet/zeronet). The problem is that some want to use Python 3.0-3.4 which obviously not supported by gevent version 1.5.0. 

Until now version 1.1.0 used for most of the python versions below version 3.8. 
I think is strange that someone need to use python 3.4 today but @imachug believes is necessary. 

PR: https://github.com/HelloZeroNet/ZeroNet/pull/2518

**Comment by jamadden** [comment]
Then you may want to write a conditional requirement ([PEP 508](https://www.python.org/dev/peps/pep-0508/), I think):

```
gevent <= 1.4.0; python_version == "3.4"
gevent >= 1.5.0; python_version == "2.7" or python_version > "3.4"
```

That may not be necessary though. gevent includes the `python_requires` metadata that restricts installation of gevent on incompatible versions. pip uses that information to pick the best version. So if you just write `gevent >= 1.4`, you'll get 'gevent==1.4' on Python 3.4 and `gevent==1.5.0` on Python 2.7 and 3.5–3.8.

**Comment by jamadden** [comment]
Upstream issue was closed.
