### ISSUE TITLE
gevent.getaddrinfo fails with IPv6 scope-id. Fails with socket.gaierror: [Errno 11] ARES_ECONNREFUSED

### ISSUE THREAD

**Issue by bdubey** [gevent/gevent#1560]
* gevent version: 1.5.0
* Python version: 2.7.5
* Operating System: CentOS 7.6.1810 x86
### Description:
On providing Ipv6 address with scope-id  to `gevent.getaddrinfo` it fais with `socket.gaierror: [Errno 11] ARES_ECONNREFUSED` with `c-ares` based resolver

From  [getaddrinfo](http://man7.org/linux/man-pages/man3/getaddrinfo.3.html)
```
getaddrinfo() supports the address%scope-id notation for specifying
the IPv6 scope-ID.
```

### What I've run:

```python
from gevent import monkey
monkey.patch_all()
import socket
targets = socket.getaddrinfo("::1%eth0", 1234, socket.AF_INET6, socket.SOCK_DGRAM)
```

**Traceback**
```
>>> targets = socket.getaddrinfo("::1%eth0", 1234, socket.AF_INET6, socket.SOCK_DGRAM)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/gevent/_socketcommon.py", line 202, in getaddrinfo
  File "build/bdist.linux-x86_64/egg/gevent/resolver/ares.py", line 248, in getaddrinfo
  File "build/bdist.linux-x86_64/egg/gevent/resolver/ares.py", line 209, in _getaddrinfo
  File "build/bdist.linux-x86_64/egg/gevent/resolver/ares.py", line 375, in get
socket.gaierror: [Errno 11] ARES_ECONNREFUSED: Could not contact DNS servers
```

**Comment by jamadden** [comment]
Why do you think this is an issue with gevent and not c-ares? If you want a resolver that behaves exactly like your system's resolver, just use the default resolver.

**Comment by bdubey** [comment]
c-ares has its own version of getaddrinfo ([ares_getaddrinfo](https://github.com/c-ares/c-ares/commits/master/ares_getaddrinfo.c)) which gevent isn't using. Instead, it is trying to work with `ares_gethostbyname` . This still could be unrelated, just pointing out.
