### ISSUE TITLE
i got this issue while typing this command in kali linux (python3 -m pip install -r requirements.txt) how to fix this?

### ISSUE THREAD

**Issue by neiIdyan** [gevent/gevent#1562]
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-9gueior3/gevent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-yqbx5hin/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-9gueior3/gevent/

**Comment by jamadden** [comment]
What actual error are you getting? What you’ve pasted here is on,y a result of an error, not the actual error.

**Comment by neiIdyan** [comment]
> What actual error are you getting? What you’ve pasted here is on,y a result of an error, not the actual error.

Failed building wheel for gevent
  Running setup.py clean for gevent
Failed to build gevent
Installing collected packages: gevent, httplib2, lxml, MarkupSafe, murmurhash, nltk, oauth2, oauthlib, pandas, plac, preshed, pycares, PySocks, python-Levenshtein, PyYAML, redis, requests-oauthlib, schedule, blessed, search-engine-parser, tqdm, socialscan, srsly, wasabi, thinc, spacy, tokenize-rt, tweepy, twint, typing, Werkzeug, langdetect, googletrans, vaderSentiment
  Running setup.py install for gevent ...

**Comment by jamadden** [comment]
Sorry, no, that's still not the error. Look higher or provide the entire output. 

Most likely the problem is that you're missing required dependencies to compile the C code for libev or libuv. See #1559 as another example.

**Comment by AnhTaiMai** [comment]
fix: sudo apt-get install requirements.txt
its work for me.
