### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by hillia** [gevent/gevent#1563]
* gevent version: 
1.5.0

* Python version: 
Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516] on linux2

* Operating System: 
Debian GNU/Linux 9.5 (stretch)

(Python + Linux version come from `ruby-2.3.7-stretch` Docker image: https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/ruby/images/2.3.7-stretch/Dockerfile)

### Description:

After the 1.5.0 release, our Docker images failed to build when trying to install `gevent` via `pip`. We temporarily fixed this by locking our version at `<1.5.0`.

### What I ran:

As part of building our Docker image, we install gevent using pip:
```
apt-get update -qq \
     && apt-get install -y -q --no-install-recommends python-pip \
     && rm -rf /var/lib/apt/lists/* \
     && pip install gevent boto3 \
     && rm -rf ~/.cache/pip \
     && apt-get autoremove -y python-pip
```

After the 1.5.0 release, we began receiving the following error:
```
Collecting gevent
  Downloading https://files.pythonhosted.org/packages/5a/79/2c63d385d017b5dd7d70983a463dfd25befae70c824fedb857df6e72eff2/gevent-1.5.0.tar.gz (5.3MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-uisHlV/gevent/
```

I fixed this by locking our gevent version to `<1.5.0`
```
apt-get update -qq \
     && apt-get install -y -q --no-install-recommends python-pip \
     && rm -rf /var/lib/apt/lists/* \
     && pip install 'gevent<1.5.0' boto3 \
     && rm -rf ~/.cache/pip \
     && apt-get autoremove -y python-pip
```

**Comment by jamadden** [comment]
Sorry, your pip environment is broken. Upgrade your pip and you’ll be able to use binary wheels, too, I think. 

Note that setuptools has been a hard dependency for building gevent from source since at least 1.2. Possibly what’s happening is you have a pip with broken or missing support for pep 518.

**Comment by hillia** [comment]
Thanks. Sorry to bother you.

**Comment by jamadden** [comment]
Thank you for the report. 

I apologize for being short.
