### ISSUE TITLE
Why do I suddenly need libffi-dev, file, and make?

### ISSUE THREAD

**Issue by josephcsible** [gevent/gevent#1566]
docker run python:3.7.7-alpine3.11 sh -c 'apk --no-cache add gcc libc-dev; pip install --no-cache-dir gevent==1.5.0'

When I run that, it fails, with the important part of the error being `fatal error: ffi.h: No such file or directory`. I already know the solution for this: install libffi-dev. However, there's one thing I don't know: if I install gevent 1.4.0 instead of 1.5.0, then it works fine even without libffi-dev. What changed in 1.5 such that libffi-dev is now a requirement? If it's in the changelog, I didn't see it.

(And once that error is gone, I get other errors unless I also install `file` and `make`, which I similarly didn't need before.)

**Comment by jamadden** [comment]
Most likely is the explicit inclusion of pyproject.toml in gevent's source distribution (binary distributions aren't permitted for alpine linux, only for distributions based on glibc), which is essentially the modern version of `setup_requires`. Implicit source dependencies are now explicit.

As for `file` and `make`, it just depends on what the third-party configure scripts do. I have no control over that.

**Comment by chrisinmtown** [comment]
Thanks for opening this issue and listing the new requirements libffi-dev, file, make.  My gevent install failed similarly on alpine, altho with python 3.8. Your note let me repair locally in minutes instead of days :)
