### ISSUE TITLE
How to make raw fork work with gevent.subprocess. Issue with gevent.waitpid OSError: [Errno 10] No child processes

### ISSUE THREAD

**Issue by bdubey** [gevent/gevent#1573]
* gevent version:1.5
* Python version: 2.7.5
* Operating System: CentOS 7.6.1810 VM

### Description:
This is more a question than an issue because this use case itself seems to be quite unique.
I am trying to update gevent from `1.0.1` to `1.5`. There is a C Extension that does `fork` and `excec` of course using system calls directly.  Using this along with `gevent.subprocess` creates problem in `os.waitpid`. I beleive `signal, subprocess, waitpid`  were not patched in `gevent-1.0.1` so this came up as a regression upon updating gevent. Somewhere  `SIGCHILD` is getting leaked. Requesting pointers in terms of any change in code or some suggested patch in gevent source so that this can be made to work while retaining maximum gevent capabilities.

### What I've run:

```python
import gevent
from gevent import monkey

#This of course works
# monkey.patch_all(os=False,subprocess=False) 

#This doesn't
monkey.patch_all()


import time
import os
import subprocess

#get original fork
raw_fork = monkey.get_original('os', 'fork')

pid = raw_fork() #####This is a part of c extension which I can't change
if pid  == 0:
  #child
  os._exit(1)

####In parent
args = 'ls'
proc = subprocess.Popen(args, close_fds=True, shell=False,stdout=subprocess.PIPE, stderr=subprocess.PIPE)
# stdout,stderr = proc.communicate()

time.sleep(3) ############# Commenting this works.
              ############# Commenting this probably ensures there is no greenlet switch so it works
              ############# Actual code has no sleep here, but after the witpid call if child is running
              ############# waitpid is again called again after sleep till we get the status
print(os.waitpid(pid, os.WNOHANG))

```
**TRACEBACK**
```
Traceback (most recent call last):
  File "raw_fork_subprocess.py", line 25, in <module>
    print(os.waitpid(pid, os.WNOHANG))
  File "build/bdist.linux-x86_64/egg/gevent/os.py", line 386, in waitpid
    saved_tb = tb
OSError: [Errno 10] No child processes
```

**Comment by jamadden** [comment]
You can't use gevent's `waitpid` to cooperatively wait for a PID that's effectively not a child of gevent. Doing so causes gevent to fall back to the raw operating system's `waitpid` call; that's not cooperative and has race conditions (like this one). And, of course, as noted, it goes the other way too: if anything else is catching SIGCHLD it's going to interfere with gevent cooperatively watching its own children.

The long and short of it is that you can't mix and match. I don't have a look-at-your-cake-and-eat-it-too solution.

Ancient versions of gevent didn't know anything about children or watching for them or have cooperative versions of any of these functions so it wasn't a problem for them, and going back to that situation (via not patching the module) is the best general solution I can offer. In particular cases you may find [disable_watch_children](http://www.gevent.org/configuration.html#gevent._config.Config.disable_watch_children) or some of the specialized [gevent.os](http://www.gevent.org/api/gevent.os.html#module-gevent.os) forking functions helpful; likewise, you might try the libuv backend, which handles observing children slightly differently

**Comment by bdubey** [comment]
I was trying to use `libuv` for the backend but get below error. I am on python `2.7.5` and have built gevent from the source.
```
Traceback (most recent call last):
  File "test2.py", line 25, in <module>
    proc = subprocess.Popen(args, close_fds=True, shell=False,stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "build/bdist.linux-x86_64/egg/gevent/subprocess.py", line 599, in __init__
    every pair of backslashes is interpreted as a literal
  File "src/gevent/_hub_local.py", line 73, in gevent.__hub_local.get_hub_noargs
  File "src/gevent/_hub_local.py", line 80, in gevent.__hub_local.get_hub_noargs
  File "build/bdist.linux-x86_64/egg/gevent/hub.py", line 425, in __init__
  File "build/bdist.linux-x86_64/egg/gevent/hub.py", line 439, in loop_class
  File "build/bdist.linux-x86_64/egg/gevent/_config.py", line 50, in getter
  File "build/bdist.linux-x86_64/egg/gevent/_config.py", line 146, in get
  File "build/bdist.linux-x86_64/egg/gevent/_config.py", line 248, in validate
  File "build/bdist.linux-x86_64/egg/gevent/_config.py", line 223, in _import_one_of
  File "build/bdist.linux-x86_64/egg/gevent/_config.py", line 237, in _import_one
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "build/bdist.linux-x86_64/egg/gevent/builtins.py", line 96, in __import__
  File "build/bdist.linux-x86_64/egg/gevent/libuv/loop.py", line 19, in <module>
ImportError: cannot import name _corecffi
```

**Comment by bdubey** [comment]
Also when using  `export GEVENT_NOWAITPID='True'`,  I still saw this issue. It seems `subprocess` is by default using `fork_and_watch` which does watch children. Is it desired?

This combination below hence is helping in getting rid of watch on children.  One more trial remaining is `libuv` if the error in the previous comment can be sorted.
export GEVENT_NOWAITPID='True'
```
```python
monkey.patch_all(subprocess=False)
```

**Comment by jamadden** [comment]
> I am on python 2.7.5

The maximum version of gevent that runs on Python 2.7.5 is 1.2. gevent 1.3 and above do not support anything earlier than 2.7.9.

> ImportError: cannot import name _corecffi

Probably the module didn't build. Check the output of the build process carefully. (You may need to use pip's verbose mode to see it.) Most likely cffi wasn't installed at build time, though pip is supposed to take care of that if you're using a modern pip; if you're not you'll have to do that manually.

>  It seems subprocess is by default using `fork_and_watch` which does watch children. Is it desired?

If you want it to work, yes. As I said, you can't mix and match. Either gevent is watching children or something else is. It can't be both. The suggestions I gave are bandaids/hacks that *may* work in certain scenarios, but it's by chance.

**Comment by bdubey** [comment]
My point was setting `GEVENT_NOWAITPID ` does nothing to subprocess as it still uses a version of fork which watches children. Only patching of `os.fork` is controlled by `GEVENT_NOWAITPID`.  Shouldn't setting this should ensure that event is not watching its children at all? At least it should be specified [here](http://www.gevent.org/configuration.html#gevent._config.Config.disable_watch_children)

**Comment by jamadden** [comment]
> Shouldn't setting this should ensure that event is not watching its children at all?

No. Don't use gevent.subprocess or monkey-patch gevent.subprocess if you don't want gevent to watch children. subprocess *must* watch children, that's just how libev works.

>  But since 1.2 is too ancient I decided to try my luck with 1.4/1.5. In fact, you recommended this on another thread :) :)

Yes, where I said it's not supported but it *may* work in very specific, very narrow use cases. But if it doesn't there's nothing I can do about it, and I don't have much time to look into weird things that happen on unsupported combos.

**Comment by jamadden** [comment]
There hasn't been any activity on this issue in quite a while, so I'm closing it. Feel free to re-open if there is additional information to add.
