### ISSUE TITLE
Unable to install gevent on Windows 10 through cygwin

### ISSUE THREAD

**Issue by dspringst** [gevent/gevent#1578]
* gevent version: 1.5.0
* Python version: Please be as specific as possible: Python 3.6 from Cygwin installer
* Operating System: Windows 10 64-bit, Cygwin

### Description:

It appears that there are no prebuilt binaries for cygwin, so the installation attempts to build from source, however, it errors out during the link step.
Here are the errors along with the last gcc command that is run

> gcc -shared -Wl,--enable-auto-image-base build/temp.cygwin-3.1.4-x86_64-3.6/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/fs-poll.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/inet.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/threadpool.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/uv-common.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/version.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/uv-data-getter-setters.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/timer.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/idna.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/strscpy.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/async.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/core.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/dl.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/fs.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/getaddrinfo.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/getnameinfo.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/loop-watcher.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/loop.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/pipe.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/poll.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/process.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/signal.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/stream.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/tcp.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/thread.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/tty.o build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/udp.o -L/usr/lib/python3.6/config -L/usr/lib -lpython3.6m -o build/lib.cygwin-3.1.4-x86_64-3.6/gevent/libuv/_corecffi.abi3.dll
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.o: in function `_cffi_f_uv_fs_event_stop':
  /tmp/pip-install-2lkhphq6/gevent/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.c:2673: undefined reference to `uv_fs_event_stop'
  /tmp/pip-install-2lkhphq6/gevent/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.c:2673:(.text+0x5210): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `uv_fs_event_stop'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.o: in function `_cffi_f_uv_fs_event_start':
  /tmp/pip-install-2lkhphq6/gevent/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.c:2635: undefined reference to `uv_fs_event_start'
  /tmp/pip-install-2lkhphq6/gevent/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.c:2635:(.text+0x538f): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `uv_fs_event_start'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.o: in function `_cffi_f_uv_fs_event_init':
  /tmp/pip-install-2lkhphq6/gevent/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.c:2570: undefined reference to `uv_fs_event_init'
  /tmp/pip-install-2lkhphq6/gevent/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.c:2570:(.text+0x55af): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `uv_fs_event_init'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.o: in function `_cffi_d_uv_fs_event_stop':
  /tmp/pip-install-2lkhphq6/gevent/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.c:2650: undefined reference to `uv_fs_event_stop'
  /tmp/pip-install-2lkhphq6/gevent/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.c:2650:(.text+0xd61): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `uv_fs_event_stop'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.o: in function `_cffi_d_uv_fs_event_start':
  /tmp/pip-install-2lkhphq6/gevent/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.c:2585: undefined reference to `uv_fs_event_start'
  /tmp/pip-install-2lkhphq6/gevent/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.c:2585:(.text+0xd71): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `uv_fs_event_start'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.o: in function `_cffi_d_uv_fs_event_init':
  /tmp/pip-install-2lkhphq6/gevent/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.c:2532: undefined reference to `uv_fs_event_init'
  /tmp/pip-install-2lkhphq6/gevent/build/temp.cygwin-3.1.4-x86_64-3.6/gevent.libuv._corecffi.c:2532:(.text+0xd81): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `uv_fs_event_init'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/core.o: in function `uv_close':
  /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/core.c:167: undefined reference to `uv__fs_event_close'
  /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/core.c:167:(.text+0x91): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `uv__fs_event_close'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/core.o: in function `uv__update_time':
  /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/internal.h:307: undefined reference to `uv__hrtime'
  /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/internal.h:307:(.text+0x388): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `uv__hrtime'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/core.o: in function `uv_run':
  /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/core.c:375: undefined reference to `uv__io_poll'
  /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/core.c:375:(.text+0x434): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `uv__io_poll'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/core.o: in function `uv__update_time':
  /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/internal.h:307: undefined reference to `uv__hrtime'
  /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/internal.h:307:(.text+0x5b6): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `uv__hrtime'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/internal.h:307: undefined reference to `uv__hrtime'
  /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/internal.h:307:(.text+0x5ef): additional relocation overflows omitted from the output
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/internal.h:307: undefined reference to `uv__hrtime'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/core.o: in function `uv_hrtime':
  /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/core.c:115: undefined reference to `uv__hrtime'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/core.o: in function `uv__io_close':
  /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/core.c:950: undefined reference to `uv__platform_invalidate_fd'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/loop.o: in function `uv__update_time':
  /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/internal.h:307: undefined reference to `uv__hrtime'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/loop.o: in function `uv_loop_init':
  /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/loop.c:67: undefined reference to `uv__platform_loop_init'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/loop.c:107: undefined reference to `uv__platform_loop_delete'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/loop.o: in function `uv_loop_fork':
  /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/loop.c:118: undefined reference to `uv__io_fork'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/loop.o: in function `uv__loop_close':
  /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/loop.c:148: undefined reference to `uv__platform_loop_delete'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/poll.o: in function `uv_poll_init':
  /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/poll.c:74: undefined reference to `uv__io_check_fd'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/poll.o: in function `uv__poll_stop':
  /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/poll.c:107: undefined reference to `uv__platform_invalidate_fd'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/poll.c:107: undefined reference to `uv__platform_invalidate_fd'
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: build/temp.cygwin-3.1.4-x86_64-3.6/deps/libuv/src/unix/thread.o: in function `uv_cond_timedwait':
  /tmp/pip-install-2lkhphq6/gevent/deps/libuv/src/unix/thread.c:803: undefined reference to `uv__hrtime'
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1

The errors seems to be mentioning cffi, but i have that installed too

**Comment by dspringst** [comment]
Fixed it by adding cygwin bin to PATH environment variable and replacing cygwin's version of python 3 with the official python 3 windows release.

**Comment by berkakinci** [comment]
I had the same problem with different versions:
gevent 20.6.0
Python 3.6.9
pip 20.1.1
Windows 10 x64, Cygwin (CYGWIN_NT-10.0 3.1.5(0.340/5/3) 2020-06-01 08:59 x86_64 Cygwin)

I also reproduced with gevent 1.5.0 and 20.5.2

I thought abandoning Cygwin distribution's Python was too much so I kept digging.  This eventually worked for me:
`GEVENTSETUP_EMBED_LIBUV=0 pip3 --verbose install gevent`
(for version 20.6.0)
or:
`GEVENTSETUP_EMBED_LIBUV=0 pip3 --verbose install gevent==1.5.0`
This abandons the embedded libuv (compiled from source) and uses the distribution-supplied one.  This is not recommended, but if you're here, you don't care...

I still suspect something is amuck in the setup scripts that may need attention, but I don't have enough to point it out.

**Comment by jamadden** [comment]
Note that cygwin is [not supported](https://github.com/libuv/libuv/blob/master/SUPPORTED_PLATFORMS.md) by upstream [libuv](https://groups.google.com/forum/#!topic/libuv/KGDJt25FjSE), not even at tier 3. It may be possible to make it build, but it's very much unknown how much it will work. Building it that way seems to break fairly often, based on the libuv issue tracker.

gevent can't really offer more support to platforms than are offered by upstream. I'd be willing to review patches that make things easier for those platforms, but can't make any guarantees about things continuing to work in the future.

The relevant file in gevent is https://github.com/gevent/gevent/blob/master/src/gevent/libuv/_corecffi_build.py. Most likely there are one or more branches missing and one or more files being left out of the build + link process. (But the most recent [version of `pyuv`](https://github.com/saghul/pyuv/blob/v2/setup_libuv.py) also doesn't seem to have anything cygwin specific, so I don't know what it would be.)

**Comment by berkakinci** [comment]
Would it be acceptable to use system-provided libuv instead of trying to build it?  That seems like a relatively straightforward change.  (Famous last words...)

**Comment by jamadden** [comment]
That's possible if you set the appropriate environment variables at build time (`GEVENT_LIBUV_EMBED=0` or `GEVENT_EMBED_LIBUV=0`, I don't remember for sure); see the setup scripts for details.

**Comment by berkakinci** [comment]
That's how I worked around it in my case (see comment above)
I was thinking about baking that into _corecffi_build.py if platform is detected as 'cygwin.'  E.g.
```
if sys.platform.startswith('cygwin'):
  LIBUV_EMBED = False
```
It looks like your initial observation that files are left out in _corecffi_build.py is correct.  Platform 'cygwin' doesn't have an if-elif case in there.
I'm looking into the "proper" fix now... If I can get a dev build working.  I already have a dev dependency telling me "platform cygwin is not supported."

**Comment by berkakinci** [comment]
The following change allowed me to build and install gevent in a virtual environment:
```
diff --git a/src/gevent/libuv/_corecffi_build.py b/src/gevent/libuv/_corecffi_build.py
index ecc99013..60f9d611 100644
--- a/src/gevent/libuv/_corecffi_build.py
+++ b/src/gevent/libuv/_corecffi_build.py
@@ -209,6 +209,20 @@ elif sys.platform.startswith('haiku'): # untested
     LIBUV_SOURCES += [
         _libuv_source('unix/haiku.c')
     ]
+elif sys.platform.startswith('cygwin'):
+    # Based on Cygwin package sources /usr/src/libuv-1.32.0-1.src/libuv-1.32.0/Makefile.am
+    # Apparently the same upstream at https://github.com/libuv/libuv/blob/v1.x/Makefile.am
+    LIBUV_SOURCES += [
+        _libuv_source('unix/cygwin.c'),
+        _libuv_source('unix/bsd-ifaddrs.c'),
+        _libuv_source('unix/no-fsevents.c'),
+        _libuv_source('unix/no-proctitle.c'),
+        _libuv_source('unix/posix-hrtime.c'),
+        _libuv_source('unix/posix-poll.c'),
+        _libuv_source('unix/procfs-exepath.c'),
+        _libuv_source('unix/sysinfo-loadavg.c'),
+        _libuv_source('unix/sysinfo-memory.c'),
+    ]


 LIBUV_MACROS = [

```
I had to skip over some test dependencies (EXTRA_PSUTIL_DEPS in setup.py) to test this.
I was able to install the dependent package (gdbgui) and do a quick smoke-test successfully.

**Comment by berkakinci** [comment]
This change could benefit pyuv project as well, but I prefer not to get too carried away.  Are you familiar enough with pyuv developers to suggest?
