### ISSUE TITLE
sys.stdin blocked greenlets

### ISSUE THREAD

**Issue by beruhan** [gevent/gevent#1584]
### Env:
* gevent version: 20.4.0
* Python version: python3.6.8
* Operating System: ubuntu16.04 LTS

### Description:

I want non-blocking stdin,but It seems the sys.stdin in producer greenlet blocked the consumer greenlet,the code as follows:

```python
# -*- coding: utf-8 -*- 
# !/usr/bin/env python

import gevent.monkey
gevent.monkey.patch_all(sys=True)
from gevent.queue import Queue
import sys

q = Queue()

def producer():
    print("producer started")
    while True:
        for line in sys.stdin:
           if not line:
               break
           q.put(line)

def consumer():
    print("consumer started")
    while True:
        val = q.get(True)
        print("From consumer: %s" % val)

def main():
    tasks = [
        gevent.spawn(producer),
        gevent.spawn(consumer)
    ]
    gevent.joinall(tasks)

if __name__ == '__main__':
    main()

```

### Output:
It seems consumer not started,but when I press CTRL+C,the consumer started.what's the right way to use non-blocking stdin?
```text
producer started
```

**Comment by jamadden** [comment]
`patch_all(sys=True) or `patch_sys()` [does nothing on Python 3](http://www.gevent.org/api/gevent.monkey.html#gevent.monkey.patch_sys). It's generally dangerous and breaks the interpreter in some cases. If you want that, you need to patch it manually. Be sure to unpatch it before exiting!

```python
# example, not tested
old_in = sys.stdin
sys.stdin = gevent.fileobject.FileObjectThread(old_in)
try:
   # do non-blocking stuff here
finally:
  sys.stdin = old_in
```
