### ISSUE TITLE
Trigger loop watcher multiple times

### ISSUE THREAD

**Issue by woutdenolf** [gevent/gevent#1590]
* gevent version: 1.4.0
* Python version: Python 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0] :: Anaconda
* Operating System: Debian 10 (4.19.0-6-amd64)

### Description:

Is there a loop watcher that can be triggered more than once?

```python
import gevent

def test():
    print("test")

watcher = gevent.get_hub().loop.async_()

watcher.start(test)
watcher.send()
watcher.send()
gevent.wait()
```

This only prints once instead of twice (what I expected from looking at the docs).

What I ultimately want to do is start a watcher in one thread and then trigger it in other threads as a mechanism for wrapping gevent-powered code and make it thread safe.

**Comment by jamadden** [comment]
An async watcher is a very low-level primitive. All it does is wake up another event loop to ensure that a function is run in the next event loop iteration. If you need semantics at a higher level than that, you'll need to implement them yourself. For example, using a counter or a list of functions to invoke, etc.

[libev docs](http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#Watcher_Specific_Functions_and_Data_-12) and [libuv docs](http://docs.libuv.org/en/v1.x/async.html) are pretty clear, I think, that multiple sends (might!) get coalesced/compressed. If the gevent docs need improvement, PRs are welcome.

**Comment by woutdenolf** [comment]
Thanks for the swift reponse! Yes the libev docs are clear but I wasn't aware I had to look there. I'm a gevent beginner. Maybe this can be added [here](http://www.gevent.org/api/gevent.hub.html#gevent._interfaces.IWatcher) as well?

So the higher level alternative you mention could be something like a queue and the watcher's callback would dequeue until empty? There is no watcher (or something with pipes I could implement myself) which will result in 1 send -> 1 call?

**Comment by jamadden** [comment]
> So a watcher which will result in 1 send -> 1 call does not exist and cannot be created with the pipe mechanism?

You could try. It's not a primitive in the event libraries for a reason, though, and it shouldn't be necessary if you use higher-level structures which will both be easier and more reliable.
