### ISSUE TITLE
TypeError when FileObject is instantiated with an already open "binary" file object

### ISSUE THREAD

**Issue by koreno** [gevent/gevent#1595]
* gevent version: 1.5.0
* Python version: 3.7.7 (default, Mar 10 2020, 17:25:08) \n[GCC 5.4.0 20160609]
* Operating System: Ubuntu 16.04.6 LTS

### Description:

Apparently when passing an open file object to FileObjectThread, the `mode` argument keeps it's `r` default value, ignoring the actual mode the file object was opened with.

### What I've run:

```python
In [1]: from gevent.fileobject import FileObjectThread                                                                                                                                        
In [2]: f=FileObjectThread(open("test", "wb"))                                                                                                                                                
In [3]: f.write(b"asd")                                                                                                                                                                       
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gevent/threadpool.py", line 137, in __run_task
    thread_result.set(func(*args, **kwargs))
TypeError: write() argument must be str, not bytes
```

**Comment by jamadden** [comment]
You need to specify the correct mode to the FileObject, e.g., `f = FileObjectThread(binary_file, 'wb')`.

Note that you may also need a more recent gevent release; 1.5.0 and earlier had known problems handling different modes with the file object.

**Comment by koreno** [comment]
This is nowhere in the documentation/changelog, and it breaks compatibility with how things worked in 1.4.

Looking at the code (`class OpenDescriptor`) the bug is still there - an `fobj` is passed, but it is not checked with the `mode` that may-or-may-not have been passed.

Naive `FileObject(open("file", "wb")).write(b"data")` (that once worked) now fails.

I would expect one of:
- Remove the ability to pass an already opened `fobj`. That's probably undesirable for other reasons.
- Require user to pass `mode` explicitly if they pass a `fobj`.
- Auto-detect `mode` from the passed `fobj`

**Comment by jamadden** [comment]
> Naive FileObject(open("file", "wb")).write(b"data") (that once worked) now fails.

Are you sure? It works perfectly for me.
```pycon
>>> from gevent.fileobject import FileObject
>>> fo = FileObject(open('/dev/null', 'wb'), 'wb')
>>> fo.write(b'abc')
3
>>> fo.write('abc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: a bytes-like object is required, not 'str'
```

**Comment by jamadden** [comment]
> This is nowhere in the documentation/changelog, and it breaks compatibility with how things worked in 1.4.

It is well documented as such: http://www.gevent.org/changelog_1_5.html#file-object-changes

**Comment by koreno** [comment]
When someone looks up documentation about the FileObject classes, he goes
here: http://www.gevent.org/api/gevent.fileobject.html


- Ofer

**Comment by koreno** [comment]
> > Naive FileObject(open("file", "wb")).write(b"data") (that once worked) now fails.
> 
> Are you sure? It works perfectly for me.
> 
> ```
> >>> from gevent.fileobject import FileObject
> >>> fo = FileObject(open('/dev/null', 'wb'), 'wb')
> >>> fo.write(b'abc')
> 3
> >>> fo.write('abc')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> TypeError: a bytes-like object is required, not 'str'
> ```

That's not the same code. Obviously if you pass the `'wb'` a second time to `FileObject` it works, but to me that seems weird, unnecessary, intuitive. Is it not possible to inspect file object and figure whether it's binary or not?
This failed us awkwardly now when we've upgraded from 1.4 to 1.5 (for fixes regarding the 1024-fd limit), and the failure is not easy to track down...
