### ISSUE TITLE
Import from gevent.event import Event error on Raspi 4

### ISSUE THREAD

**Issue by Quenos** [gevent/gevent#1616]
* gevent version: 20.5.0
* Python version: Python 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0] on linux
* Operating System: Raspbian GNU/Linux 10 (buster) version 10 debian
### Description:

I'm trying to port a program that is running perfectly fine on my iMac to the raspi 4.
In order to access a data source over a websocket I use the following:

    from gevent.event import Event

And get the following error:

```
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/mnt/samsung-ssd/python-projects/dn/lib/python3.7/site-packages/gevent/__init__.py", line 86, in <module> 
from gevent._hub_local import get_hub
 File "/mnt/samsung-ssd/python-projects/dn/lib/python3.7/site-packages/gevent/_hub_local.py", line 101, in <module> 
import_c_accel(globals(), 'gevent.__hub_local') 
File "/mnt/samsung-ssd/python-projects/dn/lib/python3.7/site-packages/gevent/_util.py", line 105, in import_c_accel
mod = importlib.import_module(cname)
    File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
    ImportError: /mnt/samsung-ssd/python-projects/dn/lib/python3.7/site-packages/gevent/__hub_local.cpython-37m-arm-linux-gnueabihf.so: failed to map segment from shared object
```
**How can I solve this?**

**Comment by jamadden** [comment]
"failed to map segment from shared object" is a binary native code loader error. I don't know why you would get that error, but my guess would be that when gevent was compiled, it used incorrect compiler or linker flags (CFLAGS, LDFLAGS, etc). I would suggest compiling it again without any special compiler or linker flags.

You can also use the (barely documented) PURE_PYTHON environment variable to cause gevent not to load the native binary accelerator modules (e.g., `PURE_PYTHON=1 python /path/to/my/program.py`). That would totally sidestep this particular issue, at a performance cost, of course. And if it's a generic problem loading compiled modules, it's likely to strike again.

**Comment by Quenos** [comment]
Thanks for quick answer 
Two follow up questions I have:

1. Do you mean to recompile the .c files part of the package? Are there makefiles that do this, which I can tweak to remove flags?

2. PURE_PYTHON=1 -> is put on the cmd line before python <filename>?

**Comment by jamadden** [comment]
> Do you mean to recompile the .c files part of the package? 
Yes.

> Are there makefiles that do this, which I can tweak to remove flags?

No. The build is handled by setuptools/disttools, which uses the standard values from the environment (e.g., `LDFLAGS`) in addition to built-in defaults (typically based on what Python itself was compiled with; these are stored in some data file somewhere in the Python installation).

> PURE_PYTHON=1 -> is put on the cmd line before python ?

Sure, that's one way to do it. It's just an environment variable.

**Comment by jamadden** [comment]
I got my own RPi 4 up and running to test this.

Compiling gevent directly from a source checkout (`git clone gevent/gevent`; `pip install -e .`) did not demonstrate any issues. `gevent.event` imported the C accelerated modules without problem.

Then, I uninstalled and attempted to install gevent from PyPI. To my great surprise, apparently there's a default configuration for pip that points it to something called `piwheels.org`, which had a built binary:
```console
$ pip install gevent
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting gevent
  Downloading https://www.piwheels.org/simple/gevent/gevent-20.5.0-cp37-cp37m-linux_armv7l.whl (4.9 MB)
     |████████████████████████████████| 4.9 MB 15.7 MB/s
Requirement already satisfied: greenlet>=0.4.14; platform_python_implementation == "CPython" in /.../lib/python3.7/site-packages (from gevent) (0.4.15)
Installing collected packages: gevent
Successfully installed gevent-20.5.0
$ cat /etc/pip.conf
[global]
extra-index-url=https://www.piwheels.org/simple
```

It too successfully imported the native binary.
```console
 python -c 'from gevent import event; print(event)'
<module 'gevent._event' from '/.../lib/python3.7/site-packages/gevent/_event.cpython-37m-arm-linux-gnueabihf.so'>
```

Maybe you can try to use the binary wheel from piwheels.org. Other than that and what I offered before, I don't know how to be of any more help; this looks like a local compilation issue.

I'll close this, but feel free to re-open if you have new information.

**Comment by CreatingNull** [comment]
I know this is old, but just in-case it helps anyone:

I just encountered this issue on RPI3, it's due to the **custom mount** Quenos is using on `/mnt/samsung-ssd/`. I suspect his mount is probably running with `noexec` privileges, and without having `exec` enabled you'll fail with that trace when running an import from gevent.

If you are having this issue, you can test it gets resolved by remounting with that option enabled (obviously substituting your own mount point) `sudo mount /mnt/samsung-ssd/ -o remount,exec`. The problem gets instantly resolved without touching the existing gevent build. 

You can update your /etc/fstab to include this option when the drive is mounted on boot. 
I don't know your setup, but you may also want to move the mount off `/mnt`. I believe by convention that directory is supposed to be for temporary use only and probably shouldn't have exec privileges to begin with.
