### ISSUE TITLE
Misleading link in README

### ISSUE THREAD

**Issue by Rosuav** [gevent/gevent#1626]
* gevent version: master branch
* Python version: n/a
* Operating System: n/a

### Description:

The README links to "bug tracker" that isn't a bug tracker

### What I've run:

https://github.com/gevent/gevent

Notice link to "bug tracker" that takes you to https://github.com/gevent/gevent/wiki/Projects

Question: Is the GitHub issue tracker the only (or at least primary) place to look, or is there a separate tracker?

**Comment by jamadden** [comment]
Thanks for the report.

github issues are the only issue tracker I use.

**Comment by Rosuav** [comment]
Cool, thanks!
