### ISSUE TITLE
`create_connection` failed when connecting to a scoped ipv6 address

### ISSUE THREAD

**Issue by j178** [gevent/gevent#1634]
* gevent version: 20.04.0
* Python version: cPython 3.7.4 downloaded from python.org
* Operating System: Ubuntu 16.04.3 LTS

### Description:
I was trying to create an IPv6 connection to a scoped IPv6 address, but I got an `Invalid argument` error:
```
Traceback (most recent call last):
  File "/project/hotspot_scanner/tests/t.py", line 42, in <module>
    sock = gevent.socket.create_connection(('fe80::fcfc:feff:feb2:32bc%eth0', 7001))
  File "/usr/lib/python3.7/site-packages/gevent/socket.py", line 96, in create_connection
    sock.connect(sa)
  File "/usr/lib/python3.7/site-packages/gevent/_socket3.py", line 421, in connect
    raise error(result, strerror(result))
OSError: [Errno 22] Invalid argument
```

### What I've run:
```python
import gevent.socket

sock = gevent.socket.create_connection(('fe80::fcfc:feff:feb2:32bc%eth0', 7001))
print(sock)
```

The problem is that `create_connection` did a `getaddrinfo`, and then when `sock.connect()`, 
there is another `getaddrinfo` in `_socketcommon._resolve_addr(self._sock, address)`,
the second `getaddrinfo` lost the IPv6 scope id, then `Invalid argument`  error occurred.

**Comment by jamadden** [comment]
The scope identifier is dropped, that's true and I think has been for some time (though it's not documented IIRC). I can reproduce that on a multi-homed host on macOS with Python 3.x and 2.7.
```pycon
>>> import socket
>>> import gevent.socket as gsocket
# Try to connect to google.com
>>> s7  = socket.create_connection(('2607:f8b0:4000:80e::200e%en7', 80))
>>> s10 = socket.create_connection(('2607:f8b0:4000:80e::200e%en10', 80))
>>> s7.getsockname(), s10.getsockname()
(('...:7441', 61130, 0, 0),
 ('...:297c', 61131, 0, 0))
>>> gs7  = gsocket.create_connection(('2607:f8b0:4000:80e::200e%en7', 80))
>>> gs10 = gsocket.create_connection(('2607:f8b0:4000:80e::200e%en10', 80))
>>> gs7.getsockname(), gs10.getsockname()
(('...:297c', 61153, 0, 0),
 ('...:297c', 61154, 0, 0))
```

(Writing tests for it that run in all environments might be tricky without mocking some things…)

I couldn't figure out where an `Invalid argument` would come from, though…until I actually looked more closely at the IP address you're using. D'oh, it's link-local. On my system, that results in `Errno 65 No route to host`.

Note that some resolvers (c-ares for sure) don't support scope IDs at all.

**Comment by j178** [comment]
Thanks for you response!
yes, it's a link-local ipv6 address, that's why the scope identifier is required. You can connect to google.com through its global unicast address with or without a scope identifier, maybe you should try to connect to a local network sevice through its link-local address.

**Comment by j178** [comment]
oh, I saw the reference commit, that's pretty nice!
