### ISSUE TITLE
Gevent with SQL Alchemy and Pyodbc

### ISSUE THREAD

**Issue by jlongo-daitan** [gevent/gevent#1649]
### Description:

This is more a question. I've tried to search in Google, but I haven't had good results.

Is it possible to use gevent with SQL Alchemy and pyodbc?

I could make it work with my current Flask Restplus application, but when SQL Alchemy comes into play, the async behavior stop working.

**Comment by jamadden** [comment]
I have no idea. It depends on whether pyodbc can be successfully monkey-patched or not. If it uses native libraries to implement ODBC connections (and based on the wheel files on PyPI, it appears to do that), it probably can't. However, that may depend on your particular ODBC setup. 

I have successfully used SQLAlchemy in production with gevent and MySQL/PostgreSQL/sqlite (given the appropriate engines; it takes just a little bit of glue code to make that happen. RelStorage contains drivers that we use as engines for all those databases. But see https://github.com/zodb/relstorage/issues/394 for a caution.)

**Comment by jlongo-daitan** [comment]
@jamadden do you know if SQL Alchemy have any limitations with gevent or if it's related to the pyodbc lib?

**Comment by jamadden** [comment]
As far as I know, there's no issues with SQLAlchemy itself. Whether it cooperates or not entirely depends on the database connection, since that's what's doing blocking IO.

**Comment by jlongo-daitan** [comment]
@jamadden thx

**Comment by jlongo-daitan** [comment]
Yes, the issue is with pyodbc. I could make it work with pymssql. Thx
