### ISSUE TITLE
CLI to patch extra modules (psycogreen)

### ISSUE THREAD

**Issue by maingoh** [gevent/gevent#1653]
* gevent version: 20.6.2
* Python version: 3.6
* Operating System: Ubuntu 18.04

### Description:

I am trying to use pytest and django manage.py with gevent without changing much to the current code. I have seen that there is a very cool command line to do this. The thing is it doesn't patch psycopg2. It would be nice somehow to ask it in the command line.

### What I've run:

Works well but without psycogreen patch:
```
python3 -m gevent.monkey --verbose --module pytest -vvs
```

Also I have a trouble running django `manage.py runserver` using the command line:
```
python3 -m gevent.monkey --verbose --module manage runserver
```

I get the following error:
```
gevent.monkey.patch_all()
sys.version=3.6.9 (default, Apr 18 2020, 01:56:04)  [GCC 8.4.0]
sys.path=['',
 '/usr/lib/python36.zip',
 '/usr/lib/python3.6',
 '/usr/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/dist-packages',
 '/usr/lib/python3/dist-packages']
sys.modules=['__future__',
 '__main__',
 '_ast',
 '_bootlocale',
 '_codecs',
 '_collections',
 '_collections_abc',
 '_cython_3_0a5',
 '_frozen_importlib',
 '_frozen_importlib_external',
 '_functools',
 '_heapq',
 '_imp',
 '_io',
 '_locale',
 '_opcode',
 '_operator',
 '_signal',
 '_sitebuiltins',
 '_sre',
 '_stat',
 '_sysconfigdata_m_linux_x86_64-linux-gnu',
 '_thread',
 '_warnings',
 '_weakref',
 '_weakrefset',
 'abc',
 'ast',
 'builtins',
 'codecs',
 'collections',
 'collections.abc',
 'contextlib',
 'copyreg',
 'cython_runtime',
 'deepomatic',
 'dis',
 'encodings',
 'encodings.aliases',
 'encodings.latin_1',
 'encodings.utf_8',
 'enum',
 'errno',
 'fcntl',
 'functools',
 'gc',
 'genericpath',
 'gevent',
 'gevent._compat',
 'gevent._config',
 'gevent._gevent_c_greenlet_primitives',
 'gevent._gevent_c_hub_local',
 'gevent._gevent_c_hub_primitives',
 'gevent._gevent_c_ident',
 'gevent._gevent_c_waiter',
 'gevent._gevent_cgreenlet',
 'gevent._greenlet_primitives',
 'gevent._hub_local',
 'gevent._hub_primitives',
 'gevent._ident',
 'gevent._interfaces',
 'gevent._tblib',
 'gevent._util',
 'gevent._waiter',
 'gevent.exceptions',
 'gevent.greenlet',
 'gevent.hub',
 'gevent.libev',
 'gevent.libev.corecext',
 'gevent.os',
 'gevent.timeout',
 'google',
 'google.cloud',
 'google.logging',
 'greenlet',
 'heapq',
 'importlib',
 'importlib._bootstrap',
 'importlib._bootstrap_external',
 'importlib.abc',
 'importlib.machinery',
 'importlib.util',
 'inspect',
 'io',
 'itertools',
 'keyword',
 'linecache',
 'marshal',
 'opcode',
 'operator',
 'os',
 'os.path',
 'pkgutil',
 'posix',
 'posixpath',
 'pprint',
 're',
 'reprlib',
 'runpy',
 'signal',
 'site',
 'sitecustomize',
 'sre_compile',
 'sre_constants',
 'sre_parse',
 'stat',
 'sys',
 'sysconfig',
 'textwrap',
 'time',
 'token',
 'tokenize',
 'traceback',
 'types',
 'warnings',
 'weakref',
 'zipimport',
 'zope',
 'zope.interface',
 'zope.interface._compat',
 'zope.interface._zope_interface_coptimizations',
 'zope.interface.advice',
 'zope.interface.declarations',
 'zope.interface.exceptions',
 'zope.interface.interface',
 'zope.interface.interfaces',
 'zope.interface.ro']
cwd=/app/engine/api/api
/usr/bin/python3: can't open file 'manage': [Errno 2] No such file or directory
```

Note however that replacing `runserver` with `help` or `makemigrations` works. So it seems specific to `runserver`.

**Comment by jamadden** [comment]
The supported way for modules to react to gevent monkey-patching and add additional patches is through entry points (or zope.event). The gevent documentation has an example of doing exactly this for [psycogreen](http://www.gevent.org/api/gevent.monkey.html#plugins-and-events). This is deployed in the wild and known to work (e.g., [relstorage does this](https://github.com/zodb/relstorage/blob/bdacaed3fed04880d232ab9eee4f9a952d04c304/setup.py#L268).

**Comment by jamadden** [comment]
> Also I have a trouble running `django manage.py runserver` using the command line:

> python3 -m gevent.monkey --verbose --module manage runserver

In the future, please open separate issues for separate problems.

If you're trying to replicate exactly what `django manage.py <something>` does, then `django` is the command you should pass to gevent.monkey, e.g:

```console
$ python -m gevent.monkey `which django` manage.py runserver
```

**Comment by maingoh** [comment]
Thank you for the quick answers and sorry about the two questions, I thought it would be easier for you :smile:

For the psycogreen auto patch, I saw this documentation but didn't really understand how it works. My issue is that I don't have a package to install (so no setup.py) I just would like to auto patch when I execute pytest or manage.py.
Ideally something like this `python3 -m gevent.monkey --extra-patch "psycogreen.gevent.patch_psycopg" -m pytest`.
Or maybe I misunderstood something but i would like to avoid having to install something using pip or `python3 setup.py install`.

**Comment by jamadden** [comment]
If you have no code of your own, perhaps you can write a trivial wrapper script and use that instead of `python -m gevent.monkey`, e.g., `python my_script …`. Do your necessary patching in that script before importing and using whatever it is you need.

I don't expect to support arbitrary "run this code" arguments in `gevent.monkey` because  that's what the existing infrastructure is already there to do, and there are many advantages to having packages define their own patching requirements in well-defined ways instead of ad-hoc command-line arguments that are easy to get wrong or forget. (Indeed, you can commit your own script to version control to avoid some of those problems.)

**Comment by maingoh** [comment]
The small wrapper sounds like the best solution for my use case, I am trying to reuse the gevent arg parsing and runpy but can't manage to make it works, ideally I would like my wrapper to do something like this:
```python
from gevent import monkey
from psycogreen.gevent import patch_psycopg

if __name__ == '__main__':
    patch_psycopg()
    monkey.main()
```
But it doesn't work for some reasons (probably due to argv)

I think being able to reuse the gevent argparsing and run_path/module would be useful. That would mean splitting/making monkey.main a bit more generic so that we could do:

```python
monkey.parse_args(my_args)
patch_psycopg()
monkey.run(my_args)
```

This way I could patch psycopg after `patch_all` which is probably better ? What do you think ? I could make a PR.

> I don't expect to support arbitrary "run this code" arguments in gevent.monkey

I understand, it seems to me that there are not so many psycogreen like libraries as it is only required for C libraries. What about having a list of extra plugins (the most famous one) that we could potentially ask to patch like `python -m gevent.monkey --pg --mysql --module pytest` ?

**Comment by jamadden** [comment]
I think the supported way to do this is with either entry points or with zope.event events. Those are the structured extension mechanisms. Writing a wrapper script is a quick-n-dirty workaround, not a solution to encourage; it's possible but may not be "elegant." 

As for patching "famous" libraries, one can certainly write a package and put it on PyPI that does that, but I don't believe it belongs in gevent core.

Good luck.
