### ISSUE TITLE
EXclusive flock blocks other greenlets

### ISSUE THREAD

**Issue by vidstige** [gevent/gevent#1657]
* gevent version: reproduced on both 1.4.0 and 20.6.2
* Python version: Please be as specific as possible: "Python 3.6.9, default installation"
* Operating System: Please be as specific as possible: "Ubuntu 18.04.4 LTS"

### Description:
First off, thanks for a fantastic library. I seem to have run into some kind of problem with gevent.

When trying to obtain a `fcntl` exclusive lock (`LOCK_EX`), while gevent monkey patch active it will block out all other greenlets while waiting for lock. Unsurprisingly, it works with a shared lock `LOCK_SH`. See the following short reproducer.

This may show as many different symptoms, for me it was a "worker timeout" in the popular [gunicorn](https://gunicorn.org/) server.

### What I've run:

```python
import fcntl
import gevent
from gevent import monkey
monkey.patch_all()

def flock_poll(fd, operation):
    """workaround for gevent bug"""
    for _ in range(100):
        try:
            fcntl.flock(fd, operation | fcntl.LOCK_NB)
            return
        except OSError:
            time.sleep(0.1)  # or something

def locked_sleep():
    with open('file.lock', 'wb') as f:
        fcntl.flock(f, fcntl.LOCK_EX)  # <------------------------ this will block on second greenlet
        # fcntl.flock(f, fcntl.LOCK_SH)  # when replaced with this, it works
        # flock_poll(f, LOCK_EX)  # when replaced with this, it works aswell
        time.sleep(1)
        fcntl.flock(f, fcntl.LOCK_UN)

greenlets = [gevent.spawn(locked_sleep), gevent.spawn(locked_sleep)]
gevent.joinall(greenlets)
```

Moreover, there is a workaround, if I create a polling version like in the example above, things work smoothly.

Let me know if I can help out in fixing this somehow.

**Comment by jamadden** [comment]
My version of the man page for flock says "requesting a lock on an object that is already locked normally causes the caller to be blocked until the lock may be acquired." That's what you're seeing here. Your second greenlet blocks because the lock is already held by someone else. (The same thing would happen if the lock was held by another process.)

`flock` doesn't cooperate with gevent's event loop, so when that greenlet blocks, the whole process blocks. It's just like using any other non-cooperative call, or spinning in a CPU intensive loop. 

You could use `gevent.get_hub().threadpool.apply(flock.flock, f, fcntl.LOCK_EX)` to pass the blocking off to a separate thread, letting the main thread switch greenlets while you wait to obtain the lock. Looping with `LOCK_NB` may also work, as you observed, but it's not particularly efficient, and it may not be anywhere close to fair (it may not ever make progress if the lock is highly contested, whereas blocking in the kernel generally should be fair—I think).

**Comment by vidstige** [comment]
Yes, of course it's expected that the second to try to acquire the lock will block. That's the whole point here. However, when using threads and processes, the _first_ one to acquire the lock eventually releases the lock and the second one can take it. 

The issue here is, as you point out, that flock does not cooperate wit the gevent event loop. The same can be said for many functions, for example `open`, `write`, `read` and more. It would be best when monkey-patched the `flock` function would be cooperative. I was under the impression that the file descriptor passed to flock could also be used in `select` or `poll` or something like that that's used in the event loop (all assumptions here). If not, things are trickier, as the file lock is global and cannot be replaced by a greenlet lock or similar.

**Comment by jamadden** [comment]
> The issue here is, as you point out, that flock does not cooperate with the gevent event loop. The same can be said for many functions, for example `open`, `write`, `read` and more

None of which are monkey-patched either. There are functions like `gevent.os.nb_read`, but on regular files, monkey-patching those functions generally does nothing useful.

> It would be best if, when monkey-patched, the flock function would be cooperative.

PRs welcome. The only approach that's generally reasonable, I suspect, is one that directs through the threadpool.

> I was under the impression that the file descriptor passed to flock could also be used in `select` or `poll` or something like that that's used in the event loop (all assumptions here). 

Well probably, but for regular files, that will generally tell you nothing. Regular files are essentially always ready to read or write (which has nothing to do with locking) and those functions return immediately when given a file descriptor for a regular file. 

```pycon
Python 3.9.0b3 (default, Jun 13 2020, 08:23:25)
>>> import select
>>> import fcntl
>>> f = open('setup.py', 'rb')
>>> fcntl.flock(f.fileno(), fcntl.LOCK_EX)
None
>>> select.select([f.fileno()], [f.fileno()], [])
([3], [3], [])
```

As far as I know, there's no way to ask the kernel "can I lock this file?" other than trying it — which either returns immediately or is of unbounded duration. Hence the use of the threadpool. Which, come to think of it, is not really all that great either; a bunch of greenlets attempting the same thing could still deadlock the process.

>  If not, things are trickier, as the file lock is global and cannot be replaced by a greenlet lock or similar.

Indeed.

**Comment by s7v7nislands** [comment]
def flock_poll(fd, operation):
    """workaround for gevent bug"""
    for _ in range(100):
        try:
            fcntl.flock(fd, operation | fcntl.LOCK_NB)
            return
        except OSError:
            time.sleep(0)  # change to 0, let the greelet yield. this change may be improve the performance
