### ISSUE TITLE
Provide a way so that hub.destroy(destroy_loop=True) never blocks forever

### ISSUE THREAD

**Issue by jgehrcke** [gevent/gevent#1669]
Disclaimer: I only spent less than an hour on this problem so far and therefore didn't fully understand it yet. I would however already appreciate some early feedback!

https://github.com/gevent/gevent/issues/1601 led to https://github.com/gevent/gevent/pull/1604 and I appreciate the direction that this takes.

An intended side effect of this change seems to be that `hub.destroy(destroy_loop=True)` might now block forever.

As part of my very brief initial inspection (see https://github.com/jgehrcke/gipc/issues/103) the destroy() method would then hang in the `self.throw(GreenletExit)` [call](https://github.com/gevent/gevent/blob/ca216c777b522db58681274b990ed41cfca472a0/src/gevent/hub.py#L794). A `hub.join()` prior to trying to call `hub.destroy(destroy_loop=True)` would also block forever.

I understand that this seems to be the new intended behavior, in the sense that callers of `hub.destroy()` are supposed to responsibly clean up resources prior to calling that very hub (and loop) destruction entry point.

However, historically, within [gipc](https://github.com/jgehrcke/gipc) the dirty trade-off was to _not_ clean up, to put up with the fact that some orphaned resources might never get cleaned up after, but to nevertheless _reliably_ destroy the old event loop.

That code has been around for a while, it's sitting here: https://github.com/jgehrcke/gipc/blob/c8125872fa263f93e920f3041cac2d51063c614c/gipc/gipc.py#L344

Now I would love to find a way to make gipc compatible with newer gevent versions.

Given the premise of gipc as a library it itself will not quite be able to implement generic, reliable cleanup gevent resources and therefore still needs a "brutal way" to create a new event loop in the child process, after forking. What can we do in gipc (or gevent) so that `hub.destroy(destroy_loop=True)` (or a variant of it) is _guaranteed_ to not block forever? If this cannot quite be done within gipc (and I might have just not seen a way to achieve that) maybe we want to introduce another argument to `hub.destroy()` via which the caller can explicitly require the dirty/brutal legacy approach (I kind of hate that, too, but...).

**Comment by jgehrcke** [comment]
@jamadden I hate to "ping" you here (there probably is a reason for you haven't replied yet; and I truly appreciate all your maintenance/dev efforts on gevent!) -- but I would love to get a feeling for what your initial intuition about this topic is!

**Comment by jamadden** [comment]
I haven't had a chance to look at this. It will probably be awhile before I have any cycles to spare for this particular thing.

**Comment by jgehrcke** [comment]
> I haven't had a chance to look at this. It will probably be awhile before I have any cycles to spare for this particular thing.

Thank you @jamadden -- understood! As always: thanks for all your truly excellent efforts here.

**Comment by jgehrcke** [comment]
@jamadden I'll try that out soon. Thank you so much for getting back to this, and for connecting the dots. All my best wishes to you, and hope you have a good holiday time!
