### ISSUE TITLE
Attach profiler to native threadpool

### ISSUE THREAD

**Issue by Suhail-MOHD** [gevent/gevent#1670]
* gevent version: 20.6.2
* Python version: Python 2.7.10
* Operating System: Mac OS X 10.13.6

### Description:

I am working on adding gevent support to the yappi python profiler - https://github.com/sumerc/yappi

In my tests, I noticed that yappi is unable to attach to native threads spawned by the threadpool class provided by gevents. I have added a snippet demonstrating this in the next section.

Yappi uses [threading.setprofile](https://docs.python.org/2/library/sys.html#sys.setprofile) to attach a profiler function to threads. Any new threads spawned by the `threading` library will have the profiler attached.

The gevent threadpool class, however, calls directly into the `start_new_thread` of `thread` [here](https://github.com/gevent/gevent/blob/master/src/gevent/threadpool.py#L89). `thread` is a lower level library which does not have any context of the profiler function attached using the `threading` library and so any threads spawned by this will not respect the profiler.

This is not an issue with gevents because the expected behaviour of mixing `threading.setprofile` and gevent native threadpools has not been defined/documented anywhere.

So, this issue is a request for guidance. I see the following options and would like to know what the way forward is:
- add support in gevents to make the `ThreadPool` class respect `threading.setprofile`
- allow users to add hooks into the `ThreadPool` class so that a particular function can be invoked before a new native thread is started. Users would have control over attaching the profiler themselves then. I did explore subclassing ThreadPool but I could not find a good solution. Once we subclass `ThreadPool`, I assume we can configure the new class via [gevent.config](http://www.gevent.org/configuration.html#gevent._config.Config.threadpool)

If one of the above options is the way forward according to you folks, I'd be happy to raise a pull-request if help is required.

If both options are not possible, please let me know if there is an alternative.

### Sample code demonstrating the problem:

The below script runs two threads, one spawned by the gevent threadpool class and the other by the inbuilt threading library.

```python
import gevent
import threading

# Functions called on each thread
def thread_1():
  pass

def thread_2():
  pass

# Profiler callback. Invoked every time a function is entered/exited
profile_events = []

def profile_callback(frame, event, arg):
  profile_events.append((frame.f_code.co_name, event))

# Test gevent threadpool:
threading.setprofile(profile_callback)
g1 = gevent.get_hub().threadpool.apply_async(thread_1)
g1.get()
print "Profile events for native thread spawned by gevent: %s" % (profile_events)

# Test thread spawned by threading
profile_events = []
threading.setprofile(profile_callback)
t1 = threading.Thread(target=thread_2)
t1.start()
t1.join()
print "Profile events for native thread spawned by threading: %s" % (profile_events)
```

Output:
```
(27) suhail@C02WJ1J2HV2R ~/C/yappi (gevent-profiling)> python test.py
Profile events for native thread spawned by gevent: []
Profile events for native thread spawned by threading: [('run', 'call'), ('thread_2', 'call'), ('thread_2', 'return'), ('run', 'return'), ('_note', 'call'), ('_note', 'return'), ('__bootstrap_inner', 'c_call'), ('__bootstrap_inner', 'c_return'), ('__stop', 'call'), ('__stop', 'c_call'), ('__stop', 'c_return'), ('__stop', 'c_call'), ('__stop', 'c_return'), ('notifyAll', 'call'), ('notifyAll', 'c_call'), ('notifyAll', 'c_return'), ('notify', 'call'), ('_is_owned', 'call'), ('_is_owned', 'c_call'), ('_is_owned', 'c_return'), ('_is_owned', 'return'), ('_note', 'call'), ('_note', 'return'), ('notify', 'return'), ('notifyAll', 'return'), ('__stop', 'c_call'), ('__stop', 'c_return'), ('__stop', 'return'), ('__bootstrap_inner', 'c_call'), ('__bootstrap_inner', 'c_return'), ('__bootstrap_inner', 'return'), ('__bootstrap', 'return')]
```

As shown above, there are no events for the thread spawned by gevents.

Please let me know how to proceed! Thanks for your time and all the great work in maintaining gevent!

**Comment by jamadden** [comment]
Thanks for bringing this up, and sorry for the slow response. Setting the profiler and tracer in threadpool threads seems like something gevent should do; I'll add that.

**Comment by Suhail-MOHD** [comment]
Thank you @jamadden !
