### ISSUE TITLE
do_handshake raises OSError

### ISSUE THREAD

**Issue by bsolomon1124** [gevent/gevent#1671]
* gevent version: `gevent-20.6.2-cp37-cp37m-manylinux2010_x86_64.whl`
* Python version: CPython 3.7 from Anaconda distro
* Operating System: RHEL 7 and 8
* Possibly related/additional examples:
  * https://github.com/gevent/gevent/issues/1170
  * https://bugs.python.org/issue31122
  * https://github.com/gevent/gevent/issues/1247
  * https://stackoverflow.com/questions/49042162/ssleoferror-using-gevent

We see this exception on almost every request using Nginx + gevent + Flask. (Though the request goes through; the exception is just logged and logs fill up to the gb size without a rotating file handler.) From the above, looks to be a CPython ssl bug that is patched for CPython 3.8 and 3.9. (Not backported to 3.7 at this time.)

Traceback (paths abridged):

```python
Traceback (most recent call last):

  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run

  File ".../gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)

  File ".../gevent/server.py", line 233, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:

  File ".../gevent/_ssl3.py", line 119, in wrap_socket
    _session=session)

  File ".../gevent/_ssl3.py", line 311, in __init__
    raise x

  File ".../gevent/_ssl3.py", line 307, in __init__
    self.do_handshake()

  File ".../gevent/_ssl3.py", line 663, in do_handshake
    self._sslobj.do_handshake()

OSError: [Errno 0] Error
2020-09-16T19:17:29Z <Greenlet at xxxxx: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at xxxxx)> failed with OSError
```

**Comment by bsolomon1124** [comment]
To reproduce:

```python
import ssl

import gevent.pywsgi

def app(environ, start_response):
    start_response("200 OK", [])
    return ""

context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
context.load_cert_chain('server.crt', 'server.key')
server = gevent.pywsgi.WSGIServer(("localhost", 4330), application=app, ssl_context=context)
server.serve_forever()
```

```bash
$ nc -vz localhost 4330
```

**Comment by jamadden** [comment]
I don't know what happened to my closing comment. Sorry about that. 

I wrote something along the lines of: This is still an exception, an error in the network connection. Even the underlying CPython bugfix for this just changes `OSError` to `SSLEOFError`. In general, I can't see that it's right to just silently ignore failed connections. If that's what's best for your application, it's possible to overrid/replace `wrap_socket`or `wrap_socket_and_hadle` to ignore that case.

**Comment by bsolomon1124** [comment]
> This is still an exception, an error in the network connection. Even the underlying CPython bugfix for this just changes OSError to SSLEOFError. 

Totally understandable. Probably not gevent's place to suppress that specific traceback regardless of whether it is OSError or SSLEOFError. I suspect this comes from a "health check" with something like `nc` periodically pinging the bind address as shown above, but again, I agree it's not really gevent's problem.

But I'm struggling to find where that actually emanates from to suppress it. I've built gevent from github source and tried to step in with `pdb` but am failing to find where that traceback is actually printed from. A logging call, print, or sys.stderr.write? `_handle_client_error`/`handle_error`?

**Comment by jamadden** [comment]
Uncaught exceptions in greenlets get passed through to the hub's [handle_error method](http://www.gevent.org/api/gevent.hub.html#gevent.hub.Hub.handle_error). But I don't recommend making changes there — that would be a global solution to a local problem. Instead, I'd suggest changing one of the two methods I mentioned on the server object. To extend your example, something like (untested):

```python
server = gevent.pywsgi.WSGIServer(…)
wrap_socket = server.wrap_socket
def my_wrap_socket(*args):
    try:
        return wrap_socket(*args)
    except OSError as ex:
        if ex.errno == 0:
            # Silently kill this greenlet.
            raise GreenletExit
server.wrap_socket = my_wrap_socket
server.serve_forever()
```

**Comment by bsolomon1124** [comment]
Yep, that does the trick. As you were typing that I was subclassing `SSLContext`, but accomplishes the same thing 😉 . Thanks for lending your time @jamadden .
