### ISSUE TITLE
Event loop destruction performs file read/write operations in gevent>=20.5.1

### ISSUE THREAD

**Issue by hashbrowncipher** [gevent/gevent#1686]
* gevent version: 20.5.1 and later
* Python version: Python 3.7.7 downloaded using pyenv
* Operating System: Linux 5.4.0-47-generic, Ubuntu Focal userspace

### Description:

The following program reliably hangs on gevent>=20.5.1. It works as expected on gevent 20.5.0.

```python
from gevent.monkey import patch_all
patch_all()  # noqa: E402

import gevent
from gevent.hub import get_hub
from gevent import os
from gevent.monkey import get_original
from gevent.socket import wait_read

hang = get_original("time", "sleep")

r, w = os.pipe()


def pipe_reader():
    os.read(r, 4096)
    print(f"Read from pipe in PID: {os.getpid()}")


print(f"Parent PID: {os.getpid()}")
hub = get_hub()
os.write(w, b"test")
wait_read(r)
gevent.spawn(pipe_reader)
pid = os.fork()
if pid == 0:
    hub.destroy(destroy_loop=True)
else:
    print(f"Child PID: {pid}")
    # Briefly prevent the parent process from executing its event loop
    hang(1)
    os.waitpid(pid, 0)
```

The expected output looks like this, with a 1 second interval between "Child PID" and "Read from pipe in PID". "Read from pipe in PID" should match "Parent PID":

```
Parent PID: 2332303
Child PID: 2332306
Read from pipe in PID: 2332303
```

Unexpected output looks like this, and hangs indefinitely:

```
Parent PID: 2333255
Child PID: 2333258
Read from pipe in PID: 2333258
```

**Comment by jgehrcke** [comment]
This might relate to https://github.com/gevent/gevent/issues/1669

**Comment by JabbaDesilijicTiure** [comment]
Create a virtual environment using `python3 -m venv your/path` , and install gevent using `pip3 install gevent` and see there if you have some problems. I doubt you would have this problem then. I'm not a fan of pyenv. 

If you work on ios or windows you should open the window where are you and throw out your devices.

**Comment by jamadden** [comment]
Thanks for the reports! 

I don't have the prerequisites to reproduce #1669, but I do suspect that they are both the same basic issue.

I expect to have this fixed in the next gevent release.

In the meantime and for older versions, if you add `hub.loop.break_()` just before `hub.destroy(destroy_loop=True)` I expect it will fix the issue (at least it does this one).
