### ISSUE TITLE
Errors in ssl

### ISSUE THREAD

**Issue by yeraycito** [gevent/gevent#1688]
.* gevent version: 20.9.0
* Python version: 3.8.5
* Operating System: 

 - Linux Mint 20: Software Calibre-web ( https://github.com/janeczku/calibre-web )

 - Nas QNAP: Calibre-web in docker: https://github.com/linuxserver/docker-calibre-web#linuxservercalibre-web

### Description:

Condition 1: SSL not active - External http access without problems

![sslno](https://user-images.githubusercontent.com/65027248/96499135-4f785500-124d-11eb-8963-7c54803f988e.png)

Condition 2: SSL active  ( certificates letsencrypt ) - External https access without problems

![ssl](https://user-images.githubusercontent.com/65027248/96499453-b7c73680-124d-11eb-94a3-96156da5cd87.png)

![ssl2](https://user-images.githubusercontent.com/65027248/96499576-e34a2100-124d-11eb-8164-393453227df2.png)

Conditions:

![conditions](https://user-images.githubusercontent.com/65027248/96499746-1db3be00-124e-11eb-855e-da1078d50676.png)

More information: https://github.com/janeczku/calibre-web/issues/1671

```

**Comment by jamadden** [comment]
This is CPython bug https://bugs.python.org/issue31122. The real fix is to upgrade to a fixed CPython (3.8.6). 

It would be possible to add a workaround for this in gevent, but it would need a test case. It may just be easier to upgrade Python.

**Comment by jamadden** [comment]
Same as #1671, and upstream has made changes.
