### ISSUE TITLE
Version for iOS and tvOS

### ISSUE THREAD

**Issue by snuntz** [gevent/gevent#1691]
* gevent version:20.9.0
* Python version: Python3.7
* Operating System: iOS tvOS

### Description:

is possible to compile source for iOS and tvOS?
I installed Python3.7 setuptools and libdev on a jailbroken device but a package i tried installing depend on gevent

**Comment by jamadden** [comment]
Those aren't supported platforms, meaning we don't test on them or distribute pre-compiled binary wheels.

But…the low-levels are (mostly) Darwin, like macOS, and we do test on macOS. So chances are fair that if you try to install from source things will at least compile (that's what happens by default when binary wheels aren't available, so just installing gevent will attempt that). Good luck! And make sure and see the documentation about installing from source: https://www.gevent.org/development/installing_from_source.html
