### ISSUE TITLE
Flask Autoreloader

### ISSUE THREAD

**Issue by abitrolly** [gevent/gevent#1696]
* gevent version: https://pkgs.alpinelinux.org/package/v3.12/community/x86_64/py3-gevent
* Python version: https://pkgs.alpinelinux.org/package/v3.12/main/x86_64/python3-dev
* Operating System: Alpine 3.12

### Description:

I am trying to debug Flask app running with `gevent` in a container. For that I need to live modify the code without restarting app or rebuilding the container.

`flask` standalone server executable supports reloading mechanism https://flask.palletsprojects.com/en/1.1.x/server/ by setting `FLASK_ENV=development`. However, the mechanism doesn't seem to work when Flask app is run by `gevent`.

### What I've run:

**REPLACE ME**: Paste short, self contained, correct example code (sscce.org), tracebacks, etc, here

I still work on self-contained example. For now this is the code is server running from https://cheat.sh
```python
...
if '--debug' in sys.argv:
    app.debug = True
if 'CHEATSH_PORT' in os.environ:
    PORT = int(os.environ.get('CHEATSH_PORT'))
else:
    PORT = CONFIG['server.port']
SRV = WSGIServer((CONFIG['server.bind'], PORT), app)
print("Starting server on {}:{}".format(SRV.address[0], SRV.address[1]))
SRV.serve_forever()
```
https://github.com/chubin/cheat.sh/blob/2820fff4cbf2caf8c1070075a5af6213ca1a6fed/bin/srv.py#L278-L286

How to make autoreloading work?

**Comment by jamadden** [comment]
gevent itself has no mechanism for reloading code, you'd just need to restart the server. (Restarting the process is the most reliable way to pick up code changes.)

You could try using gunicorn with the gevent worker (`gunicorn -k gevent …`) and the appropriate [reload configuration](https://docs.gunicorn.org/en/stable/settings.html#debugging) set to automate the process.

**Comment by abitrolly** [comment]
The core of the problem is that `gevent` works inside of Python code that invoked it, and it doesn't know about all files that application is composed of, start parameters, environment, parent process that is used to monitor the execution.

Correct me if I wrong, but `gevent` won't be able to restart its invoking Python process without changing PID and losing link with the parent. With lost PID it will also lost stdin and stdout handlers, and that means missing data in logs, if those were connected. Is that right?
