### ISSUE TITLE
Changelogs in the documentation are fragmented, hard to find

### ISSUE THREAD

**Issue by sruggier** [gevent/gevent#1700]
Looking at the [Table of Contents](http://www.gevent.org/contents.html), there's a link to the What's New in 1.5 page near the top, a link to the 20.x changelog in the middle, and a link to the release notes and changelogs of older releases near the bottom. The latest what's new page probably should be near the top, and ideally, all of those links should be next to each other in the TOC, to help make them easier to find.

Meanwhile, someone looking at the [latest changelog page](http://www.gevent.org/changelog.html) could reasonably conclude that the older change entries are missing, which is confusing, and potentially a bit of a time sink. It would be helpful to include a link within that page that points at the corresponding information for older releases, in case that's what the reader was looking for when they opened the page.

**Comment by jamadden** [comment]
Heh. Indeed, I was just noticing that yesterday. I think some of the links got lost with the move to towncrier. Also, with the move to calendar versioning the days of gigantic releases meriting a whole "what's new in X.Y" should be over; 1.5 should be the last of those.

**Comment by sruggier** [comment]
Thanks!
