### ISSUE TITLE
Do gevent have any API compatible promise between versions?

### ISSUE THREAD

**Issue by aisk** [gevent/gevent#1703]
I found the gevent's version is bumpped from `1.5.x` to `20.x.x` directly, and the major version seems to be the year number, the minor version seems to be the month version, the patch version seems to be the released count in this month. (Looks like this is the [calver](https://calver.org)?)

In this release version strategy, I think no one can found is the new version will breaking old APIs, so people must pin the gevent version to a exact version, I think this is not a friendly solution for a univeral used library like gevent.

**Comment by jamadden** [comment]
gevent has [a well-defined deprecation and removal strategy](https://www.gevent.org/development/release_process.html#deprecation-policy). It's actually much better defined [with CalVer](https://github.com/gevent/gevent/issues/1555) than it was with pseudo-SemVer.
