### ISSUE TITLE
Windows wheels missing for gevent 20.12.0

### ISSUE THREAD

**Issue by vphilippon** [gevent/gevent#1730]
* gevent version: `20.12.0`, pypi.org
* Python version: *
* Operating System: Windows

### Description:

Hello!

Just a heads-up to mention the Windows wheels for `gevent 20.12.0` are missing on pypi.org.

Maybe due to the [skip ci] on the commit used for the release? I don't see any appveyor job for the release. I don't know much of the details of how appveyor handles that though.

Cheers!

**Comment by jamadden** [comment]
Thanks. They just finished uploading.
