### ISSUE TITLE
Question about greenlets scheduling and intensive reading loop

### ISSUE THREAD

**Issue by mguijarr** [gevent/gevent#1741]
* gevent version: 20.12 from Anaconda

* Python version: cPython 3.7 from Anaconda

* Operating System: Manjaro 5.8.16-2-MANJARO #1 SMP PREEMPT Mon Oct 19 11:33:03 UTC 2020 x86_64 GNU/Linux

### Description:

I thought switching between greenlets always occurs on I/O operations, even if one greenlet is receiving lots of data from a server. What I observe, though, is that one busy greenlet receiving data from a chatty server can prevent all others from executing.

I thought there were some scheduling, that would switch control to others in this situation, at some point.

My question is : is it normal behaviour ?

Adding a `sleep(0)` in the reading loop seems to fix the problem. Is there a way to have the same thing done automatically,
by what acts as the gevent scheduler ?

Is there a way to implement more fair scheduling ?

#### server

```python
import socket

s = socket.socket()
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
s.bind(("", 9998))

while True:
    s.listen()
    client,_ = s.accept()
    while True:
        client.send(2048*b"!")
```

#### client

Here is the client test program (with gevent):

```python
import gevent
from gevent import monkey ; monkey.patch_all()
import socket

def reading():
    s = socket.socket()
    s.connect(("localhost", 9998))
    print("entering reading loop")
    while True:
        data = s.recv(1024)
        if not data:
            break
        # gevent.sleep(0) - putting sleep here 'solves' the issue

def something_else():
    while True:
        print("before sleep")
        gevent.sleep(0.5)
        print("after sleep")

gevent.spawn(something_else)
gevent.sleep(1) # ensure greenlet is started
gevent.spawn(reading)
gevent.wait()
```

The reading function consumes data from the server. When running this test, there is no output after "entering reading loop"; both greenlets are running, but the greenlet executing `something_else` is never scheduled again as the reading one takes it all.

Adding `gevent.sleep(0)` in the reading loop solves the issue, since it "forces" cooperation.
It can also be solved by increasing the `recv` call size, i.e. reading more data in one go. Is it a rule of thumb to put the maximum size, for example ? In any case, depending on what the server send, I imagine `sleep(0)` is a better bet (?)

**Comment by jamadden** [comment]
This is normal and expected.

gevent has no scheduler, and generally makes no guarantee of fairness (some recent changes aside). Greenlets are allowed to switch when operations would *block* , but as you noticed, on a localhost server constantly sending data to a localhost client making small reads, blocking is unlikely (the buffers are always full).

We're only operating in one thread here, so resources are limited, and gevent (roughly) goes for optimizing (maximizing) the throughput of operations, as compared to latency. That means that it won't arbitrarily introduce delays in one network stream just to give a chance to other network streams. If IO is ready (won't block) gevent won't make it block. 

If you expect a long-running operation — whether IO bound but never blocking or CPU bound — to dominate, then its up to you to grant time to other greenlets with `sleep()`.

In practice, for many applications with sockets *not* on localhost, network reads and writes *will* block often enough that switching happens regularly.

**Comment by mguijarr** [comment]
Thanks @jamadden - makes sense. It is clear for me now, but always better to read your explanations.

I have to deal with servers playing with TCP_NODELAY and other stuff, and the network is quite fast so I also experience problems like the one described above even not on localhost. But this is a different story :wink: 

I got confused about scheduling, due to discussions in #1072, #1068. Now it is clear.

Thanks again
