### ISSUE TITLE
FileObjectBase raises when accessing the name property on a closed file

### ISSUE THREAD

**Issue by danmilon** [gevent/gevent#1745]
* gevent version: 20.12.1 from pypi
* Python version: 2.7.18 from the official Fedora repos.
* Operating System: Fedora 5.8.10-200.fc32.x86_64

### Description:

`FileObject` variants that inherit from `FileObjectBase` raise when accessing the `name` property after the file has been closed. The file object returned by `io.open()` doesn't have the same behavior, it returns the file path fine. This breaks some libraries (e.g. [atomicwrites](https://github.com/untitaker/python-atomicwrites) which rely on this behaviour.

It happens because in `FileObjectCommon.close()` we drop the reference to the wrapped object.

I can think of two possible fixes.

1. Don't drop the `self._io` reference in `close()`, instead set a `self._closed = True` flag to be used in `__getattr__()`, and add `name` in `_delegate_methods()`.
2. In `FileObjectCommon.__init__()` do `self.name = self._io.name`.

Thoughts?

### What I've run:

```python
import gevent.monkey; gevent.monkey.patch_all()
import gevent.fileobject
import io

f = io.open("/tmp/foo", mode="w")
print("f.name by io.open before close: {}".format(f.name))
f.close()
print("f.name by io.open after close: {}".format(f.name))

f = gevent.fileobject.FileObjectThread(
    "/tmp/foo",
    mode="w",
)

print("f.name by gevent.fileobject before close: {}".format(f.name))
f.close()
print("f.name by gevent.fileobject after close: {}".format(f.name))
```

**Comment by jamadden** [comment]
Thanks for the report!
