### ISSUE TITLE
log "real" source IP (from X-Fowarded-For HTTP header)

### ISSUE THREAD

**Issue by AndreLouisCaron** [gevent/gevent#1763]
* gevent version: 21.1.0
* Python version: 3.8.7 from official `python:3.8-alpine` Docker image
* Operating System: Linux a9e044c2ebb2 4.19.76-linuxkit (from official `python:3.8-alpine` Docker image)

### Description:

I'm trying to correlate the HTTP server access log with logs from the client application (thousands of instances with unique IPs).  I was hoping to use the built-in access log emitted by `gevent.pywsgi`.  Unfortunately, the source IP seems to be that of my reverse proxy.

Here is an example entry:

```
10.40.12.6 - - [2021-01-21 15:10:58] "PUT /api/v1/some-resource HTTP/1.1" 200 108 0.004440
```

My reverse proxy fills in the `X-Forwarded-For` HTTP header and I would like to log the IP it contains (when it is present).

I've taken a quick look at the documentation and source code and I cannot figure out how to do this.  Can you recommend a solution?

Thanks!

**Comment by jamadden** [comment]
That’s not a feature of WSGI or gevent, so you’ll need to use some extension that supports it, such as Gunicorn.

**Comment by AndreLouisCaron** [comment]
Thanks for the quick reply!  Are you referring to this?  https://docs.gunicorn.org/en/stable/settings.html#access-log-format

**Comment by jamadden** [comment]
I will not be sure
