### ISSUE TITLE
ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'

### ISSUE THREAD

**Issue by dsuch** [gevent/gevent#1767]
Hello,

I am investigating a situation to do with [a third-party C-based extension](https://pypi.org/project/greenify/) called greenify, running under gevent, which apparently stumbles upon some low-level condition (such as SIGSEGV) that causes the whole process to immediately shut down.

I am not really sure yet because I have just started to work on it and the first thing I wanted to try out was to compile Python 3.8 and 3.9 from source with additional assertions and debugging flags enabled.

In particular, the below happens with Python 3.8.7, compiled with these flags ``--with-pydebug --with-trace-refs --with-assertions``.

* GCC: 7.5.0-3ubuntu1~18.04
* Ubuntu 18.04 64-bit
* gevent version 21.1.2, installed from PyPI

Here is what happens:

```
Python 3.8.7 (default, Jan 28 2021, 21:02:59) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dsuch/projects/dsuch-greenify/env/lib/python3.8/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/home/dsuch/projects/dsuch-greenify/env/lib/python3.8/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/home/dsuch/projects/dsuch-greenify/env/lib/python3.8/site-packages/gevent/_util.py", line 148, in import_c_accel
    mod = importlib.import_module(cname)
  File "/home/dsuch/install/python/3.8/Python-3.8.7/install-target/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'
>>> 
```

There is no such exception when using a non-dev Python build. Can you please assist me in understanding what the root cause of it may be? Thanks.

**Comment by jamadden** [comment]
I *think* that if you're going to use a CPython interpreter compiled with those options you also need to compile gevent (and greenlet) with that interpreter. The binary wheels distributed on PyPI are built for a standard interpreter, but the debug interpreter has a different ABI, meaning that standard extension modules can't be used under it. The tag in the extension filename is different to reflect that fact. pip's `--no-binary :all:` option can be used to compile from source.

(You could ask gevent to disable some of its optional C extensions with the `PURE_PYTHON=1` environment variable to get around the issue, but there are extensions that are required so that probably won't get you much farther.)

**Comment by dsuch** [comment]
Ah, a different ABI, that makes sense now. Here is what I did. 

First, I tried to install gevent from a git clone, the latest version from main and then from 21.1.2 branches/tags.

This resulted in an exception as here:

```
running build_ext
Not configuring libev, 'config.h' already exists
Embedding c-ares <_setuputils.ConfiguringBuildExt object at 0x7fd335d8ca60> <_setuputils.Extension('gevent.resolver.cares') at 0x7fd3360d2dc0>
Inserted  build/temp.linux-x86_64-3.8/c-ares in include dirs ['build/temp.linux-x86_64-3.8/c-ares', '/usr/include/python3.8', '/usr/include/python3.8', '/home/dsuch/install/gevent/deps', '/home/dsuch/install/gevent/deps/c-ares', 'src/gevent', 'src/gevent/libev', 'src/gevent/resolver', '.']
Running '(cd  "/home/dsuch/install/gevent/deps/c-ares"  && if [ -r ares_build.h ]; then cp ares_build.h ares_build.h.orig; fi   && sh ./configure --disable-dependency-tracking -C CFLAGS="-Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g   -fstack-protector-strong -Wformat -Werror=format-security"  && cp ares_config.h ares_build.h "$OLDPWD"   && cat ares_build.h   && if [ -r ares_build.h.orig ]; then mv ares_build.h.orig ares_build.h; fi) > configure-output.txt' in /home/dsuch/install/gevent/build/temp.linux-x86_64-3.8/c-ares
configure: error: `CFLAGS' has changed since the previous run:
configure:   former value:  `-Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g   -fstack-protector-strong -Wformat -Werror=format-security  -g -flto -fuse-linker-plugin -ffat-lto-objects'
configure:   current value: `-Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g   -fstack-protector-strong -Wformat -Werror=format-security'
configure: error: in `/home/dsuch/install/gevent/deps/c-ares':
configure: error: changes in the environment can compromise the build
configure: error: run `make distclean' and/or `rm config.cache' and start over
configure: loading cache config.cache
```

Then, I install gevent per the instructions here https://www.gevent.org/development/installing_from_source.html - which is ``/path/to/my/pip install --no-binary gevent gevent``.

This, I think, worked correctly because I saw this:

```
Building wheels for collected packages: gevent
  Building wheel for gevent (PEP 517) ... done
  Created wheel for gevent: filename=gevent-21.1.2-cp38-cp38-linux_x86_64.whl size=5180269 sha256=9a61fd2aa6f994d71891d9047d02bee37c9518010de5b8f156d15d7c27303444
```

Just to double-check it - since the wheel was created on demand, it means that the source code was first downloaded from PyPI and compiled locally, is that correct? (Importing gevent works fine).

As to the exception while building from a git clone - please let me know if you would like me to open a separate ticket. Thanks.

**Comment by jamadden** [comment]
> since the wheel was created on demand, it means that the source code was first downloaded from PyPI and compiled locally, is that correct

Yes. You can see from the filename that this is specific to your machine. 'linux_x86_64' wheels aren't portable and can't be uploaded to PyPI.

> As to the exception while building from a git clone - please let me know if you would like me to open a separate ticket. 

No, thank you. That looks like a local problem. If you tried to build multiple times while switching branches, you'd need to run `setup.py clean` to reset cached values (or follow the instructions in the error message). Same thing goes for if you change any of a number of environment variables; that's just how autotools works.

**Comment by dsuch** [comment]
Great, thanks again.
