### ISSUE TITLE
Can I safely migrate an existing synchronous project to asynchronous with gevent?

### ISSUE THREAD

**Issue by EricLin89** [gevent/gevent#1768]
Hi, here is my situation:
I have an existing project previously written in a synchronous manner. Part of its function sends requests to multiple of hosts conconcurrently, which was currently implemented using python threading. I would like to optimize the performance under large scale deployment by replacing threads with gevent.
What I'm concerning is, since gevent replaces some of python's native modules with async ones, and other parts of the project's code may still using them in a synchronous manner. I have no intention to refactor the whole project to an asynchronous manner, is it safe that I just modify the **concurrent request** part while keep the other code unchanged.
For now I've tested only monkey patch socket and ssl, and run requests with gevent instead of threads, all seems work fine. But I would still like to hear from professionals to be sure.
Thank you.

**Comment by jamadden** [comment]
The monkey-patching that gevent does is specifically intended to allow applications written in a standard Python synchronous style, possibly including concurrency using `threading`, to run using greenlets and gevent with no other changes. So yes, that should work fine—that's what it's for.

I generally recommend starting with `monkey.patch_all()`. That's the most tested configuration, and it eliminates some possible problems:
- Many things in the standard library (e.g., logging) use `threading.Lock`, or `queue` or `Event`, etc, and if those are not monkey-patched then you can find your supposed concurrency not as high as it should be.
- gevent objects are generally *not* thread safe; they can only be used in the thread that created them. If parts of the program are still creating native threads, then it can be easy to get into failure situations (e.g., passing the result of `socket.makefile()` off to another thread to handle will blow up).

OTOH, if you have a configuration you're happy with, feel free to keep using it.

**Comment by EricLin89** [comment]
Thank you for the thorough explaination and suggestion, Jason. I have more confidence in my code now. :D
Close this issue as solved.
