### ISSUE TITLE
OSError: [Errno 22] Invalid argument in threadpool.py while running celery tasks using gevent as execution pool.

### ISSUE THREAD

**Issue by Arun-N** [gevent/gevent#1776]
* gevent version: 20.12.1 (PyPi)
* Python version: 3.8.3
* Operating System: Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-26-generic x86_64)

### Description:

I'm trying to run a celery chord task using gevent as the execution pool. A while after starting the tasks, it starts throwing OSError. Below is the traceback of that error:

```python-traceback
[2021-02-26 11:46:15,669: WARNING/MainProcess] Traceback (most recent call last):
[2021-02-26 11:46:15,669: WARNING/MainProcess] File "/home/******************/venv/lib/python3.8/site-packages/gevent/threadpool.py", line 167, in __run_task
    thread_result.set(func(*args, **kwargs))
[2021-02-26 11:46:15,669: WARNING/MainProcess] OSError: [Errno 22] Invalid argument
[2021-02-26 11:46:15,670: WARNING/MainProcess] 2021-02-26T11:46:15Z
[2021-02-26 11:46:15,670: WARNING/MainProcess] (<ThreadPoolWorker at 0x7f442946aca0 thread_ident=0x7f4428c3b700 threadpool-hub=<Hub at 0x7f444aa1c580 thread_ident=0x7f444e91d740>>, <built-in function getaddrinfo>) failed with OSError
```

This is only happening on our server which is running the above mentioned OS. The same task runs fine on my local machine (MacOS Big Sur version 11.2.1)

### What I've run:

Unfortunately, I can't share the celery task code over here due to company policy, but what it does is makes 5 api calls (using [requests-futures](https://pypi.org/project/requests-futures/) library) and processes the received data. This task is spawned through celery chord() and depending on the situation, there would be around 200 - 400 such tasks running in parallel.

The code itself does not have any issue - I've made sure of that - and it runs fine on other platforms as mentioned above.

Even if a full solution is not possible, please let me know what all can cause this issue. I might be able to work something out.

**Comment by jamadden** [comment]
This looks like code is calling `socket.getaddrinfo()` and passing in an invalid argument. By default, gevent runs `socket.getaddrinfo()` in a background thread, so that's why the threadpool is involved. 

I suggest [trying a different resolver](http://www.gevent.org/dns.html). Because the blocking resolver just directly calls `socket.getaddrinfo()` it doesn't impact the traceback at all so it can be easiest to debug for cases like this.

**Comment by Arun-N** [comment]
Hi @jamadden. It seems the link you posted is not working. Can you check it?

**Comment by jamadden** [comment]
It works fine for me, so I'm not sure what you're seeing. Maybe check HTTP vs HTTPS?

The gevent homepage: https://www.gevent.org also links directly to that same page (https://www.gevent.org/dns.html) with the text "Cooperative DNS queries".

**Comment by Arun-N** [comment]
Hi @jamadden. It seems requests-futures library is not compatible with gevent. Do you know of any alternative that can allow me to run multiple http GET requests in parallel, from within a celery task running on gevent? Some library that is compatible or maybe some solution native to gevent?

**Comment by jamadden** [comment]
>  Do you know of any alternative that can allow me to run multiple http GET requests in parallel, from within a celery task running on gevent? Some library that is compatible or maybe some solution native to gevent?

Sure, it's trivial to do: Just spawn the requests into separate greenlets.

```python
jobs = [gevent.spawn(requests.get, url) for url in urls]
gevent.wait(jobs)
```

(You could also do the same thing using traditional `threading.Thread` APIs.)

There's [a more complete example](https://github.com/gevent/gevent/blob/83c9e2ae5b0834b8f84233760aabe82c3ba065b4/examples/concurrent_download.py) doing just that:

https://github.com/gevent/gevent/blob/83c9e2ae5b0834b8f84233760aabe82c3ba065b4/examples/concurrent_download.py#L1-L31
