### ISSUE TITLE
SSLContext recursion when initialized before patching

### ISSUE THREAD

**Issue by ikonst** [gevent/gevent#1777]
Simple repro:
```python
import gevent.monkey
import ssl
ctx = ssl.SSLContext()
ctx.options |= ssl.Options.OP_NO_TICKET

gevent.monkey.patch_all()
ctx.options |= ssl.Options.OP_NO_TICKET  # infinite recursion here
```

Perhaps a way to solve it would be to restructure `gevent._ssl3.SSLContext` to **copy** SSLContext instead of **basing** on it:
```diff
-class SSLContext(orig_SSLContext):
+class SSLContext(orig_SSLContext.__base__):

     __slots__ = ()

+    vars().update(orig_SSLContext.__dict__)
```

**Comment by ikonst** [comment]
Relates to https://github.com/gevent/gevent/issues/1531

**Comment by jamadden** [comment]
Thanks for the report. The issue and the solution are known.

**Comment by ikonst** [comment]
Would you consider a change as suggested?

**Comment by ikonst** [comment]
Oh, now I'm realizing there's no easy way to solve it. At least new versions of gevent have the GC scan and warning so that's probably sufficient.
