### ISSUE TITLE
gevent 20.12.0 later doesn't mention requires_dist anymore

### ISSUE THREAD

**Issue by Rahul-RB** [gevent/gevent#1781]
* gevent version: 20.12.0
* Python version: 3.7
* Operating System: Any

### Description:
For `gevent` version `<=20.9.0`, we would get the list of dependencies of the `gevent` package via `pypi` as:

```
$ curl https://pypi.org/pypi/gevent/20.9.0/json
{
....
        "requires_dist": [
            "zope.event",
            "zope.interface",
            "setuptools",
            "greenlet (>=0.4.17) ; platform_python_implementation == \"CPython\"",
            "cffi (>=1.12.2) ; platform_python_implementation == \"CPython\" and sys_platform == \"win32\"",
            "dnspython (<2.0,>=1.16.0) ; extra == 'dnspython'",
            "idna ; extra == 'dnspython'",
            "repoze.sphinx.autointerface ; extra == 'docs'",
            "sphinxcontrib-programoutput ; extra == 'docs'",
            "psutil (>=5.7.0) ; (sys_platform != \"win32\" or platform_python_implementation == \"CPython\") and extra == 'monitor'",
            "dnspython (<2.0,>=1.16.0) ; extra == 'recommended'",
            "idna ; extra == 'recommended'",
            "cffi (>=1.12.2) ; (platform_python_implementation == \"CPython\") and extra == 'recommended'",
            "selectors2 ; (python_version == \"2.7\") and extra == 'recommended'",
            "backports.socketpair ; (python_version == \"2.7\" and sys_platform == \"win32\") and extra == 'recommended'",
            "psutil (>=5.7.0) ; (sys_platform != \"win32\" or platform_python_implementation == \"CPython\") and extra == 'recommended'",
            "dnspython (<2.0,>=1.16.0) ; extra == 'test'",
            "idna ; extra == 'test'",
            "requests ; extra == 'test'",
            "objgraph ; extra == 'test'",
            "cffi (>=1.12.2) ; (platform_python_implementation == \"CPython\") and extra == 'test'",
            "selectors2 ; (python_version == \"2.7\") and extra == 'test'",
            "futures ; (python_version == \"2.7\") and extra == 'test'",
            "mock ; (python_version == \"2.7\") and extra == 'test'",
            "backports.socketpair ; (python_version == \"2.7\" and sys_platform == \"win32\") and extra == 'test'",
            "contextvars (==2.4) ; (python_version > \"3.0\" and python_version < \"3.7\") and extra == 'test'",
            "coverage (<5.0) ; (sys_platform != \"win32\") and extra == 'test'",
            "coveralls (>=1.7.0) ; (sys_platform != \"win32\") and extra == 'test'",
            "psutil (>=5.7.0) ; (sys_platform != \"win32\" or platform_python_implementation == \"CPython\") and extra == 'test'"
        ],
...
}

```

This `requires_dist` allows us to build packages (read FreeBSD pkg) for all dependencies and gevent itself. But since 20.12.0, the `requires_dist` comes out to be `null` which has made FreeBSD's gevent pkg to stop at `20.9.0` itself:

```
$ curl https://pypi.org/pypi/gevent/20.12.0/json
{
...
        "requires_dist": null,
...
}
```

thus pkg shows:
```
$ pkg rquery %v py37-gevent
20.9.0
```

Can something please be done from gevent side to fix the dependencies?

**Comment by jamadden** [comment]
> Can something be done from gevent side to fix the dependencies?

No, not to my knowledge.

gevent has essentially no control over what PyPI's non-standard JSON API returns; it can't control what metadata is extracted and how. The artifacts that gevent *is* responsible for, its sdist (.tar.gz) and wheels (.whl) have the correct metadata. (Otherwise they couldn't be installed.) Note that binary wheels, by design, have far more available metadata than source distributions.

The metadata standard is documented, and there are tools that work with it. It's plain text and can easily be extracted from a binary wheel. I suggest fetching a binary wheel and looking at the standard data therein. This should work for any project.

```console
$ wget https://files.pythonhosted.org/packages/.../gevent-21.1.2-cp27-cp27m-macosx_10_14_x86_64.whl
$ unzip -p ./gevent-21.1.2-cp27-cp27m-macosx_10_14_x86_64.whl gevent-21.1.2.dist-info/METADATA | grep Requires-Dist
Requires-Dist: zope.event
Requires-Dist: zope.interface
Requires-Dist: setuptools
Requires-Dist: greenlet (<2.0,>=0.4.17) ; platform_python_implementation == "CPython"
…
```

I have a vague memory that at one point in time PyPI required uploading artifacts in a certain order to populate some of its own metadata fields, but whether or not that's the case anymore I can't say; nor can I make any guarantees about what order artifacts are uploaded in.

**Comment by Rahul-RB** [comment]
Ok, now I understand the situation, thanks a lot for the explanation!

So firstly I need to verify if wheels of a pip package have the same (or more) dependencies being shown in the API. 
And then figure out some to get the latest wheel file, unzip in memory and get the list of dependencies.

Since this is not a gevent bug, I'll close it.
