### ISSUE TITLE
arm64 crossompile error

### ISSUE THREAD

**Issue by erdoukki** [gevent/gevent#1792]
checking build system type... x86_64-pc-linux-gnu
checking host system type... Invalid configuration `aarch64-openwrt-linux': machine `aarch64-openwrt' not recognized

is there any solution from cross compilation ?

**Comment by jamadden** [comment]
I have no idea. That's not something I ever do. 

You might try updating to the latest `config.guess` and `config.sub` files (see the README in https://github.com/gevent/gevent/tree/master/deps).

**Comment by erdoukki** [comment]
thanks, it fix my problem.
I have updated the config.guess and config.sub files in libev root folder.
Then the build correctly cross compile on my host (ubuntu amd64) for arm64 target...

**Comment by erdoukki** [comment]
Can you help on building with python setup.py (and how to override and give the --host parameter) ?

**Comment by jamadden** [comment]
I can't help with cross compiling.

**Comment by erdoukki** [comment]
Ok… thanks
