### ISSUE TITLE
UnboundLocalError: local variable 'the_watcher' referenced before assignment

### ISSUE THREAD

**Issue by davit555** [gevent/gevent#1796]
* gevent version: 1.2.2
* Python version: PyPy 6.0.0 with GCC 7.2.0

* Operating System: Ubuntu 18.04.5 LTS

### Description:

after sigint got the below exception with the trace

```python-traceback
From cffi callback <function _python_callback at 0x00007f66efba91f0>:
Traceback (most recent call last):
  File "/home/admin/venvs/pypy-6.0.0/site-packages/gevent/libev/corecffi.py", line 116, in _python_callback
    the_watcher._exc_info = sys.exc_info()
UnboundLocalError: local variable 'the_watcher' referenced before assignment
```

`@ffi.callback("int(void* handle, int revents)")
def _python_callback(handle, revents):
    """
    Returns an integer having one of three values:

    - -1
      An exception occurred during the callback and you must call
      :func:`_python_handle_error` to deal with it. The Python watcher
      object will have the exception tuple saved in ``_exc_info``.
    - 0
      Everything went according to plan. You should check to see if the libev
      watcher is still active, and call :func:`_python_stop` if so. This will
      clean up the memory.
    - 1
      Everything went according to plan, but the watcher has already
      been stopped. Its memory may no longer be valid.
    """
    try:
        # Even dereferencing the handle needs to be inside the try/except;
        # if we don't return normally (e.g., a signal) then we wind up going
        # to the 'onerror' handler, which
        # is not what we want; that can permanently wedge the loop depending
        # on which callback was executing
        the_watcher = ffi.from_handle(handle)
        args = the_watcher.args
        if args is None:
            # Legacy behaviour from corecext: convert None into ()
            # See test__core_watcher.py
            args = _NOARGS
        if args and args[0] == GEVENT_CORE_EVENTS:
            args = (revents, ) + args[1:]
        the_watcher.callback(*args)
    except: # pylint:disable=bare-except
        the_watcher._exc_info = sys.exc_info()   # <------- this is the actual place
        # Depending on when the exception happened, the watcher
        # may or may not have been stopped. We need to make sure its
        # memory stays valid so we can stop it at the ev level if needed.
        the_watcher.loop._keepaliveset.add(the_watcher)
        return -1
    else:
        if the_watcher in the_watcher.loop._keepaliveset:
            # It didn't stop itself
            return 0
        return 1 # It stopped itself`

**Comment by jamadden** [comment]
Please try again with a current version of gevent; 1.2.2 is over four years old.
