### ISSUE TITLE
immediate disconnection of gevent-websocket (code: 1005, reason: “”)

### ISSUE THREAD

**Issue by nemnemnemy** [gevent/gevent#1806]
* gevent version: gevent==21.1.2
* Python version: Python 3.8.10
* Operating System: Ubuntu 20.04.1 LTS

### Description:

I test the following simple websocket server with wscat, but it is immediately disconnected without listening.

I tried

```
python main.py &
wscat -c ws://localhost:5000/echo
```

and the result is below without showing any prompt.

```
Connected (press CTRL+C to quit)
Disconnected (code: 1005, reason: "")
```

### What I've run:

main.py
```
# -*- coding: utf-8 -*-

from geventwebsocket.handler import WebSocketHandler
from gevent.pywsgi import WSGIServer
from flask import Flask, request
from werkzeug.exceptions import abort

app = Flask(__name__)

@app.route('/echo')
def echo():
    ws = request.environ['wsgi.websocket']
    if not ws:
        abort(400)
    while True:
        message = ws.receive()
        ws.send(message)

if __name__ == '__main__':
    http_server = WSGIServer(('', 5000), app, handler_class=WebSocketHandler)
    http_server.serve_forever()
```

**Comment by jamadden** [comment]
I suggest you raise this issue with the `geventwebsocket` maintainers (which is not me). They're more likely to be able to help you than I am.

Good luck!
