### ISSUE TITLE
Use of gevent monkey patching raises TypeError: 'module' object is not callable. Otherwise, flask-socketio app runs perfectly.

### ISSUE THREAD

**Issue by razaaliabid87** [gevent/gevent#1807]
Actually, the issue is that when I use gevent monkey patching for my flask-socketio app I get `TypeError: 'module' object is not callable` otherwise without using gevent, my app runs perfectly. I already have shared my code in a discussion [#1635](https://github.com/miguelgrinberg/Flask-SocketIO/discussions/1635) with _Miguel Grinberg_. Please take a look and help me to solve this issue.

**Comment by jamadden** [comment]
There was a uWSGI bug about them trying to call `gevent.socket`, which is a module. You probably need to update your uWSGi version. 

In the future, please provide all the information requested in the bug report form. This was a very unhelpful bug report or question.

**Comment by jamadden** [comment]
Closing as a duplicate of https://github.com/gevent/gevent/issues/1556. If you can confirm that's not the case feel free to reopen.
