### ISSUE TITLE
Calling gevent.sleep from a thread creates an anon_inode and eventually "too many files open" error 

### ISSUE THREAD

**Issue by aaknitt** [gevent/gevent#1816]
* gevent version:   1.4.0 and 21.8.0 on Raspberry Pi installed using pip3
* Python version: 3.7.3
* Operating System: Please be as specific as possible. For example,
                  "Raspbian Buster"

### Description:

When gevent.sleep() is called from another thread, an anon_inode is created. If this happens enough, a "too many files open" error from the OS will be produced. For example, on a Raspberry Pi the default maximum number of file descriptors that a single process can have open is 1024. So if gevent.sleep() is called 1024 times from a thread, this error will occur.

```python traceback
SystemError: (libev) error creating signal/async pipe: Too many open files
2021-08-28T14:33:11Z
Traceback (most recent call last):
  File "src/gevent/libev/corecext.pyx", line 1327, in gevent.libev.corecext._syserr_cb
  File "src/gevent/libev/corecext.pyx", line 571, in gevent.libev.corecext.loop._handle_syserr
  File "src/gevent/libev/corecext.pyx", line 584, in gevent.libev.corecext.loop.handle_error
  File "/home/pi/.local/lib/python3.7/site-packages/gevent/hub.py", line 543, in handle_error
  File "/home/pi/.local/lib/python3.7/site-packages/gevent/hub.py", line 569, in handle_system_error
greenlet.error: cannot switch to a different thread
(libev) error creating signal/async pipe: Too many open files
Aborted
```

### To Reproduce
Minimal script to produce issue (reproducible on a Raspberry Pi running standard OS):
```python
import gevent
import _thread
import time

def newdelay():
	gevent.sleep(.001)
	print("done sleeping in thread - this created an a_inode")
	return

while 1:
	time.sleep(0.01)
	_thread.start_new_thread(newdelay,())

```
After this script is started, check the number of file descriptors that it has open by running (it will increase quickly):
`lsof -p [PID of script] | wc -l`

After about 10 seconds the "too many files open" error will occur.

**Comment by jamadden** [comment]
What's happening is that you're creating brand new threads, and in each new thread you're creating a brand new gevent hub and loop (a gevent hub/loop is specific to a particular thread). You're then exiting the thread (falling off the end) *without* disposing of the hub/loop. Each hop/loop requires certain resources, such as a pipe. If you continually create more of these without disposing of the ones you don't need, you will eventually run into system limitations. 

If you'll be manually creating threads in this fashion, you need to call [`get_hub().destroy(True)`](http://www.gevent.org/api/gevent.hub.html#gevent.hub.Hub.destroy) before exiting the thread.

A higher-level solution is to use a single [threadpool](http://www.gevent.org/api/gevent.hub.html#gevent.hub.Hub.threadpool) to manage background worker threads. These can be used to limit the number of threads in use, and background threads automatically cleanup their own hub (if needed).

**Comment by aaknitt** [comment]
Thanks, this helps a lot.  The original project wasn't using gevent but it got pulled in from another package, so I'm learning about some of these conflicts.  I have a workaround in place now based on your suggestions.  Closing the issue as I don't think it's a problem with gevent itself.
