### ISSUE TITLE
wheels for cpytnon3.10 for linux

### ISSUE THREAD

**Issue by horpto** [gevent/gevent#1822]
* gevent version: 21.8.0
* Python version: python v3.10  from docker-slim-bullseye
* Operating System: debian

### Description:

I see a wheels for Windows and MacOS on the PYPI but I don't find a wheels for linux. Although for the other python versions there is.

**Comment by auvipy** [comment]
when we could expect a python 3.10 compatible release?

**Comment by jamadden** [comment]
The release is compatible with 3.10, there just aren't published binary wheels.
