### ISSUE TITLE
libuv bug on windows

### ISSUE THREAD

**Issue by cole-dda** [gevent/gevent#1823]
* gevent version: pip install gevent==20.9.0
* Python version:  "cPython 3.8.1 downloaded from python.org"
* Operating System: "windows 2012"

### Description:

**REPLACE ME**:  when socket read

**Trackback**: 

<img width="463" alt="screenshot_4677" src="https://user-images.githubusercontent.com/1077830/137720325-40a723cb-b6b9-446f-84c8-e1369bb46a07.png">

<img width="639" alt="screenshot_4674" src="https://user-images.githubusercontent.com/1077830/137720593-007e7901-f21a-4473-a990-f3c3203ee2f9.png">
### What I've run:

**REPLACE ME**:  gevent server read

**Comment by jamadden** [comment]
None of the needed additional information has been provided, closing. Feel free to reopen to provide more information.
