### ISSUE TITLE
musllinux build of package.

### ISSUE THREAD

**Issue by WAKayser** [gevent/gevent#1824]
* gevent version: Please note how you installed it: From source, from
                  n.a.
* Python version: Please be as specific as possible. For example,
                  cPython 3.9 or cPython 3.10
* Operating System: Please be as specific as possible. For example,
                  alpine linux 3.10

### Description:
Would it be possible to add a build for musl 1.1 or musl 1.2?

This would help when installing the package in environments like alpine linux for containers.

**Comment by lithammer** [comment]
Using [cibuildwheel](https://github.com/pypa/cibuildwheel) makes this fairly easy.
