### ISSUE TITLE
FileObject is inconsistent with respect to raising IOError/OSError/ValueError

### ISSUE THREAD

**Issue by vitaly-krugl** [gevent/gevent#186]
The exceptions in FileObject that return errno should be consistent with respect to raising OSError or IOError exceptions and the one that's raised needs to be documented so developers will know which one to catch.

Presently, this is inconsistent within each of the flavors of FileObject as well as between them (FileObjectPosix and FileObjectThread); sometimes they return IOError and sometimes OSError.  This makes it error-prone for catching the correct exception when compared to the built-in file object, which always returns IOError in those scenarios.

Also, operations on a closed FileObject differer from the built-in file object: built-in raises ValueErrror; FileObjectPosix crashes with AttributeError and FileObjectThread raises IOError;

The following code snippets demonstrate these inconsistencies...

If we close its fd before read, the built-in file object raises IOError; here is an example:

```
In [94]: f = open("zzz")

In [95]: os.close(f.fileno())

In [96]: f.read(1)
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)

/Users/vkruglikov/<ipython console> in <module>()

IOError: [Errno 9] Bad file descriptor
```

FileObjectPosix raises OSError if we close its fd before read:

```
In [80]: r, w = os.pipe()

In [81]: f = FileObjectPosix(r)

In [82]: os.close(r)

In [83]: gevent.spawn(f.read, 10)
Out[83]: <Greenlet at 0x104099c30: <bound method FileObjectPosix.read of <FileObjectPosix <SocketAdapter at 0x1040d31d0 (14, 'rb')>>>(10)>

In [84]: gevent.sleep(1)
Traceback (most recent call last):
  File "/Users/vkruglikov/oss/gevent/build/lib.macosx-10.7-intel-2.6/gevent/greenlet.py", line 328, in run
    result = self._run(*self.args, **self.kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/socket.py", line 377, in read
    data = self._sock.recv(left)
  File "/Users/vkruglikov/oss/gevent/build/lib.macosx-10.7-intel-2.6/gevent/fileobject.py", line 116, in recv
    data = _read(self.fileno(), size)
OSError: [Errno 9] Bad file descriptor
<Greenlet at 0x104099c30: <bound method FileObjectPosix.read of <FileObjectPosix <SocketAdapter at 0x1040d31d0 (14, 'rb')>>>(10)> failed with OSError
```

But FileObjectThread raises IOError if we close its fd before read:

```
In [13]: r, w = os.pipe()

In [14]: f = FileObjectThread(r)

In [15]: os.close(r)

In [16]: f.read(10)
IOError: [Errno 9] Bad file descriptor
```

However, FileObjectPosix raises IOError if we close the fd before creating FileObjectPosix:

```
In [5]: r, w = os.pipe()

In [6]: os.close(r)

In [7]: f = FileObjectPosix(r)
IOError: [Errno 9] Bad file descriptor
```

But FileObjectThread raises OSError if we close the fd before creating FileObjectThread:

```
In [10]: r, w = os.pipe()

In [11]: os.close(r)

In [12]: FileObjectThread(r)
OSError: [Errno 9] Bad file descriptor
```

Another difference shows up when we attempt to read from a closed file; built-in file object handles reading from closed file like this:

```

In [106]: f = open("zzz")

In [107]: f.close()

In [108]: f.read(1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)

/Users/vkruglikov/<ipython console> in <module>()

ValueError: I/O operation on closed file
```

But gevent FileObjectPosix handles reading from closed file differently - raises AttributeError:

```
In [110]: r, w = os.pipe()

In [111]: f = FileObjectPosix(r)

In [112]: f.close()

In [113]: f.read(1)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)

/Users/vkruglikov/<ipython console> in <module>()

/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/socket.pyc in read(self, size)
    375                 # fragmentation issues on many platforms.

    376                 try:
--> 377                     data = self._sock.recv(left)
    378                 except error, e:
    379                     if e.args[0] == EINTR:

AttributeError: 'NoneType' object has no attribute 'recv'
```

But FileObjectThread raises IOError when attempting to read from a closed instance:

```
In [4]: f = FileObjectThread(r)

In [5]: f.close()

In [6]: f.read(1)

IOError: [Errno 9] Bad file descriptor (FileObject was closed)
```

**Comment by jamadden** [comment]
Under Python 3, `IOError` and `OSError` are the same thing, so that at least is solved. Under Python 2, code that's also trying to be able to run on Python 3 will usually write `except (IOError,OSError):` so that's less of a concern than it was.

Since rewriting `FileObjectPosix` to be based on the stdlib `io` package, it should now be consistent with what the stdlib does (once constructed, anyway). For example, it now raises ValueError for closed reads:
```
>>> import os
>>> from gevent.fileobject import *
>>> r, w = os.pipe()
>>> f = FileObjectPosix(r)
>>> f.close(
... )
>>> f.read(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//gevent/_fileobjectposix.py", line 269, in read
    return self.io.read(size)
ValueError: read of closed file
```

There are still the differences in the constructor under Python 2, but that may not be a big issue anymore.

**Comment by jamadden** [comment]
There has been further unification of FileObjectThread and FileObjectPosix under 1.2 (other than the constructors). Given that and my comments above, I'm going to consider this closed, although I haven't exhaustively checked every single example. Please feel free to open additional issues for specific cases that are troublesome in practical usage.
