### ISSUE TITLE
Monkey-patch didn't have desired effect on databricks notebook

### ISSUE THREAD

**Issue by oyuan124** [gevent/gevent#1868]
* gevent version: pip install - ver 21.12.0
* Python version: 3.8
* Operating System: macOS Big Sur ver 11.3.1

### Description:

I am trying to import grequests and requests in a databricks notebook. It's the first step in my notebook and it shows warning about monkey-patching too late. Later it causes Recursion error when I am using simple_salesforce package. It seems that I need to monkey-patch earlier but my first line of code is already importing grequests, which will perform a monkey patch. Did I miss something that's very obvious? How do I monkey-patch earlier? 

```python-traceback
/databricks/python/lib/python3.8/site-packages/grequests.py:22: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util (/databricks/python/lib/python3.8/site-packages/urllib3/util/__init__.py)', 'urllib3.util.ssl_ (/databricks/python/lib/python3.8/site-packages/urllib3/util/ssl_.py)']. 
  curious_george.patch_all(thread=False, select=False)
```

```
RecursionError: maximum recursion depth exceeded while calling a Python object
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
```

### What I've run:

``` import packages
import grequests
import requests
```

``` where the recursion error occurs
Salesforce(username, password, security_token)
```

**Comment by jamadden** [comment]
I suspect that if you're in a "notebook", a LOT of code has already run by the time it gets around to executing your snippets. You'd probably need to patch the entire process that runs the notebook itself. E.g., `python -m gevent.monkey whatever.runs.your.notebook`.

**Comment by oyuan124** [comment]
> I suspect that if you're in a "notebook", a LOT of code has already run by the time it gets around to executing your snippets. You'd probably need to patch the entire process that runs the notebook itself. E.g., `python -m gevent.monkey whatever.runs.your.notebook`.

that's my guess as well. looks like some util packages that use ssl are already imported. working with my team on our side but wonder if someone else has experienced before

**Comment by jagguli** [comment]
possibly related I'm experiencing this with geven on uwsgi  

https://github.com/unbit/uwsgi/issues/2405
