### ISSUE TITLE
multiprocess.Pool hangs when ForkPoolworker using python 3.9.10

### ISSUE THREAD

**Issue by allen-munsch** [gevent/gevent#1876]
### Description:

multiprocess.Pool hangs when ForkPoolworker using python 3.9.10

```
04:09:32 (.env) jm@jm poolproblems → lsb_release -av
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

04:09:37 (.env) jm@jm poolproblems → uname -a
Linux jm 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

04:07:01 (.env) jm@jm poolproblems → python --version
Python 3.9.10

04:07:04 (.env) jm@jm poolproblems → pip freeze
gevent==21.12.0
greenlet==1.1.2
psycopg2==2.8.6
```

Output hangs:

```python-traceback
04:06:48 (.env) jm@jm poolproblems → python okay.py 
> /home/jm/pycharm_projects/poolproblems/okay.py(12)<module>()
-> pool = multiprocessing.Pool(
(Pdb) c
okay
okay
okay
okay
okay
okay
okay
okay
okay
okay
okay
okay
okay
okay
okay
okay
^C
Program interrupted. (Use 'cont' to resume).
Program interrupted. (Use 'cont' to resume).
```

### What I've run:

```python
try:
    from gevent import monkey
    monkey.patch_all()
except ImportError:
    pass
import ctypes
import multiprocessing
logger = multiprocessing.log_to_stderr()
logger.setLevel(25)
counter = multiprocessing.Value(ctypes.c_int, 0)
breakpoint()
pool = multiprocessing.Pool(
    processes=16,
    initializer=lambda: print('okay'),
)
breakpoint()

```

**Comment by jamadden** [comment]
Only very limited use of the `multiprocessing` module is known to work (specifically, some basic use of `Process`) when everything is monkey-patched by a plain gevent. Most everything else will hang the process. (This is documented in a few places, the first that comes to mind is [here](http://www.gevent.org/api/gevent.monkey.html#gevent.monkey.patch_thread), which could probably be improved.)

You can try not patching the `thread` module. That may or may not work for you. You can also try [geventmp](https://pypi.org/project/geventmp/) from @arcivanov, which is intended for this sort of thing.

**Comment by allen-munsch** [comment]
@jamadden ah okay, thank you so much for pointing that out, and the suggestions. I totally missed the documentation on it.
