### ISSUE TITLE
Please add osx-arm64 binary wheels

### ISSUE THREAD

**Issue by perlow** [gevent/gevent#1878]
All new Apple laptops are now arm64 based on Apple silicon. It would be greatly appreciated if osx-arm64 wheels were created. This would greatly reduce the time our engineers spend when they update their environments. I saw that there was [this issue](https://github.com/gevent/gevent/issues/1673) from 2020 where the response was that "not currently prepared to support binary wheels for arm64", but looks like the project is now supporting arm64 for Linux. We've been using this on M1s and haven't hit any issues yet, so hopefully this should be relatively easy to support.

**Comment by jamadden** [comment]
I don't think GitHub Actions can do that. A PR that proves me wrong would be welcome.

**Comment by tyates-indeed** [comment]
https://github.com/actions/runner/releases indicates that `OSX arm64 (Apple silicon)` is now supported. Would you be open to adding that runner to publish the wheels?

**Comment by jamadden** [comment]
Binary wheels for Apple silicon have been published for many releases at this point. All provided macOS wheels are universal, able to be installed on Intel or Arm.
