### ISSUE TITLE
Failed building wheel for gevent - Termux

### ISSUE THREAD

**Issue by 13Quavo** [gevent/gevent#1887]
Hi,

I have an issue installing gevent using command pip install gevent
ERROR: fAILED BUILDING WHEEL FOR GEVENT
Could not build wheels for gevent, which is required to install pyproject.toml-based projects

CODE: https://pastebin.com/PbwxR9SH

Any solutions?

**Comment by jamadden** [comment]
The output says:
```
 configure: error: no acceptable ld found in $PATH 
```

This means you're missing the correct linker binary (`ld`) and your system isn't capable of compiling Python extensions. You need to install the complete Python development toolchain (e.g., python headers, gcc/clang, etc) to compile Python extensions from source.
