### ISSUE TITLE
GEvent triggers numpy warnings

### ISSUE THREAD

**Issue by ml31415** [gevent/gevent#1891]
* gevent version: 21.12.0
* Python version: cPython 3.10.4
* numpy version: 1.22.4
* Operating System: Ubuntu

### Description:

Importing gevent seems to modify some settings with CPU floating point handling. Referring to the bug report over at numpy, this seems to be caused by libraries compiled with `-ffast-math`. This seems to be a decision better left to the user, especially in numerical computational context, so `-ffast-math` should be avoided.

https://github.com/numpy/numpy/issues/20895

### What I've run:

```python
import gevent
import numpy
numpy.finfo(numpy.dtype('float32')).smallest_subnormal

/home/michael/.local/lib/python3.10/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/michael/.local/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
```

**Comment by mguijarr** [comment]
It seems like gevent 21.12 already has a fix for this issue:

From changelog file, in "bug fixes" section:

> Stop compiling manylinux wheels with -ffast-math. This was implicit in -Ofast, but could alter the global state of the process. Analysis and fix thanks to Ilya Konstantinov. See [:issue:`1820`](https://github.com/gevent/gevent/blob/master/CHANGES.rst#id12).

**Comment by ml31415** [comment]
Yeah, looks like my issue report is a duplicate of #1820 and #1864 . So probably #1864 or something along those lines should be accepted to really fix the issue.
