### ISSUE TITLE
please remove the tests/hosts_file.txt

### ISSUE THREAD

**Issue by MrLYC** [gevent/gevent#1892]
* gevent version: 1.4.0
* Python version: cpython 3.6
* Operating System: alpine(docker image)

### Description:

We found gevent tests directory contains a [hosts file](https://github.com/gevent/gevent/blob/master/src/gevent/tests/hosts_file.txt), our ci system thik this file contains some inappropriate text, please remove this file.

**Comment by jamadden** [comment]
That file is part of the gevent test suite and will not be removed.

**Comment by Ivoz** [comment]
Do the tests need all those porn  / shock sites listed?
