### ISSUE TITLE
Update type annotation to allow mypy to succeed

### ISSUE THREAD

**Issue by kchen** [gevent/gevent#1900]
* gevent version: 1.5.0, from Pypi, but this issue appears to still exist in master 
* Python version: cPython 3.8.10 from Ubuntu 20.04
* Operating System: Ubuntu 20.04.4 LTS

### Description:

gevent's greenlet.py has some annotations that should be tweaked. There are 3 instances of:
`# type:SwitchOutGreenletWithLoop pylint:disable=undefined-variable`

It seems that these should instead be:
`# type:SwitchOutGreenletWithLoop # pylint:disable=undefined-variable`

### What I've run:

$ cat /tmp/foo.py
import gevent

$ MYPYPATH=lib mypy --follow-imports=silent /tmp/foo.py
lib/gevent/greenlet.py:315: error: syntax error in type comment 'SwitchOutGreenletWithLoop pylint:disable=undefined-variable'
lib/gevent/greenlet.py:369: error: syntax error in type comment 'SwitchOutGreenletWithLoop pylint:disable=undefined-variable'
lib/gevent/greenlet.py:596: error: syntax error in type comment 'SwitchOutGreenletWithLoop pylint:disable=undefined-variable'
Found 3 errors in 1 file (checked 1 source file)

Changing the annotation as noted above appears to allow both mypy and pylint to work properly.

PEP 484 says:

> In some cases, linting tools or other comments may be needed on the same line as a type comment. In these cases, the type comment should be before other comments and linting markers:
> 
> `# type: ignore # <comment or other marker>`
> If type hinting proves useful in general, a syntax for typing variables may be provided in a future Python version. (UPDATE: This syntax was added in Python 3.6 through [PEP 526](https://peps.python.org/pep-0526).)

While PEP 484 references PEP 526, I didn't see this mentioned in PEP 526, although it's possible I overlooked it.

**Comment by jamadden** [comment]
Thank you for your interest. gevent is not typed and is not expected to pass any checks with mypy. Those were merely internal comments. They have been tweaked.
