### ISSUE TITLE
gevent dns resolver use threadpool, speed can't be improved! how to improve dns resolution speed

### ISSUE THREAD

**Issue by chushuai** [gevent/gevent#1904]
Resolver API using native threads

self.pool = hub.threadpool 

https://github.com/gevent/gevent/blob/master/src/gevent/resolver/thread.py#L39

   #: The size we use for our threadpool. Either use a subclass
    #: for this, or change it immediately after creating the hub.
    threadpool_size = 10

https://github.com/gevent/gevent/blob/master/src/gevent/hub.py#L399

**Comment by jamadden** [comment]
Please see the [documentation about selecting](http://www.gevent.org/dns.html) and [using](http://www.gevent.org/configuration.html#gevent._config.Config.resolver) different implementations for gevent's resolver. Many people find that the [c-ares resolver](http://www.gevent.org/api/gevent.resolver.ares.html) meets their needs. You can even write your own!
