### ISSUE TITLE
Missing wheels for Linux and Python 3.11 

### ISSUE THREAD

**Issue by alexprengere** [gevent/gevent#1917]
In light of the [changelog](https://github.com/gevent/gevent/blob/master/CHANGES.rst), this might be expected, but I thought to report it just in case.
It is not currently possible to install gevent on Docker 3.11.0rc2-slim.

```
$ docker run --rm -ti python:3.11.0rc2-slim bash
# pip install gevent
...
ERROR: Failed building wheel for gevent
```

Indeed looking at the [wheels for gevent 22.10](https://pypi.org/project/gevent/22.10.1/#files), for Python 3.10 there are those wheels:

- musllinux_1_1_x86_64.whl 
- manylinux_2_17_ppc64le.manylinux2014_ppc64le.whl 
- manylinux_2_17_aarch64.manylinux2014_aarch64.whl 
- manylinux_2_12_x86_64.manylinux2010_x86_64.whl 

But for 3.11 the *manylinux x86_64* is missing, hence the issue.

**Comment by jamadden** [comment]
I can only provide wheels for python versions that are present in the docker image when the wheel is built.

**Comment by m3brown** [comment]
Is it possible this is related to deprecated support for manylinux2010 in August?

https://github.com/pypa/manylinux/issues/1281

Perhaps the build pipeline should be updated to use manylinux2014?
