### ISSUE TITLE
Memory leak with Python 3.11

### ISSUE THREAD

**Issue by salty-horse** [gevent/gevent#1924]
* gevent version: 22.10.2, installed from PyPI
* Python version: cPython 3.11.0, compiled locally with pyenv.
* Operating System: Linux (Ubuntu 22.04.1, Linux 5.15.0-52 x86_64)

### Description:

Running the [example wsgi server](https://github.com/gevent/gevent/blob/master/examples/wsgiserver.py), and performing many requests, the memory usage of the process grows indefinitely.

### What I've run:

To reproduce, download the example wsgi server and run it:
```
wget https://raw.githubusercontent.com/gevent/gevent/master/examples/wsgiserver.py
python3.11 ./wsgiserver.py > /dev/null 2>&1
```
Then perform many requests on it, for example with apache's benchmarking tool:
```
ab -n 100000 http://localhost:8088/
```
The memory usage of the process grows from 111kb to 1.7mb (measured with `ps -o drs,command ax`), and continues growing when performing more requests. With Python 3.10, it remains at 111kb.

**Comment by jamadden** [comment]
I can confirm this, with a simpler reproducer that just spawns greenlets repeatedly. The total number of refcounts goes up (by about 39) for each spawn (and about 39MB of memory usage per 10,000). But the number of objects available to Python's GC stays the same, meaning the refcounts are in objects that aren't tracked by the GC (which explains why gevent's leak tests didn't find anything; the total number of refcounts is only available on debug builds).

If we take gevent out and just spawn raw greenlets, the number of refcounts doesn't grow  (one for every 10,000 iterations, but I suspect this is bookkeeping inside of `objgraph`), but the memory does continue to increase by the same 39MB.

```python
import objgraph
from gevent._compat import get_this_psutil_process
from datetime import datetime
import os
import sys
import gevent
import greenlet
count = 0

def show_it():
    print()
    print('Latest growth (pid=%s requests=%s time="%s")' % (os.getpid(), count, datetime.now()))
    objgraph.show_growth()
    print('Memory report')
    print(get_this_psutil_process().memory_full_info())
    if hasattr(sys, 'gettotalrefcount'):
        print('Total refcount:', sys.gettotalrefcount())

GEVENT = False
def glet_main():
    def f():
        global count
        if not count:
            show_it()
        count += 1
        if count % 10000 == 0:
            show_it()
        return
    while count < 100_000:
        if GEVENT:
            s = gevent.spawn_raw(f)
            s.join()
        else:
            g = greenlet.greenlet(f)
            g.switch()

if __name__ == '__main__':
    glet_main()
```

Python 3.11 output of raw greenlets showing the memory growth, but no trackable object growth:

```console
$ python3.11-debug example.py

Latest growth (pid=82892 requests=0 time="2022-11-04 08:18:10.458527")
function                       4757     +4757
tuple                          3777     +3777
dict                           2996     +2996
ReferenceType                  2008     +2008
wrapper_descriptor             1384     +1384
method_descriptor              1087     +1087
builtin_function_or_method      993      +993
getset_descriptor               859      +859
list                            854      +854
type                            783      +783
Memory report
pfullmem(rss=27119616, vms=35023572992, pfaults=8826, pageins=1017, uss=21618688)
Total refcount: 326785

Latest growth (pid=82892 requests=10000 time="2022-11-04 08:18:10.600210")
function                       5169      +412
cell                            855      +299
tuple                          4024      +247
dict                           3196      +200
_tuplegetter                    226      +119
list                            901       +47
ReferenceType                  2050       +42
builtin_function_or_method     1032       +39
type                            822       +39
Negsignal                        31       +31
Memory report
pfullmem(rss=68317184, vms=35187617792, pfaults=18884, pageins=1017, uss=62816256)
Total refcount: 326796

Latest growth (pid=82892 requests=20000 time="2022-11-04 08:18:10.722785")
Memory report
pfullmem(rss=109469696, vms=35351633920, pfaults=28931, pageins=1017, uss=103968768)
Total refcount: 326797

Latest growth (pid=82892 requests=30000 time="2022-11-04 08:18:10.861704")
Memory report
pfullmem(rss=150683648, vms=35515695104, pfaults=38993, pageins=1017, uss=145182720)
Total refcount: 326798

Latest growth (pid=82892 requests=40000 time="2022-11-04 08:18:10.998365")
Memory report
pfullmem(rss=191864832, vms=35679756288, pfaults=49047, pageins=1017, uss=186363904)
Total refcount: 326799

Latest growth (pid=82892 requests=50000 time="2022-11-04 08:18:11.143764")
Memory report
pfullmem(rss=233046016, vms=35843817472, pfaults=59101, pageins=1017, uss=227545088)
Total refcount: 326800

Latest growth (pid=82892 requests=60000 time="2022-11-04 08:18:11.286657")
Memory report
pfullmem(rss=274227200, vms=36007878656, pfaults=69155, pageins=1017, uss=268726272)
Total refcount: 326801

Latest growth (pid=82892 requests=70000 time="2022-11-04 08:18:11.437651")
Memory report
pfullmem(rss=315408384, vms=36171939840, pfaults=79209, pageins=1017, uss=309907456)
Total refcount: 326802

Latest growth (pid=82892 requests=80000 time="2022-11-04 08:18:11.590335")
Memory report
pfullmem(rss=356589568, vms=36336001024, pfaults=89263, pageins=1017, uss=351088640)
Total refcount: 326803

Latest growth (pid=82892 requests=90000 time="2022-11-04 08:18:11.751686")
Memory report
pfullmem(rss=397795328, vms=36500017152, pfaults=99324, pageins=1017, uss=392294400)
Total refcount: 326804

Latest growth (pid=82892 requests=100000 time="2022-11-04 08:18:11.911027")
Memory report
pfullmem(rss=438829056, vms=36663898112, pfaults=109342, pageins=1017, uss=433328128)
Total refcount: 326805
```

Same in Python 3.10; but note the near-constant `uss`:
```
Latest growth (pid=84009 requests=0 time="2022-11-04 08:26:12.454512")
function                       3911     +3911
dict                           2480     +2480
tuple                          2005     +2005
wrapper_descriptor             1321     +1321
ReferenceType                  1252     +1252
builtin_function_or_method      954      +954
method_descriptor               921      +921
getset_descriptor               742      +742
type                            612      +612
member_descriptor               401      +401
Memory report
pfullmem(rss=22663168, vms=35003744256, pfaults=6799, pageins=47, uss=17371136)

Latest growth (pid=84009 requests=10000 time="2022-11-04 08:26:12.489917")
function                       4321      +410
cell                            652      +300
tuple                          2261      +256
dict                           2692      +212
_tuplegetter                    216      +119
ReferenceType                  1294       +42
builtin_function_or_method      993       +39
type                            651       +39
list                            362       +35
Negsignal                        31       +31
Memory report
pfullmem(rss=22700032, vms=35003744256, pfaults=6808, pageins=47, uss=17408000)

Latest growth (pid=84009 requests=20000 time="2022-11-04 08:26:12.514963")
Memory report
pfullmem(rss=22732800, vms=35003744256, pfaults=6816, pageins=47, uss=17440768)

Latest growth (pid=84009 requests=30000 time="2022-11-04 08:26:12.537101")
Memory report
pfullmem(rss=22757376, vms=35003744256, pfaults=6822, pageins=47, uss=17465344)

Latest growth (pid=84009 requests=40000 time="2022-11-04 08:26:12.559938")
Memory report
pfullmem(rss=22757376, vms=35003744256, pfaults=6822, pageins=47, uss=17465344)

Latest growth (pid=84009 requests=50000 time="2022-11-04 08:26:12.583793")
Memory report
pfullmem(rss=22757376, vms=35003744256, pfaults=6822, pageins=47, uss=17465344)

Latest growth (pid=84009 requests=60000 time="2022-11-04 08:26:12.607241")
Memory report
pfullmem(rss=22769664, vms=35003744256, pfaults=6825, pageins=47, uss=17477632)

Latest growth (pid=84009 requests=70000 time="2022-11-04 08:26:12.629636")
Memory report
pfullmem(rss=22769664, vms=35003744256, pfaults=6825, pageins=47, uss=17477632)

Latest growth (pid=84009 requests=80000 time="2022-11-04 08:26:12.655623")
Memory report
pfullmem(rss=22798336, vms=35003744256, pfaults=6832, pageins=47, uss=17506304)

Latest growth (pid=84009 requests=90000 time="2022-11-04 08:26:12.679802")
Memory report
pfullmem(rss=22798336, vms=35003744256, pfaults=6832, pageins=47, uss=17506304)

Latest growth (pid=84009 requests=100000 time="2022-11-04 08:26:12.703793")
Memory report
pfullmem(rss=22798336, vms=35003744256, pfaults=6832, pageins=47, uss=17506304)
```

This points to an issue in `greenlet`

**Comment by jamadden** [comment]
It also doesn't matter whether it's greenlet 1.1.3 or 2.0.0; Python 3.11 grows in both of those. So it's clearly something 3.11 specific.

**Comment by jamadden** [comment]
When examining the allocation pattern (and with `PYTHONMALLOC=malloc`), the macOS `malloc_history(1)` command gives this as the heaviest allocation trace for a similarly simple script:
```
High water mark of allocated heap + VM memory: 633.5 MB  at malloc stack log record index 1,791,588
     Current total allocated heap + VM memory: 633.4 MB  at malloc stack log record index 1,838,864
  Cumulative total allocated heap + VM memory: 696.1 MB
            Total heap + VM memory operations: 1,838,864  allocations: 1,001,548  deallocations:   837,316

Call graph:
    164265 (878M) << TOTAL >>
      40000 (625M) greenlet::UserGreenlet::g_switch()  (in _greenlet.cpython-311d-darwin.so) + 124  [0x125e1d64c]
      + 40000 (625M) greenlet::UserGreenlet::g_initialstub(void*)  (in _greenlet.cpython-311d-darwin.so) + 2213  [0x125e1ede5]
      +   40000 (625M) PyObject_Call  (in Python) + 41  [0x10c6dbb49]  call.c:355
      +     40000 (625M) _PyObject_Call  (in Python) + 136  [0x10c6dba88]  call.c:328
      +       40000 (625M) _PyVectorcall_Call  (in Python) + 287  [0x10c6db87f]  call.c:245
      +         40000 (625M) _PyFunction_Vectorcall  (in Python) + 96  [0x10c6dbc70]  call.c:0
      +           40000 (625M) _PyEval_Vector  (in Python) + 177  [0x10c7b63f1]  ceval.c:6423
      +             40000 (625M) _PyEvalFramePushAndInit  (in Python) + 63  [0x10c7c6c3f]  ceval.c:6360
      +               40000 (625M) _PyThreadState_BumpFramePointer  (in Python) + 53  [0x10c7c4a55]  pycore_frame.h:215
      +                 40000 (625M) _PyThreadState_BumpFramePointerSlow  (in Python) + 71  [0x10c80a9d7]  pystate.c:2195
      +                   40000 (625M) push_chunk  (in Python) + 55  [0x10c80aa67]  pystate.c:2165
      +                     40000 (625M) allocate_chunk  (in Python) + 26  [0x10c80b0fa]  pystate.c:719
      +                       40000 (625M) _PyObject_VirtualAlloc  (in Python) + 20  [0x10c724c84]  obmalloc.c:560
      +                         40000 (625M) _PyObject_ArenaMmap  (in Python) + 34  [0x10c7259e2]  obmalloc.c:152
      +                           40000 (625M) mmap  (in libsystem_kernel.dylib) + 0  [0x7ff8029053dd]
```

That's dealing with the [new-in-3.11 per-thread-state "stack chunks"](https://github.com/python-greenlet/greenlet/pull/306/files#diff-98aec0a05657427241b330f6514931482276b068dc3b15d2b4102a1871b9a9a0R563), `tstate->datastack_chunk` and friends. These are managed as a sort of linked list. It seems likely that we're orphaning some entries during switching.

**Comment by jamadden** [comment]
>  It seems likely that we're orphaning some entries during switching.

Actually, I think we may be orphaning an entire chain of entries (technically; in reality, there's probably just one entry on the chain). When we first start a greenlet, the `tstate->datastack_chunk` et al are set to `NULL`. This makes `pystate.c` allocate a new root chunk. When evaluation needs to pop frames, `pystate.c` goes to some effort to make sure that this root chunk is never popped.

So I *think* this means that when execution leaves a greenlet for the last time and switches back to the parent greenlet, we're left with a root chunk that will never get deallocated.

**Comment by jamadden** [comment]
Indeed, if I cause the greenlet to deallocate all the chunks on `tstate` when it exits, the memory growth stops. 🎉 

However, there are some challenges:

1. The chunks are allocated and freed using `_PyObject_VirtualAlloc` and `_PyObject_VirtualFree`. Those are not public functions, are cannot be trivially linked to (their symbols aren't exposed by default it seems).  It so happens that those two functions are currently implemented to go through the static `_PyObject_Arena` allocator, and that allocator _is_ available to us through the `PyObject_GetArenaAllocator` API. So I think we can free the chunks in a generic fashion, but  we'll be introducing another place where we're tightly coupled to the CPython implementation.
2. The trivial fix (deallocating the chunks when `inner_bootstrap` exits) results in at least one greenlet test crashing unexpectedly. I feel hopeful that can be resolved, though.

**Comment by jamadden** [comment]
This issue should be solved by using the just-released greenlet 2.0.1.

**Comment by AdrianBunk** [comment]
@jamadden This issue is in gevent, which still vendors an older version.

**Comment by AdrianBunk** [comment]
> This issue should be solved by using the just-released greenlet 2.0.1.

@jamadden This issue is in gevent, which still vendors an older version.

**Comment by jamadden** [comment]
No, it doesn't.

**Comment by salty-horse** [comment]
@AdrianBunk gevent depends on greenlet >= 2.0.0, which includes both the problem version, and any future fixed versions. It doesn't specifically "vendor the older version".

It's up to you, the user of gevent, to pick which greenlet version you wish to use. (You're generally expected to use the latest version you can, based on your other project requirements)

The gevent project can change its dependency to greenlet >= 2.0.1, but this is not a hard requirement, and there's no need for a new gevent release just for this.

**Comment by AdrianBunk** [comment]
> @AdrianBunk gevent depends on greenlet >= 2.0.0, which includes both the problem version, and any future fixed versions. It doesn't specifically "vendor the older version".

FTR, what I was looking at was https://github.com/gevent/gevent/blob/master/deps/greenlet/greenlet.h which is copied from greenlet, and I got confused regarding the rest.

Looking more carefully this file is vendored, but it is only the interface to greenlet so assuming greenlet will never break ABI in the future everything is fine.

Sorry for the noise.
