### ISSUE TITLE
Multipack flashing blocking data upload

### ISSUE THREAD

**Issue by vatsalmehta1994** [gevent/gevent#1943]
Hi,
I am using zerorpc to connect to server. My backend is in python and frontend is in js. Code flashed hex file to MCB chip. When I connect multiple MCBs through PCAN it stops uploading code at random time and gives HeartbeatError: Lost Remote after 10000 ms. I tried changing default HeartbeatInterval from 5000 ms to 10000 ms but it didn't work.

Can anyone help resolve this issue or disable Heartbeat checks?

Here is the code that connects to server:
Python:

```python
def start_rpc_server():
    address = 'tcp://122.0.0.0:' + str(parse_port())
    cfg_file_name = 'uds_flasher_cfg.json5'
    cfg = load_json5_portable(file=cfg_file_name, mode='r')  # from json configuration file
    server = zerorpc.Server(UpdateUtility(uds_cfg=cfg['uds_cfg'], system_cfg=cfg['system_cfgs'][platform.system()], bl_cfg=cfg['bl_cfg'], user_cfg=cfg['user_cfg']))
    server.bind(address)
    print('start running on {}'.format(address))
    server.run()
```
JS:
```javascript
const zerorpc = require("zerorpc");
let client = new zerorpc.Client({ timeout: 2 });
client.connect("tcp://122.0.0.0:4444");
```
It appears that the flashing operation is most likely a blocking operation. That blocks the current greenlet. In turn blocking the ioloop. Is there any way I can switch the greenlet and start new greenlet for each loop? or if there is any way that I can troubleshoot this issue.

Below is the function that upload the data on each MCB:

```python
    def do_upload(self, *interactive_args):

        self.initialize_can_bus()
        self.initialize_uds_client()

        while True:

            self._upload0()
            time.sleep(1)
            for i in range(1, 10):
                self.initialize_uds_client_after_increment()
                gevent.sleep(10)
                method_name = f"self._upload{i}"
                eval(method_name)

            if not self.bl_cfg['run_continuously']:
                print('\n' * 15)
                break

            self.uds_state['sequence_number'] += 1
```

PS: When I try to flash in development mode it flashes all MCBs fine but when I package the code into executable it shows this error.

**Comment by jamadden** [comment]
This seems like a very specialized question, involving specialized hardware. Since I don't know anything about this hardware, I can't really help. You'll need to figure out what is doing the blocking and if there's a way to make it cooperative. [gevent's monitoring tools](http://www.gevent.org/monitoring.html) can help with this.

If there's not a way to make it cooperative, then your best bet is to move the blocking operation into its own thread using gevent's threadpool.

Good luck.
