### ISSUE TITLE
universal2 wheels for Python 3.8-3.10 

### ISSUE THREAD

**Issue by wayne-li2** [gevent/gevent#1945]
* gevent version: 21.12.0, from PyPI
* Python version: 3.8.10, via `pyenv install 3.8.10`
* Operating System: Mac OS 13.3, M1 Pro (arm64)

### Description:

Nothing is wrong, but it would be nice to get a universal2 Mac wheel for Python versions 3.8-3.10. I can successfully build 21.12.0 from source but it takes a few minutes. As more people migrate onto M1 macbooks, Python 3.8 is the minimum version that can generally be run on M1s, so lots of people will run into this slight delay.

### What I've run:

None, feature request.

**Comment by jamadden** [comment]
Pre-built binary wheels are provided best-effort. I've been able to put some effort towards it and expect more Mac wheels in the next release.

**Comment by wayne-li2** [comment]
I appreciate it, thank you!
