### ISSUE TITLE
Is gevent file I/O blocking guaranteed?

### ISSUE THREAD

**Issue by nscmcgrath** [gevent/gevent#1953]
### Description:

In the [learn gevent documentation](https://learn-gevent-socketio.readthedocs.io/en/latest/gevent.html#exceptions-to-i-o-operations-advantage), it details that file I/O is a blocking operation at all times when using greenlets. Is this behavior desired and guaranteed for future releases, or is there a possibility that file I/O will become nonblocking in the future?

**Comment by arcivanov** [comment]
This is not a guarantee nor something that is provided by Gevent. This is a property of virtually all OS IO system calls that end up dealing with file-based descriptors. Gevent does nothing to assure that behavior.

**Comment by nscmcgrath** [comment]
Got it, makes sense. I will check the man pages for file io operations for the operating systems we are running on. I do see in the learn gevent documentation the following excerpt:

> the linux read man-page says:

> Many file systems and disks were considered to be fast enough that the implementation of O_NONBLOCK was deemed unnecessary. So, O_NONBLOCK may not be available on files and/or disks.

However, when referencing the [read man page](https://man7.org/linux/man-pages/man2/read.2.html) I could not find this excerpt. I will dig deeper and see what I can find. Thank you!

**Comment by jamadden** [comment]
`learn-gevent-socketio.readthedocs.io` is not maintained by this project.

See [gevent's own documentation on files, especially FileObjectPosix](http://www.gevent.org/api/gevent.fileobject.html). gevent does not monkey-patch the generic `open` function, and has no effect on files unless you use one of the gevent-specific APIs such as those. But as noted here and in that documentation, there's no such thing as non-blocking IO for regular files (hence `FileObjectThread`).
