### ISSUE TITLE
when killing gevent.greenlet during migration an exception is thrown

### ISSUE THREAD

**Issue by ayushpratap17** [gevent/gevent#1956]
My application uses gevent 22.10.2 tand greenlet 2.0.2

It is a TCP server which spawns 3 gevent.greenlets.
During disconnection flow when the code tries to kill the greenlets it throws an exception "Cannot convert greenlet.greenlet to gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop" 

It occurs occassionally, say 1 out of 10 times.

This is how I'm creating and killing greenlets.
```
//Create
routine = gevent.spawn(Routine)

//kill
if routine:
    if not routine.dead:
        routine.kill() // exception thrown from here
    routine = None
```
'Routine' is in 'sleep' when kill is called.
 
Perhaps I'm doing something wrong?

**Comment by jamadden** [comment]
Can you provide at least a  traceback and ideally a [short, self-contained example](http://sscce.org)? Otherwise it's just guesswork trying to figure out what's going on.

**Comment by jamadden** [comment]
I think this is the source of the problem:
```
File "/usr/local/lib/python3.9/site-packages/eventlet/hubs/poll.py", line 111, in wait
	listener.cb(fileno)
```

You appear to be mixing `eventlet` and `gevent` event loops. In very very simple cases, and if you only ever use `gevent.spawn_raw` that *might* sometimes work, but it is in no way a tested or supported configuration.

**Comment by jamadden** [comment]
I don't know what to tell you. Maybe you're not using `eventlet` but whatever server framework you're using is? At any rate, you either need to stop using `eventlet` or stop using `gevent`.

Good luck!
