### ISSUE TITLE
More tasks run faster?

### ISSUE THREAD

**Issue by dgrigonis** [gevent/gevent#1960]
2.8 GHz Quad-Core Intel Core i7
Big Sur   11.7.7
CPython 3.11.3
gevent    22.10.2

1000 tasks are always faster than 10 or 100 tasks. Anyone has any idea what is happening here?

```python
import gevent
import datetime as dt

N = 1000

def task(number):
    for i in range(100):
        gevent.sleep(0.01)


def main():
    start = dt.datetime.now()

    gevent.joinall([
        gevent.spawn(task, i) for i in range(N)
    ])

    runtime = (dt.datetime.now() - start).total_seconds()
    print(f'program executed in {runtime:.2f}s')


main()
```

```
# N  10     100     1000     10000
#    1.15   1.15    1.06     7.61s
```

**Comment by jamadden** [comment]
To a point, given more greenlets doing trivial stuff, you can get more overlapping of creating objects and sleeping. That is, more sleeping happens while you're doing other "useful" work.

**Comment by dgrigonis** [comment]
Good, as long as it's expected.
