### ISSUE TITLE
DeprecationWarning: pkg_resources is deprecated as an API

### ISSUE THREAD

**Issue by jfly** [gevent/gevent#1964]
* gevent version: 22.10.2 (from PyPI via pip)
* setuptools version: 68.0.0 (from PyPI via pip)
* Python version: 3.8.17 (from nixpkgs)
* Operating System: NixOS

<details>
<summary>pip freeze</summary>

```
$ pip freeze --all
gevent==22.10.2
greenlet==2.0.2
pip==23.0.1
setuptools==68.0.0
zope.event==5.0
zope.interface==6.0
```
</details>

### Description:

gevent uses `pkg_resources` in `gevent.events`: https://github.com/gevent/gevent/blob/22.10.2/src/gevent/events.py#L74

setuptools 67.5.0 deprecated `pkg_resources` in favor of importlib: https://github.com/pypa/setuptools/commit/a1aeda391a0c462ea53627bcdf50dd4c0daadaed

Here's a simple repro:

```python
$ PYTHONWARNINGS=error python -c 'import gevent.events'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jeremy/tmp/2023-06-28-pyhack-2/.direnv/python-3.8/lib/python3.8/site-packages/gevent/events.py", line 74, in <module>
    from pkg_resources import iter_entry_points
  File "/home/jeremy/tmp/2023-06-28-pyhack-2/.direnv/python-3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 118, in <module>
    warnings.warn(
DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
```

(We run our test suite with warnings treated as errors, which is how I noticed this.)

**Comment by jamadden** [comment]
Thanks for the report. This has been fixed in the upcoming gevent release.

**Comment by jfly** [comment]
Glad to here! Do you mind linking to the relevant commit?
