### ISSUE TITLE
Does it support python-zeep library? 

### ISSUE THREAD

**Issue by AzikDeveloper** [gevent/gevent#1977]
As the title says does it support python-zeep library?

**Comment by jamadden** [comment]
I have no idea what `python-zeep` is, I've never heard of it.  But if it's a networking library implemented using the standard `socket` (or `SSLSocket`) classes, then it _probably_ works fine when monkey-patched by gevent; most things do. If it's just a straightforward datastructure library or parsing library or something, then it shouldn't be affected by gevent at all --- just be aware of CPU intensive loops that don't allow other greenlets to have a chance to run.

Beyond that, I won't guess.

**Comment by AzikDeveloper** [comment]
[zeep](https://github.com/mvantellingen/python-zeep) is a Python SOAP client. 
I just found out that it uses requests library. But it also uses lxml library that uses c code. So I'm not sure if i should use gevent

**Comment by jamadden** [comment]
I see no reason not to give it a try --- just avoid its "AsyncTransport" via `httpx` and `asyncio`. That won't play nicely.

Good luck.
