### ISSUE TITLE
`gevent.select.select` is too strict on input arguments

### ISSUE THREAD

**Issue by Daverball** [gevent/gevent#1979]
* gevent version: 23.7.0 from PyPI
* Python version: 3.10.12 installed through OpenSUSE Tumbleweed
* Operating System: OpenSUSE Tumbleweed

### Description:

This is mostly a nitpick, but it has come up while trying to create type stubs for gevent.

gevent's implementation of `select` mandates that rlist/wlist/xlist are at the very least a `Collection` i.e. they need to be `Iterable`, but they also need to remain unchanged by iteration, since the argument gets passed unmodified to two different functions: the original select implementation (or a  wrapper on windows) and a `SelectResult.select` if the first call didn't already yield a result on one of the file descriptors.

The original implementation accepts an `Iterable`. So technically you would need to first copy each input argument into e.g. a tuple (or split into two iterables using `itertools.tee`, although the truthiness check on win32 would still be incorrect) if the input does not already implement a `__len__`.

I realize this change creates some small overhead, and as such it is not free, for something that should come up rarely, but on the flip side you could end up with some nasty, difficult to track down bugs in external libraries that rely on this part of the specification.

**Comment by jamadden** [comment]
While yes, the documentation of `select.select` does claim to accept iterables. But the CPython test suite doesn't actually test that iterables are accepted (at least not if they don't already have IO available)--- I say this because gevent runs the CPython `select` and `selectors` test suites when monkey-patched, and they pass.

I don't know when I will have any more time to do anything about this, but I'd be happy to review a PR that adds tests and fixes the problem by copying the inputs.

**Comment by Daverball** [comment]
I'm happy to take a stab at it.

I had a look at the C code for `select.select` just in case there were some undocumented gotchas, but it seems they just use `PySequence_Fast` on the inputs, which is essentially a no-op for lists/tuples and a conversion to a list for any other iterable, so it seems like it shouldn't actually introduce any appreciable overhead if we do something like the following at the start of the function:
```python
rlist = rlist if isinstance(rlist, (list, tuple)) else list(rlist)
wlist = wlist if isintsance(wlist, (list, tuple)) else list(wlist)
```
We can leave xlist as is, since it would only do something for the native `select.select` call anyways.
