### ISSUE TITLE
How to determine the saturation of the generated little green leaves

### ISSUE THREAD

**Issue by xpf629629** [gevent/gevent#1981]
I want to observe how long the green applet waits in the ready queue for the loop to be dispatched.
Because I want to determine if I am generating too many greenlets

**Comment by jamadden** [comment]
You'll have to track that yourself. Either use a subclass of Greenlet or adjust the functions you spawn.

**Comment by xpf629629** [comment]
Can you give me an example? An example that lets me know if a greenlet is scheduled to run as soon as the event is ready, please.

**Comment by jamadden** [comment]
It's entirely up to you of what you want to track and how you want to track it. The simple example [of subclassing](http://www.gevent.org/api/gevent.greenlet.html#subclassing-greenlet) probably looks something like this (from memory, untested):

```python
class MyGreenlet(Greenlet):
    def __init__(self, run=None, *args, **kwargs):
        self.created_at = time.time()
        self.ran_at = None
        self.__run = run
        super().__init__(None, *args, **kwargs)

    def _run(self, *args, **kwargs):
       self.ran_at = time.time()
       self.__run(*args, **kwargs)

greenlet = MyGreenlet.spawn(some_function, some_arg, another_arg, kwarg=42)
greenlet.join()

waiting_time = greenlet.ran_at - greenlet.created_at
```
