### ISSUE TITLE
Installing gevent 21.1.0 Error using command 'pypy setup.py install'

### ISSUE THREAD

**Issue by Luancem** [gevent/gevent#1986]
* gevent version: Please note how you installed it: From source, from
                  gevent-21.1.0.tar.gz
* Python version: Please be as specific as possible. For example,
                  pypy3.10
* Operating System: Please be as specific as possible. For example,
                  RedHat-4.8.5

### Description:
    Steps:
         1）tar -zxvf gevent-21.1.0.tar.gz
         2)  cd gevent-21.1.0/
         3) /home/***/pypy3.10 setup.py install

    I follow above procedures to install gevent. 
    Because my pc is offline, I used " /home/***/pypy3.10 setup.py install" to install gevent.
    But it reported Error "Download error on https://pypi.org/simple/: [Errno -2] name or service not known --some packages may not be founded!  No local packages or working download links found for gevent=21.1.0 "

     I am already download gevent-21.1.0.tar.gz in my directory and install offline. Why it also reports this error?
     How can I install it on my offline redhat os?
   
     Thanks in advance!

```python-traceback
Remember to put tracebacks in literal blocks
```

### What I've run:

**REPLACE ME**: Paste short, self contained, correct example code (See
http://sscce.org), tracebacks, etc, here

```python
"Put python code in python blocks"
```

**Comment by jamadden** [comment]
If you're going to attempt an offline installation, you'll need to gather all the dependencies necessary and install them as well. I'm sure there are plenty of tutorials online if you look --- gevent isn't unique here in any way, it's a bog standard build and installation process. 

One easy way is with `pip wheel`. That would go something like this:

1. On a system with Internet access and the same operating system and Python interpreter, download and extract the gevent source archive. I *strongly* recommend you use a more recent version of gevent. Change to the directory you extracted the source into. 
2. Run `<thepython> -m pip wheel -w <somedir> .`  where `<thepython>` is the correct Python interpreter, and `<somedir>` is the directory you want the output put into.
3. Copy `<somedir>` and all its contents onto your isolated machine.
4. On the isolated machine, run `<thepython> -m pip install -f <somedir> <somedir>/gevent*whl`, where again, `<thepython>` is the desired interpreter and `<somedir>` is the directory containing all the dependencies.

I probably don't have some of the details right, I'm working from memory, but like I said, you should find plenty of information online.

Good luck.
