### ISSUE TITLE
Vulnerability in gevent.pywsgi.WSGIServer

### ISSUE THREAD

**Issue by mukeran** [gevent/gevent#1989]
* gevent version: 23.7.0 (pypi)
* Python version: 3.8.15
* Operating System: Linux

### Description:

We found a vulnerability in gevent.pywsgi.WSGIServer. The detailed report has been sent to @jamadden 's email address.

**Comment by jamadden** [comment]
Thank you for your interest in gevent and your bug report. While `gevent.pywsgi` [has *never* been advertised as an Internet-facing, production-ready implementation](https://github.com/gevent/gevent/issues/1832) and [users have been advised to use something that is, like `gunicorn`](https://flask.palletsprojects.com/en/2.3.x/deploying/gevent/), or at the very least a reverse proxy, I will prioritize a fix for this issue.

**Comment by jamadden** [comment]
gevent 23.9 has been released with tests and a fix for this. Thank you again for the report.

**Comment by mukeran** [comment]
@jamadden Hi. Sorry for my late response and thanks for your quick fix. Here's a request:
According to MITRE's email, if I want to make the CVE public, I have to modify the description of this issue with the (negative) detail of this vulnerability.
Is it OK to replace my description with details of the vulnerability since the issue has been fixed?

**Comment by jamadden** [comment]
I don't see why not; [the release notes](http://www.gevent.org/changelog.html#id2) already include a summary.

**Comment by mukeran** [comment]
OK, thanks.
