### ISSUE TITLE
ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 40 from PyObject 

### ISSUE THREAD

**Issue by IamJasonBoy** [gevent/gevent#1991]
我知道 gevent和greenlet包之间依赖有了不兼容问题，那么请作者可以在setup.py
打包成PYPI包的时候对包兼容锁定一下版本呢

我现在 两个包都使用最新的 还是报错  降级gevent就好了

为了大家良好的使用 请对版本明示一下

**Comment by jamadden** [comment]
That error means you are using greenlet compiled one way on an interpreter compiled another way. Compile both the same.
