### ISSUE TITLE
Fail to install v23.9.0 - tries to build from source instead of pre-compiled wheel

### ISSUE THREAD

**Issue by rpmcginty** [gevent/gevent#1993]
* gevent version: **23.9.0** from PyPI (as unpinned dependency on `gevent`)
* Python version: CPython 3.9.? (from AWS CodeBuild Ubuntu Standard:5 image)
* Operating System: installed in container from [AWS CodeBuild's Ubuntu Standard:5 Image](https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/5.0/Dockerfile) (Ubuntu 20.04) on a generic EC2 linux-x86_64 machine
  
### Description:

The latest `gevent` release (23.9.0) is failing to build for python 3.9 on this [aws/codebuild/standard:5.0](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html) image. We have an indirect dependency through another package `cloud-files` which has an unpinned dependency on `gevent`. 

**v23.7.0 (PASS)**
```
#12 23.47 Collecting gevent (from cloud-files~=4.15->-r requirements-docker.txt (line 4))
--
4772 | #12 23.47   Obtaining dependency information for gevent from https://files.pythonhosted.org/packages/84/04/5a4ee24bb71a4bdd4c1f173c5d74bf963d2c4d01ed387d639cfd248514f6/gevent-23.7.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
4773 | #12 23.48   Downloading gevent-23.7.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
```

**v23.9.0 (FAIL)**: downloads tar.gz source from pypi and installs source by default
```
4422 | #12 23.31 Collecting gevent (from cloud-files~=4.15->-r requirements-docker.txt (line 4))
--
4423 | #12 23.33   Downloading gevent-23.9.0.post1.tar.gz (5.8 MB)
#12 23.35      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 278.2 MB/s eta 0:00:00
--
4425 | #12 23.86   Installing build dependencies: started
4426 | #12 27.11   Installing build dependencies: finished with status 'done'
4427 | #12 27.11   Getting requirements to build wheel: started
4428 | #12 29.29   Getting requirements to build wheel: finished with status 'done'
4429 | #12 29.29   Installing backend dependencies: started
4430 | #12 29.84   Installing backend dependencies: finished with status 'done'
4431 | #12 29.84   Preparing metadata (pyproject.toml): started
4432 | #12 30.53   Preparing metadata (pyproject.toml): finished with status 'done'
....
12233 |#12 36.99   Building wheel for gevent (pyproject.toml): started
--
12234 | #12 38.67   Building wheel for gevent (pyproject.toml): finished with status 'error'
12235 | #12 38.70   error: subprocess-exited-with-error
12236 | #12 38.70
12237 | #12 38.70   × Building wheel for gevent (pyproject.toml) did not run successfully.
12238 | #12 38.70   │ exit code: 1
12239 | #12 38.70   ╰─> [344 lines of output]
...
12519 | #12 38.70       running build_ext
--
12520 | #12 38.70       generating cffi module 'build/temp.linux-x86_64-cpython-39/gevent.libuv._corecffi.c'
12521 | #12 38.70       creating build/temp.linux-x86_64-cpython-39
12522 | #12 38.70       Running '(cd  "/tmp/pip-install-erth84_2/gevent_60d4e7e1e6d7425492946b23b1f4d8e7/deps/libev"  && sh ./configure -C > configure-output.txt )' in /tmp/pip-install-erth84_2/gevent_60d4e7e1e6d7425492946b23b1f4d8e7
12523 | #12 38.70       configure: error: in `/tmp/pip-install-erth84_2/gevent_60d4e7e1e6d7425492946b23b1f4d8e7/deps/libev':
12524 | #12 38.70       configure: error: no acceptable C compiler found in $PATH
12525 | #12 38.70       See `config.log' for more details
```

The problem seems to be that the setuptools is downloading a tar.gz source instead of the wheel. That leads to building the actual package which causes the failure. When comparing the PyPi wheels of >v23.9.0 and 23.7.0, I do not see wheels for the `manylinux2014_x86_64` or `manylinux_2_17_x86_64`

Summary of Notes:
* 23.9.0 is building source when installing. Cannot find wheel for ubuntu 20.04 
* last known passing build of `gevent` is version = **23.7.0**
* we are building on aws codebuild ubuntu standard:5 image.

**Comment by rpmcginty** [comment]
Looking at the [PyPi package `23.9.0.post1`](https://pypi.org/project/gevent/23.9.0.post1/#files), under "Download files", I can't find wheels for `manylinux2014_x86_64`, only for `manylinux_2_28_x86_64`. Is this expected?

links: https://github.com/pypa/manylinux

**Comment by rpmcginty** [comment]
Hmm, but I see that some architectures for `manylinux2014*` are still available though. So why do you support some but not all of the builds? Based on info in https://github.com/pypa/manylinux, seems like `manylinux2014*` End of Life (EOL) is only June 30th, 2024. Can you explain why you dropped support based on possible miscompilation? Seems like a pretty big drop in support. 

One reason this could become problematic is that amazon's Amazon Linux 2 (EOL in 2025) is a flavor of CentOS 7 - thus supporting only `manylinux2014_x86_64` platform tag. So anything that builds with these standard images, could run into issues when compiling the source code (let alone waiting for compilation to complete).

**Comment by rpmcginty** [comment]
@jamadden I see the [commit](https://github.com/gevent/gevent/commit/74ef8762bbd5404f9423723c1e76d7496d14f2b8) that drops `manylinux2014_x86_64` support. Is it solely because of failures with python 3.12 compatibility? It is necessary to drop support for `manylinux2014_x86_64` for all other python versions < 3.12?

**Comment by alicederyn** [comment]
Looks like gevent 23.9.1 now has `manylinux2014_x86_64` wheels again. This appears to be due to https://github.com/gevent/gevent/commit/ca0f9cb7b43b37384d7c291401eab8e79cacbdfd.
