### ISSUE TITLE
Bad use of gevent: the Thread has created before patch_all, is_alive() always True

### ISSUE THREAD

**Issue by yaokuku123** [gevent/gevent#2011]
* gevent version: gevent-21.12.0
* Python version: Python 3.8.17 
* Operating System: Darwin

### Description:
Hi,Dear developer. 
When I study gevent, I found a problem.  I defined a Thread before monkey.patch_all(), then I used the Thread to run a function. after the function down, is_alive() always True. I did not know what happen about that. 

case1: when I set Daemon is False. error:gevent.hub.LoopExit: This operation would block forever.
case2: when I set Daemon is True. I could not find any error, but is_alive() was True.

```python
import threading
from gevent import monkey

class MyThread(threading.Thread):
    pass

monkey.patch_all()

def my_function():
    print('my_func:', threading.current_thread().ident)
    return "Result"

t = MyThread(target=my_function)
t.setDaemon(True)
t.start()
t.join(3)
print(t.is_alive())      # True
```

**Comment by yaokuku123** [comment]
I known bad use of gevent, but I want to know why this happen. Thank you very much.

**Comment by wangyf123** [comment]
If you use the native thread,  you should not path the thread. Below maybe run well:
`from gevent import monkey
monkey.patch_all(thread=False)
import threading

class MyThread(threading.Thread):
    pass



def my_function():
    print('my_func:', threading.current_thread().ident)
    return "Result"

t = MyThread(target=my_function)
t.setDaemon(True)
t.start()
t.join()
print(t.is_alive()) `

**Comment by arcivanov** [comment]
The monkey-patching should occur first virtually always. It's not an issue with Gevent, it's the issue of you not following the documentation on how monkey-patching should work.
