### ISSUE TITLE
Test units with 0 ran tests (skipped) exit with code 5 on Python 3.12

### ISSUE THREAD

**Issue by bnavigator** [gevent/gevent#2012]
* gevent version: 23.9.1
* Python version: 3.12.1 from openSUSE Tumbleweed rpm
* Operating System: openSUSE Tumbleweed Linux openbuildservice (primarily x86_64)

### Description:

When running the test suite on the opensuse build service for checking the rpm package, there is a change of behavior from Python 3.11 to 3.12:

Test units which have all tests in it skipped, e.g. due to no network resources, the unit exits with code 5, causing the whole suite to fail.

```python-traceback
[   89s] + export PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-gevent-23.9.1-0.x86_64/usr/lib64/python3.12/site-packages
[   89s] + PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-gevent-23.9.1-0.x86_64/usr/lib64/python3.12/site-packages
[   89s] + python3.12 -m gevent.tests --ignore skip_tests.txt -u-network --verbose --processes 12
[   89s]         GEVENTTEST_QUIET       =       False
[   89s] GEVENTTEST_USE_RESOURCES       =       -network
[   89s]          GEVENT_RESOLVER       =       thread
[   89s]            PYTHONDEVMODE       =       1
[   89s]       PYTHONFAULTHANDLER       =       true
[   89s]           PYTHONHASHSEED       =       0
[   89s]               PYTHONPATH       =       /home/abuild/rpmbuild/BUILDROOT/python-gevent-23.9.1-0.x86_64/usr/lib64/python3.12/site-packages
[   89s]           PYTHONWARNINGS       =       default,default::DeprecationWarning,default::ResourceWarning,ignore:::site:,ignore:::pkgutil:,ignore:::importlib._bootstrap:,ignore:::importlib._bootstrap_external:,ignore:::pkg_resources._vendor.pyparsing:,ignore:::dns.namedict:,ignore:::dns.hash:,ignore:::dns.zone:

...
[   93s] | GEVENTTEST_USE_RESOURCES=-network /usr/bin/python3.12 -u -mgevent.tests.test__monkey_futures_thread
[   93s]   s
[   93s]   ----------------------------------------------------------------------
[   93s]   Ran 0 tests in 0.000s
[   93s]   
[   93s]   NO TESTS RAN (skipped=1)
[   93s] 
[   93s] ! GEVENTTEST_USE_RESOURCES=-network /usr/bin/python3.12 -u -mgevent.tests.test__monkey_futures_thread [code 5] [Ran 0 tests in 0.1s (skipped=1)]
...
[  133s] 2/67 unexpected failures
[  133s]  - GEVENTTEST_USE_RESOURCES=-network /usr/bin/python3.12 -u -mgevent.tests.test__monkey_futures_thread
[  133s]  - GEVENTTEST_USE_RESOURCES=-network /usr/bin/python3.12 -u -m unittest gevent.tests.test__core_callback gevent.tests.test__core_stat gevent.tests.test__core_timer gevent.tests.test__core_watcher gevent.tests.test__destroy_default_loop gevent.tests.test__event
[  133s] 
[  133s] Ran 3618 tests (skipped=870) in 67 files in 00:44
[  133s] error: Bad exit status from /var/tmp/rpm-tmp.QCoHIf (%check)
```

#### Python 3.12
Example using the APPVEYOR skip in test__backdoor:

```
abuild@skylab:~/rpmbuild/BUILD/gevent-23.9.1> export PYTHONPATH=~/rpmbuild/BUILDROOT/python-gevent-23.9.1-0.x86_64/usr/lib64/python3.12/site-packages/
abuild@skylab:~/rpmbuild/BUILD/gevent-23.9.1> GEVENTTEST_USE_RESOURCES=-network /usr/bin/python3.12 -u -mgevent.tests.test__backdoor 
......
----------------------------------------------------------------------
Ran 6 tests in 0.220s

OK
abuild@skylab:~/rpmbuild/BUILD/gevent-23.9.1> echo $?
0
abuild@skylab:~/rpmbuild/BUILD/gevent-23.9.1> export APPVEYOR=1
abuild@skylab:~/rpmbuild/BUILD/gevent-23.9.1> GEVENTTEST_USE_RESOURCES=-network /usr/bin/python3.12 -u -mgevent.tests.test__backdoor 
ssssss
----------------------------------------------------------------------
Ran 0 tests in 0.000s

NO TESTS RAN (skipped=6)
abuild@skylab:~/rpmbuild/BUILD/gevent-23.9.1> echo $?
5
```

#### Python 3.11
```
abuild@skylab:~/rpmbuild/BUILD/gevent-23.9.1> export PYTHONPATH=~/rpmbuild/BUILDROOT/python-gevent-23.9.1-0.x86_64/usr/lib64/python3.11/site-packages/
abuild@skylab:~/rpmbuild/BUILD/gevent-23.9.1> GEVENTTEST_USE_RESOURCES=-network /usr/bin/python3.11 -u -mgevent.tests.test__backdoor 
......
----------------------------------------------------------------------
Ran 6 tests in 0.218s

OK
abuild@skylab:~/rpmbuild/BUILD/gevent-23.9.1> echo $?
0
abuild@skylab:~/rpmbuild/BUILD/gevent-23.9.1> export APPVEYOR=1
abuild@skylab:~/rpmbuild/BUILD/gevent-23.9.1> GEVENTTEST_USE_RESOURCES=-network /usr/bin/python3.11 -u -mgevent.tests.test__backdoor 
ssssss
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK (skipped=6)
abuild@skylab:~/rpmbuild/BUILD/gevent-23.9.1> echo $?
0
```

**Comment by bnavigator** [comment]
They sneaked that into the documentation without a clear indication that it is new:

https://docs.python.org/3.12/library/unittest.html#unittest.main
> An exit code of 5 indicates that no tests were run or skipped.

Which doesn't seem hold true for the above examples. There were 6 tests skipped, yet the exit code is 5.

**Comment by jamadden** [comment]
Yeah, that's an annoying change [that bit me too](https://github.com/gevent/gevent/commit/86ea07e273ed7938446688cef5492d48034b7ddb#diff-3e1e38609c019123040816bb04ac207b135fbe0de6c7d8c26af3a581b3c91bf2). But gevent's behaviour here is exactly what the stdlib does --- it uses `unittest.main()`, tests are standard `unittest.TestCase` subclasses, etc.

For example, `test__backdoor.py`, like most or all test files, has the standard invocation block that gets run by `python -m gevent.tests.test__backdoor`:

https://github.com/gevent/gevent/blob/305b919188215dcee09a27af855c15492e3a7cff/src/gevent/tests/test__backdoor.py#L170-L171

`greentest` is imported above:

https://github.com/gevent/gevent/blob/305b919188215dcee09a27af855c15492e3a7cff/src/gevent/tests/test__backdoor.py#L8

But `greentest.main` is just an alias for `unittest.main`:

https://github.com/gevent/gevent/blob/305b919188215dcee09a27af855c15492e3a7cff/src/gevent/testing/__init__.py#L139

**Comment by jamadden** [comment]
As the link to the commit implies, if you use the testrunner provided by `gevent`, instead of running the individual files, we compensate for this: `python -m gevent.tests gevent.tests.test__backdoor` should have consistent exit codes across versions.

**Comment by bnavigator** [comment]
As the first code block shows, The `gevent` testrunner *is* used. The return code handling is just not yet released. Thanks for pointing out that this is already fixed.

**Comment by jamadden** [comment]
That was the first of two commits; a second followup commit was needed to handle some cases. I just pointed to that one because it had the bulk of the changes.

**Comment by bnavigator** [comment]
Yeah sorry, I didn't realize they were that easy to find in the commit log.
