### ISSUE TITLE
Feature request - Queue.abort()

### ISSUE THREAD

**Issue by davidkhess** [gevent/gevent#2016]
Would like to make a feature request for the Queue class: the ability to throw errors to all greenlets that may be waiting on a Queue.put() or Queue.get() on that queue and to any future calls to those two APIs on that particular Queue instance.

The use case is a Queue might be part of a more complicated structure of gevent resources stitched together to accomplish a task. If an error occurs (say a greenlet dies or a resource like a serial port closes), the simplest way to recover is to just tear it all down and rebuild it again. For that to happen cleanly without leaking resources, we need a way to cause all current greenlets waiting on get()s or put()s and any future calls to those methods to return an error.

The workaround I'm using at the moment is using getcurrent() to track every greenlet that is entering a potentially blocking Queue.get() or Queue.put() call and then iterating over that list and kill()ing them.

**Comment by davidkhess** [comment]
I'm running into an issue with this strategy. When I kill one of the greenlets waiting on Queue.get(), it terminates but the greenlet that made the call to Greenlet.kill() never comes out of the kill call.

**Comment by jamadden** [comment]
Luckily, Python 3.13 added `Queue.shutdown` and `gevent.queue.Queue` has picked that up for all versions.

**Comment by davidkhess** [comment]
Nice. Thank you!
