### ISSUE TITLE
AssertionError: Thread.__init__() not called

### ISSUE THREAD

**Issue by wilson3q** [gevent/gevent#2020]
* gevent version: 23.9.1
* Python version: 3.12.2
* Operating System: Linux

### Description:

The following assertion failure after upgrading to python 3.12.2. Please take a look at the threading monkey patch. I have reported a similar issue to [python dev](https://github.com/python/cpython/issues/115121).

```
Exception ignored in: <function _after_fork at 0x7f04dd0b0400>
Traceback (most recent call last):
  File "/home/scm/lib/python3.12/threading.py", line 1691, in _after_fork
    thread._set_tstate_lock()
  File "/home/scm/lib/python3.12/threading.py", line 1051, in _set_tstate_lock
    if not self.daemon:
           ^^^^^^^^^^^
  File "/home/scm/lib/python3.12/threading.py", line 1246, in daemon
    assert self._initialized, "Thread.__init__() not called"
AssertionError: Thread.__init__() not called
```

### What I've run:

I was running gevent together with gunicorn to provide rest services. Never have issues before python 3.12.2.

In _DummyThread definition, super init was not called, which caused assertion failures.

```
def __init__(self): # pylint:disable=super-init-not-called
        #_DummyThread_.__init__(self)
```

**Comment by serhiy-storchaka** [comment]
Also note that the code in 3.13 is different from 3.12, so it may be broken again.

**Comment by mashley310** [comment]
I'm also seeing this issue after upgrading from python 3.11.7 to 3.11.8.
