### ISSUE TITLE
Deprecation warning for os.fork on Python 3.12

### ISSUE THREAD

**Issue by elishagreenwald** [gevent/gevent#2052]
* gevent version: pypi ==24.2.1
* Python version: 3.12.5
* Operating System: Docker image `python:3.12.5-bookworm` (debian)

### Description:

I'm seeing a deprecation warning when running gevent (via gunicorn) on python 3.12.5. It seems this warning was added in python 3.12 (see [here](https://github.com/python/cpython/pull/109767) for more details)

The warning says:

`/usr/local/lib/python3.12/site-packages/gevent/os.py:426: DeprecationWarning: This process (pid=17) is multi-threaded, use of fork() may lead to deadlocks in the child.`

I'm happy to provide more details but my question is, is this a known issue and is there anything to worry about?

Thanks!

**Comment by arcivanov** [comment]
This is unrelated to gevent or gunicorn. Forking in Python will cause this deprecation warning and there is a plan, I believe, to kill `os.fork` entirely.

**Comment by elishagreenwald** [comment]
> This is unrelated to gevent or gunicorn. Forking in Python will cause this deprecation warning and there is a plan, I believe, to kill `os.fork` entirely.

Ok thank you. So in other words, it's something else in my project that's calling os.fork? But gunicorn or gevent aren't making the fork call?

**Comment by arcivanov** [comment]
Well, gevent itself doesn't call anything related to forking AFAIR. Gunicorn - maybe.

**Comment by jamadden** [comment]
The next release of gevent silences those warnings when `gevent.os.fork` is called. It is not a new problem, it's a well understood issue going back decades, and this new warning added no benefit other than making it harder to read test output.

**Comment by elishagreenwald** [comment]
Thank you for the response and for maintaining this library! I just upgraded to gevent `24.10.1` but I'm still seeing:

```
/usr/local/lib/python3.12/site-packages/gevent/os.py:431: DeprecationWarning: This process (pid=18) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = fork()
```

**Comment by jamadden** [comment]
Because that's `fork_and_watch`, not just `fork` :) The only one that was cluttering the test output enough to bother with was the pure `fork`...

**Comment by elishagreenwald** [comment]
Thanks @jamadden! I don't see any calls in my application code or in the dependencies calling `fork_and_watch` is it just gevent internally calling `fork_and_watch`? And if it's gevent can I assume its doing things safely and I can just ignore these warnings?
