### ISSUE TITLE
No 24.10.1 source tarball on pypi

### ISSUE THREAD

**Issue by opoplawski** [gevent/gevent#2063]
### Description:

There is no source tarball for 24.10.1 on pypi.  Is this coming soon?  Oversight?  Thanks for cutting a new release though!

**Comment by RitchiS99** [comment]
Having more or less the same issue. Poetry is finding the new version of gevent (24.10.1) when running `poetry update` but cant install it: "Unable to find installation candidates for gevent (24.10.1)"

**Comment by benoit-cty** [comment]
Same here. We pin to previous version as a workaround.

**Comment by jamadden** [comment]
I can't win. If I upload the tarball before all the wheels are finished building, people complain they have to build from source. If I wait until all the wheels are built, people complain the source isn't available. 

tarball has been uploaded.
