### ISSUE TITLE
return in finally swallows exceptions

### ISSUE THREAD

**Issue by iritkatriel** [gevent/gevent#2073]
In https://github.com/gevent/gevent/blob/07d2b7e4a3c5881e0a3637062b3c7c7c0027971c/src/gevent/_ffi/loop.py#L226  there is a `return` statement in a `finally` block, which would swallow any in-flight exception.

This means that if an unhandled exception (including a `BaseException` such as `KeyboardInterrupt`) is raised from the `try` body, it will not propagate on as expected.

If the intention is to suppress all exceptions, I would propose to make this clear by using `except BaseException`.

See also https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions.

**Comment by jamadden** [comment]
No thank you. We're already specifically in an error handler. _Nothing_ is supposed to propagate from here because it's simply not safe at the C level.

**Comment by jamadden** [comment]
LWN [provides some context](https://lwn.net/Articles/1000635/) and links to the [related report](https://github.com/iritkatriel/finally/blob/main/README.md). I think gevent must be the "one [that] said that they intend to swallow all exceptions" 😄
