### ISSUE TITLE
Not compatible with Cython 3.1 due to Py2 code

### ISSUE THREAD

**Issue by scoder** [gevent/gevent#2076]
Cython 3.1 removes Py2 support, but gevent still has Py2 code in its code base, e.g.

https://github.com/gevent/gevent/blob/07d2b7e4a3c5881e0a3637062b3c7c7c0027971c/src/gevent/libev/corecext.pyx#L64-L69

This leads to build failures for users who have Cython 3.1 installed, as described in

https://github.com/cython/cython/issues/6490

A quick fix would be to exclude Cython 3.1 from the build dependencies:

https://github.com/gevent/gevent/blob/07d2b7e4a3c5881e0a3637062b3c7c7c0027971c/pyproject.toml#L21

However, since Python 2.x support seems no longer intended for gevent, removing the Py2 left-overs seems the best path forward.

**Comment by aramhuseiny** [comment]
Is there any fix for this issue?
I have same error on installing gevent=21.8.0. I try to install odoo 17 CE. Python version is 3.10.12.

```      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef tuple integer_types
      
      if sys.version_info[0] >= 3:
          integer_types = int,
      else:
          integer_types = (int, long)
                                ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:60:26: undeclared name not builtin: long```

**Comment by jamadden** [comment]
> Is there any fix for this issue?

The fix right now is: Don't use an alpha version of Cython.

**Comment by aramhuseiny** [comment]
I'm using a stable version. It is not alpha version.

**Comment by jamadden** [comment]
>> Is there any fix for this issue?

> The fix right now is: Don't use an alpha version of Cython.

If for some reason you cannot opt-out of alpha versions of software, then, because gevent's sdist ships with all the needed .c files and thus does not actually require Cython to be available (at least on already-supported versions of Python), you can instruct your installer to ignore `pyproject.yaml`. With pip, that's `--no-build-isolation` (and/or `--no-use-pep517`).

**Comment by jamadden** [comment]
> I'm using a stable version. It is not alpha version.

No, you're not. This bug report is only applicable to using an alpha version of Cython. The gevent version is immaterial.

**Comment by aramhuseiny** [comment]
Is python 3.10.12 is alpha version? I'm confused.

**Comment by jamadden** [comment]
No, CYTHON 3.1 is alpha. Normally, installers don't automatically pick alpha versions of dependencies, but yours apparently is. If you're using `pip` that's the `PIP_PRE` environment variable or the `--pre` argument. (There are other ways, but those are the most common and only ones I know of that impact build-time dependencies.)

**Comment by oerp-odoo** [comment]
> > I'm using a stable version. It is not alpha version.
> 
> No, you're not. This bug report is only applicable to using an alpha version of Cython. The gevent version is immaterial.

What do you mean, `gevent` version does not matter?

If you use this gevent version: https://github.com/gevent/gevent/blob/21.8.0/pyproject.toml

I see there is `"Cython >= 3.0a9",` dependency. So it looks like gevent depends on alpha Cython version there. And I have the same problem, because I am not installing `cython` directly, it is being installed using `gevent`. 

Or it should still use "stable" version even if minimum dependency is alpha?

**Comment by ap-wtioit** [comment]
@aramhuseiny, @oerp-odoo for Odoo CE 17.0 you can use the same patch as we are preparing in doodba change the gevent to 22.10.2 and greenlet to 2.0.2 in Odoo's requirements.txt (currently already used for python3.11 we also use it now for python 3.10 as well)

**Comment by jamadden** [comment]
@oerp-odoo Good point, I forgot there was a time when adding support for a new version of Python required an unreleased version of Cython. But that's been over three years ago, so I'm not beating myself up about it 🤷 

Obviously I can't do anything about already-released versions.

**Comment by Hongze-Wang** [comment]
Hello, I have already tried python 3.9.13, python3.10.11, python 3.10.13, Cython 3.0.11, 3.0a6, all failed with this error, I can't find a way to install gevent.

**Comment by jamadden** [comment]
Only certain old versions of gevent (for example, 23.7) will implicitly opt-in to Cython 3.1a1; use a newer gevent version that doesn't have that problem (for example, 23.9). If you _want_ to use Cython 3.1a1, then you need gevent 24.11.1 (or the code in git).

**Comment by Hongze-Wang** [comment]
> Only certain old versions of gevent (for example, 23.7) will implicitly opt-in to Cython 3.1a1; use a newer gevent version that doesn't have that problem (for example, 23.9). If you _want_ to use Cython 3.1a1, then you need gevent 24.11.1 (or the code in git).

**Comment by Hitsaa** [comment]
I was also facing same issue while installing odoo17 on my local system. My ubuntu version is 22.04 and Python version is 3.10.12
To resolve the issue, 
first I installed cython 3.0.11 as gevent depends on cython.
Then I edited requirements.txt file in odoo17 and changed the versions like as follows

dependency           existing version               new version 
gevent                        21.8.0                                   24.2.1
greenlet                       1.1.2                                    2.0.2

and then re-installed dependencies using `pip install -r requirements.txt` and it got resolved.

**Comment by owl-with-beard** [comment]
I was really struggeling to install gevent. As we are working on old 32bit embeded systems and Python3.9, everything is rather wonky.
I got it to work by installing:

> pip3 install Cython==3.0.11
> pip3 install greenlet==2.0.2
> pip3 install gevent==22.10.2 --no-build-isolation

gevent 23 started requiring greenlet 3 (which in turn [requires some baseline features of compilers](https://greenlet.readthedocs.io/en/stable/changes.html#a1-2023-06-21) to build), so we stuck with 22.10.2 until we update the whole pipeline and the Python version.

Thank you all for the help and hints !
