### ISSUE TITLE
gevent.socket.getaddrinfo does not parse /etc/hosts

### ISSUE THREAD

**Issue by denik** [gevent/gevent#21]
<b>What steps will reproduce the problem?</b>
1. add a host alias to /etc/hosts that contains dots
2. call gevent.socket.getaddrinfo(host alias)

<b>What is the expected output? What do you see instead?</b>

Expected the host to resolve to the ip entered in /etc/hosts
Instead get DNSError(3, 'name does not exist')

The problem is is that gevent.socket.getaddrinfo does not implement parsing
of /etc/hosts at all. Later versions of libevent have async getaddrinfo
that gevent should use (see issue #16), but on the older versions of
libevent we should parse /etc/hosts ourselves.

<p><a href="http://code.google.com/p/gevent/issues/detail?id=21">Reported by Denis.Bilenko.</a></p><hr/><h2>earlier comments</h2>
<p><strong>drprofessor said, at 2010-06-25T23:02:18.000Z:</strong></p>

<p>I made a quick change to dns.py to get this working as it was preventing me from testing an application I'm building that makes requests to a locally run webserver whose host is faked in /etc/hosts. Here it is in case anyone needs a fix before gevent works with libevent 2. I'm sure it has issues as I'm new to Python (for one, it won't work on Windows).</p><p><strong>Denis.Bilenko said, at 2011-04-07T08:33:38.000Z:</strong></p>

<p>The trunk now uses c-ares which handles /etc/hosts and /etc/resolv.conf
https://bitbucket.org/denis/gevent/changeset/9d3a45d85486</p><p><strong>Denis.Bilenko said, at 2011-06-08T10:13:51.000Z:</strong></p>

<p>Issue 87 has been merged into this issue.</p><p><strong>Denis.Bilenko said, at 2011-12-29T09:28:53.000Z:</strong></p>

<p>Issue 110 has been merged into this issue.</p><p><strong>arab.gawen said, at 2012-04-24T13:54:42.000Z:</strong></p>

<p>Same problem with gevent 0.13.6 (currently last version) installed through PyPI. I think c-ares is not used.

Here's a patch I did to make it work. I modified the comment #2's dns.py

Changelog:
- FIRST check host file, and if still unresvoled, THEN check online
- FIX: if line was malformed (i.e. blank, no IPv4, syntax error, ...), crashed.</p><p><strong>Denis.Bilenko said, at 2012-04-24T14:37:35.000Z:</strong></p>

<p>c-ares is used starting with 1.0 version which is currently in beta.

Please get it from http://code.google.com/p/gevent/downloads/list</p><p><strong>arab.gawen said, at 2012-04-24T14:57:32.000Z:</strong></p>

<p>It works with 1.0b2. Thanks !</p><p><strong>bob@veznat.com said, at 2012-04-24T16:10:34.000Z:</strong></p>

<p>Understanding that this patch will not be applied I want to comment that not supporting IPv6 in 2012 is not ok. Please stop writing code that uses inet_aton and use inet_pton instead. IPv6 and this API (RFC 2133) have been around for over a decade.</p><p><strong>arab.gawen said, at 2012-04-24T16:21:58.000Z:</strong></p>

<p>My bad, I just copied/pasted & fixed the comment #2's dns.py without paying attention of inet_aton and its deprecation. Call it "patch-of-extreme-urgency-that-can-save-you-a-sleepless-night".</p>

**Comment by jamadden** [comment]
According to my tests, current master/1.1a2 on Python 2.7.10 and 3.4.3 is returning results from /etc/hosts with both the threaded and c-ares resolvers. If someone still has a system configuration where that's not the case please let us know.
