### ISSUE TITLE
Popen returns pipes that don't support O_NONBLOCK

### ISSUE THREAD

**Issue by dekkers** [gevent/gevent#222]
Popen from the gevent subprocess module returns pipes that don't support non-blocking mode. The following example demonstrates the problem:

``` python
import sys, os, fcntl, subprocess, select
from gevent import monkey

monkey.patch_all(subprocess=False)

p = subprocess.Popen([sys.executable, '-c',
                      'import time,sys;print "test";sys.stdout.flush();time.sleep(10)'],
                     stdout=subprocess.PIPE)
fcntl.fcntl(p.stdout, fcntl.F_SETFL, os.O_NONBLOCK)
select.select([p.stdout], [], [])
print p.stdout.read(1024)
```

Without monkey patching subprocess the code doesn't block, removing subprocess=False causes it to block. The reason is that p.stdout is a FileObjectPosix object instead of a normal File object and calling fcntl on the FileObjectPosix object doesn't really change anything: the underlying file descriptor is already non-blocking.

I don't really know what the right way to fix this is. We could add support for non-blocking I/O to FileObjectPosix, but that doesn't seem easy. The other option would be to change Popen to return normal File objects instead of FileObjectPosix objects.

**Comment by jamadden** [comment]
The implementation has changed substantially since this was written, but the basic issue remains. I've added clarifying remarks to the documentation, to wit:

>  Although this object provides a fileno() method and so can itself be passed to fcntl.fcntl(), setting the os.O_NONBLOCK flag will have no effect; likewise, removing that flag will cause this object to no longer be cooperative.

A workaround is to use `p.stdout.fileio`; that (undocumented!) object by definition is already in non-blocking mode. You'd get out of sync with any buffering performed at higher levels, though, and it only works in bytes mode.

**Comment by jamadden** [comment]
I can imagine a workaround that involves a monkey-patch on `fcntl`. It's not especially pretty, but if there's demand for it (and especially if there's a quality PR) it's something we can consider. (It's too late for 1.1.0 though, maybe for 1.2.0.)

**Comment by kolis** [comment]
Same problem here
