### ISSUE TITLE
PyPy support

### ISSUE THREAD

**Issue by eallik** [gevent/gevent#248]
As per the discussions on #pypy @ irc.freenode.org, it's been reported that `pypycore` runs successfully, with minor as of yet unfixed bugs, on PyPy 2.0 dev and is able to outperform `gevent` on CPython in some benchmarks by a factor of 2.

So in general, could we hope for a future direction of the adaptations in `pypycore` becoming an integral part of `gevent`? Something comparable to how `gevent-zeromq` has become part of `pyzmq` in recent versions (http://zeromq.github.com/pyzmq/api/zmq.green.html#module-zmq.green).

This would, in the future, give us an awesome stack of gevent and ZeroMQ running on PyPy with the currently under development but functional JIT compilation support for `continulet` based stacks (which include `greenlet` and `stackless`), easily on par in its potential with the success of Node.js.

**Comment by jamadden** [comment]
I've been working on fixing the remaining tests in my branch at https://github.com/NextThought/gevent. (with much thanks to the earlier semaphore commit from @parasyte among others). Currently under PyPy nightly, I'm down to 14 failures and still whittling away; notably, most of the non-SSL server tests pass: 

```
14/123 tests failed in 03:31

11/123 expected failures
 - //pypy-c-jit-76386-58059c786617-osx64/bin/pypy -u test___example_servers.py
 - //pypy-c-jit-76386-58059c786617-osx64/bin/pypy -u -m monkey_test test_ssl.py
 - //pypy-c-jit-76386-58059c786617-osx64/bin/pypy -u -m monkey_test --Event test_ssl.py
 - //pypy-c-jit-76386-58059c786617-osx64/bin/pypy -u -m monkey_test test_subprocess.py
 - //pypy-c-jit-76386-58059c786617-osx64/bin/pypy -u -m monkey_test --Event test_subprocess.py
 - //pypy-c-jit-76386-58059c786617-osx64/bin/pypy -u -m monkey_test test_socket.py
 - //pypy-c-jit-76386-58059c786617-osx64/bin/pypy -u -m monkey_test --Event test_socket.py
 - //pypy-c-jit-76386-58059c786617-osx64/bin/pypy -u test__ares_host_result.py
 - //pypy-c-jit-76386-58059c786617-osx64/bin/pypy -u test__core_stat.py
 - //pypy-c-jit-76386-58059c786617-osx64/bin/pypy -u test__pywsgi.py
 - //pypy-c-jit-76386-58059c786617-osx64/bin/pypy -u test__threading_vs_settrace.py

3/123 unexpected failures
 - //pypy-c-jit-76386-58059c786617-osx64/bin/pypy -u test__all__.py
 - //pypy-c-jit-76386-58059c786617-osx64/bin/pypy -u test__example_portforwarder.py
 - //pypy-c-jit-76386-58059c786617-osx64/bin/pypy -u test__socket_dns6.py
```

However, there is a catch. In naively fixing the `test__server` tests in commit https://github.com/NextThought/gevent/commit/37c6edc2bfd21321011f7448bf17f848517cdffb I discovered that gevent's `Base/StreamServer` is relying on CPython's reference counting to keep sockets alive until they are no longer in use. Under PyPy's GC, this becomes non-deterministic behaviour, leading to many of the test failures, and probably real-life failures too (or at least way too many open sockets). But deterministically closing the socket when the server's handler completes leads to the failure in `test__example_portforwader` which passes its sockets on to new greenlets and then returns. 

Are there any thoughts on how best to fix this? Do real-life frameworks like, say, gunicorn, rely on the sockets being open after their handler returns? (I don't seem to find that documented anywhere?) Is this an issue the server should deal with, or should it be documented that each handler needs to close its own sockets? The former is nice and deterministic but breaks at least one test case; the latter changes the requirements for /all/ existing handlers (under PyPy anyway) but could be used to fix the test cases without changing the server code.

**Comment by tilgovi** [comment]
Gunicorn does try close except pass. It doesn't assume.

**Comment by jamadden** [comment]
For anyone interested, the `with-ssl-fix` branch at https://github.com/NextThought/gevent/tree/with-ssl-fix incorporates the SSL changes from #546 . It currently has the following failure report:

```
10/123 expected failures
- //PyPy26/bin/pypy -u -m monkey_test test_socket.py
- //PyPy26/bin/pypy -u -m monkey_test --Event test_socket.py
- //PyPy26/bin/pypy -u -m monkey_test test_ssl.py
- //PyPy26/bin/pypy -u -m monkey_test test_subprocess.py
- //PyPy26/bin/pypy -u -m monkey_test --Event test_ssl.py
- //PyPy26/bin/pypy -u test__ares_host_result.py
- //PyPy26/bin/pypy -u -m monkey_test --Event test_subprocess.py
- //PyPy26/bin/pypy -u test__core_stat.py
- //PyPy26/bin/pypy -u test__socket_dns6.py
- //PyPy26/bin/pypy -u test__threading_vs_settrace.py

1/123 unexpected failures
- //PyPy26/bin/pypy -u test__all__.py
```

**Comment by parasyte** [comment]
Very nice contribution @jamadden When I get some free cycles, I will be updating some code from PyPy 2.1/gevent 1.0, and this work will be the starting point for that. If I come up with any fixes myself, I'll submit some PRs. :+1:

**Comment by dmk23** [comment]
Why not upgrade everything to the latest and greatest PyPy? 2.5.0?

**Comment by parasyte** [comment]
@dmk23 That's the plan.

**Comment by jamadden** [comment]
I've actually been working with the PyPy 2.6 builds at the moment. There were a few failures with 2.5 that immediately went away when using 2.6. (I haven't gone back to see what those were.) 2.6 has the `ssl` module from CPython 2.7.9 whereas 2.5 is still based on 2.7.8. I'm not sure how the two roadmaps coincide, but our organization is probably looking at using early builds of PyPy 2.6 for the various improvements.

**Comment by jamadden** [comment]
I've finished integrating the changes from #546 for PyPy 2.5.1. It's down to 6 expected failures and no unexpected failures:

```
6/123 tests failed in 02:37

6/123 expected failures
 - //VirtualEnvs/pypy/bin/python -u -m monkey_test test_socket.py
 - //VirtualEnvs/pypy/bin/python -u -m monkey_test --Event test_socket.py
 - //VirtualEnvs/pypy/bin/python -u test__ares_host_result.py
 - //VirtualEnvs/pypy/bin/python -u test__core_stat.py
 - //VirtualEnvs/pypy/bin/python -u test__socket_dns6.py
 - //VirtualEnvs/pypy/bin/python -u test__threading_vs_settrace.py
```

**Comment by thedrow** [comment]
Has anyone tried to run the tests with PyPy 2.6.0 yet?

**Comment by jamadden** [comment]
@thedrow Locally I had one failure under PyPy 2.6.0. The failing test is no longer part of the PyPy test suite (or CPython's for that matter), so I've push a commit that doesn't run that test under PyPy 2.6.0.

**Comment by thedrow** [comment]
@jamadden Is the main blocker the fact that cares doesn't work with PyPy?

**Comment by jamadden** [comment]
The main blocker for what?

**Comment by thedrow** [comment]
For releasing this into gevent 1.1.

**Comment by jamadden** [comment]
For a 1.1, personally I would like to see [this issue](https://bitbucket.org/cffi/cffi/issue/152/handling-errors-from-signal-handlers-in) that Denis mentioned resolved so that signal handlers are reliable under PyPy. I also think that master is not in a good state to release with regards to the Python 3 support; there's enough there that it can be installed, but not enough there to make it usefully work in many scenarios and I can see that being very confusing. That's just my thoughts, I haven't seen this discussed anywhere else.

**Comment by thedrow** [comment]
@jamadden I just spoke with PyPy maintainers. It was waiting for Denis to respond. I responded as well and I hope that would get things moving.

**Comment by thedrow** [comment]
@jamadden Would it be possible to have a release with PyPy support but without Python 3 support?

**Comment by thedrow** [comment]
Also there's a lot of Python 3 tests that are waiting to be merged. @jamadden Can you take a look?

**Comment by thedrow** [comment]
@jamadden Had a really long session with Armin Rigo yesterday.
He thinks that the only solution to our problems is to rewrite some of the Python code to C.
The other solution would be to allow to disable signals in PyPy and re-enable them later only for the same thread. That's something he's not willing to do though since it won't work on CPython.
See his comments at https://bitbucket.org/cffi/cffi/issue/152/handling-errors-from-signal-handlers-in
I don't know enough about libev to help unless someone walks me through it.

**Comment by jamadden** [comment]
1.1a2 has three failing tests on PyPy 2.5.0--2.6.0 and one failing test on PyPy 2.7.0. master has two failing tests on 2.5.0--2.6.0 and *zero* failing tests on 2.7.0. I think we can consider this issue closed, with future issues being opened for specific behaviour differences or pypy-specific bugs. Thanks everyone!

**Comment by thedrow** [comment]
Great job! Thanks everyone!

**Comment by alexhayes** [comment]
High 5s!

**Comment by heikoheiko** [comment]
What needs to be done to also support pypy3?

**Comment by thedrow** [comment]
If we support python 3.2 then PyPy 3 should be supported.

**Comment by heikoheiko** [comment]
Ok, I see. Is the same true if PyPy supported Python 3.3?

**Comment by thedrow** [comment]
Yes but it doesn't for now although work is being done on it.
