### ISSUE TITLE
'Connection reset by peer' when download a binary file to Android

### ISSUE THREAD

**Issue by stkim1** [gevent/gevent#259]
I am running a http server on python(2.7.3) with bottle (0.11.6) and gevent (1.0rc2). Whenever I try to download a binary file to an Android client (2.2~4.1), I get this <code>connection reset by peer</code> error. 

Oddly enough, the client successfully downloads the file after not one but two(!) connection reset errors. 

Could anyone be kind enough to enlighten me in this?
<pre>Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 504, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 491, in run_application
    self.process_result()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 482, in process_result
    self.write(data)
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 371, in write
    self._write(data)
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 364, in _write
    self._sendall(data)
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 350, in _sendall
    self.socket.sendall(data)
  File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 458, in sendall
    data_sent += self.send(_get_memory(data, data_sent), flags)
  File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 443, in send
    return sock.send(data, flags)
<strong>error: [Errno 104] Connection reset by peer</strong>
{'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_CHARSET': 'windows-949,utf-8;q=0.7,*;q=0.3',
 'HTTP_ACCEPT_ENCODING': 'gzip,deflate,sdch',
 'HTTP_ACCEPT_LANGUAGE': 'ko-KR,ko;q=0.8,en-US;q=0.6,en;q=0.4',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_HOST': '192.168.1.100:8080',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Linux; Android 4.0.4; SHW-M250L Build/IMM76D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19',
 'HTTP_X_PURPOSE': 'instant',
 'PATH_INFO': '/appdata/9024-oclm.dat',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '192.168.1.253',
 'REMOTE_PORT': '40418',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'el-panchito',
 'SERVER_PORT': '8080',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
 'bottle.app': <bottle.Bottle object at 0x92fe0ec>,
 'bottle.request': <LocalRequest: GET http://192.168.1.100:8080/appdata/9024-oclm.dat>,
 'bottle.request.urlparts': SplitResult(scheme='http', netloc='192.168.1.100:8080', path='/appdata/9024-oclm.dat', query='', fragment=''),
 'bottle.route': <GET '/appdata/<dat_target>' <function transmit_dat_file at 0x9444b8c>>,
 'route.handle': <GET '/appdata/<dat_target>' <function transmit_dat_file at 0x9444b8c>>,
 'route.url_args': {'appdata': '9024-oclm.dat'},
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0xb76e70d0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x9646bcc>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with error

192.168.1.253 - - [2013-03-21 17:38:34] "GET /appdata/9024-oclm.dat HTTP/1.1" socket 131397 0.145209
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 504, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 491, in run_application
    self.process_result()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 482, in process_result
    self.write(data)
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 371, in write
    self._write(data)
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 364, in _write
    self._sendall(data)
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 350, in _sendall
    self.socket.sendall(data)
  File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 458, in sendall
    data_sent += self.send(_get_memory(data, data_sent), flags)
  File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 443, in send
    return sock.send(data, flags)
<strong>error: [Errno 104] Connection reset by peer</strong>
{'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_CHARSET': 'windows-949,utf-8;q=0.7,*;q=0.3',
 'HTTP_ACCEPT_ENCODING': 'gzip,deflate,sdch',
 'HTTP_ACCEPT_LANGUAGE': 'ko-KR,ko;q=0.8,en-US;q=0.6,en;q=0.4',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_HOST': '192.168.1.100:8080',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Linux; Android 4.0.4; SHW-M250L Build/IMM76D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19',
 'PATH_INFO': '/appdata/9024-oclm.dat',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '192.168.1.253',
 'REMOTE_PORT': '40414',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'el-panchito',
 'SERVER_PORT': '8080',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
 'bottle.app': <bottle.Bottle object at 0x92fe0ec>,
 'bottle.request': <LocalRequest: GET http://192.168.1.100:8080/appdata/9024-oclm.dat>,
 'bottle.request.urlparts': SplitResult(scheme='http', netloc='192.168.1.100:8080', path='/appdata/9024-oclm.dat', query='', fragment=''),
 'bottle.route': <GET '/appdata/<dat_target>' <function transmit_dat_file at 0x9444b8c>>,
 'route.handle': <GET '/appdata/<dat_target>' <function transmit_dat_file at 0x9444b8c>>,
 'route.url_args': {'appdata': '9024-oclm.dat'},
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0xb76e70d0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x9651c8c>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with error

192.168.1.253 - - [2013-03-21 17:38:36] "GET /appdata/9024-oclm.dat HTTP/1.1" socket 196933 0.239190
192.168.1.253 - - [2013-03-21 17:38:44] "GET /appdata/9024-oclm.dat HTTP/1.1" 200 15332303 7.041028</pre>

**Comment by jamadden** [comment]
"Connection reset by peer" means the other end (the client) has closed the socket. You'd need to check its logs to see why it closed the socket (maybe it timed out? maybe it ran out of memory?).

Closing as part of triage for 1.1. Please feel free to reopen or create a new issue if you think you've found a reproducible problem in gevent.
