### ISSUE TITLE
Lock when using gevent wih named PIPE

### ISSUE THREAD

**Issue by pigmej** [gevent/gevent#279]
Consider

file `a.py`:
```
from gevent import monkey
monkey.patch_all()

import gevent
import os
import sys
import time
import errno

import subprocess


def printer(d):
    print 'printer', d


def printer_all():
    for x in xrange(100):
        gevent.spawn(printer, x)
        time.sleep(0.1)


def main():
    fifo_p = '/tmp/block_fifo'
    try:
        os.unlink(fifo_p)
    except:
        pass
    os.mkfifo(fifo_p)
    fd = os.open(fifo_p, os.O_RDONLY | os.O_NONBLOCK)
    cmd = '%s block_pipe_wr.py ' % sys.executable
    sub = subprocess.Popen(cmd.split(' '))
    gevent.spawn(printer_all)
    gevent.sleep(0)
    data = None
    while True:
        try:
            data = os.read(fd, 2)
        except OSError as e:
            if e[0] not in (errno.EAGAIN, errno.EWOULDBLOCK):
                raise
            continue
        if not data:
            gevent.sleep(0.05)
        if data:
            print data
        if sub.poll() is not None:
            break

if __name__ == '__main__':

    main()
```

file: `block_pipe_wr.py`
```
import os
import time


def main():
    fifo_p = '/tmp/block_fifo'
    fd = os.open(fifo_p, os.O_WRONLY)
    for x in xrange(100):
        os.write(fd, '%.2d' % x)
        time.sleep(0.5)

if __name__ == '__main__':
    main()
```

Running this code will result a lock in gevent.  it will first print all numbers from named FIFO and then from the printer_all function (if any obviously).

The question is why gevent does not release context with that read ?

changing loop in `a.py` to:

```
    while True:
        try:
            data = os.read(fd, 2)
        except OSError as e:
            if e[0] not in (errno.EAGAIN, errno.EWOULDBLOCK):
                raise
            gevent.sleep(0.05)
            continue
        if not data:
            gevent.sleep(0.05)
        if data:
            gevent.sleep(0.05)
            print data
        if sub.poll() is not None:
            break
```
(added `gevent.sleep(0.05)`) allows `printer_all` to continue.

Also changing the `os.read` to `gevent.os.nb_read` also works fine.

While I understand that normal file IO is in fact blocking (no context release), I wonder why FIFO operations aren't working like socket ones.

// it's part of bigger concept, that's why there is `patch_all`

**Comment by jamadden** [comment]
In general, gevent can't automatically do much with functions that deal in raw file descriptors like `os.makefifo`---there's no object wrapper around them to present a blocking interface but also allow the loop to run. It also can't know the uses to which those descriptors will be put so it doesn't know if it's sensible to make them non-blocking. So it's up to the application.

For uses like this one, gevent provides `gevent.os.make_nonblocking` and `gevent.os.nb_read`/`nb_write`. Call `make_nonblocking` just after opening the fifo, and change `os.read` to `gevent.os.nb_read`, and you'll see all the calls neatly interleaved.
