### ISSUE TITLE
gevent.subprocess.Popen alters the behavior of time.sleep

### ISSUE THREAD

**Issue by eallik** [gevent/gevent#280]
It seems that after calling `gevent.subprocess.Popen`, the behavior of calling `time.sleep` for the first time is altered so that the call to `time.sleep` returns almost immediately.

I've discovered and been able to reproduce the problem reliably on OS X 10.8 and have not tested on other platforms. I'm using gevent==1.0rc2.

Here is the code to reproduce the issue.

```python
import time

from subprocess import Popen
from gevent.subprocess import Popen as g_Popen


T = time.time()
t = lambda: "%.4f" % (round(time.time() - T, 4),)

D = 1.0


if __name__ == '__main__':
    print t(), "calling Popen"
    Popen('false')
    print t(), "sleeping %s sec" % (D,)
    time.sleep(D)
    print t(), "after sleep"

    print "========="

    print t(), "calling gevent Popen"
    g_Popen('false')
    print t(), "sleeping %s sec" % (D,)
    time.sleep(D)  # this one returns almost immediately
    print t(), "sleeping %s sec" % (D,)
    time.sleep(D)  # the second one works fine
    print t(), "after sleep"

    print "========="

    print t(), "calling gevent Popen"
    g_Popen('false')
    print t(), "sleeping %s sec" % (D,)
    time.sleep(D)  # this one returns almost immediately
    print t(), "sleeping %s sec" % (D,)
    time.sleep(D)  # the second one works fine
    print t(), "after sleep"
```

**Comment by jamadden** [comment]
The stdlib `time.sleep` method is implemented by calling `select`, passing in a timeout value, and no file descriptors to actually select on. The intended effect is to block in the operating system, sleeping until the timeout has elapsed.

However, `select` is one of those system calls that is vulnerable to signals. When a signal is delivered to the process, `select` prematurely wakes up and sets `errno` to `EINTR` (interrupted). In that case, `time.sleep` makes no attempt to account for any unelapsed time; it simple returns. Therefore, `time.sleep` can sometimes return early. [This is documented](https://docs.python.org/3/library/time.html#time.sleep).

It so happens that gevent (and libev) uses signals (SIGCHLD) to monitor children. The use of gevent's subprocess module may *increase* the chances that a `time.sleep` will be premature, but `time.sleep` is not reliable even without it.

Suggestions:
- Do not rely on `time.sleep` being accurate. It's documented not to be. It can be either fast or slow.
- Use `gevent.sleep`. It's not vulnerable to the signal problem and seems to be more reliable *in this particular case*, but can still potentially suffer from being early or late.
