### ISSUE TITLE
gevent throws spurious errors in interactive mode use (Python REPL, IPython, BPython, and debuggers)

### ISSUE THREAD

**Issue by gordon-morehouse** [gevent/gevent#286]
Please see https://github.com/ipython/ipython/issues/2785 for an example.  It appears to be related to the order of imports vs when monkey patching occurs.

This also happens in BPython, in the regular Python REPL, and (most troublingly) when using an interactive debugger.

Thus, some code using gevent can become extremely difficult to debug.

**Comment by jamadden** [comment]
In my experience, the basic Python REPL is generally fine, as long as you understand and accept the limitations, e.g., that the gevent loop gets a chance to run only when you type a green function call at the prompt. Other more complicated systems like IPython that do more work before the user gets control are going to require their own specific solutions. `python -m gevent.monkey ...` trick is probably about as general as it's possible to be, given gevent's mode of operation (though I will say that in my own use monkey patching gevent after IPython is up and running works fine, with the same limits as the normal REPL plus the addition of losing history).

Closing for 1.1 triage. Please feel free to open another issue or add further comments here if there are specific general things that can be done.
