### ISSUE TITLE
gevent/pywsgin overflow error

### ISSUE THREAD

**Issue by ggjjlldd** [gevent/gevent#289]
```python
class Input(object):
   def _do_read(self, length=None, use_readline=False):
       left = content_length - self.position
```
if left > 2.5G, get error that overflow,signed integer exceed the maxinum

**Comment by jamadden** [comment]
FWIW, this is "fixed" in Python 3. I put "fixed" in quotation marks because it probably doesn't make sense to try to read 2.5GB into memory at once...
