### ISSUE TITLE
Release wheels for gevent 1.0

### ISSUE THREAD

**Issue by Ivoz** [gevent/gevent#371]
Binary [wheels] would be great for gevent to release. Wheels are static binaries that can be installed by pip.

Notably, Gevent doesn't currently have any released binaries for Windows or Mac, forcing users to figure out how to compile it themselves. Releasing wheels which users could install with pip would alleviate this.

They also work nicely within virtualenv environments, which the Windows installers don't, and unfortunately binary eggs aren't installable with `pip` either, only `easy_install`. Overall wheels are a greatly improved format for distributing (binary) python packages.

To build a wheel, you should have the `wheel` package installed and can then run `python setup.py bdist_wheel`.

Greenlet has very recently released wheels for its 1.4.2 release. You might find its [make-win-release] script handy to adapt for building binary releases (including wheels), at least on windows.

As of v1.5, pip will also install appropriate wheels automatically if they are found on pypi. This would allow a naive windows user to install gevent simply with `pip install gevent`!

Donald Stuff's [twine] tool also makes it very easy to upload things to pypi in general, fwiw.

[wheels]: https://pypi.python.org/pypi/wheel
[make-win-release]: https://github.com/python-greenlet/greenlet/blob/master/make-win-release
[twine]: https://pypi.python.org/pypi/twine

**Comment by codeape** [comment]
A wheel for windows would be very appreciated.

**Comment by jamadden** [comment]
Starting with 1.1b2, common wheels are uploaded to PyPI (windows comes from AppVeyor, the maintainer has to build the OS X wheels).
