### ISSUE TITLE
Greenlet.successful() returns True for a killed greenlet

### ISSUE THREAD

**Issue by maxpmaxp** [gevent/gevent#375]
If I kill running greenlet with ```Greenlet.kill()``` its ```successful()``` method returns ```True``` and ```Greenlet.get()``` returns an instance of ```GreenletExit``` class.

I feel ```successful()``` must return ```True``` if and only if a greenlet was successfully finished.

Gevent version 1.0dev

Steps to reproduce
```
>>> import gevent
>>> gevent.__version__
'1.0dev'
>>> import gevent.monkey
>>> gevent.monkey.patch_all()
>>> from time import sleep
>>> def f():
...     while True: sleep(0.1)
... 
>>> g=gevent.spawn(f)
>>> g.successful()
False
>>> g.kill()      
>>> g.successful()
True
>>> g.get()
GreenletExit()
```

**Comment by jamadden** [comment]
Documented in ff5632e.
