### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by denik** [gevent/gevent#38]
Would be cool to have python3 support, ideally as single source.

Here's an old python3 fork: http://bitbucket.org/jjonte/gevent

<p><a href="http://code.google.com/p/gevent/issues/detail?id=38">Reported by Denis.Bilenko.</a></p><hr/><h2>earlier comments</h2>
<p><strong>Denis.Bilenko said, at 2011-01-28T05:36:07.000Z:</strong></p>
<p>There's some work going on at https://bitbucket.org/Edmund_Ogban/gevent-py3k</p><p><strong>carsten.klein@axn-software.de said, at 2011-03-20T18:40:50.000Z:</strong></p>
<p>Exception handling is a problem here. With Python2.5 there is only except Exception, e, whereas Python3.x requires except Exception as e.

Making this single source supporting 2.5 and higher is therefore quite difficult. Or is there some __future__ that can be used to simulate the new syntax included with the language since 2.6?

Otherwise I would say: drop support for Python 2.5 with the next release version, and make that one compatible with 2.6 .. 3.2.
</p><p><strong>anacrolix said, at 2011-09-13T00:03:14.000Z:</strong></p>
<p>I'm keen to try gevent, but I sailed for Python3 over a year ago.</p><p><strong>anacrolix said, at 2011-09-20T00:23:26.000Z:</strong></p>
<p>Denis can you report on the status of Python3 support for gevent?</p><p><strong>Denis.Bilenko said, at 2011-12-20T18:14:35.000Z:</strong></p>
<p>Issue 89 has been merged into this issue.</p><p><strong>luchenue said, at 2011-12-23T09:14:52.000Z:</strong></p>
<p>Any news ?</p><p><strong>anacrolix said, at 2011-12-23T11:09:10.000Z:</strong></p>
<p>From what I've observed, I don't think Denis wants to break support for Python 2 yet, and so won't accept patches that don't support both 2 *and* 3, which is a complex obstacle.</p><p><strong>k.cherkasoff said, at 2011-12-23T11:42:53.000Z:</strong></p>
<p>Is there any up to date forks for python 3.x ?
</p><p><strong>whitelynx said, at 2012-02-01T07:13:18.000Z:</strong></p>
<p>I think the general approach for maintaining anything that's supposed to work on 2.5 - 3.x is to use the 2to3 tool to automatically generate a python3 version from the python2 source. The exception handling issue mentioned by carsten above (comment 2) is treated by the 'except' fixer in 2to3. (http://docs.python.org/library/2to3.html?highlight=except#2to3fixer-except) Since fixers can be run individually, it shouldn't be too difficult to put together a 2to3 command line that would be able to translate gevent with a minimum amount of breakage, and then just manually clean up the results. I do wish there was a 3to2 or similar that would translate some of the python3-style idioms to something compatible with 2.5, as with the 'except _ as _' syntax.</p><p><strong>amcnabb8 said, at 2012-02-09T19:14:00.000Z:</strong></p>
<p>The six library makes it very easy to support both Python 2 (>=2.6) and Python 3 without needing 2to3. With a couple of workarounds, Michael Foord has shown that it's entirely possible to support Python 2.4 without 2to3. But really, it's not as hard as it sounds to support both Python 2 and 3, and there are two reasonable approaches.</p>

**Comment by kkurian** [comment]
@dcramer @sontek @mjumbewu @thiderman 👍👍👍👍

**Comment by novocaine** [comment]
@mateuszf not sure if you already worked this out, but for anyone else trying to get the @fantix fork to work on windows one way of getting it to work is, if you are using cygwin:

1. install cython
2. In Makefile, change $(PYTHON) util/cythonpp.py -o gevent.corecext.c gevent/core.ppyx to $(PYTHON) util/cythonpp.py -o gevent.corecext.c gevent/core.ppyx
3. run 'make'
4. rename 'make' to Makefile.ext
5. python setup.py install as usual.

The gevent build is a bit dodgy and mixes and matches invocations to 'system' to calls from GNU make, which means mixing windows and cygwin paths.

This might be smoother with mingw?

**Comment by sontek** [comment]
I am personally willing to donate and also gather money from my company for this effort, lets make py3 happen

**Comment by fantix** [comment]
@novocaine thanks a lot for the tips on windows!

**Comment by robertlagrant** [comment]
Maybe people willing to pay for this, combined with @fantix looking for a job, is a match made in heaven :)

**Comment by lyschoening** [comment]
This is maybe a bit of an unfair question to ask, but given that Python 3.4 and onwards ships with asyncio, why not simply provide a thin wrapper under the gevent namespace and skip support for Python 3.3? The need for gevent support in Python 3 stems primarily from all the legacy packages that depend on it. Has anyone run benchmarks that suggest gevent with libev is significantly faster?

It's fair to assume that the momentum will be with asyncio once it is sufficiently stable. At that point gevent could simply provide an EventLoop implementation if that brings performance gains over the default implementation.

**Comment by jgehrcke** [comment]
@lyschoening: While clearly similar, gevent's and asyncio's programming paradigms differ significantly. I believe it is not easy to come up with a thin wrapper to combine one with the other. gevent is quite feature-rich, and heavily relies on how greenlets work, so it will be difficult to shape something that *looks* like gevent, but does not work with greenlets, a Hub, and its own event loop under the hood. A re-implementation of gevent-like behavior using asyncio clearly is a complex project, which could be a waste of time.

In the long-term, you are right -- there should definitely be a clarification/an official guideline about how the gevent ecosystem should respond to the existence of asyncio.

From my point of view, if I am allowed to express a vision, gevent should be based on libuv for better Windows support, and also support PyPy out of the box. Python 3 support should be there. That would be tremendous, and people would proceed using gevent, as of its super-simple synchronous way to implement things (the way of doing things with asyncio does not convince me too much).

**Comment by fantix** [comment]
A few links to share here:

Explicit vs. Implicit: https://glyph.twistedmatrix.com/2014/02/unyielding.html
asyncio on gevent: https://bitbucket.org/haypo/aiogevent
gevent on asyncio: https://github.com/decentfox/tulipcore

**Comment by davidfischer-ch** [comment]
+1

**Comment by ml31415** [comment]
Another related project: https://github.com/veegee/guv

**Comment by gawry** [comment]
Are we to far from finishing this?

**Comment by aidylewis** [comment]
Is it worth entering in the [installation notes](http://www.gevent.org/intro.html#installation) that python 3 is not supported. It currently states: 'gevent runs on Python 2.5 and newer and requires'.

**Comment by kolis** [comment]
+1

**Comment by thedrow** [comment]
Hi guys @fantix  has contributed a lot of Pull Requests.
Some are not merged and some are only partially merged.
Can we please have someone look at those?

**Comment by macolo** [comment]
Yes, please, what's going on?

**Comment by jamadden** [comment]
I've just merged (updates of) many of the open Python 3 PRs or variations on them, including #412, #413, #416, #421, #462, #474, and #409. The Py3 build is green now with only one known failing test (`test__socket_dns.py`).

**Comment by fantix** [comment]
@jamadden Awesome! Much appreciated for the hard work! :rocket:

**Comment by mjumbewu** [comment]
@jmadden @fantix you guys are amazing.

**Comment by thedrow** [comment]
Wonderful.
Now let's fix that test and the failing tests in #248 and we can release 1.1.

**Comment by thedrow** [comment]
@jamadden It seems that the DNS test should be fixed in #418 but it isn't.

**Comment by thedrow** [comment]
Other pull requests related to Python 3: #390 #399

**Comment by jamadden** [comment]
Just like with #248, 1.1a2 has been released with no unaccounted for failures under Python 3. Master currently has several improvements but only one specific to Python 3, and it's minor. I think we can consider the major thrust of this issue to be completed. Please open new issues/PRs for specific issues with Python 3 support. Thanks everyone!

**Comment by mjumbewu** [comment]
:clap:

**Comment by ramnes** [comment]
:dancers:

**Comment by ultrabug** [comment]
:dancer:

**Comment by giampaolo** [comment]
This is awesome! Glad to see one of the biggest stoppers for python 3 adoption finally supports Python 3.

**Comment by tebanep** [comment]
😀🎉🎉🎉

**Comment by zubinmehta** [comment]
:-)

**Comment by sylvinus** [comment]
Congrats!!

**Comment by chuliang** [comment]
Good job !

**Comment by maguowei** [comment]
Great Job ！ 🍺🍉👏

**Comment by brunoalano** [comment]
Yay (:

**Comment by waynew** [comment]
Great job, and a huge thank you to everyone involved in this!

**Comment by sieben** [comment]
:+1:

**Comment by svieira** [comment]
:night_with_stars:  :fireworks: :sparkler:Fantastic, fantastic, fantastic!  Thank you all!

**Comment by mavier** [comment]
:sparkles: :+1: :sparkles:

**Comment by jvrsantacruz** [comment]
Great job!

**Comment by gitaarik** [comment]
:surfer:
