### ISSUE TITLE
SIGCHLD is missing

### ISSUE THREAD

**Issue by pelt** [gevent/gevent#380]
I try to migrate a project from gevent 0.13.8 to 1.0. There is a signal handler for SIGCHLD registered with gevent. This event is missing in 1.0. When I import gevent.subprocess and perform a call, the callback is executed but waitpid was already called. So I don't know the process which has been exited.

Currently I use the system signal handler (signal.signal(...)) and avoid the usage of gevent.subprocess.

Is this the normal behavior for gevent 1.0?

**Comment by jamadden** [comment]
The implementation of `gevent.subprocess` uses libev's child watchers; behind the scenes on posix this uses SIGCHLD and waitpid so no other code can get those. Under gevent, `communitace` and `join` are non-blocking and allow specifying a timeout so the same effect can be achieved, potentially with the additional use of `Event`.
