### ISSUE TITLE
-m32 needed during configure c-ares step for 32 bit Python on 64 bit Linux

### ISSUE THREAD

**Issue by lanstin** [gevent/gevent#381]
Otherwise it the configure discovers that long is 8 bytes and build (getting the -m32 I guess from the python overlord of c-ares) has long as 4 bytes and the compile chokes.  For now I am export CFLAGS="-m32" before invoking python setup.py   If I find out how to tell c-ares configure about this in some more sane way, I'll post a pull request.

**Comment by jamadden** [comment]
Does this still happen with the latest release (1.1a2)? If so, can you provide the error message you get? It would be nice to add to the installation documentation how to work around that error.

**Comment by lanstin** [comment]
I'll check, thanks.

**Comment by lanstin** [comment]
Still happens.  The first error is:

Running '/bin/sh /x/home01/caustinlane/lib-src/gevent-trunk/c-ares/configure CONFIG_COMMANDS= CONFIG_FILES= > configure-output.txt' in /x/home01/caustinlane/lib-src/gevent-trunk/build/temp.linux-x86_64-2.7/c-ares
building 'gevent.ares' extension
gcc -pthread -fno-strict-aliasing -O3 -m32 -DNDEBUG -m32 -fPIC -DHAVE_CONFIG_H= -DCARES_EMBED=1 -Ibuild/temp.linux-x86_64-2.7/c-ares -Ic-ares -I/x/opt/pp/include/python2.7 -c gevent/gevent.ares.c -o build/temp.linux-x86_64-2.7/gevent/gevent.ares.o
In file included from c-ares/ares.h:23,
                 from gevent/gevent.ares.c:311:
c-ares/ares_rules.h:101: error: size of array ‘__cares_rule_01__’ is negative


The end of the build emits this warning:

WARNING: The gevent.ares extension has been disabled.

It must be in the step that builds the ares_rules.h step; the config doesn't seem to have any options for 32 or 64 bit options, and indeed the compile is with -m32 even when that isn't specified during the configure time.  having CFLAGS=-m32 at configure time results in a compile command like:

gcc -pthread -DNDEBUG -m32 -m32 -fPIC -DHAVE_CONFIG_H= -DCARES_EMBED=1 -Ibuild/temp.linux-x86_64-2.7/c-ares -Ic-ares -I/x/opt/pp/include/python2.7 -c c-ares/ares__close_sockets.c -o build/temp.linux-x86_64-2.7/c-ares/ares__close_sockets.o

with 2 -m32's  

CARES_SIZEOF_LONG is 4 with -m32 defined and 8 otherwise (but the setuptools seems to use the -m32 from the python build at the time of actually making, so the compile time sizeof(long) != config time CARES_SIZEOF_LONG.  Actually, I have a small patch to gevent's setup.py that should fix this, I'll do a PR once it seems to build ok on my various supported actitectures.  

--Chris

**Comment by lanstin** [comment]
https://github.com/gevent/gevent/pull/616 -- against master, which seems to be a bit different than 1.1a2  I have it against 1.1a2 tag as well, but not sure what branch to use for it.
