### ISSUE TITLE
gevent.local.local Doesn't Garbage Collect when the Greenlet Finishes

### ISSUE THREAD

**Issue by AusIV** [gevent/gevent#387]
I've recently run into an issue with the way items attached to gevent.local.local get garbage collected. I've put together the simplest example I can think of to demonstrate it:

    from gevent.local import local
    import gevent

    # The sentinel object will let us know when it gets deleted
    class Sentinel(object):
        def __del__(self):
            print "%s deleted" % self

    # A simple subclass of local, which references a Sentinel
    class MyLocal(local):
        def __init__(self):
            self.sentinel = Sentinel()

    my_local = MyLocal()

This creates a `my_local` object that will be re-instantiated for each greenlet, containing an object that will alert us when it gets garbage collected.

To demonstrate the Sentinel class, if I run:

    def demonstrate_sentinel():
        a = Sentinel()

    demonstrate_sentinel()

I get

    # <__main__.Sentinel object at 0x7f509b6f7690> deleted

and

    gevent.spawn(demonstrate_sentinel)
    gevent.sleep()

yields

    # <__main__.Sentinel object at 0x7f509b702750> deleted

if I subsequently run:

    def demonstrate_my_local():
        # Get the important parts
        my_local.sentinel

    greenlets = [gevent.spawn(demonstrate_my_local) for _ in range(5)]
    gevent.sleep()

I see no output to indicate the Sentinel was garbage collected. If I run:

    for greenlet in greenlets:
        print greenlet.dead

I see that all greenlets are dead, but the sentinels attached to the my local object have never been garbage collected. If I run:

    del greenlets

I get:

    # <__main__.Sentinel object at 0x7f509b702a10> deleted
    # <__main__.Sentinel object at 0x7f509b702b50> deleted
    # <__main__.Sentinel object at 0x7f509b702ad0> deleted
    # <__main__.Sentinel object at 0x7f509b7028d0> deleted

From what I see, the local object is keeping dictionaries of the values for each greenlet in a WeakKeyDictionary. When the greenlet gets garbage collected, the values in the WeakKeyDictionary will get garbage collected. But if a reference to the greenlet persists after it dies, the values never get garbage collected.

This is an issue for me because something (possibly gunicorn, which I'm using as a web server) is keeping references to my greenlets long after they die, which means my  local objects (which contain socket connections) aren't being cleaned up and my connections aren't being closed.

For now I'm working around it by doing something like:

    for greenlet in my_local._local__dicts.keys():
        if greenlet.dead:
            del my_local._local__dicts[greenlet]

But this feels fragile, given that it relies on what I assume is an implementation detail of how gevent.local.local currently works.

When using threading.local with threads, it doesn't matter if something keeps a reference to the thread object, the local objects for that thread get garbage collected when it terminates. Would it be possible for greenlet.local.local to match this behavior for greenlets? Would there be a downside to doing so?

**Comment by jamadden** [comment]
Fixed in 1192b1c. Note that the above fragile workaround will not work anymore.
