### ISSUE TITLE
Gevent refusing to event.wait() when signal handler is registered

### ISSUE THREAD

**Issue by karlbohlmark** [gevent/gevent#392]
From a user perspective, I see no reason that this should not work, but currently it results in a `gevent.hub.LoopExit: This operation would block forever`

```
import signal
import gevent
from gevent.monkey import patch_all
patch_all()
from gevent import sleep
from gevent.event import Event

stopped = Event()

def stop(signum, frame):
    stopped.set()

signal.signal(signal.SIGINT, stop)

stopped.wait()
print "Done"
```

**Comment by jamadden** [comment]
Closing in triage for the next release, because there has been no discussion for two years, and because several alternatives were presented.

**Comment by F3ngdw** [comment]
@jamadden i came across the same issue with @karlbohlmark , here is my script:
`
import gevent

def main():
    complete = gevent.event.Event()
    def shutdown():
        log.info("Signal handler: stopping")
        complete.set()

    gevent.hub.signal(signal.SIGTERM, shutdown)
    gevent.hub.signal(signal.SIGINT, shutdown)
    
    while not complete.is_set():
        complete.wait(timeout=1)
`
After running the program normally for a period of time, an error suddenly occurs：
Traceback (most recent call last):
  File "/opt/calamari/venv/bin/cthulhu-manager", line 9, in <module>
    load_entry_point('calamari-cthulhu==0.1', 'console_scripts', 'cthulhu-manager')()
  File "/opt/calamari/venv/lib/python2.7/site-packages/calamari_cthulhu-0.1-py2.7.egg/cthulhu/manager/manager.py", line 1156, in main
    complete.wait(timeout=1)
  File "/opt/calamari/venv/lib/python2.7/site-packages/gevent/event.py", line 77, in wait
    result = self.hub.switch()
  File "/opt/calamari/venv/lib/python2.7/site-packages/gevent/hub.py", line 338, in switch
    return greenlet.switch(self)
gevent.hub.LoopExit: This operation would block forever

Please let me know where I went wrong and how to fix it, Thanks!

**Comment by jamadden** [comment]
@F3ngdw you appear to be running on an obsolete version of Python (2.7) and an obsolete version of gevent. I barely have any time to work on current versions of Python and gevent, so I'm afraid I can't help you.
