### ISSUE TITLE
pywsgi always logs errors to stderr, regardless of log setting

### ISSUE THREAD

**Issue by raylu** [gevent/gevent#426]
[`log_request`](https://github.com/surfly/gevent/blob/master/gevent/pywsgi.py#L473) logs to the [object passed to the server constructor](https://github.com/surfly/gevent/blob/master/gevent/pywsgi.py#L621), but [`log_error`](https://github.com/surfly/gevent/blob/master/gevent/pywsgi.py#L306) ignores it

**Comment by jamadden** [comment]
I believe this was fixed with #106.
