### ISSUE TITLE
Failed Installation onto SunOS 5.10 Generic_138889-08 i86pc i386 i86pc

### ISSUE THREAD

**Issue by chfw** [gevent/gevent#427]
Hi all,

I am installing gevent to solaris but failed with the following messages that was greped with "error" from pip.log:

    "gevent/callbacks.h", line 29: warning: syntax error:  empty declaration
    "gevent/callbacks.h", line 29: warning: syntax error:  empty declaration
    "gevent/callbacks.h", line 29: warning: syntax error:  empty declaration
    "gevent/callbacks.h", line 29: warning: syntax error:  empty declaration
    "gevent/callbacks.h", line 29: warning: syntax error:  empty declaration
    "gevent/callbacks.h", line 29: warning: syntax error:  empty declaration
    "gevent/callbacks.h", line 29: warning: syntax error:  empty declaration
    "gevent/callbacks.h", line 29: warning: syntax error:  empty declaration
    "gevent/callbacks.c", line 187: warning: syntax error:  empty declaration
    "gevent/callbacks.c", line 187: warning: syntax error:  empty declaration
    "gevent/callbacks.c", line 187: warning: syntax error:  empty declaration
    "gevent/callbacks.c", line 187: warning: syntax error:  empty declaration
    "gevent/callbacks.c", line 187: warning: syntax error:  empty declaration
    "gevent/callbacks.c", line 187: warning: syntax error:  empty declaration
    "gevent/callbacks.c", line 187: warning: syntax error:  empty declaration
    "gevent/callbacks.c", line 187: warning: syntax error:  empty declaration
    error: command '/opt/SUNWspro/bin/cc' failed with exit status 2
"gevent/callbacks.h", line 29: warning: syntax error:  empty declaration
"gevent/callbacks.h", line 29: warning: syntax error:  empty declaration
"gevent/callbacks.h", line 29: warning: syntax error:  empty declaration
"gevent/callbacks.h", line 29: warning: syntax error:  empty declaration
"gevent/callbacks.h", line 29: warning: syntax error:  empty declaration
"gevent/callbacks.h", line 29: warning: syntax error:  empty declaration
"gevent/callbacks.h", line 29: warning: syntax error:  empty declaration
"gevent/callbacks.h", line 29: warning: syntax error:  empty declaration
"gevent/callbacks.c", line 187: warning: syntax error:  empty declaration
"gevent/callbacks.c", line 187: warning: syntax error:  empty declaration
"gevent/callbacks.c", line 187: warning: syntax error:  empty declaration
"gevent/callbacks.c", line 187: warning: syntax error:  empty declaration
"gevent/callbacks.c", line 187: warning: syntax error:  empty declaration
"gevent/callbacks.c", line 187: warning: syntax error:  empty declaration
"gevent/callbacks.c", line 187: warning: syntax error:  empty declaration
"gevent/callbacks.c", line 187: warning: syntax error:  empty declaration
error: command '/opt/SUNWspro/bin/cc' failed with exit status 2

My machine type is:

SunOS 5.10 Generic_138889-08 i86pc i386 i86pc

Do you know what might have gone wrong?

Thanks,

**Comment by jamadden** [comment]
Closing because there have been no updates in almost two years. There have been other issues raised with the open-source versions of solaris (E.g., #711) so check those. Please feel free to reopen if there's more information.
