### ISSUE TITLE
gevent.monkey.patch_sys() breaks ipdb (through readline)

### ISSUE THREAD

**Issue by tobinvanpelt** [gevent/gevent#437]
When executing the following:

    from gevent import monkey
    monkey.patch_sys()

    import ipdb; ipdb.set_trace()
    # now hit arrow keys at the prompt

The arrow keys no longer work in `ipdb` (ipython debugger).  I believe that this is related to `readline`.  It also appears the be closely related to: https://github.com/surfly/gevent/issues/6

I am using iterm within OSX.

Is there an issue here in the patching?  Or is it possibily related to my terminal somehow?

**Comment by jamadden** [comment]
See discussion on #274.
