### ISSUE TITLE
gevent not compatible with Python io module?

### ISSUE THREAD

**Issue by davidkhess** [gevent/gevent#439]
See this issue over in PyMySQL: https://github.com/PyMySQL/PyMySQL/issues/238

The summary is that the io module uses PyThread_get_thread_ident to check to see if a thread has reentered the io module and throws an exception if so. If gevent doesn't patch this (which it does not appear to) then it seems that this code could throw exceptions that are false positives because every greenlet will have the exact same posix thread id.

At least, that's what seems to be going on.

**Comment by jamadden** [comment]
Closing this as PyMySQL/PyMySQL#238 was closed; the underlying issue was a bug is SQLAlchemy.
