### ISSUE TITLE
gevent BaseServer doesn't accept gevent.pool.Group

### ISSUE THREAD

**Issue by todds02** [gevent/gevent#442]
BaseServer (which WSGIServer inherits from) allows passing in a 'spawn' parameter to its __init__.  This can be used to pass in a gevent.pool.Pool object.  If you pass in a Group, the code fails, as BaseServer.set_spawn() unconditionally tries to access the private _semaphore member of the pool:

        if self.pool is not None:
            self.pool._semaphore.rawlink(self._start_accepting_if_started)

It doesn't look like this is actually required, and supporting Group should work just fine.

As a workaround, Pool currently allows a size of None, and sets up a DummySemaphore - which has an XXX comment asking what it is used for.  Since the documentation implies Group is for unlimited and Pool has a maximum size, it seems like making a size=None Pool is not the correct way to go, and that BaseServer should have Group natively.

**Comment by jamadden** [comment]
The documentation for `BaseServer` specifies what four types of arguments are accepted, and a `Group` is not one of them. A `Group` would add little or no value; the default value for `spawn` is to not limit the number of greenlets used, which is what a `Group` would accomplish.
