### ISSUE TITLE
Gevent 1.1 in gunicorn 18 

### ISSUE THREAD

**Issue by aztrock** [gevent/gevent#443]
Traceback (most recent call last):
  File "/home/aztrock/vozip/lib/python3.3/site-packages/gevent/baseserver.py", line 147, in _do_read
    args = self.do_read()
  File "/home/aztrock/vozip/lib/python3.3/site-packages/gevent/server.py", line 99, in do_read
    fd, address = sock._accept()
BlockingIOError: [Errno 11] Resource temporarily unavailable
<StreamServer at 0x7ff12d6f9bd0 fileno=5 address=127.0.0.1:8002 handle=functools.partial(<bound method GeventWorker.handle of <gunicorn.workers.ggevent.GeventWorker object at 0x7ff12b9b8b10>>, <gunicorn.sock.TCPSocket object at 0x7ff12b965890>)> failed with BlockingIOError

I'm making a connection with django, gunicorn by SSE, the data connection and work well, I think it is important to report this

**Comment by thedrow** [comment]
Can you retry with latest master?

**Comment by jamadden** [comment]
Closing this as it's been over a year without comment, and several releases of gevent and gunicorn occurred during that time. I know of many users successfully using gevent 1.1x and gunicorn 19 in production at this time (note that gunicorn 19.4 is required to avoid some annoying but mostly harmless exceptions being printed). Please open a new issue if you still have problems on current versions.
