### ISSUE TITLE
gevent.subprocess vs os.waitpid

### ISSUE THREAD

**Issue by neuroid** [gevent/gevent#452]
Hi,

I'm seeing some strange behaviour when using gevent's subprocess in combination with `gevent.fork()`. I extracted a minimal example from my application, which can be found at https://gist.github.com/neuroid/5d42760310f7af843150.

The example code forks a child process, then spawns a greenlet in the main process, and waits for both to finish. The greenlet in turn uses the patched subprocess to run a command. After the main process receives a SIGINT it sends a termination signal to the child and kills the greenlet.

Everything works as expected until the `os.waitpid()` call (line 48), after the main process receives SIGINT. This results with an `OSError: [Errno 10] No child processes`. However, if I remove `subprocess.call()` from the task, the program terminates correctly, without raising an exception.

It seems that something else consumes the termination status of the forked child when subprocess is used. Is this a known issue?

Tested with gevent 1.0.1 on Linux and OS X.

**Comment by jamadden** [comment]
Indeed, this is a known issue, albeit not a well documented one. `gevent.subprocess` and `os.waitpid` do not mix well together. `gevent.subprocess` uses a libev child watcher to *asynchronously* get notified of the death of the child (via SIGCHLD); under most circumstances this is instantaneous. By the time anything else wants to run and use `waitpid`, libev has already done so.

It might be nice if gevent had a replacement for `waitpid` that took that into account...
