### ISSUE TITLE
Strange resolver hang 

### ISSUE THREAD

**Issue by vitek** [gevent/gevent#455]
Hi!

Trying to figure out gevents + pymongo related hang. I've came out with minimal hang example:

```
$ cat case.py
from gevent import monkey
monkey.patch_all()
import socket
socket.getaddrinfo(u'localhost', 27017, 2, 1, 0, 0)
$ cat show.py
import case
$ python case.py  # It works!
$ python show.py # Never finish
```

Hang occurs when `_socket.getadddrinfo()` tries to idna encode `localhost` hostname

**Comment by jamadden** [comment]
Closing as fixed with b8826b7a3f3e283ef3a2980f74184a7ec6ec98cc.
