### ISSUE TITLE
SystemError (libev Unknown error) on Windows

### ISSUE THREAD

**Issue by rgalanakis** [gevent/gevent#459]
Hi, I am the author of [goless](https://github.com/rgalanakis/goless) and we think we found a bug with gevent (or libev?) on Windows. The following code will raise `SystemError: (libev) select: Unknown error` on Windows (it works as expected on Linux):

```
from gevent.queue import Channel
import gevent
c = Channel()
def sender():
    while True:
        c.put(0)
gevent.spawn(c.put, 1)
for i in range(1000):
    gevent.sleep(0)
```

We've also found issues where code that loops forever on Linux (or raises a `LoopExit`) will raise the `SystemError` (unknown error) on Windows. However those circumstances are less of a concern than the above code which should work fine.

Please tell me if I can be of any assistance!

You can refer to the issue here for more information: https://github.com/rgalanakis/goless/issues/28

**Comment by wzyuliyang** [comment]
import socket on windows  works for me

**Comment by krist-jin** [comment]
I was using windows and following the code here to learn about gevent: http://stackoverflow.com/a/9195332

And it failed with SystemError: (libev) select: Unknown error

Then I added "import socket" at the beginning and everything works fine. Thanks!
