### ISSUE TITLE
single-threaded uwsgi with gevent - causing multiple threads

### ISSUE THREAD

**Issue by rakeshdatta** [gevent/gevent#468]
PROBLEM:
--------------
 When single-threaded uwsgi (run with 'gevent' loop) receives concurrent requests, multiple threads are spawned by gevent.Although it is expected that the parallel requests are handled through greenlets (one thread only). 

LOGS:
--------
<snip>

$ ./uwsgi --http  10.106.2.186:3056 --wsgi-file wsma_gevent.py --master --processes 1 --gevent 10 --show-config

;uWSGI instance configuration
[uwsgi]
http = 10.106.2.186:3056
wsgi-file = wsma_gevent.py
master = true
processes = 1
gevent = 10
show-config = true
;end of configuration

*** Starting uWSGI 2.0.6 (64bit) on [Tue Aug  5 11:42:31 2014] ***
compiled with version: 4.6.3 on 30 July 2014 01:56:17
os: Linux-3.8.0-35-generic #50~precise1-Ubuntu SMP Wed Dec 4 17:25:51 UTC 2013
nodename: bgl-pnp-lumos3
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/enc/rakesh/uwsgi/uwsgi-master
detected binary path: /home/enc/rakesh/uwsgi/uwsgi-master/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 192763
your memory page size is 4096 bytes
detected max file descriptor number: 1024
- async cores set to 10 - fd table size: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 10.106.2.186:3056 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:48580 (port auto-assigned) fd 3
Python version: 2.7.3 (default, Sep 26 2013, 20:13:52)  [GCC 4.6.3]
Python main interpreter initialized at 0x14bf690
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 331008 bytes (323 KB) for 10 cores
*** Operational MODE: async ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x14bf690 pid: 29959 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 29959)
spawned uWSGI worker 1 (pid: 29960, cores: 10)
spawned uWSGI http 1 (pid: 29961)
*** running gevent loop engine [addr:0x489a80] ***

</snip>

After sending 10 concurrent requests to uwsgi, we see total 4 threads created by the worker process...
 
<top -Hp 29960>
    29960 enc       20   0  294m  10m 2736 S    0  0.0   0:00.04 uwsgi                                                                                                                  
     30021 enc       20   0  294m  10m 2736 S    0  0.0   0:00.00 uwsgi                                                                                                                  
     30022 enc       20   0  294m  10m 2736 S    0  0.0   0:00.00 uwsgi                                                                                                                  
     30023 enc       20   0  294m  10m 2736 S    0  0.0   0:00.00 uwsgi                                                                                                                  

 </top>

CODE:
---------

import gevent
from gevent import monkey
gevent.monkey.patch_all()
import urllib2
import json

def prettyprint(msg):
       return json.dumps(msg)

def greenlet_body():
       msg = urllib2.urlopen("www.google.com").read()
       return msg

def application(env, start_response):
       start_response('200 OK',  [('Content-Type','application/json')])

       if env["REQUEST_METHOD"] == "GET" :
           msg = greenlet_body()
       else:
           msg = "unknown option"

       return prettyprint(msg)
 
EXPECTATION:
-------------------

When uwsgi is run as a single thread, gevent should not create multiple threads to handle the concurrent requests.

FIX:
----
The issue is introduced in 1.0b2 release onwards.

**Comment by thedrow** [comment]
@rakeshdatta Any updates on this or should we close this issue?
I think @mikekap provided the correct solution for you.

**Comment by jamadden** [comment]
Closing as part of triage for 1.1. Please do feel free to reopen or comment if the threads are something other than gevent's built-in threadpool.
