### ISSUE TITLE
Add 64bit binary packages for Windows

### ISSUE THREAD

**Issue by denik** [gevent/gevent#47]
They can either be compiled on 64bit Windows (maybe via amazon micro instance) or cross-compiled on 32bit Windows via cross-compiled Python (http://docs.python.org/distutils/builtdist.html#cross-compiling-on-windows)

Note, that there are two 64 bit architectures: amd64 and ia64<p><a href="http://code.google.com/p/gevent/issues/detail?id=47">Reported by Denis.Bilenko.</a></p>

**Comment by jamadden** [comment]
#624 started building 32 and 64 bit wheels for windows. Future releases can upload those. (By 64 bit, I mean "amd64" aka x86_64; Itanium windows is mostly used in enterprise environments, as I understand it, and those folks are probably capable of building their own wheels.)
