### ISSUE TITLE
gevent.subprocess and gevent.fileobject Python3 issue

### ISSUE THREAD

**Issue by erikhvatum** [gevent/gevent#474]
On Python 3.4.1 with the latest HEAD (adb7b838ed66c13abe5059605730bb4b4531bbcd), gevent.fileobject seems to be broken, breaking gevent.subprocess, which depends upon it:

In [1]: import gevent.subprocess
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-16362f1d6e9d> in <module>()
----> 1 import gevent.subprocess

/usr/lib64/python3.4/site-packages/gevent-1.1-py3.4-linux-x86_64.egg/gevent/subprocess.py in <module>()
      8 from gevent.event import AsyncResult
      9 from gevent.hub import get_hub, linkproxy, sleep, getcurrent, integer_types, string_types, xrange
---> 10 from gevent.fileobject import FileObject
     11 from gevent.greenlet import Greenlet, joinall
     12 spawn = Greenlet.spawn

/usr/lib64/python3.4/site-packages/gevent-1.1-py3.4-linux-x86_64.egg/gevent/fileobject.py in <module>()
     29 else:
     30 
---> 31     from gevent.socket import _fileobject, _get_memory
     32     cancel_wait_ex = IOError(EBADF, 'File descriptor was closed in another greenlet')
     33     from gevent.os import make_nonblocking

ImportError: cannot import name '_fileobject'

**Comment by dmwyatt** [comment]
Yes, would be good to get #409 merged to fix this issue.

**Comment by jamadden** [comment]
#409 has been merged, so this issue should be fixed. Please reopen if it's still a problem.
