### ISSUE TITLE
Setup script from Git version breaks during "install"

### ISSUE THREAD

**Issue by slaff** [gevent/gevent#478]
When I try to install gevent from the latest source from the git  repository using the command below:

```sudo python setup.py install```

I get the following error message:

```
Extracting gevent-1.1-py2.7-linux-i686.egg to /usr/local/lib/python2.7/dist-packages
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1-py2.7-linux-i686.egg/gevent/_socket3.py", line 133
    def makefile(self, mode="r", buffering=None, *,
                                                  ^
SyntaxError: invalid syntax
```

My Python version is:

```
Python 2.7.6 (default, Mar 22 2014, 22:59:38) 
[GCC 4.8.2] on linux2
```

**Comment by thedrow** [comment]
This issue is not relevant any more since Gevent master can be installed on Python 2 correctly now.

**Comment by oblalex** [comment]
Hi!
I have no idea why, but this issue is still relevant with 1.1b6 @ Python 2.7.
Any thoughts?

**Comment by jamadden** [comment]
That SyntaxError is expected and *not* a problem. You don't see it using 'pip' to install the distributions from PyPI, but there's nothing to do about it when running setup.py manually. See also #601.

**Comment by oblalex** [comment]
Usage of `pip` works like a charm out-of-the-box. But for a one insane reason I need to get a `RPM` package from `gevent` via `rpmbuild` without usage of `pip`. I cannot change this requirement and I would like to know whether there is some workaround?

Here is a `spec` for the package:

```
Name:           python-gevent
Version:        1.1b6
Release:        1%{?dist}
Summary:        Coroutine-based network library

Group:          Development/Libraries
License:        BSD
URL:            https://pypi.python.org/pypi/gevent
Source0:        https://pypi.python.org/packages/source/g/gevent/gevent-1.1b6.tar.gz
BuildArch:      x86_64

BuildRequires:  python2-devel
BuildRequires:  python-setuptools
BuildRequires:  python-nose
BuildRequires:  pytest
Requires:       python2

%description
Coroutine-based network library

%prep
%setup -q -n gevent-1.1b6

%build
%{__python2} setup.py build

%install
%{__python2} setup.py install -O1 --root %{buildroot}

%files
%doc LICENSE README.rst
/usr/lib/debug/*
/usr/lib64/python2.7/*
/usr/src/*
```

Please, could you share any thoughts on that? I appreciate your help anyway.

**Comment by jgehrcke** [comment]
As Jason said, **that SyntaxError is expected and not a problem**. Just ignore it. Your installation still works.

**Comment by oblalex** [comment]
Yeah, I understand it, but it's not easy to tell this to `rpmbuild` :sweat:. In normal `_socket3.py` should not even be loaded, but it gets and that is the problem. I guess, most easy way is to remove `_socket3.py`, and the right way is to switch to `pip`.

**Comment by jamadden** [comment]
I don't understand why this is a problem. Even though the syntax error is *printed*, `setup.py` still exits with a successful exit code (0). E.g.,:

```
$ python ./setup.py install
...
  File "//lib/python2.7/site-packages/gevent-1.1b7.dev0-py2.7-macosx-10.11-x86_64.egg/gevent/_socket3.py", line 165
    def makefile(self, mode="r", buffering=None, *,
                                                  ^
SyntaxError: invalid syntax

Adding gevent 1.1b7.dev0 to easy-install.pth file
...
Finished processing dependencies for gevent==1.1b7.dev0
$ echo $?
0
```

So the driving process shouldn't be able to know anything about the SyntaxError. As far as it knows, `setup.py` was successful. Which it was.

**Comment by oblalex** [comment]
Well, you are totally right, `setup.py install` exits with `0` code.

`rpmbuild` generates own temporary byte-compilation script which runs after `setup.py install` and then fails with SyntaxError. So, nothing is wrong with `gevent`. I'll provide a comment about this as far as I'll find solution. This might help someone in future.

**Comment by oblalex** [comment]
Finally, I make it to work. Just needed to skip execution of `brp-python-bytecompile` which exists with non-zero status code in case of errors. Skipping can be achieved by overriding `__os_install_post` hook:

```
%global __os_install_post /usr/lib/rpm/redhat/brp-compress \
  %{!?__debug_package:/usr/lib/rpm/redhat/brp-strip %{__strip}} \
  /usr/lib/rpm/redhat/brp-strip-static-archive %{__strip} \
  /usr/lib/rpm/redhat/brp-strip-comment-note %{__strip} %{__objdump} \
  /usr/lib/rpm/redhat/brp-python-hardlink
```

I've placed it at the top of the spec and now everything is OK.

Thanks you, guys!

**Comment by thedolphin** [comment]
insert
`%define _python_bytecompile_errors_terminate_build 0`
in your spec file
