### ISSUE TITLE
ssl broken on Debian (and derivatives), as of python 2.7.8-12

### ISSUE THREAD

**Issue by csillag** [gevent/gevent#513]
In v2.7.8-12 of the Debian python suit, which was released 3 days ago, they added [a patch](https://bugs.debian.org/cgi-bin/bugreport.cgi?msg=17;filename=python2.7-nossl3.patch;att=1;bug=768611), which, according to the [changelog](http://metadata.ftp-master.debian.org/changelogs//main/p/python2.7/python2.7_2.7.8-12_changelog),  "Allow building and testing without SSLv3 support"

In fact it removes many of the SSLv3-related constants, including `ROTOCOL_SSLv3`, which make gevent fail with a message similar to this:

```
  File "<whatever>/h/local/lib/python2.7/site-packages/gevent/ssl.py", line 386, in <module>
    def get_server_certificate(addr, ssl_version=PROTOCOL_SSLv3, ca_certs=None):
NameError: name 'PROTOCOL_SSLv3' is not defined
```

One could argue that it's not nice for a distribution to haphazardly remove constants that are still there in the upstream version, but these things happen, so... maybe gevent could do something about this?
(Like, maybe, move to  'PROTOCOL_SSLv23' instead?)

**Comment by Starefossen** [comment]
Ok, thanks a lot for fixing this issue, but we need a new version with this fix in. Any ETA on v1.0.2 @denik?

**Comment by csillag** [comment]
> Any ETA on v1.0.2 @denik or @Ivoz? 

+1

**Comment by bastianl** [comment]
> Any ETA on v1.0.2 @denik or @Ivoz?

+1

**Comment by pcdinh** [comment]
@denik It is time for a new release. Lots of people are waiting for it

**Comment by AxelVoitier** [comment]
Yes, please!

This bug is biting anyone using gevent in a docker container using the official image for python, as it uses a debian image as a base...

**Comment by aleksandr-vin** [comment]
I'm too on the waiting list, guys!

**Comment by dbrgn** [comment]
+1 here

**Comment by pedrudehuere** [comment]
+1 here

**Comment by lmanolov** [comment]
+1

**Comment by telbizov** [comment]
+1 here as well.

Jessie is now the Debian stable release as of a week ago. Just upgraded to it and my gevent based server experiences this problem.

Is there an ETA on releasing this in pip ?

**Comment by baljanak** [comment]
+1

**Comment by jonblack** [comment]
It drives me nuts all these "me too" posts. I want to know when this is fixed, hence I'm subscribed, but I really don't need to be notified every time someone waves their hands frantically in the air because they want it fixed.

**Comment by dbrgn** [comment]
The "+1" comments show to the maintainer that this is really an issue that affects a lot of people.

If people would use something like [Zenhub](https://www.zenhub.io/) they could +1 without commenting, thus solving that issue.

**Comment by tilgovi** [comment]
It's maybe worth asking if anyone knows @denik and whether they are okay. It's been five months since the last commit on master and since December that they last had any public activity on GitHub.

Is @denik okay?
Does the project need help from additional maintainers?

**Comment by Champax** [comment]
Hey,

Agreed, we really need a release to fix these SSL issues, and really need
to know if the project is still maintained and/or need maintainers...

Please revert.

Thanks.



2015-05-06 16:49 GMT+02:00 Randall Leeds <notifications@github.com>:

**Comment by jamadden** [comment]
@tilgovi I exchanged emails with @denik on the subject of additional maintainers yesterday. I don't want to put words in anybody's mouth or quote out of context, though.

**Comment by tilgovi** [comment]
@jamadden that's great to here. I was less worried about the project as I was about @denik :).
