### ISSUE TITLE
Group.join(raise_error=True) does not raise if the greenlet has been discarded

### ISSUE THREAD

**Issue by magnushiie** [gevent/gevent#521]
The following code finishes successfully:

```python
from gevent import sleep
from gevent.pool import Group

def raise_error():
    raise Exception("raise_error raising error")


group = Group()
group.spawn(raise_error)

sleep(0.5)

group.join(raise_error=True)
print "Joined"
```

Removing the sleep makes group.join() raise errors.

**Comment by thomasst** [comment]
I'm also running into this issue. Also, the method is missing documentation.

**Comment by jamadden** [comment]
The documentation for `Group` begins "Maintain a group of greenlets that are still running." Once a greenlet has finished running, it is no longer in the Group. In this example, by the time `group.join` is called, the `raise_error` greenlet has finished running and the group is empty...there is nothing in the Group to wait for, and the behaviour is as intended.

If you want to wait for arbitrary greenlets that may have already finished, try `gevent.joinall(greenlets, raise_error=True)`. You could write a wrapper for `Group` with an API compatible with it that uses `joinall`.

**Comment by flushentitypacket** [comment]
Just to be explicit for any future readers about @jamadden suggestion (since I was confused for a bit too), this is a way to fix the issue:

```python
import gevent
from gevent import sleep
from gevent.pool import Group

def raise_error():
    raise Exception("raise_error raising error")

greenlets = []
group = Group()
greenlets.append(group.spawn(raise_error))

sleep(0.5)

gevent.joinall(greenlets, raise_error=True)
print "Joined"
```

This also seems to work with `Pool`s.
