### ISSUE TITLE
Allow passing of events (`pass_events`) to the IO callback

### ISSUE THREAD

**Issue by mnunberg** [gevent/gevent#531]
The C version has a `pass_events` kwarg which lets the callback receive the actual events which took place. This might be useful for integration with other lower level libraries, as it saves on the check in Python itself.

Can you add this to the coreffi layer?

See https://github.com/gevent/gevent/blob/72119c8c3e704b75a2d91d8555ca8673928ebabb/gevent/corecffi.py#L761 for an example, and

https://github.com/couchbase/couchbase-python-client/blob/8cbd028432dab97701c6396c40f2899b881e0016/gcouchbase/iops_gevent10.py#L29-41 for a use case

**Comment by jamadden** [comment]
If someone were to submit a PR that does this and includes a test case I'd be happy to review it.

**Comment by jamadden** [comment]
This was implemented in PR #604.
