### ISSUE TITLE
 Monkey patched  boto is not thread-safe

### ISSUE THREAD

**Issue by aktywnitu** [gevent/gevent#535]
After running gunicorn with gevent I have some error in my log:
```
  File "/opt/app/venv/local/lib/python2.7/site-packages/boto/s3/key.py", line 981, in should_retry
    '%s vs. %s' % (self.etag, self.md5))

S3DataError: BotoClientError: ETag from S3 did not match computed MD5. "aadef69fe4340beac4d8f9e5c5246105" vs. 5f89db4b7b145346ee28d5c0a03d6a9d
```

Here are some information about this problem:
http://thinkinghard.com/blog/MultiThreadedPythonS3Application.html

Before running gevent I have readln that many people use it with boto s3, but i see that it is not such easy to make it working. I use s3 storage library for django, which use popular boto library.

My s3 django storage backend make connection with cloud in init:
```
  conn = S3Connection('secret','secret', host = 'example.com')
  self.bucket = conn.get_bucket('pics')
  self.key = Key(bucket)
```

**Comment by jamadden** [comment]
Can you be more specific about why you think this is a gevent issue? Perhaps the mailing list is the place to ask general questions like this; the issue tracker should be used for specific issues with gevent itself. I personally work on a project that heavily uses boto in a monkey-patched environment so I'm reasonably confident that it should work as expected.

**Comment by jamadden** [comment]
Closing because it's been a year (and numerous gevent releases) since there was feedback. Our large project continues to run with gevent+boto. If you still have this issue, please try the mailing list or opening a new, more specific, issue.
