### ISSUE TITLE
gevent / requests hangs while making lots of head requests

### ISSUE THREAD

**Issue by vgoklani** [gevent/gevent#536]
I need to make 100k head requests, and I'm using gevent on top of requests. My code runs for a while, but then eventually hangs. I'm not sure why it's hanging, or whether it's hanging inside requests or gevent. I'm using the timeout argument inside both requests and gevent.

Please take a look at my code snippet below, and let me know what I should change.

```python
import gevent
from gevent import monkey, pool
monkey.patch_all()
import requests

def get_head(url, timeout=3):
    try:
        return requests.head(url, allow_redirects=True, timeout=timeout)
    except:
        return None

def expand_short_urls(short_urls, chunk_size=100, timeout=60*5):
    chunk_list = lambda l, n: ( l[i:i+n] for i in range(0, len(l), n) )
    p = pool.Pool(chunk_size)
    print 'Expanding %d short_urls' % len(short_urls)
    results = {}
    for i, _short_urls_chunked in enumerate(chunk_list(short_urls, chunk_size)):
        print '\t%d. processing %d urls @ %s' % (i, chunk_size, str(datetime.datetime.now()))
        jobs = [p.spawn(get_head, _short_url) for _short_url in _short_urls_chunked]
        gevent.joinall(jobs, timeout=timeout)
        results.update({_short_url:job.get().url for _short_url, job in zip(_short_urls_chunked, jobs) if job.get() is not None and job.get().status_code==200})
    return results 
```

**Comment by jaddison** [comment]
I'm willing to bet that "Setting the environment variable GEVENT_RESOLVER=ares fixes the hang." as has been discovered in various projects that use gevent.

I started using this a couple of weeks ago due to hangs in gunicorn when using the gevent pool/worker model. Observationally, everything seems more stable.

**Comment by thedrow** [comment]
@jaddison Wait isn't that the default?

**Comment by jaddison** [comment]
@thedrow: not according to http://www.gevent.org/whatsnew_1_0.html#new-dns-resolver.

**Comment by thedrow** [comment]
Oh cool I learned something new.

**Comment by jamadden** [comment]
Since there have been no updates on the original issue in over a year I'm going to close this. Please feel free to re-open with additional information.
