### ISSUE TITLE
gevent has function wait or not

### ISSUE THREAD

**Issue by wolfxiaozhai** [gevent/gevent#537]
https://github.com/gevent/gevent/blob/master/examples/concurrent_download.py#L1 
In the example, the last line, gevent.wait(jobs), did not work. 
Instead using the function wait, I used joinall, and it worked well.
In my computer, gevent.version_info is (0,13,6)

**Comment by pigmej** [comment]
current gevent version is 1.x+ you have oldish / broken 0.13.x series. that's why.
