### ISSUE TITLE
using dns=False in monkey.patch_all still monkey-patches some DNS calls

### ISSUE THREAD

**Issue by denik** [gevent/gevent#54]
Even if dns=False in calls to monkey.patch_all etc., socket.connect and create_connection still use gevent's dns functions.

I expected passing dns=False to use the built-in socket synchronous DNS functions.

<p><a href="http://code.google.com/p/gevent/issues/detail?id=54">Reported by dcreemer.</a></p><hr/><h2>earlier comments</h2>
<p><strong>equand said, at 2010-11-01T06:32:40.000Z:</strong></p>

<p>yes found this problem when forking, the gevent dns doesn't work at all in multiple server configuration, when using urllib for example, had to patch with pycurl all the code...
urllib is still monkeypatched through httplib...</p><p><strong>Denis.Bilenko said, at 2012-01-13T09:32:00.000Z:</strong></p>

<p>This issue is still not solved, however, with 1.0b1 there are options that might be helpful if you find you want to avoid gevent DNS functions:

Setting GEVENT_RESOLVER=block environment variable would disable c-ares based resolver and use standard blocking functions

Setting GEVENT_RESOLVER=thread would also disable c-ares based resolver and use standard blocking functions in a thread pool.</p>

**Comment by jamadden** [comment]
Because `GEVENT_RESOLVER=thread' is the default in 1.0 and 1.1, this should be much less of an issue.

**Comment by jamadden** [comment]
Closing in triage for 1.2a1 since there has been no further input since 2012, and things have changed substantially since then.
