### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by geekgao** [gevent/gevent#547]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with gevent. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable gevent on @Sourcegraph by going to https://sourcegraph.com/github.com/gevent/gevent and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by denik** [comment]
I've enabled it.
