### ISSUE TITLE
wait_read() doesn't yield after receiving an exception

### ISSUE THREAD

**Issue by wolever** [gevent/gevent#548]
I noticed this issue with psycogreen, but after some investigation it seems gevent related.

In short:
1. wait_read(…) is called on an fd connected to Postgres ([source](https://bitbucket.org/dvarrazzo/psycogreen/src/115d0627da1ac9ff48c0cb9287257cd35868cdf9/psycogreen/gevent.py?at=master#cl-33); according to `lsof` the socket in question is a regular TCP socket: `… 7u IPv6 0xefd47d4c0050a443       0t0      TCP localhost:56666->localhost:postgresql (ESTABLISHED)`)
2. A `Timeout()` exception is raised in the thread waiting on the socket
3. The thread begins to block the world and doesn't yield control until there are data to read

On investigating with strace, it appears that `epoll_wait` is used before the exception is raised, but a regular `poll` is used after the exception. Line `A`, below, shows where `epoll` is correctly used to wait on the Postgres socket (fd=5), and line `B` shows the call to `poll` after the exception is raised:

```
   21:08:31 recvfrom(5, "C\0\0\0\nBEGIN\0C\0\0\0\10SET\0Z\0\0\0\5T", 16384, 0, NULL, NULL) = 26
   21:08:31 sendto(5, "Q\0\0\0\30select pg_sleep(10)\0", 25, MSG_NOSIGNAL, NULL, 0) = 25
   21:08:31 epoll_ctl(3, EPOLL_CTL_ADD, 5, {EPOLLIN, {u32=5, u64=21474836485}}) = -1 EEXIST (File exists)
   21:08:31 clock_gettime(CLOCK_MONOTONIC, {179866, 55234130}) = 0
A: 21:08:31 epoll_wait(3, {}, 64, 4979)    = 0
   21:08:36 clock_gettime(CLOCK_MONOTONIC, {179871, 39352128}) = 0
   21:08:36 gettimeofday({1427332116, 435776}, NULL) = 0
B: 21:08:36 poll([{fd=5, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=5, revents=POLLIN}])
   21:08:41 recvfrom(5, "T\0\0\0!\0\1pg_sleep\0\0\0\0\0\0\0\0\0\10\346\0\4\377\377\377\377"..., 16384, 0, NULL, NULL) = 65
   21:08:41 fstat(1, {st_mode=S_IFREG|0664, st_size=443149, ...}) = 0
   21:08:41 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd4aef1b000
   21:08:41 gettimeofday({1427332121, 454229}, NULL) = 0
```

I've tested on both OS X 10.8.4 and Linux + epoll.

Original psycogreen issue: https://bitbucket.org/dvarrazzo/psycogreen/issue/1/gevent-exceptions-are-ignored-while

**Comment by wolever** [comment]
Test case to recreate the problem on Linux and OS X:

```
#!python

import time

from gevent import monkey
monkey.patch_all(subprocess=True)

from psycogreen.gevent import patch_psycopg
patch_psycopg()

import psycopg2

import gevent

start = time.time()

def spinner():
    while True:
        gevent.sleep(0.5)
        print "ping: %0.01f" %(time.time() - start)

try:
    gevent.spawn(spinner)
    gevent.Timeout(2).start()
    cxn = psycopg2.connect("host=localhost")
    cur = cxn.cursor()
    cur.execute("select pg_sleep(5)")
finally:
    print "=" * 80
    print "ELAPSED: %0.01f" %(time.time() - start)
    print "=" * 80
```

Note that a `Timeout` should be raised after  2 second, but instead it is raised after 5 seconds, and the main thread is blocked (even to `^C`) after 2 seconds:

```
$ python test.py
ping: 0.5
ping: 1.0
ping: 1.5
================================================================================
ELAPSED: 5.0
================================================================================
Traceback (most recent call last):
    …
gevent.timeout.Timeout: 2 seconds
```

**Comment by jamadden** [comment]
I am unable to reproduce this on current master (roughly gevent 1.1a1) using the following script (which takes third-party code out of the equation---but I may have misunderstood). Can you still reproduce this? If so, can you please update your test case to simply use plain sockets?

```python
import time

from gevent import monkey
monkey.patch_all()

import gevent
from gevent import socket

start = time.time()

def spinner():
	while True:
		gevent.sleep(0.5)
		print( "ping: %0.01f" %(time.time() - start) )

try:
	gevent.spawn(spinner)
	gevent.Timeout(2).start()
	cxn = socket.create_connection(('127.0.0.1', 8080))
	data = socket.wait_read(cxn.fileno())
finally:
	print( "ELAPSED: %0.01f" %(time.time() - start) )
```

```
ping: 0.5
ping: 1.0
ping: 1.5
ELAPSED: 2.0
Traceback (most recent call last):
  File "/tmp/test.py", line 20, in <module>
    data = socket.wait_read(cxn.fileno(), timeout=4)
  File "/gevent/_socketcommon.py", line 136, in wait_read
    return wait(io, timeout, timeout_exc)
    ...
gevent.timeout.Timeout: 2 seconds
```

**Comment by wolever** [comment]
Hurumph. You're very right — I can't recreate using your testcase either, so it's very possible that this is an issue with psycogreen / psycopg. Thanks for taking the time to take a look!
