### ISSUE TITLE
ImportError: undefined symbol: PyUnicodeUCS4_DecodeUTF8

### ISSUE THREAD

**Issue by dyf102** [gevent/gevent#549]
It displays the error "ImportError: /usr/local/lib/python2.7/dist-packages/gevent/_semaphore.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8" when I import "from gevent.fileobject import FileObjectThread"
gevent version is 1.0.1
install it by pip in python 2.7.9, Ubuntu 14.04.2 LTS. The problem shows when I upgraded python from 2.7.5(system default version) to 2.7.9 from source code.
Is there any way to solve it?
THANKS

**Comment by jamadden** [comment]
It seems like you've gone from a "wide unicode" Python build to a "narrow unicode" Python build. The two types of Python builds have different ABIs, and any C extension modules that were installed with one are likely to fail on the other with an error similar to this. The solution is to uninstall and re-install the package, thus recompiling the C code with the correct ABI.
