### ISSUE TITLE
gevent.socket.wait_read with timeout yields segmentation fault

### ISSUE THREAD

**Issue by nils-werner** [gevent/gevent#555]
On a Raspberry Pi running Arch Linux and Python 2.7.8 and the following environment

    gevent (1.0.1)
    greenlet (0.4.5)
    pip (1.5.6)
    setuptools (3.6)
    wsgiref (0.1.2)

the following code **results in a segmentation fault**:

    import sys
    import gevent
    import gevent.socket

    def tasklet():
        while True:
            try:
                gevent.socket.wait_read(sys.stdin.fileno(), timeout=1)
                string = sys.stdin.readline()
            except gevent.socket.timeout:
                print "timeout"

    gevent.spawn(tasklet)
    while True:
        gevent.sleep(0.5)

while the following does not:

    import sys
    import gevent
    import gevent.socket

    def tasklet():
        while True:
            gevent.socket.wait_read(sys.stdin.fileno())
            string = sys.stdin.readline()

    gevent.spawn(tasklet)
    while True:
        gevent.sleep(0.5)

**Comment by jamadden** [comment]
Others have reported (#543) that compiler optimizations on ARM can cause segmentation faults. Can you try compiling gevent and greenlet without optimizations and see if that fixes the problem?

**Comment by jamadden** [comment]
I can't reproduce this with Python 2.7.9 and gevent 1.1 on a raspberry pi, with the usual -O2 optimization level. Please feel free to reopen if this still occurs for you or you have more information.
