### ISSUE TITLE
hub.loop.stat is *very* slow under Windows

### ISSUE THREAD

**Issue by fpom** [gevent/gevent#563]
Dear all,

I'm trying to have a portable system to watch updates on a file system, I've created one that rely on  `gevent.get_hub().loop.stat`. While it works perfectly fine under Linux, it's terribly slow under Windows: some updates take up to 30s to be reported. Here is the code, I think it's quite straightforward but I'll add some comments below: https://gist.github.com/fpom/92a690a8cf89cebd7d4a

`Timeout` is needed to handle situations where we remove entire directories, eg: if we have `foo/` and `foo/bar`, then when we delete `foo`, `foo/bar` is not detected as changed. But because we remove it from `self.w`, it will destroy itself on its next timeout.

As far as I understand, `gevent` is performing poling under Windows and uses `inotify` under Linux. This may explain small delays and this is also the reason for setting `stat(path, 1)` and `Timeout(2)` in my code. But I don't understand how this can explain the delays I observe.

Any help will be welcome. Thanks in advance!
Franck

**Comment by fpom** [comment]
I've written a blog post to explain the code: https://www.ibisc.univ-evry.fr/~fpommereau/blog/2015-05-28-watching-filesystem-updates-with-gevent.html
So far, I still have no idea about why the Windows version is so slow...

Can't anybody help me? Thanks!
Franck

**Comment by jamadden** [comment]
gevent's stat watcher is just a small wrapper around libev's stat watcher. Under all non-linux systems, it's implemented as repeated polling through libev timers. The amount of time between polling checks doesn't vary by system as far as I can tell. If you have many (many) watchers active, I suppose it's possible that the event loop can take awhile to get around to each of them, especially if the filesystem is at all slow (the underlying `stat` function is blocking and may perform disk I/O). 

There are simple tests in the gevent source code that check how long stat watchers take to respond (greentest/test__core_stat.py). They pass for me under OS X, which uses polling. You may try running that and seeing if they fail for you on your platform.

Other than that, you may have better luck asking on the libev mailing list or issue tracker.

**Comment by fpom** [comment]
Indeed, timings are very different: around 0.001 seconds under Linux, but 4.5160 under Windows. If the event loop pays so much for each watcher started, I understand better the problem. I'll have to find another solution...

Thanks a lot for your help!
Franck
