### ISSUE TITLE
pip install gevent fails for python 3

### ISSUE THREAD

**Issue by AnilRedshift** [gevent/gevent#566]
Somewhere along the distribution chain, there is a stale version of gevent that isn't compatible with python 3. Setup.py has the following python2-only code when running `pip install gevent` (with a python 3 virtualenv on OSX):
  
     
      File "/private/var/folders/l1/q9ks4p3s2xj8b54pnc2vlb_w0000gn/T/pip-build-w36lj8pf/gevent/setup.py", line 111, in make_universal_header
        print >>f, line
    TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'
    Running '/bin/sh /private/var/folders/l1/q9ks4p3s2xj8b54pnc2vlb_w0000gn/T/pip-build-w36lj8pf/gevent/libev/configure > configure-output.txt' in /private/var/folders/l1/q9ks4p3s2xj8b54pnc2vlb_w0000gn/T/pip-build-w36lj8pf/gevent/build/temp.macosx-10.10-x86_64-3.4/libev
    
  
but from looking at the source code for setup.py on github, that line doesn't exist. Running `pip install cython git+git://github.com/gevent/gevent.git#egg=gevent` works fine locally.

**Comment by AnilRedshift** [comment]
Ok so looking at https://github.com/gevent/gevent/releases/tag/v1.0.2 this release has the offending non-functional print line for python 3. This line was fixed in 2013, with this commit:
https://github.com/gevent/gevent/commit/08570bf3b752128bdfbced840110371b0c33bc26

Can someone please rev a new version that picks up this fix, thanks.

    def make_universal_header(filename, *defines):
    defines = [('#define %s ' % define, define) for define in defines]
    lines = open(filename, 'r').read().split('\n')
    ifdef = 0
    f = open(filename, 'w')
    for line in lines:
        if line.startswith('#ifdef'):
            ifdef += 1
        elif line.startswith('#endif'):
            ifdef -= 1
        elif not ifdef:
            for prefix, define in defines:
                if line.startswith(prefix):
                    line = '#ifdef __LP64__\n#define %s 8\n#else\n#define %s 4\n#endif' % (define, define)
                    break
        print >>f, line
    f.close()`

**Comment by jamadden** [comment]
There is no released version of gevent that supports Python 3. The development version features *partial* support, but it is not yet ready for release (e.g., there are known problems with sockets).

**Comment by gitaarik** [comment]
By now Python 3 support is pretty good! :)
https://github.com/gevent/gevent/issues/38
