### ISSUE TITLE
Strange context switch with garbage collector

### ISSUE THREAD

**Issue by max0d41** [gevent/gevent#567]
Since I updated from gevent 1.0.1 to 1.0.2 and, at the same time updated from greenlet 0.4.6 to 0.4.7 I get a strange behaivor with WeakValueDictionary.
  Here is a stack of a deadlock that appeared since the garbage collector called the `__delitem__` function twice in the same greenlet:
  ```
    File "foobar/httpserver/__init__.py", line 233, in _call_api
      return make_response((result, status_code, headers))
    File "/usr/lib/python2.7/weakref.py", line 54, in remove
      del self.data[wr.key]                                     <<< First garbage collection
    File "foobar/util.py", line 257, in __delitem__
      redis.unsubscribe('ItemChannel:%s' % key)    <<< Here the lock was acquired the first time
    File "/lib/python2.7/site-packages/redis/client.py", line 2210, in unsubscribe
      return self.execute_command('UNSUBSCRIBE', *args)
    File "/lib/python2.7/site-packages/redis/client.py", line 2128, in execute_command
      self._execute(connection, connection.send_command, *args)
    File "/lib/python2.7/site-packages/redis/client.py", line 2132, in _execute
      return command(*args)
    File "/lib/python2.7/site-packages/redis/connection.py", line 556, in send_command
      self.send_packed_command(self.pack_command(*args))
    File "/lib/python2.7/site-packages/redis/connection.py", line 610, in pack_command
      for arg in imap(self.encode, args):                       <<< I think here is a conext switch possible
    File "/usr/lib/python2.7/weakref.py", line 54, in remove
      del self.data[wr.key]                                     <<< Second garbage collection, the same code will be called again
    File "foobar/util.py", line 257, in __delitem__
      redis.unsubscribe('ItemChannel:%s' % key)
    File "/foobar/repubsub2.py", line 46, in unsubscribe
      with self._lock:                                          <<< Second lock acquire (deadlock)
  ```

Here is the `__delitem__` function:
  ```
  def __delitem__(self, key):
      super(GlobalCallbackDict, self).__delitem__(key)
      redis.unsubscribe('ItemChannel:%s' % key)
  ```

When the network IO of redis started the garbage collector told the current greenlet to jump to a completely other code position than it was before and this resulted in a deadlock.
However, I fixed my code but think this behavior is kind of strange.

**Comment by jamadden** [comment]
I don't actually see any network I/O taking place yet in that stack. Line 610 of `connection.py` is invoking the builtin `map` function under Python 2.7. The `map` function allocates and populates a list, in this case with the result of invoking `self.encode`; both operations can cause memory allocation, and any memory allocation can potentially lead to the garbage collector being run. So it looks to me like gevent/greenlet probably had nothing to do with this, it was just an unfortunate coincidence exposing a pre-existing deadlock condition (an item is deleted from a dictionary while another item is deleted from that dictionary; it wouldn't even take the GC to trigger it).

Closing in triage for 1.1. Please feel free to comment or open other issues if this analysis seems wrong.
