### ISSUE TITLE
use “while true” in gevent(Greenlets), the program will stop gradually

### ISSUE THREAD

**Issue by binhe22** [gevent/gevent#587]
I want to make the function run all the time:

```
  def check_all_proxy():
        while True:
            try:
                r = get_redis()
                proxy = r.spop(tmp_key)
                if proxy == None:
                    gevent.sleep(3)
                    continue
                if_right, used_time = check_proxy(proxy, TEST_URL)
                if if_right:
                    r.sadd(key, proxy)
                else:
                    r.setex(proxy, 1, 120)
                gevent.sleep(0) 
            except:
                gevent.sleep(2)
   gevent.joinall([gevent.spawn(check_all_proxy) for i in xrange(200)])

```
But it will stop gradually. What is the reason?

Thanks

**Comment by jgehrcke** [comment]
Hallo! This issue tracker is for you to submit details after having identified an issue with gevent. For support questions, please refer to the mailing list.

However, if you describe your problem like this, it is not likely that you will get some help. You did not properly describe what you want to achieve or what the desired behavior of your code is. On top of that you also did not properly describe how your code "fails". Apart from this, your code smells in many regards. You surely want to get rid of that over-generalized try/except block and, instead, write more explicit code.

**Comment by jamadden** [comment]
Closing for lack of specific details. Please try asking questions like this on the mailing list. Or please feel free to re-open or submit a new issue if you feel like you've found a specific problem.
