### ISSUE TITLE
pip3 install gevent error! unsupported operator "printf >>f"

### ISSUE THREAD

**Issue by summer1988** [gevent/gevent#596]
I met an error while using "pip3 install gevent" command.
File "/private/var/folders/nq/9wqvtf292m7dtrj37tcld4bw0000gn/T/pip-build-77znm6uq/gevent/setup.py", line 139, in configure_libev
        make_universal_header('config.h', 'SIZEOF_LONG', 'SIZEOF_SIZE_T', 'SIZEOF_TIME_T')
      File "/private/var/folders/nq/9wqvtf292m7dtrj37tcld4bw0000gn/T/pip-build-77znm6uq/gevent/setup.py", line 111, in make_universal_header
        print >>f, line
I think its a setup.py compatibility error. How can I fix it ? just fix the setup.py file ?

**Comment by squeaky-pl** [comment]
Can you try `pip3 install https://github.com/gevent/gevent/archive/master.zip` instead?

I think latest stable version on pypi is not python 3 ready.

**Comment by summer1988** [comment]
Thanks for your help. I try the github master version. But I got this syntax error and warning:
```
creating dist
creating 'dist/gevent-1.1a2.dev0-py2.7-macosx-10.10-x86_64.egg' and adding 'build/bdist.macosx-10.10-x86_64/egg' to it
removing 'build/bdist.macosx-10.10-x86_64/egg' (and everything under it)
Processing gevent-1.1a2.dev0-py2.7-macosx-10.10-x86_64.egg
creating /usr/local/lib/python2.7/site-packages/gevent-1.1a2.dev0-py2.7-macosx-10.10-x86_64.egg
Extracting gevent-1.1a2.dev0-py2.7-macosx-10.10-x86_64.egg to /usr/local/lib/python2.7/site-packages
  File "/usr/local/lib/python2.7/site-packages/gevent-1.1a2.dev0-py2.7-macosx-10.10-x86_64.egg/gevent/_socket3.py", line 157
    def makefile(self, mode="r", buffering=None, *,
                                                  ^
SyntaxError: invalid syntax

Adding gevent 1.1a2.dev0 to easy-install.pth file

Installed /usr/local/lib/python2.7/site-packages/gevent-1.1a2.dev0-py2.7-macosx-10.10-x86_64.egg
Processing dependencies for gevent==1.1a2.dev0
Searching for greenlet==0.4.7
Best match: greenlet 0.4.7
Adding greenlet 0.4.7 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Finished processing dependencies for gevent==1.1a2.dev0

WARNING: The gevent.ares extension has been disabled.
```
Does it matter ?

**Comment by squeaky-pl** [comment]
I am confused. In the second output I see Python 2.7, not Python 3. Anyway this question doesnt belong to bugtracker. It might be answered faster on IRC or mailing list.

**Comment by summer1988** [comment]
@squeaky-pl 
Sorry. I made a mistake.
Thank you very much ...
