### ISSUE TITLE
pywsgi.py UnicodeEncodeError

### ISSUE THREAD

**Issue by jiangjianxiao** [gevent/gevent#599]
current like line 431

 towrite.extend(('%s: %s\r\n' % header).encode('latin-1'))

in python 2.7 , header like 

response.set_header('Content-disposition', 'attachment; filename=中文文件名') # bottle encoding utf-8

raise 

UnicodeEncodeError: 'latin-1' codec can't encode characters in position x-x: ordinal not in range(256)

**Comment by methane** [comment]
It's not a bug.  There are no right answer about it.
See http://greenbytes.de/tech/webdav/rfc6266.html#rfc.section.D

**Comment by jiangjianxiao** [comment]
thanks
