### ISSUE TITLE
Support patching select.poll

### ISSUE THREAD

**Issue by 3ddi** [gevent/gevent#602]
Being used in many python libraries, and is supported by eventlet.

**Comment by jamadden** [comment]
Hmm, in eventlet's [select module](https://github.com/eventlet/eventlet/blob/master/eventlet/green/select.py) I don't see any evidence that it supports `epoll`. Am I looking in the wrong place?

Pull requests welcome!

**Comment by 3ddi** [comment]
You are right, they simply don't use aggressive removal of poll/epoll by default. so you get a patched select.poll witch is not green.
Nevertheless, I'm adding a green poll support.

**Comment by jamadden** [comment]
Merged in 722f833
