### ISSUE TITLE
PyWSGI doesn't seem to be stoppable

### ISSUE THREAD

**Issue by zstars** [gevent/gevent#613]
pywsgi.WSGIServer doesn't seem to react to stop(). Looking at the code, it seems that it doesn't actually do anything when the _server_stop event is set, so the server just keeps running.

Is this actually a mistake on my part? Is there actually any way to stop the server?

**Comment by jamadden** [comment]
I can't reproduce that. While `pywsgi.WSGIServer` itself doesn't do anything with the stop method, the superclass, `gevent.baseserver.BaseServer` does. Specifically, it stops accepting new connections and closes the listening socket, making it impossible to handle new connections.

Given this script:

```python
from gevent import monkey
monkey.patch_all()

from gevent import pywsgi
import socket

def application(env, start_response):
	start_response('200 OK', [('Content-Type', 'text/plain'), ('Content-Length', '11')])
	return [b'hello ', b'world']

server = pywsgi.WSGIServer(('127.0.0.1', 0), application)
server.start()

def talk_to_server():
	sock = socket.create_connection(('127.0.0.1', server.server_port))
	fd = sock.makefile('rwb')
	fd.write(b'GET / HTTP/1.0\r\n\r\n')
	fd.flush()
	print("\tFrom server:", fd.readline(), '\n')

# First one works fine, server is listening
talk_to_server()

# Stop the server
server.stop()

# This should now raise a socket error
talk_to_server()
```

I get the expected output:

```
$ python /tmp/test.py
127.0.0.1 - - [2015-07-14 11:43:51] "GET / HTTP/1.0" 200 132 0.000449
	From server: b'HTTP/1.1 200 OK\r\n'

Traceback (most recent call last):
  File "/tmp/test.py", line 28, in <module>
    talk_to_server()
  File "/tmp/test.py", line 15, in talk_to_server
    sock = socket.create_connection(('127.0.0.1', server.server_port))
  File "/.../gevent/socket.py", line 73, in create_connection
    raise err
  File "/.../gevent/socket.py", line 60, in create_connection
    sock.connect(sa)
  File "/.../gevent/_socket3.py", line 252, in connect
    raise error(err, strerror(err))
ConnectionRefusedError: [Errno 61] Connection refused
```

Note that if you have requests in progress, what happens to *them* depends on how you configured the server (with a pool or not) and what timeout you pass to `stop`. In the case of no pool, nothing is done to requests in progress, they are allowed to finish gracefully (they may be in the middle of complicated transactions).

**Comment by zstars** [comment]
I see, thank you. 

The requests I was doing were keeping the connection alive, so the server was receiving an unlimited number of HTTP requests after the .stop(). I understand now that this is probably the expected behaviour (though not a too intuitive one, if you think of each HTTP request as discrete).

In case anyone wants to check, the code to "test" this behaviour (which is probably correct nonetheless), would be:

```python

from gevent import monkey
import gevent

monkey.patch_all()

from gevent import pywsgi
import socket

def handle_request(env, start_response):
    start_response('200', [('Content-Type', 'text/plain')])
    return ['HELLO']

server = pywsgi.WSGIServer(('127.0.0.1', 0), handle_request)
server.start()

sock = socket.create_connection(('127.0.0.1', server.server_port))
fd = sock.makefile('rwb')

def do_http_request(fd):
    fd.write(b'GET / HTTP/1.1\r\n\r\n')
    fd.flush()

    r = fd.readline()
    while len(r.strip()) > 0:
        r = fd.readline()
        print("\tFrom server:", r, '\n')

# Works
do_http_request(fd)

# Stop the server
server.stop()

# Works
do_http_request(fd)

# Works
do_http_request(fd)

```

I'll probably just start sending a Connection: Close header, or find some way to notify the request handler that it should actually stop accepting new requests.

Thanks for your help!

**Comment by jamadden** [comment]
If you want the WSGIServer to track outstanding greenlets, you need to pass a `Pool` for the `spawn` argument. (A Pool with no `size` given is unbounded and simply tracks open greenlets.) Making these changes to that script:

```python
from gevent.pool import Pool

server = pywsgi.WSGIServer(('127.0.0.1', 0), application, spawn=Pool())
```

Causes the open connection to get killed when the server is stopped:

```
27.0.0.1 - - [2015-07-16 07:06:09] "GET / HTTP/1.1" 200 113 0.000281
	From server: b'Content-Type: text/plain\r\n'

	From server: b'Content-Length: 11\r\n'

	From server: b'Date: Thu, 16 Jul 2015 12:06:09 GMT\r\n'

	From server: b'\r\n'

Traceback (most recent call last):
  File "/tmp/test.py", line 35, in <module>
    do_http_request(fd)
  File "/tmp/test.py", line 23, in do_http_request
    r = fd.readline()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
  File "//gevent/_socket3.py", line 305, in recv_into
    return _socket.socket.recv_into(self._sock, *args)
ConnectionResetError: [Errno 54] Connection reset by peer
```
