### ISSUE TITLE
pytest failing on python3.4 but not 2.7

### ISSUE THREAD

**Issue by mzdaniel** [gevent/gevent#615]
Hi there and thank you for this wonderful project!

I've been using gevent and pytest, and found this on debian and archlinux::

    $ cat test_gevent.py 
    import gevent.monkey
    gevent.monkey.patch_all()

    pip2 freeze | grep gevent
    gevent==1.1a2

    $ py.test-2.7 test_gevent.py 
    ======================================= test session starts ========================================
    platform linux2 -- Python 2.7.10 -- py-1.4.30 -- pytest-2.7.2
    rootdir: /data/salt/prog/sphinxserve, inifile: 
    collected 0 items 
    =========================================  in 0.01 seconds =========================================

    $ pip freeze | grep gevent
    gevent==1.1a2

    $ py.test-3.4 test_gevent.py 
    ======================================= test session starts ========================================
    platform linux -- Python 3.4.3 -- py-1.4.30 -- pytest-2.7.2
    rootdir: /data/salt/prog/sphinxserve, inifile: 
    collected 0 items / 1 errors 
    ============================================== ERRORS ==============================================
    ______________________________ ERROR collecting tests/test_gevent.py _______________________________
    /usr/lib/python3.4/site-packages/py/_path/local.py:650: in pyimport
        __import__(modname)
    <frozen importlib._bootstrap>:2237: in _find_and_load
        ???
    <frozen importlib._bootstrap>:269: in __exit__
        ???
    <frozen importlib._bootstrap>:221: in release
        ???
    E   RuntimeError: cannot release un-acquired lock
    ----------------------------------------- Captured stderr ------------------------------------------
    Monkey-patching not on the main thread; threading.main_thread().join() will hang from a greenlet
    ===================================== 1 error in 0.06 seconds ======================================

**Comment by jamadden** [comment]
Interesting. One of the many things that py.test imports before loading user-modules is causing the monkey-patching to be done incorrectly. In general, monkey-patching relatively late in the lifetime of a process like this is not recommended (though we do try to not let it fail spectacularly). I'll look into it, but I don't know if we'll be able to do anything about it.

Two ways to fix this now:

- Use the monkey module to run the code: `python -m gevent.monkey 'which py.test' ...`
- Disable the thread patch: `gevent.patch_all(thread=False)`

**Comment by jamadden** [comment]
I can reproduce the same error under Python2.6/7 with the following script; I cannot reproduce it with Python 3.3/4, probably because RLock has been implemented in C in those versions. So importlib must be using the python version of the lock?

```python
from gevent import monkey
import threading
with threading.RLock():
	monkey.patch_all()
```

```
Traceback (most recent call last):
  File "/tmp/test.py", line 4, in <module>
    monkey.patch_all()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 216, in __exit__
    self.release()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 204, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock
```

**Comment by pigmej** [comment]
Isn't this‎ related to https://github.com/gevent/gevent/issues/308 ?(I'm on mobile so...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Jason MaddenSent: środa, 15 lipca 2015 17:50To: gevent/geventReply To: gevent/geventSubject: Re: [gevent] pytest failing on python3.4 but not 2.7 (#615)I can reproduce the same error under Python2.6/7 with the following script; I cannot reproduce it with Python 3.3/4, probably because RLock has been implemented in C in those versions. So importlib must be using the python version of the lock?

from gevent import monkey
import threading
with threading.RLock():
    monkey.patch_all()

Traceback (most recent call last):
  File "/tmp/test.py", line 4, in <module>
    monkey.patch_all()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 216, in __exit__
    self.release()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 204, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock


—Reply to this email directly or view it on GitHub.

**Comment by jamadden** [comment]
Not really. This seems to be because we're swapping the thread ident
out from under an active lock (after patch it's the greenlet id)

**Comment by mzdaniel** [comment]
@jamadden: Yes, as you mention, both running code using the monkey module and disabling threading work, so certainly these are great options to have. Sometimes I do the monkeypatching on sitecustomize.py to try to give gevent the best chance without touching test code. In this case, it seems that it is not enough, but the interesting part is that the same error occur::

    PYTHONPATH=. py.test-3.4 test_gevent.py
    Error in sitecustomize; set PYTHONVERBOSE for traceback:
    RuntimeError: cannot release un-acquired lock
    Failed to import the site module
    Traceback (most recent call last):
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 269, in __exit__
      File "<frozen importlib._bootstrap>", line 221, in release
    RuntimeError: cannot release un-acquired lock

Hope it helps.

**Comment by jamadden** [comment]
@mzdaniel Yes, that's the same basic problem. The problem occurs if `gevent.monkey.patch_all` is executed *while* another import statement is active. In the case of `sitecustomize.py`, it goes like this: The python interpreter executes `import site`; at the top-level of `site.py` there's code that attempts to import `sitecustomize.py`.

**Comment by jamadden** [comment]
I've added tests and a patch that should fix this under both python 2 and 3. The original example now works for me.

**Comment by mzdaniel** [comment]
Awesome! I can confirm that c01eb80 effectivelly solved this issue in Debian, Centos and Archlinux for both python 2 and 3.  Thank you Jason!

**Comment by d-salodki** [comment]
sad, but i have this error on python=3.2.3 and gevent=1.1.1

**Comment by jamadden** [comment]
Python 3.2 is *not* supported. For Python 3 you need at least 3.3'

**Comment by maicss** [comment]
Hi, seems that this problem has solved.
But when i debug my script, **the warning** shows again
```
# debug in pycharm, with gevent 1.1.1,  python 3.5.1
Connected to pydev debugger (build 143.1919)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gevent/monkey.py:395: RuntimeWarning: Monkey-patching not on the main thread; threading.main_thread().join() will hang from a greenlet
  _warnings)
Traceback (most recent call last):
  File "gevent/_semaphore.py", line 101, in gevent._semaphore.Semaphore._notify_links (gevent/gevent._semaphore.c:1940)
greenlet.error: cannot switch to a different thread
(<built-in method switch of greenlet.greenlet object at 0x103c7eb90>,
 <gevent.thread.LockType object at 0x10415d320>) failed with error
```

**Comment by advance512** [comment]
@maicss 
I am facing this same issue right now, out of the blue. 

Python 3.5.2
gevent==1.1.2
greenlet==0.4.11

Did you ever find out what caused the issue?

**Comment by advance512** [comment]
Found it!
If you see this in the context of debugging using PyCharm, try this:

Go to Settings --> Build, Execution, Deployment -> Python Debugger.
In that dialog, you'll see a "Gevent compatible" checkbox. Not sure how it got unticked in the new project.

Tick that option and enjoy!
