### ISSUE TITLE
gevent 1.1b1 raises import error on PyPy

### ISSUE THREAD

**Issue by Taik** [gevent/gevent#619]
I'm trying to get gevent to run under pypy 2.6.0, and it is raising an ImportError. More info here: https://gist.github.com/Taik/7472a2d98baed2b9b1aa

Any thoughts/help would be appreciated. Thanks!

**Comment by jamadden** [comment]
How did you install gevent? Can you import it directly on the command line, e.g., `$pypy -c 'import gevent.core; print gevent.core.get_version()'`?

**Comment by parasyte** [comment]
FWIW, I am able to reproduce a similar error with the following minimal test case under PyPy 2.6.0:

```python
import gevent.monkey
gevent.monkey.patch_os()

import gevent.event
gevent.event.Event()
```

Clear the `__pycache__` directory inside the gevent module path before running this test. E.g.:

```bash
$ rm -rf ~/env-pypy-2.6-gevent1.1/site-packages/gevent/__pycache__/; python test.py
```

Output is here: https://gist.github.com/parasyte/abb7884fcead1f76b92e#file-gevent-pypy-pywsgi-log

There appears to be a recursive dependency upon the CFFI compiler needing `os.fork`, and `os.fork` compiling the core with CFFI. I discovered this with the basic pywsgi module, which creates an `Event` object.

Interesting to note that the CFFI compiler is actually running in the the child process... it just races the parent for the `core` module.

**Comment by parasyte** [comment]
I workaround the issue by compiling `core` ahead of time:

```bash
$ python -c 'import gevent; gevent.spawn(lambda: None)'
```

**Comment by matthewdupre** [comment]
I'm also seeing this exception, with the new 1.1b2 release:

```
...
File "/var/lib/jenkins/workspace/unit-test/.tox/pypy/site-packages/gevent/os.py", line 314, in fork return fork_and_watch(*args, **kwargs)
  File "/var/lib/jenkins/workspace/unit-test/.tox/pypy/site-packages/gevent/os.py", line 293, in fork_and_watch
    loop = loop or get_hub().loop
  File "/var/lib/jenkins/workspace/unit-test/.tox/pypy/site-packages/gevent/hub.py", line 308, in get_hub
    hub = _threadlocal.hub = hubtype(*args, **kwargs)
  File "/var/lib/jenkins/workspace/unit-test/.tox/pypy/site-packages/gevent/hub.py", line 423, in __init__
        loop_class = _import(self.loop_class)
  File "/var/lib/jenkins/workspace/unit-test/.tox/pypy/site-packages/gevent/hub.py", line 337, in _import
    return _import(path[-1])
  File "/var/lib/jenkins/workspace/unit-test/.tox/pypy/site-packages/gevent/hub.py", line 354, in _import
    raise ImportError('Cannot import %r from %r' % (attr, oldx))
    ImportError: Cannot import 'core' from <module 'gevent' from '/var/lib/jenkins/workspace/unit-test/.tox/pypy/site-packages/gevent/__init__.py'>
```

I'm using tox - I've attached the environment from tox.ini.
```
[testenv:pypy]
commands=nosetests calico/felix/test calico/test
deps =
    nose
    mock==1.0.1
    coverage==4.0a5
    unittest2
    git+https://github.com/Metaswitch/python-etcd.git@3f14a002c9a75df3242de3d81a91a2e6bd32c5a8#egg=python-etcd
    gevent>=1.1a2, !=1.1b1
```

For now I'll add 1.1b2 to our list of excluded versions, but it would be good to get this fixed so we can get back to tracking new releases.

I'm not a Python expert, so I'm sorry if I've missed anything important here - if there's any further information you need please let me know.

**Comment by jamadden** [comment]
If we could take a firm dependency on a recent version of PyPy, which we can't, then we might could use some of the new pre-compiled CFFI support to do things differently. 

What's odd is that even when installing with a recent Pip version, so that the installation actually happens through a `bdist_wheel` and produces a fully populated `__pycache__` directory, @parasyte's example still fails for me (albeit with a different error, a `DistutilsModuleError`). 

I'm not sure how to reliably add a test case for this, but on my machine with that example, adding these lines to the bottom of `gevent/__init__.py` solves the problem:

```python
if PYPY:
    get_hub()
```

Can anyone confirm the change works for them? The cost is a slower import, and doing more work while the import lock is held, and initializing the hub and loop when maybe they wouldn't be needed.

**Comment by jamadden** [comment]
Actually, this works equally well, without the side-effects:

```
if PYPY:
	from gevent.core import loop
	del loop
```
