### ISSUE TITLE
version 1.1.b1 fail to compile in windows 

### ISSUE THREAD

**Issue by jeffpeiyt** [gevent/gevent#625]
1.0.2 successfully under the same env.

 windows 7 64, using the visual C++ 2008 express

S:\python-infra\gevent-1.1b1>python setup.py build
running build
running build_py
running build_ext
building 'gevent.core' extension
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /G
S- /DNDEBUG -DFD_SETSIZE=1024 -D_WIN32=1 -DLIBEV_EMBED=1 -DEV_COMMON= -DEV_CLEANUP_ENABLE=
0 -DEV_EMBED_ENABLE=0 -DEV_PERIODIC_ENABLE=0 -DCARES_STATICLIB= -DCARES_EMBED=1 -DEV_STAND
ALONE=1 -Ilibev -IC:\Python27\include -IC:\Python27\PC /Tcgevent/gevent.corecext.c /Fobuil
d\temp.win32-2.7\Release\gevent/gevent.corecext.obj
gevent.corecext.c
libev\ev.c(946) : warning C4244: 'function' : conversion from 'uint64_t' to 'uint32_t', po
ssible loss of data
libev\ev.c(982) : warning C4244: 'function' : conversion from 'uint64_t' to 'uint32_t', po
ssible loss of data
libev\ev.c(1027) : warning C4244: 'function' : conversion from 'uint64_t' to 'uint32_t', p
ossible loss of data
libev\ev.c(1221) : warning C4244: '=' : conversion from 'double' to 'float', possible loss
 of data
libev\ev.c(1222) : warning C4244: '=' : conversion from 'double' to 'float', possible loss
 of data
libev\ev.c(1813) : error C2059: syntax error : 'type'
libev\ev.c(1863) : warning C4013: 'array_realloc' undefined; assuming extern returning int

libev\ev.c(2329) : warning C4133: '=' : incompatible types - from 'WSABUF *' to 'CHAR *'
s:\gitsources\cronusagentstore\python-infra\gevent-1.1b1\libev\ev_select.c(200) : warning
C4244: 'initializing' : conversion from 'ev_tstamp' to 'unsigned long', possible loss of d
ata
gevent/gevent.corecext.c(33907) : warning C4133: 'function' : incompatible types - from 'e
v_statdata *' to 'stat *'
gevent/gevent.corecext.c(33993) : warning C4133: 'function' : incompatible types - from 'e
v_statdata *' to 'stat *'
error: command '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe"' failed
 with exit status 2

**Comment by jamadden** [comment]
I believe this is fixed in https://github.com/gevent/gevent/commit/249d93b33c2dd01511e2ab26a4fa1a4c382fd69c. Can you retry with current master?

**Comment by ipid** [comment]
I met exactly the same problem. `249d93b` seems already fixed it.

**Comment by jamadden** [comment]
Thanks for the report!

**Comment by jeffpeiyt** [comment]
Thanks @jamadden !! Will try it out
