### ISSUE TITLE
Broken socket in python3

### ISSUE THREAD

**Issue by kolis** [gevent/gevent#633]
Im using the following example using the ws4py websocket library with the new gevent 1.1b2 release

https://ws4py.readthedocs.org/en/latest/sources/servertutorial/#gevent

It works without problem with python2, but gives the following crash on Mac OS X 10.10

```
Failed to receive data
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ws4py/websocket.py", line 300, in once
    b = self.sock.recv(self.reading_buffer_size)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/gevent/_socket3.py", line 280, in recv
    return _socket.socket.recv(self._sock, *args)
OSError: [Errno 9] Bad file descriptor
```

Not sure if this is a problem with ws4py or gevent

**Comment by jamadden** [comment]
This looks like a problem with ws4py, exacerbated by a tightening of the WSGIServer contract. w4py's ``WebSocketWSGIHandler`` class is spawning a greenlet when handling a request and then returning without waiting for the greenlet. When the handler returns, sockets are now closed deterministically by the server; this is required for Python 3 and PyPy compatibility. Previously, sockets would be closed at some arbitrary time in the future, if at all, based on the garbage collector---this was undocumented behaviour. There's more in the [change notes](http://www.gevent.org/whatsnew_1_1.html#compatibility).

**Comment by kolis** [comment]
Ok, thanks!
