### ISSUE TITLE
gevent.queue.peek()

### ISSUE THREAD

**Issue by michaelvol** [gevent/gevent#643]
self.getters of queue class was changed from set to deque by commit d243caa3ae60e93776e9c845ff60de6050797cb3. 
the method peek() still uses discard() and throws an exception:
File "/usr/local/lib/python2.7/dist-packages/gevent/queue.py", line 305, in peek
self.getters.discard(waiter)
AttributeError: 'collections.deque' object has no attribute 'discard'.

you also use self.getters.add(waiter), which is probably where the exception is throws at the first place.

**Comment by jamadden** [comment]
Thanks for the report.
