### ISSUE TITLE
how to close socket

### ISSUE THREAD

**Issue by feimat** [gevent/gevent#646]
when using gevent.monkey.patch_socket(), we find that socket.close() can not send fin package to peer,

**Comment by byaka** [comment]
what gevent and python version?

**Comment by oxbambooxo** [comment]
try to use your_sock.shutdown(socket.SHUT_RDWR) ?

**Comment by jamadden** [comment]
Are there any updates on this?

**Comment by jamadden** [comment]
Closing since there have been no updates in six months. Please feel free to reopen with additional information.
