### ISSUE TITLE
Regression with Python 3.5.0 final

### ISSUE THREAD

**Issue by squeaky-pl** [gevent/gevent#653]
I get a following stacktrace:

```
Traceback (most recent call last):
  File "upyc/minimal.py", line 12, in <module>
    main()
  File "upyc/minimal.py", line 7, in main
    foo = gevent.subprocess.Popen([sys.executable, '--version'])
  File "/data/venv/lib/python3.5/site-packages/gevent/subprocess.py", line 415, in __init__
    restore_signals, start_new_session)
  File "/data/venv/lib/python3.5/site-packages/gevent/subprocess.py", line 1100, in _execute_child
    raise child_exception
NameError: name 'MAXFD' is not defined
```

running following minimal example

```
import sys

import gevent.subprocess


def main():
    foo = gevent.subprocess.Popen([sys.executable, '--version'])
    foo.wait()


if __name__ == '__main__':
    main()
```

Platform information

```
python --version     
Python 3.5.0
uname -a       
Linux 59e85089ab62 4.1.6-200.fc22.x86_64 #1 SMP Mon Aug 17 19:54:31 UTC 2015 x86_64 Linux
pip freeze | grep gevent
gevent==1.1b4

```

This seems to be related to changes in Python 3.5 stdlib, it worked perfectly with 3.4

**Comment by squeaky-pl** [comment]
It seems that MAXFD is gone in Python 3.5 according to this comment here:

https://bugs.python.org/issue10838#msg240240

**Comment by squeaky-pl** [comment]
I realized that you don't have Python 3.5 in your test matrix. I run the test suite under Python 3.5:
I include output of `make fulltoxtest` here (if that helps):

https://gist.github.com/squeaky-pl/9cc10930a3714c9c6336

**Comment by jgehrcke** [comment]
Awesome, Travis CI already supports Python 3.5: http://docs.travis-ci.com/user/languages/python/

After the official Python 3.4 release, Travis CI needed a couple of weeks before they supported it.

**Comment by squeaky-pl** [comment]
I found exact commit where MAXFD was removed: https://hg.python.org/cpython/rev/f98b0a5e5ef5

**Comment by jamadden** [comment]
Thank you for the report!
