### ISSUE TITLE
gevent 1.0.2 (and earlier) fails to build on OS X Yosemite

### ISSUE THREAD

**Issue by aelse** [gevent/gevent#656]
```
libev/ev.c:1029:42: error: '_Noreturn' keyword must precede function declarator
  ecb_inline void ecb_unreachable (void) ecb_noreturn;
```

I noticed this problem in about the last week. I think it started since I upgraded xcode on my laptop on the 18th.  It can be fixed by replacing libev/ev.c and libev/ev.h in the sdist of gevent 1.0.2 with those files from libev 4.20 release and then running 'python setup.py build'.

I see issue #590 upgrades to this version in master. Can we have that backported to 1.0.x branch? I note the branch named 1.0.x is well behind 1.0.2. If I were to submit a PR for this what should i base it against?

**Comment by aelse** [comment]
xcode
```
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by jamadden** [comment]
I suggest using 1.1b5. It's reasonably stable, has many bugfixes over 1.0, and is being used in production. It's only awaiting some burn time to declare it final. Partly because of the interesting branch situation, I don't expect to produce any more 1.0 releases.

**Comment by jhgg** [comment]
Just ran into this problem. Will use 1.1b5 ;) Thanks @jamadden!

**Comment by jumpchat** [comment]
Try this
CFLAGS='-std=c99' pip install gevent==1.0.2

**Comment by aelse** [comment]
@jumpchat Thanks, that works.

**Comment by stillzhl** [comment]
@jumpchat Thanks, that is great!

**Comment by sreejith-driveu** [comment]
@jumpchat :+1: Thanks. That worked.

**Comment by kilojoules** [comment]
Thanks @jumpchat !
