### ISSUE TITLE
how to monkey patch socket.recv but not socket.send

### ISSUE THREAD

**Issue by fcntl** [gevent/gevent#661]
Basically I want a greenlet to send data over a socket, without yielding to other greenlets until it has finished sending all the data, but when it calls socket.recv to wait for the response, then I would like to yield to other greenlets so they can start sending data too.

Is there a monkey.patch_socket_read or something like that?

**Comment by jamadden** [comment]
There is no direct support for something like that. Depending on your platform you may be able to get the desired results using `gevent.os.nb_read`, but it's not something I've given any thought to.
