### ISSUE TITLE
pywsgi logs bytes for HTTP status code under python 3

### ISSUE THREAD

**Issue by kchen** [gevent/gevent#664]
Very minor issue: In python 3, pywsgi logs lines like:
1.2.3.4 - - [2015-10-14 21:14:10] "GET / HTTP/1.1" b'403' 123 0.000083

The HTTP status code should be converted to a string.

**Comment by jamadden** [comment]
Hmm, that just about looks like a client issue to me. 

The values provided to `start_response` are supposed to be [*native str values*](http://www.gevent.org/whatsnew_1_1.html#compatibility), which should *not* be `bytes` on PY3. pywsgi's `log_request` [method](https://github.com/gevent/gevent/blob/master/gevent/pywsgi.py#L772-L789) simply spits out the `status` value that the [application provided](https://github.com/gevent/gevent/blob/master/gevent/pywsgi.py#L740) to `start_response` (the first part of it anyway). If it's bytes, then the application provided bytes, which is in violation of the specification (and gevent shouldn't have accepted it in the first place, but that's a different bug).

**Comment by jamadden** [comment]
D'oh, I think I take that back. pywsgi will still accept the wrong type under PY3, but it also looks like it does an early conversion.
