### ISSUE TITLE
cannot create weak reference to 'gevent._semaphore.Semaphore' object

### ISSUE THREAD

**Issue by Ivan-Zhu** [gevent/gevent#666]
why cann't  create weak reference to 'gevent._semaphore.Semaphore' object after version 1.1a2?
How can we work around? use threading.Semaphore instead?
gevent version 1.1b1

from gevent.lock import Semaphore
import weakref

_semaphores = weakref.WeakValueDictionary()

_semaphores['test']=Semaphore()

output:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/weakref.py", line 80, in __setitem__
    self.data[key] = KeyedRef(value, self._remove, key)
  File "/usr/local/lib/python2.7/weakref.py", line 224, in __new__
    self = ref.__new__(type, ob, callback)
TypeError: cannot create weak reference to 'gevent._semaphore.Semaphore' object

it works under version 1.1a2

**Comment by jamadden** [comment]
Thanks for the report, this has been corrected. Weak referencing Semaphores seems to me like it could be error prone, but I assume you have a use-case.

**Comment by Ivan-Zhu** [comment]
We use weak referencing cache Semaphore.
