### ISSUE TITLE
Question against gevent.fileobject.FileObjectPosix

### ISSUE THREAD

**Issue by osier** [gevent/gevent#673]
Hi, 

I did some testing on writing to local filesystem, with using gevent, but it seems the greenlet for file io blocks the gevent.hub's eventloop. E.g.

```
015-10-26 01:30:05,038 CRITICAL -34892368- Code did not yield to gevent for 0.2194 seconds

  ...... SKIPPED ......

  File "/tock/lib/tock-gr/dispatcher.py", line 226, in _request_dispatcher
    ret = _dispatch_mock()
  File "/tock/lib/tock-gr/dispatcher.py", line 161, in _dispatch_mock
    return func()
  File "/tock/lib/tock-gr/handlers/mock.py", line 22, in get
    f.write("*" * (4000 * 1024))
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/tock/lib/tock-gr/helpers/tracer.py", line 75, in check_for_gevent_blocking
    msg += "".join(traceback.format_stack())
 (tracer:76)(0778463a7b3e11e58afd5254c1d65e8f)
2015-10-26 01:30:05,039 CRITICAL -140576790680272- Greenlet blocked the eventloop for 0.2234 seconds (tracer:44)(None)
```

The code (in "**/tock/lib/tock-gr/handlers/mock.py**", the HTTP request handler class) for testing is like:

```python
class Mock(object):                                                             
    def get(self):                                                                                                                                                                                              
        with check_for_gevent_blocking():                                       
            f = open("/tmp/tock/" + request_get_id(), "w")                                                                                                      
            f.write("*" * (4000 * 1024))                                         
            f.close()
```                                                      

Code to check whether the greenlet blocks the eventloop is borrowed from:

http://hg.mozilla.org/services/server-core/raw-file/9dc68b7bf6be/services/gevent_helper.py

I also tried gevent.fileobject.FileObjectPosix like:

```python
with check_for_gevent_blocking():                                       
    f_raw = open("/tmp/tock/" + request_get_id(), "w")                       
    f = FileObjectPosix(f_raw, 'w', close=True, bufsize=400 * 1024)    
    f.write("*" * (4000 * 1024))
```

But there is no effect. I checked the source code of gevent/_fileobjectposix.py, it looks to me there is no code could block the eventloop.  So I'm wondering:

1) Why not using and using  gevent.fileobject.FileObjectPosix makes no difference?
2) What blocks the gevent.hub's eventloop?

**Comment by osier** [comment]
Forgot to mention, I'm using git top of both gevent and greenlet.

**Comment by jamadden** [comment]
In general, on most platforms, normal file operations are *always* considered non-blocking (yes, it may block for the length of time it takes to copy data from userspace to the kernel and disk buffers, but it's not an indefinite wait like a socket or pipe). Therefore, the underlying `write` system call is never going to raise `EAGAIN` or `EINTR` (unless a signal actually arrives) and all of the data will be written before `write` returns. That's exactly what's happening here.

In other words, the dance that `FileObjectPosix` does of setting the file descriptor in `O_NONBLOCK` is pretty much wasted and ignored for normal files. (In theory, `O_NONBLOCK` can make a difference when opening a file initially, but that's not done or possible here.)

There are system specific ways of doing asynchronous I/O on normal files (e.g., `aio`) but gevent doesn't expose or use those.

If you know you're working with normal files, and doing IO in large chunks, you may consider using `FileObjectThread`, which pushes the actual IO operation off to the thread pool. You can do this manually each time you open a file, or you can [configure gevent to always use threads](http://www.gevent.org/gevent.fileobject.html#configuration). You could also use `gevent.os.tp_write` and `tp_read`.
