### ISSUE TITLE
Terrible subprocess performance

### ISSUE THREAD

**Issue by WGH-** [gevent/gevent#675]
Consider the following code:

**Comment by WGH-** [comment]
...damn keyboard shortcuts.

    subprocess.check_output("yes 2>/dev/null | head -c 1000000", shell=True)

Plain Python `subprocess` takes 0.04s, when `gevent.subprocess` takes 1.13s. Quick debugging reveals that gevent reads pipe file descriptor by one byte.

    read(5, "\n", 1)                        = 1
    read(5, "y", 1)                         = 1
    read(5, "\n", 1)                        = 1

Plain subprocess, however, uses reads with increasing buffer size.

**Comment by WGH-** [comment]
Interestingly, Python 3 is not affected.

I have a bit more debugging observations to follow, will post them soon.

**Comment by jamadden** [comment]
Also interesting: I have the exact *opposite* result. gevent.subprocess runs in ~2s, but the stdlib subprocess module runs in...well, I gave up after about 45s. What platform and python version are you testing with? My results were observed with python 2.7.10 on OS X, with gevent 1.1b6.

**Comment by jamadden** [comment]
I can reproduce the slowness using gevent 1.0.2, where it appears to do exactly the same thing the stdlib does (i.e., I gave up after awhile).

**Comment by WGH-** [comment]
Python 3.4.3 and Python 2.7.10, all on Linux. gevent installed directly from git (`pip[23] install git+https://github.com/gevent/gevent`, that would be master branch, I suppose?)

In Python 2, `GreenFileDescriptorIO.read` gets called by `io.BufferedReader.read`, and it calls `GreenFileDescriptorIO.read` with no arguments, so `n` defaults to 1.

In Python 3, `io.BufferedReader.read` calls `GreenFileDescriptorIO.readall`, so it does more or less the right thing.

**Comment by jamadden** [comment]
Yup, the io module changed behaviour in https://github.com/python/cpython/commit/d810119eacf118d9cb77335263ec3b32aa74bb0c which looks like it went into 3.3
