### ISSUE TITLE
Using gevent with the multiprocessing standard library module

### ISSUE THREAD

**Issue by denik** [gevent/gevent#68]
1. Implement a gevent based server solution.
2. Try to use the standard library multiprocessing module.
3. You won't find any documentation on how could it be done without loss of performance, increased latency.

Ubuntu 10.10
Python 2.6.6
gevent 0.13.3
libevent 1.4.13

I'm also interested in a platform independent solution, e.g. the resulting code has to run on Windows as well. On Windows the multiprocessing module uses a Pipe implementation which is based on named pipes, so timeouts are possible. But I'm not sure waiting on those pipes would work, e.g whether the underlaying libevent supports that or not.<p><a href="http://code.google.com/p/gevent/issues/detail?id=68">Reported by ferenczi.viktor.</a></p><hr/><h2>earlier comments</h2>

<p><strong>Denis.Bilenko said, at 2012-05-12T17:10:33.000Z:</strong></p>

<p>There is now cross-platform gevent.subprocess module in the trunk. No multiprocessing yet.</p>

**Comment by jamadden** [comment]
The `multiprocesing.Process` primitive is known to work now, at least on POSIX.

**Comment by jamadden** [comment]
There's some commentary [here](https://github.com/gevent/gevent/issues/200#issuecomment-121237491).

**Comment by jamadden** [comment]
Closing in triage for 1.2a1 since there have been no updates since either the original report in 2012 or the expanded subprocess support in 1.1.
