### ISSUE TITLE
Possible for spawn_raw to accept kwargs?

### ISSUE THREAD

**Issue by RonRothman** [gevent/gevent#680]
Greetings,

Just wondering: why does `spawn_raw` accept `*args` but no `*kwargs`?  (In contrast, `Greenlet.spawn` does accept kwargs.)

I looked briefly at the code and noticed that under the hood, `spawn_raw` calls `run_callback`, which itself does not accept kwargs, but I stopped following the trail at that point.

(Also note that the docstring for `spawn_raw` mistakenly says that it accepts kwargs.)

**Comment by jamadden** [comment]
Thanks for the report.
