### ISSUE TITLE
pip install --upgrade gevent -> error

### ISSUE THREAD

**Issue by zjyExcelsior** [gevent/gevent#690]
I use `pip install --upgrade gevent` to upgrade gevent in OS X. This is the error:
```
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-McPmSC/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1gThFs-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-McPmSC/greenlet
```

**Comment by jamadden** [comment]
The parts of the command that includes `greenlet/setup.py` strongly suggests that this is an issue with the `greenlet` dependency, and not with `gevent` itself. You might check the greenlet project and issue tracker.

**Comment by jimcasteleiro** [comment]
I am unable to install via pip on OS X 10.10.5. I tried using both python 2.7 and 3.4. I've attached pip's terminal output

[python2.7.txt](https://github.com/gevent/gevent/files/52308/python2.7.txt)
[python3.4.txt](https://github.com/gevent/gevent/files/52309/python3.4.txt)

**Comment by jamadden** [comment]
You seem to be installing gevent 1.0.2, which is not supported on Python 3.x or OS X 10.10. Please install the current release of gevent, gevent 1.1rc1.

**Comment by jamadden** [comment]
Closing due to availability of gevent 1.1rc1 which works with Python 3 and 2.7 on all versions of OS X. For more about using outdated versions of gevent on OS X, see #662.
