### ISSUE TITLE
Why socket can not reuse out of hander function?

### ISSUE THREAD

**Issue by wanglihe** [gevent/gevent#700]
In 1.1, every socket will close after hander exit, but if I want use it in another way, gevent will not support it?

I run these code under gevent 1.1rc2 + python 2.7.9 on debian 8.2

```
#!/usr/bin/python

from gevent import monkey; monkey.patch_all()
from gevent.server import StreamServer

CLIENT = None
def handler(sock, (ip, port)):
    global CLIENT
    if CLIENT != None:
        print("new sock %d and old sock %d" % (sock.fileno(), CLIENT.fileno()))
    CLIENT = sock
    print CLIENT

if __name__ == '__main__':
    StreamServer(("", 1900), handler).serve_forever()
```
and then

nc 127.0.0.1 1900

many times.

It gives the exception about 
error: [Errno 9] Bad file descriptor
\<Greenlet at 0x7fc9587d2af0: _close_when_done(\<socket at 0x7fc95872f650 fileno=[Errno 9] Bad fil, ('127.0.0.1', 60822))\> failed with error

I think it is a bug about close the socket. greenlet should only close socket which ref number is zero.

**Comment by pigmej** [comment]
https://github.com/gevent/gevent/issues/594

**Comment by jamadden** [comment]
As mentioned, that is the desired behaviour. Keep the handler alive to keep the socket alive.
