### ISSUE TITLE
gevent.select seems causing confusion between multiple socket operations

### ISSUE THREAD

**Issue by JilinXie** [gevent/gevent#706]
I made 30 pair of socket send and receive operation to simulate a traceroute logic,
select.select and socket.recv_from is the key  part for performance.
But gevent.select seems not working properly as illustrated in the code below, I tested them on Ubuntu and Mac OS, where I observed:
       gevent.select.select([recv_socket], [], [], 5)
       it returns socket readable ready even if it's a socket from other eventlet.
       (It's only my guess based on the result)

Please run the code, and try use the "import select" instead of gevent select for comparison.
This requires root privilege to run

```python
# -*- coding: utf-8 -*-
import time
import gevent
from gevent import socket
from gevent import select
#import select

def _is_ip(ip):
    if not isinstance(ip, str) and not isinstance(ip, unicode):
        return False
    res = ip.split('.')
    if len(res) != 4:
        return False
    if not all(map(lambda x: x.isdigit(), res)):
        return False
    if not all(map(lambda x: 0<= int(x)< 256, res)):
        return False

    return True

def _send_icmp_packet(ip, ttl):
    st = time.time()
    if not _is_ip(ip):
        ip = socket.gethostbyname(ip)

    port = 33434

    icmp = socket.getprotobyname('icmp')
    udp = socket.getprotobyname('udp')
    recv_socket = socket.socket(socket.AF_INET,
            socket.SOCK_RAW, icmp)
    send_socket = socket.socket(socket.AF_INET,
            socket.SOCK_DGRAM, udp)
    send_socket.setsockopt(socket.SOL_IP,
            socket.IP_TTL, ttl)

    recv_socket.bind(('', port))
    send_socket.sendto('', (ip, port))

    cur_addr = None
    cur_name = None

    recv_socket.setblocking(0)
    readable, _, _ = select.select([recv_socket], [], [], 5)
    if not readable:
        return ttl, 'x'
    try:
        _, cur_addr = recv_socket.recvfrom(512)
    except socket.error as e:
        return ttl, '*'
    finally:
        send_socket.close()
        recv_socket.close()
    cur_addr = cur_addr[0]
    cur_name = cur_addr
    #print ttl, ip, cur_name
    return ttl, cur_name

def _gtraceroute(ip):
    jobs = []
    for i in xrange(1, 31):
        jobs.append(gevent.spawn(_send_icmp_packet, ip, i))
        #_send_icmp_packet(ip, i)
    gevent.joinall(jobs)
    values = [job.value for job in jobs]
    values = sorted(values, key=lambda x: x[0])

    for i in xrange(len(values)):
        if values[i][1] == ip:
            break
    if values[i][1] == ip:
        values = values[:i+1]
        return values, True
    return values, False

if __name__ == '__main__':
    print _gtraceroute('123.123.32.234')
```

**Comment by JilinXie** [comment]
Here is what I get using gevent.select:
([(1, '198.11.175.248'), (2, '198.11.175.248'), (3, '198.11.175.248'), (4, '198.11.175.248'), (5, '198.11.128.158'), (6, '198.11.128.158'), (7, '198.11.128.158'), (8, '198.11.128.158'), (9, '10.107.64.10'), (10, '4.15.79.73'), (11, '4.15.79.73'), (12, '4.15.79.73'), (13, '144.232.12.217'), (14, '144.232.12.217'), (15, '144.232.12.217'), (16, '144.232.12.217'), (17, '144.232.12.217'), (18, '144.232.12.217'), (19, '144.232.12.217'), (20, '144.232.12.217'), (21, '144.232.12.217'), (22, '144.232.12.217'), (23, '144.232.12.217'), (24, '144.232.12.217'), (25, '144.232.12.217'), (26, '144.232.12.217'), (27, '144.232.12.217'), (28, '144.232.12.217'), (29, '144.232.12.217'), (30, '144.232.12.217')], False)

The time-to-live number seems totally not working in this case,,,, so I'm wondering if it's like: the socket in greenlet 1 is also used for greenlet 2-4..

This is the number I get for using the original select.select
([(1, '198.11.175.248'), (2, '10.107.64.22'), (3, '198.11.128.174'), (4, '4.16.87.133'), (5, '4.69.152.208'), (6, '4.69.152.80'), (7, '144.232.19.33'), (8, '144.232.0.163'), (9, '144.232.8.167'), (10, '144.232.7.164'), (11, '144.232.6.43'), (12, '144.228.17.98'), (13, '219.158.102.85'), (14, '219.158.101.65'), (15, '219.158.3.145'), (16, '123.126.0.90'), (17, '202.106.34.54'), (18, 'x'), (19, '123.123.32.234')], True)

**Comment by jamadden** [comment]
* It would be very helpful if you could simplify your example to the minimum necessary to reproduce the issue. Posting snippets of your actual application/script is usually not very helpful. In particular, your example should generally not require root access (tests that require root access cannot be added to the automated test suite).
* I don't understand what you mean when you write "it returns socket readable ready even if it's a socket from other eventlet.". sockets and greenlets have nothing to do with each other. A greenlet does not "own" a socket and sockets can freely be passed between and used by multiple greenlets over the course of their lifetime. Every creation of a socket object results in a distinct operating system socket with a distinct file descriptor.
* `gevent.select.select` returns events based on the file descriptor (`socket.fileno()`), as reported by libev, which in turn is as reported by the operating system (on OS X, that boils down to a call to the *real* `select()` function, while on Linux it's typically epoll). If the file descriptors passed to `gevent.select.select` separate calls to do not overlap, then the results shouldn't overlap either. (That said, I *think* the underlying syscalls are allowed to return spurious results, and they certainly aren't free of race conditions. I also have no idea how they interact with `SOCK_RAW` sockets these days, but in the past I know there were some bugs there.)

**Comment by JilinXie** [comment]
Thanks for your reply, I'll try to simplify the code and make clear I problem I'm facing.

**Comment by JilinXie** [comment]
Hi, I simplified the code.
It's a simulation of  traceroute tool. Simply sends an UDP packet with an Time-To-Live number,
and receives  the icmp packet.

In the code below, I tested using gevent.select.select and select.select, but they gives quite different results.
But sorry, it seems ICMP packet works best with RAW_SOCK, and requires root privilege.
I hope to know if I'm misusing the gevent.select function, if so, how should I use it.
Thanks 

```python
import time, gevent
from select import select
from gevent import socket, spawn
from gevent.select import select as gselect

def trace(ip, ttl, select_method):
    recv_socket = socket.socket(socket.AF_INET, socket.SOCK_RAW, 1)
    send_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, 17)
    send_socket.setsockopt(socket.SOL_IP, socket.IP_TTL, ttl)

    recv_socket.bind(('', 33434))
    send_socket.sendto('', (ip, 33434))

    recv_socket.setblocking(0)
    if select_method([recv_socket], [], [], 5)[0]:
        _, cur_addr = recv_socket.recvfrom(512)
        print ttl, ip, cur_addr[0]

if __name__ == '__main__':
    jobs = []
    for i in xrange(1, 10):
        jobs.append(spawn(trace, '123.123.32.234', i,gselect))
    gevent.joinall(jobs)
    print '\n-----------------\n'
    jobs = []
    for i in xrange(1, 10):
        jobs.append(spawn(trace, '123.123.32.234', i, select))
    gevent.joinall(jobs)
```

**Comment by jamadden** [comment]
Ah, I think I see your problem now.

`select.select` is going to block the entire thread, so in effect each call to `trace(..., select)` is going to run *sequentially*, in order, one after the other. The first one will open up a socket, send data, then sleep in `select.select` and nothing will happen until it returns; only then will the next one open a socket and send data.

In contrast, gevent's select is going to be cooperative, allowing all the greenlets to run concurrently. The first one will open up a socket, send data, then call `gevent.select.select` and cooperatively switch to the next one, which will open a socket, send data, call `gevent.select.select` and so on. Crucially, because all the `recv_socket`s are bound to the same port, it's non-deterministic which one will be woken up---it could be any one of them, no order is enforced.

If you change `jobs.append(spawn(...))` to `spawn(...).join()`, you get the same output from both `select.select` and `gevent.select.select`, because now you're forcing the `gevent.select` case to run sequentially in the same way that `select.select` already did.

**Comment by JilinXie** [comment]
Yes,
ICMP protocal defines no port information in ICMP packet's header, so, all the recv_sockets are in effect bound to the same port.
So, using threading also gives the same result.
Thanks a lot for your kind help and time, jamadden.
Gevent is great.
