### ISSUE TITLE
Upgrade libev to 4.22

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#709]
> Date: Sun, 20 Dec 2015 22:16:04 +0100
> From: Marc Lehmann <schmorp@schmorp.de>
> To: libev@lists.schmorp.de
> Subject: libev-4.22 has just been released
>
> I am pleased to announce libev 4.22!
> 
> Distribution: http://dist.schmorp.de/libev/libev-4.22.tar.gz
> Documentation: http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod?pathrev=rel-4_22
> Changes: http://cvs.schmorp.de/libev/Changes?pathrev=rel-4_22
> 
> This release is mainly a bugfix release. Unless you are directly affected
> by one of the fixes, there is no urgent need to upgrade.
> 
> The complete Changes are:
>
> 4.22 Sun Dec 20 22:11:50 CET 2015
>       - when epoll detects unremovable fds in the fd set, rebuild
>         only the epoll descriptor, not the signal pipe, to avoid
>         SIGPIPE in ev_async_send. This doesn't solve it on fork,
>         so document what needs to be done in ev_loop_fork
>         (analyzed by Benjamin Mahler).
>       - remove superfluous sys/timeb.h include on win32
>         (analyzed by Jason Madden).
>       - updated libecb.

**Comment by thedrow** [comment]
Maybe after 1.1 unless we're hitting a bug related to those fixed in 4.22?

**Comment by jamadden** [comment]
Yes, this is marked with the 1.1+ milestone.

**Comment by thedrow** [comment]
:+1:

**Comment by Ivoz** [comment]
Gah, why are they still shipping 2014 config.{sub,guess} files -_-

**Comment by jamadden** [comment]
Updated in #764, being careful to keep our newer copies of config.guess/sub.
