### ISSUE TITLE
pypy + gevent + pycares hangs process

### ISSUE THREAD

**Issue by thestick613** [gevent/gevent#710]
https://github.com/saghul/pycares/issues/21

**Comment by jamadden** [comment]
As mentioned in a comment on that report, modules written in C tend to be extremely flaky on PyPy (not to mention slow). gevent itself has had to disable some of its C code under PyPy due to memory leaks and crashes. (cf #704, #708.)

**Comment by thestick613** [comment]
Darn, this is the first big issue i've had with pypy, **this year**. I think it should have been obvious to me that it's a pypy issue, because it only exited with a -9.

**Comment by thedrow** [comment]
@thestick613 Did you try with PyPy 5.0.1?
They fixed a bunch of problems with CPyExt.

**Comment by thestick613** [comment]
Same result with 5.0.0 and 5.0.1.

**Comment by boytm** [comment]
pycares always crash on pypy 5.0.1 due to cpyext bug,  https://bitbucket.org/pypy/pypy/issues/2274/pypygilstate_ensure-crash. 
So I create a cffi port of pycares, which only support windows and linux and tested on win8 x86 and CentOS6 x64 with pypy 5.0.1 . You can try it now https://github.com/boytm/pycares.

**Comment by thedrow** [comment]
We don't use pycares ourselves.
@jamadden Do we want to use it and get rid of our own implementation?
@boytm Do you mind releasing your fork to PyPi?
BTW you can rename the repository so people could find it.

**Comment by jamadden** [comment]
My instinct is that we'll be better off using a small custom CFFI binding built in to gevent than taking a third-party dependency. For example, that way we can easily support both embedded and non-embedded versions of the library, something that our downstream distributors use.

**Comment by jamadden** [comment]
Closing in triage for 1.2a1 since there have been no updates since April and since there has been substantial work on PyPy since then (currently at 5.4.1.)

**Comment by thestick613** [comment]
It works very good now!
https://github.com/saghul/pycares/issues/36

**Comment by thedrow** [comment]
Can't we simply vendor pycares?

**Comment by jamadden** [comment]
I don't see why we would do that.

**Comment by thedrow** [comment]
Because the binding has already been written for us and we won't need to invest time in making cares work for PyPy as well.
