### ISSUE TITLE
Multiple gevent threads write on same file descriptor (stdout)

### ISSUE THREAD

**Issue by ryanchou1991** [gevent/gevent#714]
My program has spawning multi gevent threads. All of them have written on the same file descriptor. While I recognized that it will do harmful to the performance. Does anybody could offer me some suggestions on this issue? 
FileObjectThread?

**Comment by jamadden** [comment]
I'm not sure what question you're asking. Are you trying to improve the performance of multiple greenlets writing simultaneously to `sys.stdout`? Under Python 2, you can *try* passing `sys=True` as an argument to `gevent.monkey.patch_all()`, or manually call `gevent.monkey.patch_sys()` to enable the use of a `FileObjectThread`. But whether you'll see any performance improvement, or even performance regression, will be application dependent. (Note that this is not an option under Python 3.)

**Comment by ryanchou1991** [comment]
@jamadden Oh sorry the confused description of my question. I have commented on the other issue. you could refer to this issue `https://github.com/gevent/gevent/issues/6#issuecomment-167275187` 

While I have written a program which spawn multiple gevent threads to write on a file descriptor.  I am care about the performance on the operations. I have searched for the case, and found that issue above.

According the discussion on the issue, It provided a solution was that using the `fileobjectThread` while I am not sure whether it could be significant to the case i described above.

**Comment by jamadden** [comment]
I'm sorry, the comment you reference is just a restatement of this and doesn't really help clarify.

As for performance, you'll just have to *try it* and *measure* your specific scenario to see what works for you.

**Comment by ryanchou1991** [comment]
OK.  Thanks It doesn't works on my program when I use `fileobjectThread`
