### ISSUE TITLE
type error on file, is it python version related?

### ISSUE THREAD

**Issue by Zodzie** [gevent/gevent#715]
`127.0.0.1 - - [2015-12-28 15:10:53] "GET / HTTP/1.1" 500 21 0.002569
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 495, in run_application
    self.process_result()
  File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 486, in process_result
    self.write(data)
  File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 380, in write
    self._write_with_headers(data)
  File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 399, in _write_with_headers
    towrite.extend(data)
TypeError: an integer or string of size 1 is required
{'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_HOST': 'localhost:8080',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0',
 'PATH_INFO': '/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '54408',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'localhost',
 'SERVER_PORT': '8080',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7f92d32691e0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x1543350>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with TypeError`

related versions, etc:

`[root@coragaming Python-2.7.6]# pip2.7 install gnotty
Collecting gnotty
/usr/local/lib/python2.7/site-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached Gnotty-0.2.7.tar.gz
Collecting gevent-socketio==0.3.5-beta (from gnotty)
  Downloading gevent-socketio-0.3.5-beta.tar.gz
Collecting irc==2.0 (from gnotty)
  Downloading irc-2.0.zip (106kB)
    100% |████████████████████████████████| 106kB 2.3MB/s 
Collecting daemon==1.0 (from gnotty)
  Downloading daemon-1.0.tar.gz
Collecting sphinx-me (from gnotty)
  Downloading sphinx_me-0.3-py2.py3-none-any.whl
Collecting gevent-websocket (from gevent-socketio==0.3.5-beta->gnotty)
  Downloading gevent-websocket-0.9.5.tar.gz
Collecting anyjson (from gevent-socketio==0.3.5-beta->gnotty)
  Downloading anyjson-0.3.3.tar.gz
Collecting gevent (from gevent-websocket->gevent-socketio==0.3.5-beta->gnotty)
  Using cached gevent-1.0.2.tar.gz
Collecting greenlet>=0.4.7 (from gevent->gevent-websocket->gevent-socketio==0.3.5-beta->gnotty)
  Downloading greenlet-0.4.9.tar.gz (54kB)
    100% |████████████████████████████████| 57kB 3.9MB/s 
Installing collected packages: greenlet, gevent, gevent-websocket, anyjson, gevent-socketio, irc, daemon, sphinx-me, gnotty
  Running setup.py install for greenlet
  Running setup.py install for gevent
  Running setup.py install for gevent-websocket
  Running setup.py install for anyjson
  Running setup.py install for gevent-socketio
  Running setup.py install for irc
  Running setup.py install for daemon
  Running setup.py install for gnotty
Successfully installed anyjson-0.3.3 daemon-1.0 gevent-1.0.2 gevent-socketio-0.3.5b0 gevent-websocket-0.9.5 gnotty-0.2.7 greenlet-0.4.9 irc-2.0 sphinx-me-0.3
/usr/local/lib/python2.7/site-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning`

Thanks

**Comment by jamadden** [comment]
This means that your application callable (`application(environ, start_response)`) has returned something that is not a simple sequence of byte strings. Perhaps you opened the file using the `io` module, for example, such that it returns unicode strings when iterated.

I suggest using gevent 1.1rc2. It is stable, and produces more clear exception messages when application programming errors such as this arise.

**Comment by jamadden** [comment]
Closing in triage. Please comment or open a new issue if the explanation doesn't seem correct.
