### ISSUE TITLE
pip install doesn't work on OSX 10.11

### ISSUE THREAD

**Issue by benoitc** [gevent/gevent#716]
Installing from pip produces the following error:

[log-gevent-install.txt](https://github.com/gevent/gevent/files/73813/log-gevent-install.txt)

**Comment by jamadden** [comment]
Please install gevent 1.1c2 to use Python 3.

**Comment by benoitc** [comment]
why not making it available on pypi?

**Comment by jamadden** [comment]
It is available on PyPi. That's the default version on PyPI; the page at https://pypi.python.org/pypi/gevent is titled "gevent 1.1rc2". But pip by default won't install "pre-release" versions so you either have to configure it to do so or explicitly mention the version, e.g., `pip install gevent==1.1rc2`.

**Comment by pigmej** [comment]
or by `pip install gevent --pre`

**Comment by benoitc** [comment]
oh ok. thanks for the info!

**Comment by Chris-May** [comment]
Should this be added to the documentation, or will this be "fixed" soon? I was banging my head wondering why it wasn't installing.

**Comment by Ivoz** [comment]
@Chris-May how does https://github.com/gevent/gevent/pull/724/files seem to you?

**Comment by Chris-May** [comment]
Hey! Thanks!
That works very well. 

Thanks also for updating the dependencies. I thought I had to install 3.4 to get it to work.
