### ISSUE TITLE
gevent.pywsgi buffers the return value of the application callable

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#717]
Before sending any part of the response to the client, `gevent.pywsgi:WSGIHandler` collects all the headers into a `bytearray` known as `towrite`. It then calls `towrite.extend(...)` passing in the results iterable returned by the application callable. Last, it sends everything to the client with a single call to `socket.sendall()`.

This has the effect of buffering in memory the entire response produced by the application. This is problematic when the response is large (e.g., a file was returned), or when the application is trying to do Comet-style pushing and returns something like a generator. Furthermore, it [violates the PEP 3333 spec](https://www.python.org/dev/peps/pep-3333/#specification-details)  which states:

> When called by the server, the application object must return an iterable yielding zero or more bytestrings....The server or gateway **must** transmit the yielded bytestrings to the client in an unbuffered fashion, completing the transmission of each bytestring before requesting another one.

**Comment by parasyte** [comment]
FWIW, this should only be a problem when the `Transfer-Encoding: chunked` response header is used. HTTP long-poll is perfectly happy when headers are flushed immediately. HTTP clients will only process body contents when the full content is received, or on chunk boundaries when using chunked transfer encoding.

**Comment by jamadden** [comment]
That's a situation where the end client would notice, true. But it can also be a problem when the response is large: instead of being streamed, it is buffered in memory, potentially exhausting all available memory and leading to MemoryErrors for this and other requests (not to mention confounding developer expectations). Sending large responses all at once may also be an issue for downstream proxies for the same reason (I'm hand-waving on that one).

**Comment by parasyte** [comment]
Hah! I like that one better.
