### ISSUE TITLE
Syntax error in Python 3.4

### ISSUE THREAD

**Issue by farin** [gevent/gevent#718]
When compiling from master branch I getting

    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/build/temp.linux-x86_64-3.4/gevent._corecffi.o -o build/lib.linux-x86_64-3.4/gevent/_corecffi.cpython-34m.so
    Linking /tmp/pip-build-5fzm85_u/gevent/build/lib.linux-x86_64-3.4/gevent/_corecffi.cpython-34m.so to /tmp/pip-build-5fzm85_u/gevent/gevent/_corecffi.cpython-34m.so
      File "/home/farin/py3venvs/outpost/lib/python3.4/site-packages/gevent/_util_py2.py", line 8
        raise type, value, tb
                  ^
    SyntaxError: invalid syntax

**Comment by farin** [comment]
but whole compilation end with success

**Comment by jamadden** [comment]
Yes, that is expected and common to many projects that strattle both Python 2 and 3. See #601 and others.
