### ISSUE TITLE
Gevent creating multiple pthreads?

### ISSUE THREAD

**Issue by coleifer** [gevent/gevent#720]
Hi, I'm running 1.0.1 on 64-bit linux with Python 2.7. I've got a task queue implementation that creates a number of worker Greenlets using gevent. When I look at the queue in a process manager I see that there are 6 pthreads running, which I find surprising. The very first line of executed Python code applies `gevent.monkey.patch_all()`, and besides, I'm creating `Greenlet` objects explicitly rather than relying on the `threading` monkeypatch.

So my question is, is it normal for `gevent` to spawn os threads, or is my application misbehaving somehow? I'm using `Greenlet().start()` to start the greenlets...perhaps I should be using `gevent.spawn()`?

**Comment by jamadden** [comment]
Yes, gevent will spawn OS threads for its threadpool. This can happen explicitly (if you use the threadpool) or implicitly (if you resolve any hostnames---which is easy to do without realizing it---or use the FileObjectThread).

**Comment by jamadden** [comment]
See also [issue 468](https://github.com/gevent/gevent/issues/468#issuecomment-54246078). Closing a s part of triage for 1.1. Please feel free to reopen or comment if this does not answer your question.

**Comment by coleifer** [comment]
Thank you for the quick response, makes sense now but I thought I had a bug in my code. Might make sense to document this unless it already is, in which case a link would be appreciated.

**Comment by jamadden** [comment]
It is documented in at least the place pointed to in the issue I linked to. I'm happy to review a documentation PR if there's a better/different place.

**Comment by coleifer** [comment]
Well, I suppose, though using gevent one really expects that everything will run in a single os thread, so making it clear that there's a hidden threadpool might make sense.
