### ISSUE TITLE
Installation issue with pip 8.0 and PyPy 4.0.1 using a .whl

### ISSUE THREAD

**Issue by btegs** [gevent/gevent#722]
When using pip 7.1.2, setuptools 19.4, and wheel 0.26.0 in PyPy 4.0.1, there was no issue in converting gevent 1.1rc3 to a wheel file that gives the name gevent-1.1rc3-pp27-none-linux_x86_64.whl using the command "pip wheel gevent.tar.gz". This version of pip properly points to /usr/bin/pypy.

When upgrading to pip 8.0 and above, the wheel conversion goes fine like before. But when trying to install via "pip install gevent-1.1rc3-pp27-none-linux_x86_64.whl", it gives this error:

"gevent-1.1rc3-pp27-none-linux_x86_64.whl is not a supported wheel on this platform."

I'm trying to figure out if this is something that has to be fixed in gevent or if its something that pip 8.0 does not like and is blocking the installation of the wheel.

**Comment by jamadden** [comment]
Because gevent has been successfully distributed as a shell on the OS X and Windows platforms for some time now, this would seem to be an issue in pip/setuptools.

**Comment by btegs** [comment]
I forgot to mention this was GNU/Linux running the 64 bit version of Ubuntu 15.10

**Comment by FRidh** [comment]
Issue by @btegs upstream. We're experiencing this with many PyPy packages and pip 8.0.

**Comment by jamadden** [comment]
Specifically, pypa/pip#3414

**Comment by jamadden** [comment]
It looks like we're waiting on an updated wheel release now. The fix has been merged per https://bitbucket.org/pypa/wheel/pull-requests/55/soabi-support-for-python-2x-and-pypy/diff and the referenced pip issue.

**Comment by btegs** [comment]
@jamadden - Thanks!

**Comment by jamadden** [comment]
wheel 0.28 is out with the fix for this. I successfully built then installed a 1.1rc3 wheel with pypy 4.0.1 under raspbian (in this case, the wheel name is now `gevent-1.1rc3-pp240-pp240u-linux_armv7l.whl`; before the wheel upgrade, the broken name was `gevent-1.1rc3-pp27-none-linux_armv7l.whl`).

**Comment by btegs** [comment]
I know this was closed over the weekend, but I wanted to chime in that it works as it should now with 8.x. :-)
