### ISSUE TITLE
SSLSocket.recv sometimes returns str or bytes

### ISSUE THREAD

**Issue by kchen** [gevent/gevent#723]
I'm having some trouble cleanly reproducing this, and may try more next week, but figured I'd submit this bug in case the problem is obvious:

I'm running python 3.4 with gevent 1.1b6.  I have a class that inherits from WSGIServer that handles connections with:
```python
            while True:
                try:
                    data = sock.recv()
                    log_info("data is %s, %s" % (data, type(data)))
                    log_info("sock is %s, %s" % (sock, type(sock)))
                    if data == "":
                        log_info("Lost connection to %s" % (queue.remote))
                        break
```
My log file shows:
```
Sat Jan 23 02:15:58 2016 INFO: data is , <class 'str'>
Sat Jan 23 02:15:58 2016 INFO: sock is <gevent._ssl3.SSLSocket object, fd=43, family=2, type=2049, proto=0>, <class 'gevent._ssl3.SSLSocket'>
Sat Jan 23 02:18:13 2016 INFO: data is b'', <class 'bytes'>
Sat Jan 23 02:18:13 2016 INFO: sock is <gevent._ssl3.SSLSocket object, fd=25, family=2, type=2049, proto=0>, <class 'gevent._ssl3.SSLSocket'>
```

SSLSocket should presumably consistently return bytes, rather than sometimes str or bytes.  (I've fixed the code above to "if not data" instead.)

**Comment by jamadden** [comment]
Thanks. I believe this issue with empty strings was fixed in 1.1rc1(http://www.gevent.org/changelog.html#rc1-nov-14-2015)
