### ISSUE TITLE
which should be used to stop wsgi server, close or stop?

### ISSUE THREAD

**Issue by Ivan-Zhu** [gevent/gevent#730]
hi guys:
which should be used to stop wsgi server, close or stop?
    I think we should use "close" to stop wsgi server, because it will wake up the stop action in serve_forever. But the comment in stop method show stop should be used to stop wsgi server.
I want to know if there is some special reason.

**Comment by jamadden** [comment]
``close`` simply closes the accepting socket. ``stop`` does that, and then actually waits for existing requests to finish (if applicable). ``stop`` is a strict superset of ``close``. For best generality, use ``stop``.

**Comment by Ivan-Zhu** [comment]
But close will wake  stop action in server_forever up, it is executed in a greeenlet separately.If we use stop, the stop action in server_forever also be wokend up, then two stop action will be executed  in different greenlets, is it ok?

**Comment by jamadden** [comment]
I don't see why not, but why not try it and see?
