### ISSUE TITLE
what will happend if gevent.hub.reinit called more than one time, in a forked process ?

### ISSUE THREAD

**Issue by Ivan-Zhu** [gevent/gevent#731]
What will happend if gevent.hub.reinit called more than one time?

In document, it shows  "If this function is not called in a forked process, symptoms may include hanging of functions like socket.getaddrinfo(), and the hub’s threadpool is unlikely to work."

I also find the reinit will be called in gevent,os.fork() automatically, so I think the application needn't call the reinit explicitly. But if the application call it again, what will happend?

**Comment by jamadden** [comment]
The major (documented) consequence is that any fork watchers installed may be called again, and libev itself will change some internal datastructures. 

In the first case, so long as fork watchers are properly written to be idempotent (`newpid = os.getpid(); if oldpid == newpid: return; else: oldpid = newpid; ...`) then that shouldn't be a problem. The watchers that ship with gevent are written this way.

In the second case, so long as libev wasn't being used in between the two calls to `reinit`, that also should not be a problem.

**Comment by Ivan-Zhu** [comment]
so, if we use gevent.os.fork() in application, we needn't call reinit again, because it has been called in gevent.os.fork()?

**Comment by jamadden** [comment]
Correct.

**Comment by jgehrcke** [comment]
I have definitely seen that calling `gevent.hub.reinit()` multiple times did not create issues. However, a very humble recommendation when dealing with `fork()` in the context of gevent: have a look at https://gehrcke.de/gipc/ -- it could simplify your life :)
