### ISSUE TITLE
SyntaxError when using gevent 1.1rc4 and python3.5

### ISSUE THREAD

**Issue by giyyapan** [gevent/gevent#741]
Hi all!
I was using gevent 1.1rc1 + uWSGI on python3.5, and it works fine, but I got this error after upgrade to rc4
```
*** running gevent loop engine [addr:0x4801b0] ***
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gevent/__init__.py", line 41, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/usr/local/lib/python3.5/dist-packages/gevent/hub.py", line 289
    except Exception, ex:
                    ^
SyntaxError: invalid syntax
```
Is this a bug of gevent? or should I report this to somewhere else?

Let me know if there's more information I can provide. Thanks!

**Comment by jamadden** [comment]
I'm confident that line is not in 1.1rc4, because it is unit tested and built on Python 3. Perhaps version 1.0 was accidentally installed? It's easy to forget pips --pre option.

**Comment by jamadden** [comment]
Indeed, that line only matchs 1.0.2 (https://github.com/gevent/gevent/blob/1.0.2/gevent/hub.py#L289). 1.1 is completely different.

**Comment by giyyapan** [comment]
Thanks for your super fast reply! : )
I think you where right.
I rolled back to rc1 after I had that error, and I can't reproduce it now too. 
So it must be my mistake
Thanks again, close this issue now ~
