### ISSUE TITLE
`gevent.monkey` not present in python 3.5

### ISSUE THREAD

**Issue by mikeyhew** [gevent/gevent#742]
This may be expected, but I searched the issues and couldn't find any reporting it. I take it monkey patching is not supported for python 3 yet?

```
$ pip install gevent --pre
$ python
```
```python
Python 3.5.1 (default, Dec 18 2015, 00:00:00) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent
>>> gevent.monkey
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'gevent' has no attribute 'monkey'
```

**Comment by jamadden** [comment]
`gevent.monkey` should be present on all installations of gevent, so this suggests an installation problem. You may try uninstalling and re-installing gevent. (I've seen similar issues when working with gevent from a git clone while being in the wrong working directory.)

**Comment by mikeyhew** [comment]
OK, thanks - I'll take a look. How long until v1.1 is stable by the way?

2016-02-18 10:24 GMT+01:00 Jason Madden <notifications@github.com>:

**Comment by jamadden** [comment]
For all practical purposes, I consider 1.1 to be stable, and I know of many sites that are using it in production now. It's certainly a better choice than 1.0 (for any platform). It just has a long release cycle because it's so heavily used.

**Comment by mikeyhew** [comment]
OK, I tried it again, but no luck. Can anyone reproduce this?
Running python 3.5.1 on Ubuntu 14.04 LTS in a Cloud9 IDE workspace.
```
$ pip uninstall gevent
$ pip install gevent --pre
... (the usual syntax errors) ...
Successfully installed gevent
Cleaning up...
$ python3
Python 3.5.1 (default, Dec 18 2015, 00:00:00) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent
>>> gevent.monkey
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'gevent' has no attribute 'monkey'

**Comment by jamadden** [comment]
What are the values of `gevent.__file__` and `gevent.__path__`? Does `monkey.py[c]` exist on the filesystem beside `gevent.__file__`?

**Comment by methane** [comment]
You should `import gevent.monkey` or `from gevent import monkey`.

**Comment by jamadden** [comment]
D'oh! @methane is exactly right. I looked right past that...

**Comment by mikeyhew** [comment]
Oh... =D
