### ISSUE TITLE
Trim github branches

### ISSUE THREAD

**Issue by Ivoz** [gevent/gevent#745]
We've got [a lot of branches](https://github.com/gevent/gevent/branches/all) going, which I think could use cleaning up.

Rather than asking what should be thrown away, I think the opposite question is more useful.

@denik are there any older branches you really want to keep around at all?

Apart from `master`, `1.0.2` to keep, which are you currently working on @jamadden?

Lastly, for discussion, a light form of [gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) branching work flow seems to work well for a lot of larger projects I've seen. `master` always tracks the latest release only, `develop` tracks active development. A big empirical improvement from using this is that it's easy to create patch releases from `master` while `develop` may not be in any release-able state. Jason do you like the sound of using that, or not care for it?

**Comment by jamadden** [comment]
The only truly active branch I have at the moment is the one associated with #732 (which I plan to merge as soon as 1.1 is final). I know I create a lot of branches. I try to clean them up "periodically", i.e., when I remember. 

Let me qualify all of what I'm about to say by noting that I'm not a git expert, just a journeyman practitioner. I'm sure my usage is sub-optimal in many ways.

I create branches in this repo to run the tests on AppVeyor and Travis without merging to the default branch---something that doesn't work with a fork---but unless it's a "big" change, I often don't go the whole create-and-merge-a-pr dance on GitHub (which offers the option to "automatically" clean up a branch). There's two reasons for this. First, I can't do it all from the command-line (to my knowledge); I can create a PR with the `hub` command, but I can't trigger a merge or delete the remote branch of that PR. I avoid the GUI if possible as it slows down the workflow for me. Second, I don't much care for the way github creates a new commit for the merge when a simple fast-forward merge will do, so for the simple/small branches, I merge on the command line. But that may just be me.

As for gitflow, I've seen it, but I don't know that much about it. I can look into it. In my experience with the python projects I contribute to/follow, though, it doesn't seem to be all that popular. Offhand, the only places I can remember seeing it used are in (some of) the pypa repos. So I worry about creating friction for contributors that are unfamiliar with it.

At my current day job, we practice a continuous release process. `trunk` or `master` is expected to be in a releasable state pretty much all the time, with at least no known regressions. We've grown comfortable with that process, and that's more-or-less how I've been handling the 1.1rc series. I honestly hadn't given much thought to the gevent project lifecycle after that though, and that's something that needs done--1.1.0 is right around the corner IMHO.

So I guess I've got some reading to do. Thoughts, pointers, and discussion are more than welcome!

**Comment by Ivoz** [comment]
> I create branches in this repo to run the tests on AppVeyor and Travis without merging to the default branch---something that doesn't work with a fork

As long as you send the fork's branch to a PR then it should get CIed.

> but unless it's a "big" change, I often don't go the whole create-and-merge-a-pr dance on GitHub

True, I also like to differentiate whether to split a branch or not based on the size/effect of changes I'm currently wanting to make- edit a readme? Can get a commit straight onto `master`. Want to work out a bug that'll touch 5 different files? Just create a feature branch to merge in instead.

> but I can't trigger a merge

If you create a branch `feature`, put it in a PR to merge to `master`, and then do necessary `pull`, `merge` and `push` with `feature` -> `master` on the cli, after the push Github will recognise that the PR was merged. To grab someone else' branch easily on the cli you can run

    hub checkout https://github.com/gevent/gevent/pull/NNN

> or delete the remote branch

    git push origin --delete `feature`

Unless I misunderstand what you're asking for

> Second, I don't much care for the way github creates a new commit for the merge when a simple fast-forward merge will do

If you truly hate that (I don't have too much opinion) then yes ofc you can run the merge yourself on the cli, whether for a PR or other branch.

> Offhand, the only places I can remember seeing it used are in (some of) the pypa repos.

Heh, full disclosure, I might be a contributor to there...

> At my current day job, we practice a continuous release process. trunk or master is expected to be in a releasable state pretty much all the time, with at least no known regressions.

Well, true, I think as long as on master you are aiming to only ever work towards stability / reliability, then this can work just fine. And as it happens most of gevent development is currently on stabilising a 1.1 release. I guess gitflow type workflows start to make a lot more sense when you get into heavy development, i.e if we wanted to make a `1.2` or `2.0`. It also has a slightly nicer story for granularity of git checkouts, should someone want it - if they just want the latest stable code, then `master` is always their port of call. If they want latest commits, then they want `develop`. Whereas with only a `master`, there is no branch invariantly holding the latest known good stable state.

**Comment by jamadden** [comment]
> As long as you send the fork's branch to a PR then it should get CIed.

True. But then there's on open PR for a change that may never get merged. (Example: the branches I created while working on some of the SSL bugs.) That strikes me as confusing at best.

> Heh, full disclosure, I might be a contributor to there...

I know :)

> It also has a slightly nicer story for granularity of git checkouts, should someone want it - if they just want the latest stable code, then master is always their port of call. If they want latest commits, then they want develop. Whereas with only a master, there is no branch invariantly holding the latest known good stable state.

That strikes me as much more likely to be a problem with projects that don't release frequently (as per the mantra "release early, release often"). With an actively releasing project, the latest stable code should pretty much be up on PyPI, IMO; I've been trying to push roughly monthly releases of gevent for that reason. With pip not installing pre-releases by default anymore, it's even possible to maintain two or more streams on PyPI: an LTS stream of releases as well as a latest-and-greatest-we-think-its-stable-and-works-for-us-but-this-is-new-code feature release. I understand and value gevent's reputation for stable releases, but hopefully there's other ways to achieve than then, well, not releasing. (Plus it's not like there aren't a few other high-profile, widely used projects that are depended upon by *many* Python projects that have released with major bugs only to release again a few days later. Not that I want that, but it doesn't seem to have been disastrous.)

I guess this is could be a pretty general discussion about release management...

**Comment by jamadden** [comment]
FWIW, at least pypa/pip has switched away from using `develop` to use `master` in order to "[adopt a more standard workflow](https://github.com/pypa/pip/pull/2689#issuecomment-220303667)".
