### ISSUE TITLE
easy_install error on Ubuntu 14.04.4 with Python3.1

### ISSUE THREAD

**Issue by larkost** [gevent/gevent#746]
I am trying to instal `gevent` on Python 3.1.5 (installed at /usr/local/opt/python3.1 from source) on Ubuntu 14.04.4 using `sudo easy_install-3.1 event` and am getting the following error (and failure to install). On the same machine I used the same method to install for Python 2.6, 2.7, 3.2, 3.3, 3.4, and 3.5. Python3.0 is giving me a similar error. Note that all of these interpreters appear to be working fine for the testing we are performing on this machine.

Because of the length of the error I have had to put it into the gist: https://gist.github.com/larkost/f0dff8c9b969fd851b24

I tried to regress this, and version 1.0 compiles, but has other problems when I try to run it on these interpreters.

**Comment by jamadden** [comment]
For Python 3, gevent 1.1 is only supported on Python 3.3 and above. gevent 1.0 does not support Python 3 at all.
