### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#749]
A checklist of things to remember, mostly for my own benefit. Incomplete and changing. What have I forgotten?

Before Release
============

- [x] Scan documentation, particularly whatsnew_1_1.rst and changelog for any clarifications and updates
- [x] Link directly to changelog.rst and/or whatsnew_1_1.rst in README.rst so it shows up on PyPI

During Release
============

- [x] Update README.rst/intro.rst to remove references to being a pre-release (pip --pre)

Standard release things
---------------------------------
- [x] Build sdist
- [x] Build OS X CPython wheels (2.6, 2.7, 3.3, 3.4, 3.5)
- [x] Build OS X PyPy wheel
- [x] Build manylinux wheels in Docker image
- [x] Build Windows wheels (download from appveyor) (2.6, 2.7, 3.3, 3.4, 3.5)
- [x] Upload wheels and sdists

After Release
===========

- [x] Announcement on gevent google group
- [x] Announcement on twitter gevent 
- [x] Announcement on python-announce?
- [ ] Write a blog post (optional? need access @denik)
- [x] Alert PyPy devs to update packages.pypy.org (fijal on #pypy irc)

**Comment by jamadden** [comment]
Any thoughts on including #751 in 1.1? It's a small behaviour change that corrects a bug identified and fixed in Python three or so years ago...but it wasn't beckported to 2.7, just 3.x. To me it's an obviously correct behaviour and I would be confused to see it otherwise. It strikes me as much better to include the fix in 1.1.0 instead of slipstreaming it into 1.1.1 because it is a user-visible change, but also I'd rather not wait for 1.2.0 because it's so minor.

(This implicitly includes #732, which has a much smaller change in ordering of notifications for Event.)

Speaking of which, I'm honestly leaning towards not doing another RC and simply drawing an arbitrary line and calling it 1.1.0. If I keep waiting for new bugs to be discovered, it's going to be a game of Zeno's Arrow: asymptotically approaching but never quite getting there. Philosophically, I don't like having any changes between an RC and the Final, but practically speaking...

**Comment by jamadden** [comment]
I looked back at the changelogs, and the project doesn't seem to shy away from making bugfixes in final .0 release. Everything is green with #751 (modulo the usual appveyor timing issue or two), and it enables more tests, so I'm leaning towards merging it.

**Comment by Ivoz** [comment]
If it's behaviour change, then I'm not sure it would be appropriate for a patch X.X.1 release anyway.

But if it's where behaviour is buggy in the first place, then I'd call it a bug correction anyway. Gevent has never *perfectly* replicated python APIs AFAIK, so I wouldn't think too harshly on this anyway. Especially if 2.X users are also likely to merely see this as a bugfix?

Changelog of fixes seems to be getting smaller and smaller :clap: so I personally don't see too much value in waiting for an RC6 containing only one bugfix. That could simply be a 1.1.1.

**Comment by jamadden** [comment]
Well I put 1.1 up on PyPI. I was going to try to wait a few days before sending announcements to see if any early adopters filed critical bug reports, but, silly me, the news made it to reddit in about two hours and twitter at the same time. I should have known better. So I went ahead and sent the announcement emails and tweets.

**Comment by jamadden** [comment]
packages.pypy.org has a pending PR to update the note (https://github.com/baroquesoftware/pypy.packages/pull/6); fijal has indicated that the actual build status will be updated after pypy 5.0 is released (which does pass our test suite).

**Comment by nolar** [comment]
Just to mention:

Somehow 1.1.0 release has broken everything for me. Gevent-based greenlet synchronisation hangs after a first event+queue item (queue is pushed, event is set from multiple greenlets; event is waited, queue is pulled till empty, event is cleared in the parent greenlet).

The overall greenlets layout & the top-level code is quite complicated, so it will be not so easy to extract an isolated broken sample. And it will take time. But I'll try later.

When I downgrade to 1.1rc5, everything works fine, as it worked with 1.1rc3, 1.1rc1, so on. For now, as a fast workaround, I have switched back to 1.1rc5 — and I hope that it will not be deleted from PyPI for long time.

PS: Python-2.7.10.

**Comment by nolar** [comment]
Extracted the single class with few key methods to #771. And also a possible explanation of the issue.
