### ISSUE TITLE
RLock.acquire() not blocking

### ISSUE THREAD

**Issue by joyzheng** [gevent/gevent#750]
It appears that the patched `RLock` doesn't block when `acquire()` is called, even if `blocking=1` is passed in, but immediately returns with `False` if somebody else holds the lock.

I first ran into this with the locking in `logging.Handler.handle()` throwing a `RuntimeError: cannot release un-acquired lock`. 

Gevent: 1.1rc5
Python: 3.5.1 
OS: OSX 10.10.3 (also seen in Ubuntu 14.04)
It blocks as expected when running in Python 2.7.10 on the same machine.

Here's a piece of code that reproduces it (same if we call with `blocking=1` in `g_2`):

```
from gevent import monkey
monkey.patch_all()

import gevent
from gevent import Greenlet
import time
from threading import get_ident, RLock


lock = RLock()


def g_1():
    print("Greenlet 1 acquiring lock")
    print(lock.acquire())
    print("Greenlet 1 lock acquired")
    time.sleep(10)


def g_2():
    print("Greenlet 2 acquiring lock")
    print(lock.acquire())
    print ("Greenlet 2 lock acquired")
    lock.release()
    print("Greenlet 2 lock released")


if __name__ == "__main__":
    greenlet_1 = Greenlet.spawn(g_1)
    time.sleep(1)
    greenlet_2 = Greenlet.spawn(g_2)

    gevent.joinall([greenlet_1, greenlet_2])
```

Output:
```
Greenlet 1 acquiring lock
True
Greenlet 1 lock acquired
Greenlet 2 acquiring lock
False
Greenlet 2 lock acquired
Traceback (most recent call last):
  File "venv/lib/python3.5/site-packages/gevent/greenlet.py", line 522, in run
    result = self._run(*self.args, **self.kwargs)
  File "badger/test.py", line 32, in g_2
    lock.release()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 170, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock
<Greenlet at 0x102cd6cc0: g_2> failed with RuntimeError
```

**Comment by jamadden** [comment]
Sure enough, I can confirm the issue with recent versions of Python---probably has something to do with `_CRLock` being different. It works as expected under Python 2.7, which is what all the production usage that I have personal knowledge of is based on.

Neither gevent's nor the stdlib's test cases pick up this failure, which is disappointing...

**Comment by jamadden** [comment]
Thanks for the report. The default value of *timeout* changed in 3.2 and our test cases that thought they were testing that were actually testing the raw gevent.thread.RLock class. Fixed and added a bunch more tests.

**Comment by joyzheng** [comment]
Thanks!
