### ISSUE TITLE
Failure to build on powerpc64le

### ISSUE THREAD

**Issue by daxtens** [gevent/gevent#754]
Hi,

Running `pip install gevent` on powerpc64le is failing for me:
```
Installing collected packages: gevent, greenlet
  Running setup.py install for gevent
    /tmp/pip-build-m04Ylo/gevent/libev/config.guess: unable to guess system type
    
    This script, last modified 2008-01-23, has failed to recognize
    the operating system you are using. It is advised that you
    download the most up to date version of the config scripts from
    
      http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
    and
      http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD
    
    If the version you run (/tmp/pip-build-m04Ylo/gevent/libev/config.guess) is already up to date, please
    send the following data and any information you think might be
    pertinent to <config-patches@gnu.org> in order to provide the needed
    information to handle your system.
    
    config.guess timestamp = 2008-01-23
    
    uname -m = ppc64le
    uname -r = 4.2.0-30-generic
    uname -s = Linux
    uname -v = #35-Ubuntu SMP Fri Feb 19 13:50:54 UTC 2016
    
    /usr/bin/uname -p =
    /bin/uname -X     =
    
    hostinfo               =
    /bin/universe          =
    /usr/bin/arch -k       =
    /bin/arch              =
    /usr/bin/oslevel       =
    /usr/convex/getsysinfo =
    
    UNAME_MACHINE = ppc64le
    UNAME_RELEASE = 4.2.0-30-generic
    UNAME_SYSTEM  = Linux
    UNAME_VERSION = #35-Ubuntu SMP Fri Feb 19 13:50:54 UTC 2016
    configure: error: cannot guess build type; you must specify one
    Running '/bin/sh /tmp/pip-build-m04Ylo/gevent/libev/configure > configure-output.txt' in /tmp/pip-build-m04Ylo/gevent/build/temp.linux-ppc64le-2.7/libev
```

However, compiling the latest version from source (`pip install setuptools cffi tox 'cython>=0.23.4' git+git://github.com/gevent/gevent.git#egg=gevent`) is working fine.

Could you please push a version of the gem with a more recent `config.sub` and `config.guess`? Thanks in advance!

**Comment by jamadden** [comment]
You seem to be installing the outdated 1.0 version of gevent. The current version on PyPI is 1.1rc5. Please try installing that instead. Installation instructions are on PyPI.

**Comment by daxtens** [comment]
Hmm, interesting - I just ran `pip install gevent`. I will investigate on my end.

**Comment by jamadden** [comment]
1.1rc5 is a prerelease, so one must either specify --pre or ==1.1rc5 to install it. The former is documented in the web page. This is a relatively recent change to pip, we get questions about it frequently :). But 1.1.0 final should be out soon.

**Comment by daxtens** [comment]
Right, I can confirm that running `pip install gevent` pulls gevent-1.0.2, and running `pip install 'gevent>=1.1-rc5` works. I will update my scripts appropriately.

Thank you very much for your help and your patience!

**Comment by jamadden** [comment]
No problem. Personally, I have a great deal of interest in the PPC architecture; I really miss my G5, it was so easy to write assembly for. But we have no continuous integration story for ppc, so I'm just glad it works for you.

**Comment by daxtens** [comment]
So, I'm with IBM, we're working on that, stay tuned :)

**Comment by jamadden** [comment]
I will admit to noticing the email address :)
