### ISSUE TITLE
Test failures in 1.1.0

### ISSUE THREAD

**Issue by felixonmars** [gevent/gevent#759]
Hi, I am getting two test failures under Arch Linux x86_64. Please let me know what I should do to correct this, thanks!

One failure is for both Python 2.7.11 and 3.5.1:
```
+ GEVENT_RESOLVER=thread /usr/bin/python2 -u test_close_backend_fd.py
| GEVENT_RESOLVER=thread /usr/bin/python2 -u test_close_backend_fd.py
  Traceback (most recent call last):
    File "test_close_backend_fd.py", line 13, in <module>
      fileno = hub.loop.fileno()
  AttributeError: 'gevent.corecext.loop' object has no attribute 'fileno'
```

And another only for Python 3.5.1:
```
| GEVENT_RESOLVER=thread /usr/bin/python -u test__ssl.py
  /build/python-gevent/src/gevent/greentest/greentest.py:269: ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_INET, type=2050, proto=0, laddr=('0.0.0.0', 0)>
    return method(self, *args, **kwargs)
  ..........FF
  ======================================================================
  FAIL: test_sendall_timeout (__main__.TestSSL)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/build/python-gevent/src/gevent/greentest/greentest.py", line 280, in wrapped
      return method(self, *args, **kwargs)
    File "/build/python-gevent/src/gevent/greentest/greentest.py", line 269, in wrapped
      return method(self, *args, **kwargs)
    File "/build/python-gevent/src/gevent/greentest/test__socket.py", line 188, in test_sendall_timeout
      self.assertRaises(self.TIMEOUT_ERROR, client.sendall, self._test_sendall_data)
  AssertionError: timeout not raised by sendall

  ======================================================================
  FAIL: test_ssl_sendall_timeout0 (__main__.TestSSL)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/build/python-gevent/src/gevent/greentest/greentest.py", line 280, in wrapped
      return method(self, *args, **kwargs)
    File "/build/python-gevent/src/gevent/greentest/greentest.py", line 269, in wrapped
      return method(self, *args, **kwargs)
    File "test__ssl.py", line 53, in test_ssl_sendall_timeout0
      self.assertRaises(expected, client.sendall, self._test_sendall_data)
  AssertionError: SSLWantWriteError not raised by sendall

  ----------------------------------------------------------------------
  Ran 12 tests in 7.259s

  FAILED (failures=2)

! GEVENT_RESOLVER=thread /usr/bin/python -u test__ssl.py [code 1] [took 22.3s]
```

**Comment by jamadden** [comment]
I don't know what to tell you. I can't reproduce either failure locally or on Travis CI (64-bit ubuntu). 

I know for a fact that `gevent.corecext.loop` *absolutely* has a `fileno` attribute:
```
Python 3.5.1 (default, Dec 11 2015, 09:20:00)
>>> import gevent
>>> gevent.get_hub().loop.fileno
<built-in method fileno of gevent.corecext.loop object at 0x1085706a8>
```
Can you reproduce that failure on the command line?

It's possible that the apparent SSL issue is due to a difference in the underlying OpenSSL library or Python's `_ssl` module. Does your distro patch either of those?

**Comment by felixonmars** [comment]
Yes, I can reproduce it on the command line:

```
$ GEVENT_RESOLVER=thread /usr/bin/python2 -u test_close_backend_fd.py
Traceback (most recent call last):
  File "test_close_backend_fd.py", line 13, in <module>
    fileno = hub.loop.fileno()
AttributeError: 'gevent.corecext.loop' object has no attribute 'fileno'
$ GEVENT_RESOLVER=thread /usr/bin/python -u test_close_backend_fd.py
Traceback (most recent call last):
  File "test_close_backend_fd.py", line 13, in <module>
    fileno = hub.loop.fileno()
AttributeError: 'gevent.corecext.loop' object has no attribute 'fileno'
```

And your example doesn't work here, either:
```
Python 3.5.1 (default, Mar  3 2016, 09:29:07)
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent
>>> gevent.get_hub().loop.fileno
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'gevent.corecext.loop' object has no attribute 'fileno'
```

We have a rather simple openssl build: https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/openssl#n55

**Comment by jamadden** [comment]
Are you perhaps trying to use a system-provided libev instead of the embedded libev that ships with gevent? If libev isn't compiled with the expected definitions then things like this are liable to break.

**Comment by felixonmars** [comment]
Hrm, I see. This should be the problem. I'll build and try again.

Any plans to make the modifications to libev upstream?

Also it would be good to know if system c-ares would be safe to use.

**Comment by jamadden** [comment]
This isn't a modification to libev, it's a configuration that gevent requires for full functionality. 

gevent is only tested with the shipped versions of libev and c-ares, built with the gevent settings. Outside of that, I can't guarantee anything. Things may just work, or they may result in some features being missing (such as fileno), or they may fail in ways which may or may not be caught by the test suite.

**Comment by felixonmars** [comment]
Built with EMBED=1 and the `'gevent.corecext.loop' object has no attribute 'fileno'` errors were gone. The other `test__ssl` error only reproduce in my build chroot. Really sorry for the false alarm.

But in the long term I would really like to see system libraries being supported, perhaps either via making the configuration the default in upstream, or some instructions for distributor so we can build libev/c-ares in a way that gevent supports.
