### ISSUE TITLE
gevent 1.1 segfault with python3.4 on cygwin

### ISSUE THREAD

**Issue by rossengeorgiev** [gevent/gevent#763]
Code to reproduce:

```python
import gevent

def worker():
    raise RuntimeError('ops')

gevent.spawn(worker).join()
```
Works as expected with `python 2.7`

**Comment by jamadden** [comment]
What about with python 3.5? 

What version of greenlet and cython are you using?

What part of the code is necessary to make things crash? Is it the greenlet that raises the exception (i.e., greenlets that complete successfully don't crash)?  

Can this be reproduced just with raw greenlets?

gevent's native code is all created by Cython, so this is unlikely to be a direct gevent bug, although it may be possible to work around it at the gevent level. We don't test on cygwin, only on the native python builds, so I have no way to debug this.

**Comment by rossengeorgiev** [comment]
My bad for not clarifying. It's something to do with the exception, maybe the way it propagates back. The join is not necessary, only a greenlet raising an exception. Raw greenlet works as expected. 
```
CYGWIN_NT-10.0 2.4.1(0.293/5/3) 2016-01-24 11:26 x86_64
Cython version 0.22
Python 3.4.3 (default, May  5 2015, 17:58:45)
[GCC 4.9.2] on cygwin
gevent==1.1.0
greenlet==0.4.9
```

I tried `gdb`, but no stacktrace. Not sure how to debug further. Maybe it's something to do with cygwin64 ?

**Comment by jamadden** [comment]
Ok, if it's related to the exception, that starts to suggest the use of the bundled copy of [tblib](https://pypi.python.org/pypi/tblib). That does use `ctypes`, so there is native stuff going on and the potential for crashes. Can you try disabling that and seeing if it fixes the issue? (e.g., Change `Greenlet._report_error` to not call `dump_traceback`; I think you can just make the third object in that tuple be None.)

**Comment by Ivoz** [comment]
I've seen quite a few errors for python where it ends up being Cygwin's python not compiling ctypes support in.

**Comment by jamadden** [comment]
Thanks for the input! I have absolutely no experience with Python-on-Cygwin (and very little desire to gain any 😀). If it works on 2.7 but not 3.4, that does suggest some issue either in ctypes support or the way tblib uses it. tblib claims support for, and is tested on, both versions, but only the native Windows build. Cygwin seems to be poorly represented in general.

**Comment by rossengeorgiev** [comment]
@jamadden removing `dump_traceback` as you suggested resolved the issue.

**Comment by jamadden** [comment]
Awesome. So this looks like an upstream problem.  @rossengeorgiev do you feel like creating an issue with tblib?

If there's a reliable way to detect impacted Cygwin Python, we could probably workaround this in gevent by disabling that feature, although I'd much rather see an upstream fix. In the meantime, it shouldn't be hard for affected users to monkey-patch `dump_traceback` to return None.

**Comment by rossengeorgiev** [comment]
Ops. I opened an issue on the wrong repo. Could you @jamadden open the issue? I am not sure what I should say there as I am not familiar with the module. I assume https://github.com/ionelmc/python-tblib is the right repo?

**Comment by jamadden** [comment]
Yes, that is the right repo. I can open an issue, but I'll have to CC you and I'm afraid any tests/reproduction requests will wind up directed your way.

**Comment by rossengeorgiev** [comment]
That's fine. I can do that.

**Comment by jamadden** [comment]
Ok, from the discussion at ionelmc/python-tblib#12, this looks to be an issue with the cygwin ctypes build in 64-bit Python 3. It needs a new release by cygwin to fix; the workaround is to use a 32-bit build.
