### ISSUE TITLE
gevent 1.1.0 fails to install on Solaris 10

### ISSUE THREAD

**Issue by wiggin15** [gevent/gevent#777]
Hi. We just started using the latest version of gevent. Unfortunately, easy_install fails to install gevent on Solaris 10 with the message "/bin/sh: test: argument expected" and a weird traceback. See full output here: https://gist.github.com/wiggin15/0e0158cb1ca795c40322.

I think that what causes the issue is this line: https://github.com/gevent/gevent/blob/master/setup.py#L114

    # /bin/sh
    # if [ -e ares_build.h ]; then cp ares_build.h ares_build.h.orig; fi   && /bin/sh ./configure CONFIG_COMMANDS= CONFIG_FILES=   && cp ares_config.h ares_build.h "$OLDPWD"   && mv ares_build.h.orig ares_build.h
    test: argument expected

I don't know what version of 'sh' Solaris 10 is using. I can only offer this:

    # ls -la /sbin/sh
    -r-xr-xr-x 1 root root 82456 Sep 22  2010 /sbin/sh

Installation is successful on all other operating systems, including Solaris 11.

**Comment by wiggin15** [comment]
http://unix.stackexchange.com/questions/62811/62815#62815

**Comment by jamadden** [comment]
It appears that [/bin/sh is a vestigial remanent](http://unix.stackexchange.com/questions/62811/bourne-shell-if-e-directory-file-suffix) of a time before POSIX, and doesn't support `-e`. Does it work for you if you substitute `-r`?

**Comment by wiggin15** [comment]
Yes, `-r` works.
