### ISSUE TITLE
Python gevent under the windows framework of the multi process model?

### ISSUE THREAD

**Issue by zhenghan008** [gevent/gevent#787]
hi！guys:
  python"s gevent  concurrency framework in Windows really can not use multiprocessing to do coroutine and multi process concurrency model?if it can,can you provide a code example?

**Comment by jamadden** [comment]
I'm afraid I don't understand what you are asking. There are documented limitations with mutiprocessing that apply to all platforms. Can you be more specific?

**Comment by zhenghan008** [comment]
@jamadden ,ok!thank you for your answer.in fact, I want to use gevent and multiprocessing to do coroutine + multi-process in windows.I know it can use gevent.fork() to open multiple processes in linux.but in windows,I don't know how to combine them to use.because of the job, I just use the python2.7

**Comment by jamadden** [comment]
I'm sorry, I still do not understand what the *problem* is with gevent, or what it is *missing*. 

If the underlying operating system doesn't support it, gevent can't magically add it. So if Windows doesn't support `os.fork()`, gevent can't somehow make that work.

If `os.fork` isn't available, check out the `subprocess` and `multiprocessing` modules (but again, know that there are some documented limitations there.)

**Comment by zhenghan008** [comment]
@jamadden ok!thank you.
