### ISSUE TITLE
Multiple native threads created when using requests.

### ISSUE THREAD

**Issue by lvella** [gevent/gevent#792]
When I monkey patched `requests` library to use it with `gvent`, it actually worked, and all greenlets executed from the same native thread (checked by calling syscall `gettid()`). But if I run `ps -eLf` while my app is executing, I see a number of native threads equal to the number of spawned greelets.

See for yourself. Run the following code, and while it is running, run `ps -eLf`. Did it with Python 3.5. Requires `requests` (obviously) and `cffi` (used for `gettid()`).

```python
import gevent
from gevent import monkey; monkey.patch_all()
import requests
from cffi import FFI

s = requests.Session()

ffi = FFI()
ffi.cdef("""
     long syscall(long number, ...);
""")

C = ffi.dlopen(None)

def gettid():
    return C.syscall(186) # On linux x86 64 bits
    #return C.syscall(224) # On linux x86 32 bits

def do_get(number):
    url = 'http://ipv4.download.thinkbroadband.com/5MB.zip'
    local_filename = '{:04}.zip'.format(number)

    print('get number', number, ', tid', gettid())
    r = s.get(url, stream=True)
    with open(local_filename, 'wb') as f:
        for chunk in r.iter_content(chunk_size=1024*4):
            if chunk:
                print('chunk for number', number, ', tid', gettid())
                f.write(chunk)
    print('done number', number)

def main():
    evs = [gevent.spawn(do_get, x) for x in range(1, 10)]
    gevent.joinall(evs)

if __name__ == '__main__':
    main()
```

I really don't know where the threads came from, but `requests` shouldn't be able to spawn then, since the module was monkey patched, right?

**Comment by jamadden** [comment]
You're probably seeing gevents thread pool,which is used by default for DNS resolution.

**Comment by lvella** [comment]
Indeed! Using c-ares they were gone.
