### ISSUE TITLE
_handle_and_close_when_done cause socket closed after connection established 

### ISSUE THREAD

**Issue by codepython** [gevent/gevent#794]
hi:)

  I am puzzled that why it close the socker stream after connection success ?  

 the relevant code   is :
  _handle_and_close_when_done   
```python
try:
        ret= handle(*args_tuple)
finally:
       close(*args_tuple)
```

why it alwayes close()

**Comment by codepython** [comment]
my continoues operation of socket.recv() failed with error :  invalide fd error
but if I remove the close() ,it works pretty .

**Comment by Ivoz** [comment]
Hi mate, you could provide a working example of code? http://sscce.org/

**Comment by jamadden** [comment]
See http://www.gevent.org/whatsnew_1_1.html#compatibility 

In a nutshell, the socket is closed deterministically *after* the handler function finishes to ensure that it gets closed and its output flushed. This avoids ResourceWarnings under Python 3, and by not relying on garbage collection to close sockets eliminates a whole class of bugs involving leaked sockets or sockets involved in cycles (plus makes it compatible with PyPy).

**Comment by codepython** [comment]
This is the code In my handle method :
handler():
   t = Transport(socket,address,self.sessionno)// //Transport is greenlet subclass
   t.start() //start the socket thread 
   p = self.protocol(t,self)    //protocol is greenlet subclass
   p.start() //this will call greenlet.start()

After this code executed ,it return to _handle_and_close_when_done ,then it will close the transport socket ,then the after recv operation will fail with a invalid fd error.

 so I should invoke _run() in my handler method directly to avoid the handler to return ?

**Comment by jamadden** [comment]
You *must* keep your handler function from returning before you're done with the socket.

You should probably not directly invoke the private method `_run`.

If you have two greenlet instances that are doing the work, `t` and `p`, you should probably `join` them to make sure that the handler function doesn't return before they do:
```python
   gevent.joinall((t, p))
```

**Comment by jamadden** [comment]
If there's nothing else here @codepython can you close this issue?

**Comment by codepython** [comment]
That works!
