### ISSUE TITLE
NoneType AttributeError when reading from closed socket

### ISSUE THREAD

**Issue by kchen** [gevent/gevent#800]
My application encountered the following exception with gevent 1.1rc5, although I'm having trouble reproducing it in a simplified test case:

(The file paths have been modified from the original output.)

```
  File "server.py", line 617, in read_to_check_for_disconnection
    data = sock.recv()
  File "gevent/_ssl3.py", line 388, in recv
    return self.read(buflen)
  File "gevent/_ssl3.py", line 230, in read
    return self._sslobj.read(len or 1024)
AttributeError: 'NoneType' object has no attribute 'read'
```
This appears to be caused by my application calling shutdown and close on the socket in another greenlet.  I tried to reproduce this with the following code:

```
import gevent.server

def handler(sock, address):
    gevent.spawn(sock.recv)
    gevent.sleep(1)
    sock.close()

server = gevent.server.StreamServer(
    ("127.0.0.1", 8888),
    handle=handler,
    keyfile="key",
    certfile="cert")

server.serve_forever()
```
but was unable to reproduce the error, since I got the expected "OSError: [Errno 9] File descriptor was closed in another greenlet" instead.

**Comment by jamadden** [comment]
Yes, if you're closing a socket in one greenlet while it's being read in a different greenlet, you have a race condition. You'd encounter this error if the remote socket needed to be waited on more than once.

We can probably make this specific case a little better, but I won't promise that there won't be other races possible :)
