### ISSUE TITLE
gevent.ssl should use gevent.socket.create_connection

### ISSUE THREAD

**Issue by dubglan** [gevent/gevent#801]
We're using gevent 1.1rc2. Turns out `ssl.get_server_certificate` does not work without monkey-patching socket:

```
>>> from gevent import ssl
>>> ssl.get_server_certificate(("google.com", 443))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 684, in get_server_certificate
    with closing(context.wrap_socket(sock)) as sslsock:
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 68, in wrap_socket
    _context=self)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 259, in __init__
    raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
ValueError: do_handshake_on_connect should not be specified for non-blocking sockets
```

This happens because `_sslgte279` uses `create_connection` function inherited form the standard `ssl` module. So when `get_server_certificate` creates initial tcp socket it receives a standard blocking socket:
```with closing(create_connection(addr)) as sock:```

Then `context.wrap_socket(sock)` passes this socket object to `SSLSocket ` constructor. It calls the superclass constructor:
```socket.__init__(self, _sock=sock._sock)```

Superclass comes from ```gevent._socket2```, reads the timeout setting of the wrapped socket:
```self.timeout = _socket.getdefaulttimeout()```

and then sets wrapped socket into non-blocking mode:
```self._sock.setblocking(0) ```

However, `SSLSocket.__init__` reads timeout again after `socket.__init__`:
```self.settimeout(sock.gettimeout()) ```

Keep in mind that `sock` in `SSLSocket` constructor is still the same underlaying system socket, not the gevent object created on top of it (i.e. `self`), it was switched into non-blocking mode and its timeout is now 0. This is how `SSLSocket` get timeout 0 itself.

Then, when `do_handshake_on_connect` is checked, it raises an exception:
```
if do_handshake_on_connect:
    timeout = self.gettimeout()
    if timeout == 0.0:
        # non-blocking
        raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
    self.do_handshake()
```

The following code works:
```
>>> from gevent import ssl
>>> from gevent import _sslgte279
>>> from gevent import socket
>>> _sslgte279.create_connection = socket.create_connection
>>> ssl.get_server_certificate(("google.com", 443))
```

**Comment by jamadden** [comment]
Thanks for the report!

**Comment by Zane96** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/gevent/_sslgte279.py", line 707, in get_server_certificate
    with closing(create_connection(addr)) as sock:
  File "/Library/Python/2.7/site-packages/gevent/socket.py", line 86, in create_connection
    raise err
socket.error: [Errno 65] No route to host

Why I got this?
