### ISSUE TITLE
separating pywsgi from gevent

### ISSUE THREAD

**Issue by byaka** [gevent/gevent#803]
I love pywsgi, it light-wieght and has many nice functions (also nice architecture). for some projects i really want to change werkzeug to pywsgi.

but in some scenarios it's very important to run server without gevent.

first look on source say, that need many minor (and maybe some not-minor) changes to separate it.

is anybody really interesting it, or it's only my case?

**Comment by jamadden** [comment]
pywsgi is pretty coupled to gevent and its server architecture. I would not separate it at this point. Of course you're free to fork it.
