### ISSUE TITLE
Is it possible to make python Queue work in gevent?

### ISSUE THREAD

**Issue by zj8487** [gevent/gevent#807]
I have to use a python library(grpc python client or server) that is incompatible with gevent.
So i use multiple threading to solve it. one threading is work on gevent mode and the other threading is work on the non gevent mode. 
The two thread is communicated with a python Queue.
in the gevent thread, i use timer to check the python Queue, the demo is [here](https://github.com/zj8487/helloworld/blob/master/proxy/grpc_proxy.py)

if there is another way like gevent Queue to check the python Queue, is very helpful.

**Comment by jamadden** [comment]
I'm afraid I don't understand what you're asking. Assuming you're not monkey-patching (if you're using grpc you can't be monkey-patching), the builtin standard library Queue will work just fine, in a thread-safe manner---that includes blocking all the other greenlets in the thread when it has to wait. You can use the `block=False` arguments to prevent that.

**Comment by zj8487** [comment]
I am sorry i did not say that clearly, I want to use a greelet to wait on a python Queue(```_queue.get()```) and need it is not blocking all the system if the queue is empty.
I will try the ```block=False``` arguments

thanks a lot
