### ISSUE TITLE
OSError: (24, 'Too many open files') on El Capitan

### ISSUE THREAD

**Issue by vlsd** [gevent/gevent#810]
I'm running into this really weird issue when trying to run a `fabric` script we wrote, but only when using `gevent`. This happens on OS X El Capitan and seems to be (at least a little bit) platform dependent. The following is the traceback:

```python
localhost] local: pelican -s publishconf.py
Done: Processed 238 articles, 0 drafts, 0 pages and 0 hidden pages in 32.78 seconds.
Checking existing redirects... Done.
[8 of 406] [localhost] local: aws s3 cp output/what-we-think/2016/05/18/q-a-with-meta-brown/index.html s3://staging.datascopeanalytics.com/what-we-think/2016/05/18/q-a-with-meta-brown/index.html --acl public-read --website-redirect "/blog/q-a-with-meta-brown/"
Traceback (most recent call last):
  File "/Users/vlad/.virtualenvs/website/lib/python2.7/site-packages/fabric/main.py", line 745, in main
    *args, **kwargs
  File "/Users/vlad/.virtualenvs/website/lib/python2.7/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/vlad/.virtualenvs/website/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/vlad/projects/datascopesite/fabfile.py", line 159, in publish
    _push_to_s3(S3_BUCKETS['staging'])
  File "/Users/vlad/projects/datascopesite/fabfile.py", line 144, in _push_to_s3
    % (redirect_source_local, redirect_source_remote, redirect_target))
  File "/Users/vlad/.virtualenvs/website/lib/python2.7/site-packages/fabric/operations.py", line 1221, in local
    close_fds=(not win32))
  File "/Users/vlad/.virtualenvs/website/lib/python2.7/site-packages/gevent/subprocess.py", line 534, in __init__
    reraise(*exc_info)
  File "/Users/vlad/.virtualenvs/website/lib/python2.7/site-packages/gevent/subprocess.py", line 503, in __init__
    restore_signals, start_new_session)
  File "/Users/vlad/.virtualenvs/website/lib/python2.7/site-packages/gevent/subprocess.py", line 1097, in _execute_child
    errpipe_read, errpipe_write = self.pipe_cloexec()
  File "/Users/vlad/.virtualenvs/website/lib/python2.7/site-packages/gevent/subprocess.py", line 1027, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files
```
This only happens when the `gevent` version of `Popen` is used, which is used in this case because of the aggressive monkey patching that `grequests` does when imported (we don't actually *need* to use `gevent` here, but `grequests` "makes" us). You can ignore most of the top of the traceback, it involves `fabric` running an `aws` script using the `Popen` command, which fails deep in the guts of `gevent`.

**Comment by jamadden** [comment]
OS X has an insanely low default ulimit for open file descriptors (256, I think? I changed it so long ago I don't remember). It is not surprising to me that gevent uses a different number of file descriptors than the raw stdlib does, so unless you have evidence of a *leak*, I wouldn't consider this a bug. Instead I would recommend [increasing the open file descriptor limit](https://www.google.com/search?q=os+x+ulimit+open+files).

**Comment by vlsd** [comment]
Ok, but why would `gevent` use more than 256 file descriptors to run one shell command? This does not make it past the first call to `Popen` in that loop...

**Comment by jamadden** [comment]
I don't know, it completely depends on what the process is doing and what it has open and what it has imported. Why don't you set a breakpoint there and then use `lsof` to see what files are open? 

On my system, a simple `python` command starts out using 40 file descriptors.

**Comment by vlsd** [comment]
I ran the code with both `requests` and `grequests` and did continuous `lsof` during both. In order for the comparison to make sense, I set the size of the `gevent.Pool` that `grequests` uses to 1, which, if I understand correctly, would make one request at a time. 

With the built-in requests, the number of open sockets stayed constant, as old sockets were closed and new ones were open. With the `gevent` version the number of open sockets went steadily up (until my machine crapped out because of the ridiculously low number of open files allowed --- thanks for pointing that out btw). Here's a link to the relevant line in `grequests` https://github.com/kennethreitz/grequests/blob/master/grequests.py#L115

Is the way in which `gevent.Pool` is used there supposed to close sockets as they become unnecessary, or keep them open until the `join` event? I can't tell if this is a bug in `grequests` or a bug in `gevent`...

**Comment by jamadden** [comment]
I don't know enough about requests to be able to answer definitively. However, I'm guessing that the response objects returned by `send` contain an open socket to be able to read the response body from (it's unlikely that they completely buffer the arbitrary-sized body in memory?). So by using `map` and waiting until all `n` responses are available, you'd have `n` open sockets. Consider `imap` instead, maybe.

**Comment by vlsd** [comment]
`imap()` does not behave differently. I think you're right though, the code for `grequests` does not seem to close the session anywhere, so it seems like it's up to the user to deal with it. Explicitly making all of the requests to use the same session seems to have fixed the problem. Thanks for working through this one with me! Definitely *not* a leak :)
