### ISSUE TITLE
gevent.joinall and pool.join dont work

### ISSUE THREAD

**Issue by rafaelcapucho** [gevent/gevent#811]
Hello,

My code is:

```python
def send_resources_info(socketio, subprocess_pids):
    pool = gevent.pool.Pool(5)
    while True:

        dict_info_server = get_resources_info()
        subprocess_info = []

        for pid, spider in subprocess_pids:
            info = pool.spawn(get_resources_info, pid=pid, extra=False)
            subprocess_info.append(info)

        pool.join()

        dict_info_server['sub'] = subprocess_info
        print('\n\npids: ', dict_info_server, '\n\n')

        gevent.sleep(1)
```

And with `gevent.spawn` version:

```python
def send_resources_info(socketio, subprocess_pids):

    while True:
        dict_info_server = get_resources_info()

        subprocess_info = []

        for pid, spider in subprocess_pids:
            info = gevent.spawn(get_resources_info, pid=pid, extra=False)
            subprocess_info.append(info)

        gevent.joinall(subprocess_info)

        dict_info_server['sub'] = subprocess_info
        print('\n\npids: ', dict_info_server, '\n\n')

        gevent.sleep(1)
```

Both produce the result:

`pids:  {'memory_available_mb': 4844.375, 'cpu_percent': 2.0, 'pid': 4055, 'sub': [<Greenlet at 0x7fdf303feb90>], 'memory_used_mb': 30.078125, 'memory_total_mb': 7935.77734375}`

The `sub` key isn't evaluated, in other words the `joinall` and `pool.join` don't have effect. I already testes the same code without gevent, only the raw for and it is working fine.

Thank you,
Py3.5.1 Gevent 1.1.1 - Arch Linux

**Comment by jamadden** [comment]
The purpose of `gevent.joinall` and `pool.join` is simply to wait for the all the greenlets to finish. In the case of `gevent.joinall`, nothing is done to the passed in argument. So for your second example, I would expect exactly the output you're getting. `pool.join` doesn't take an argument, so obviously it can't modify a list it knows nothing about.

You probably need to do something like this: `dict_info_server['sub'] = [greenlet.get() for greenlet in subprocess_info]`

**Comment by rafaelcapucho** [comment]
@jamadden Thank you, your suggestion works for me.

May `join` and `joinall` causes wrong interpretation, probably because we compare it to threads. Articles like that ( http://blog.hownowstephen.com/post/50743415449/gevent-tutorial ) frequently says:

```
# Wait for everything to complete
gevent.joinall(greenlets)
```

**Comment by jamadden** [comment]
Yes, that's exactly what it's doing: waiting for all the greenlets to complete. Joining a thread just waits for the thread to complete, it doesn't change the value of the variable that holds the thread. The two are exactly comparable.

**Comment by rafaelcapucho** [comment]
@jamadden Then actually I should use both, `gevent.joinall` that blocks until all process finish and `.get()` to collect the results?

in other words, I should never asign a `gevent.spawn` to a variable when I want the results, I need to access that value using `.get` possibly after a join.

is it the correct way of thinking?

My final script, 

```
def send_resources_info(socketio, subprocess_pids, public_ip):

    while True:
        dict_info_server = gevent.spawn(get_resources_info)

        subprocess_info = []

        for pid, spider in subprocess_pids:
            info = gevent.spawn(get_resources_info, pid=pid, extra=False)
            subprocess_info.append(info)

        dict_info_server.join()
        dict_info_server = dict_info_server.get()

        gevent.joinall(subprocess_info)
        dict_info_server['sub'] = [greenlet.get() for greenlet in subprocess_info]

        print('\n\npids: ', dict_info_server, '\n\n')

        gevent.sleep(1)
```

Thank you so much.

**Comment by jamadden** [comment]
That's the concept, yes. 

Part of the confusion might be in the variable names. A greenlet is a (possibly running or finished) task, *not* the result of the task. So try this:

```python
def send_resources_info(socketio, subprocess_pids, public_ip):

    while True:
        dict_info_server_greenlet = gevent.spawn(get_resources_info)

        subprocess_info_greenlets = []

        for pid, spider in subprocess_pids:
            info_greenlet = gevent.spawn(get_resources_info, pid=pid, extra=False)
            subprocess_info.append(info_greenlet)

        dict_info_server_greenlet.join()
        dict_info_server = dict_info_server_greenlet.get()

        gevent.joinall(subprocess_info_greenlets)
        dict_info_server['sub'] = [greenlet.get() for greenlet in subprocess_info_greenlets]

        print('\n\npids: ', dict_info_server, '\n\n')

        gevent.sleep(1)
```

For something that just returns results (and you don't have to be concerned about greenlets), consider the `Pool.map` method, which works like the builtin `map` function. It's less flexible, but can be simpler.
