### ISSUE TITLE
DNS resolution fails indefinitely when Greenlet.spawn is used.

### ISSUE THREAD

**Issue by 4simple-org** [gevent/gevent#822]
* gevent version: 1.0.2, 1.1.1
* Python version: 2.7
* Operating System: FreeBSD 10.1

### Description:

```
The application can run fine for some hours 9~17. Then DNS resolution fails forever in libs that use sockets(beanstalk, database, ect), while any other services like (nginx, uwsgi, StreamServer) in the same computer don't fail.

The error output is:
[Errno 8] hostname nor servname provided, or not known
```

### What I've run:

If we spawn monkey.patch threads using Greenlet.spawn, like in code bellow:

```
from gevent import Greenlet, monkey, sleep, queue
monkey.patch_all()

Greenlet.spawn(one_funct, param1, etc)
```

**Comment by jamadden** [comment]
Which resolver are you using, the threaded or ares resolver?

**Comment by 4simple-org** [comment]
I am using default resolver, I think it is c-ares.

**Comment by jamadden** [comment]
The default resolver is the threaded resolver. Check on the state of your processes threads and the gevent threadpool when you get in this situation, that would be interesting to know.

Otherwise, please try the ares resolver.

**Comment by 4simple-org** [comment]
Even if I use monkey.patch_all() I am using threaded resolver?

**Comment by jamadden** [comment]
Yes, the two have nothing to do with each other.

**Comment by 4simple-org** [comment]
ok thanks. I will set ares resolver, and post what happens.

**Comment by 4simple-org** [comment]
After 15 hours running fine, DNS resolve functions starts to fail indefinitely again now through c-ares.

I see c-ares failing forever showing this log message:

> [Errno 4] ARES_ENOTFOUND: Domain name not found

 when python beanstalkc [client](https://github.com/earl/beanstalkc) try to connect inside one Greenlet.spawn thread.

Database functions based in mysqldb fails too with this message:

> Unknown MySQL server host

**Comment by 4simple-org** [comment]
If I restart the service it works fine again, this is what I am doing now until find a solution.

**Comment by jamadden** [comment]
The errors directly from c-ares, and a fact that a restart clears them up, suggest this is a system level problem. Perhaps you're running out of file descriptors or memory or some other resource. An strace/truss/dtrace of the system calls leading to the error could be interesting.

I know of other long-running apps using gevent that don't run into this problem. They're on Linux though.

I don't know how else I could help debug this.

**Comment by 4simple-org** [comment]
The main process and threads remains active, gevent spawn threads displays DNS error logs continuously each 5 seconds and main process is in normal status.

In last test I run only 30 Greenlet.spawn threads, in a separated server alone with not other services.

I will check now strace/truss/dtrace give me some minutes

**Comment by 4simple-org** [comment]
I see where the problem was, you are right the service reach a limit (open ports) due to the usage of a custom buggy data base lib.

89958 is the pid of the affected service.

procstat -f 89958 | wc -l
   32771

sockstat -4 | wc -l
   32765

I see > 32k open ports, most of the file descriptors belong to database connections open.

Thanks

**Comment by 4simple-org** [comment]
See last update, all looks like the app using gevent is the only one affected by the OS limit, other services can use network fine while gevent app fails.

Maybe is just a per process limit at the OS.

**Comment by jamadden** [comment]
file descriptor limits are per-process, yes. see `ulimit`
