### ISSUE TITLE
gevent.monkey.patch_sys(stderr=True) break KeyboardInterrupt exception handling

### ISSUE THREAD

**Issue by smetj** [gevent/gevent#825]
* gevent version:
1.1.1
* Python version:
2.7.11
* Operating System:
Linux indigo 4.5.7-202.fc23.x86_64
Fedora release 23 (Twenty Three)

### Description:
I'm trying to catch and handle the KeyboardInterrupt exception but that does not appear to be possible when sys is monkey patched with parameter _stderr_ set to _True_

I expect the try/except clause to honor the the KeyboardInterrupt handling and continue to execute the code following the except statement.

### What I've run:

```
import gevent
from gevent import monkey; monkey.patch_sys(stderr=True)
from gevent import sleep

def main():
    try:
        while True:
            print "hello"
            sleep(1)
    except KeyboardInterrupt:
        print "hurray"

if __name__ == "__main__":
    main()
```
### Output
```
hello
hello
hello
^CKeyboardInterrupt
Traceback (most recent call last):
hello
hello
hello
^CKeyboardInterrupt
Traceback (most recent call last):
hello
hello
hello
hello
```

**Comment by jamadden** [comment]
Thank you for the report.
