### ISSUE TITLE
Implement channel closing

### ISSUE THREAD

**Issue by munro** [gevent/gevent#827]
Adding channel closing would be an extremely useful feature, the suggested `.put(StopIteration)` doesn't work multiple consumers [1]—unless you know the number of consumers & do the correct number of `put`s, at which point the code becomes coupled with the consumers.  Not sure the best way to implement it, but inspiration could be taken from `core.async`'s `close!`.

[1]
```python
import gevent
from gevent.queue import Channel


def load(ch):
    for x in range(5):
        ch.put(x)

    ch.put(StopIteration)


def process(name, ch):
    for x in ch:
        print('[{}] Processed {}'.format(name, x))
    print('[{}] Done'.format(name))


def good():
    ch = Channel()
    gevent.joinall([
        gevent.spawn(load, ch),
        gevent.spawn(process, 'A', ch),
    ])


def bad_block_forever():
    ch = Channel()
    gevent.joinall([
        gevent.spawn(load, ch),
        gevent.spawn(process, 'B.1', ch),
        gevent.spawn(process, 'B.2', ch),
    ])


if __name__ == '__main__':
    good()
    bad_block_forever()
```
[2] https://clojure.github.io/core.async/#clojure.core.async/close!

**Comment by jamadden** [comment]
I haven't thought much about this, but the `balance` property already lets a producer know how many consumers are blocked waiting on a channel. You can `put_nowait` `StopIteration` until that number either becomes non-negative or you get a timeout exception. That should handle most common cases; it certainly does here:
```
def load(ch):
	for x in range(5):
		ch.put(x)

	while ch.balance < 0:
		ch.put(StopIteration)
	print("[Producer] Done")
```

**Comment by munro** [comment]
Woaah that would be a pretty clever implementation.  One implementation I used was catching `LoopExit` exception, but it's not perfect and fails in quite a few scenarios.  Some practical edge cases to test for: random sleeps between things, multiple writers starting & stoping, multiple consumers, and working over gipc (I could see this being weird with `ch.balance` not working since information is delayed).

**Comment by munro** [comment]
Thinking about it a little more, that should work really well.  Also adding a `.closed` property, so if anything tries to listen afterward an exception can be thrown.  Then testing like crazy 😎

**Comment by jamadden** [comment]
I wasn't suggesting that as an implementation strategy for gevent itself, I was suggesting it as a pattern that would work well for this example and most common uses of a channel---but each example might vary.

Alternatively, a `close` method and property can easily be added in a subclass if the pattern doesn't work due to esoteric uses.

**Comment by jamadden** [comment]
I would review a PR that added a `close` method to the existing Channel if it was simple enough. But because this can be accomplished now via a pattern or a subclass I myself am not inclined to spend more time on it than that right now.

**Comment by munro** [comment]
That's fair!  When I get back into it, I'll open a PR. 😄  I feel strongly it's core functionality, especially for doing CSP—and it's non obvious to implement (yet to see checking `.balance` in any tutorials so kudos!).  Even Gevent docs suggest to use the `.put(StopIteration)`, which only works in the most basic cases.

**Comment by jamadden** [comment]
Closing in triage for 1.2a1 since there have been no updates since July, and this pattern can be implemented by clients, either directly or with a subclass. Feel free to open a PR that references this discussion.
