### ISSUE TITLE
gevent always prints tracebacks to stderr

### ISSUE THREAD

**Issue by denik** [gevent/gevent#83]
# What steps will reproduce the problem?
1. run

```
cat <;foo.py >>;EOF
import gevent
g = gevent.spawn(lambda: 1/0)
def nom(e):
    print 'nom nom'
g.link_exception(nom)
g.join()
EOF
```
1. python foo.py
2. observe that the above prints out:

```
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/gevent/greenlet.py",, line 405, in run
    result = self._run(*self.args, **self.kwargs)
  File "gev-example.py", line 2, in <lambda>
    g = gevent.spawn(lambda: 1/0)
ZeroDivisionError: integer division or modulo by zero
<Greenlet at 0x185e8d0: <function <lambda> at 0x1880410>> failed with ZeroDivisionError
nom nom
```
# What is the expected output? What do you see instead?

I expect to see only "nom nom", as I'm explicitly handling the exception from the greenlet.

The way gevent is now, handling errors from greenlets (without spamming stderr) is very laborous; I ended up writing a wrapper to using AsyncResult, because it's actually able to pass exceptions without spamming the user:

``` python
def spawn_asyncresult(fn, *args, **kwargs):
   """
    Spawn a Greenlet and pass it's results to an AsyncResult.

    This function is useful to shuffle data from a Greenlet to
    AsyncResult, which then again is useful because any Greenlets that
    raise exceptions will cause tracebacks to be shown on stderr by
    gevent, even when ``.link_exception`` has been called. Using an
    AsyncResult avoids this.
   """
    r = gevent.event.AsyncResult()
    def wrapper():
        try:
            value = fn(*args, **kwargs)
        except Exception as e:
            r.set_exception(e)
        else:
            r.set(value)
    g = gevent.spawn(wrapper)

    return r
```
# What version of the gevent are you using?

Ubuntu 11.04 package python-gevent 0.13.0-1build1.
# What version of libevent are you using?

libevent-1.4-2     1.4.13-stable-1
# On what operating system?

Ubuntu 11.04.
# On what Python?

2.7.1-0ubuntu5

Which event loop are you running? (Paste the output of python -c "from
gevent.core import *; print get_method(), get_version()")

epoll 1.4.13-stable
# Please provide any additional information below.

`Greenlet._report_error` has explicit traceback.print_exception and sys.stderr.write in it. I'd suggest these to be done only if the greenlet was not linked to anything via .link_exception<p><a href="http://code.google.com/p/gevent/issues/detail?id=83">Reported by tommi.virtanen.</a></p><hr/><h2>earlier comments</h2>

<p><strong>tommi.virtanen said, at 2011-05-20T01:11:31.000Z:</strong></p>

<p>For the next person stumbling on this:

mailing list discussion: https://groups.google.com/group/gevent/browse_thread/thread/42a15ebfa84f29fe

The approach there seems to be to return exceptions as values, which makes code like "g.get()" (ran for the side effect of waiting for g to complete) succeed, the error gets eaten silently -- that's no good.

The code has changed in latest development (to be 0.14 I guess), I haven't tested if this is fixed or not.</p>

**Comment by ml31415** [comment]
I was also quite annoyed by this behaviour. My solution was to create `LoggingHub` and `LoggingGreenlet`, to integrate the gevent error reporting into the standard logging mechanisms. It's basically feeding a logger object into hub and greenlets, and overwrites any method which do printing. So unfortunately it has to copy several of the original methods right now, which is a bit messy. Maybe some similar logging mechanism could also be integrated into mainline gevent?

```python
class LoggingHub(Hub):
    """ Extension for using standard python logging on a per-greenlet basis instead of printing for error output """

    def __init__(self, loop=None, default=None, logger=None):
        Hub.__init__(self, loop=loop, default=default)
        self.logger = logger or default_logger

    def print_exception(self, context, exc_type, value, tb):
        # Overwrite, to faciliate custom logging and formatting
        if isinstance(context, (tuple, list)) and len(context) == 2:
            link, context = context
        else:
            link = None

        logger = getattr(context, 'logger', self.logger)
        err_name = getattr(exc_type, '__name__', 'exception')
        tb_str = self._format_exception(exc_type, value, tb)
        del tb

        if isinstance(context, Greenlet) and hasattr(context, 'name'):
            # We should have a LoggingGreenlet here
            tb_prefix = "Linked function from " if link else ''
            context_name = ' ' + context.name if context.name else ''
            tb_prefix += type(context).__name__ + context_name + ' failed with %s\n' % err_name
        else:
            # context here can be greenlet type or a greenlet object
            if not isinstance(context, str):
                try:
                    context_str = self.format_context(context)
                except:
                    logger.exception()
                    context_str = repr(context)
            else:
                context_str = context
            tb_prefix = '%s failed with %s\n' % (context_str, err_name)

        logger.error(tb_prefix + tb_str)

        if link is not None:
            try:
                logger.error('Failed to notify link %s of %r', gevent.greenlet.getfuncname(link), context)
            except:
                logger.exception("Logging within linked function failed")

    def _format_exception(self, exc_type, value, tb):
        # Remove empty lines
        return '\n'.join(l.rstrip() for l in traceback.format_exception(exc_type, value, tb) if l.strip())

class LoggingGreenlet(gevent.Greenlet):
    """ Named greenlet writing errors to a logger instead of std.err """
    info_len = 70

    def __init__(self, *args, **kwargs):
        self.logger = kwargs.pop('logger', logging.getLogger())
        self.name = kwargs.pop('greenlet_name', None)
        gevent.Greenlet.__init__(self, *args, **kwargs)

    def _formatinfo(self):
        # Overwrite to define custom info length
        try:
            return self._formatted_info
        except AttributeError:
            pass
        try:
            result = getfuncname(self.__dict__['_run'])
        except Exception:
            pass
        else:
            args = []
            if self.args:
                args = [repr(x)[:self.info_len] for x in self.args]
            if self.kwargs:
                args.extend(['%s=%s' % (key, repr(value)[:self.info_len]) for (key, value) in self.kwargs.items()])
            if args:
                result += '(' + ', '.join(args) + ')'
            # it is important to save the result here, because once the greenlet exits '_run' attribute will be removed
            self._formatted_info = result
            return result
        return ''

    def __repr__(self):
        # Overwrite method to consider greenlet name in the representation
        classname = self.__class__.__name__
        name = self.name + ' ' if self.name else ''
        result = '<%s %sat %s' % (classname, name, hex(id(self)))
        formatted = self._formatinfo()
        if formatted:
            result += ': ' + formatted
        return result + '>'

def get_logging_hub():
    hub = get_hub()
    if not isinstance(hub, LoggingHub):
        # We need a LoggingHub for the LoggingGreenlets to work
        try:
            from gevent.hub import set_hub
            set_hub(logging_hub(hub))
        except ImportError:
            from gevent.hub import _threadlocal
            _threadlocal.hub = logging_hub()
        hub = get_hub()
    return hub
```

**Comment by jamadden** [comment]
In the general case, it is *not safe* to use loggers to print the exceptions. The functions that do this can be called in the hub, where it is not allowed to use the gevent blocking API. If the system is monkey-patched and the logging configuration includes a SocketAppender or SysLogAppender, for example, then the logger will fail. 

Alternatively, if the system is not monkey-patched, such loggers would block the event loop for an indeterminate amount of time.

Those reasons seem sufficient to me not to directly include such functionality in gevent---gevent shouldn't make it *too* easy to shoot yourself in the foot out of the box.

**Comment by ml31415** [comment]
I'm using simple `StreamHandler`s in there, to write to disk as well to as to stderr itself, in order to catch any issues all together into a unified log format and not loose any error messages somewhere in the console. To say that the time spent by the `StreamHandler`s is indefinite seems to be a bit far fetched, the same is true for anything inside a greenlet.

I agree shit may happen with more elaborate log handlers, using networking, mailing etc. Though in my case this setup now runs quite well for some years already, not causing any errors itself. If there is a cleaner way to do this, I'm all ears.

**Comment by jamadden** [comment]
1.2 adds the `exception_stream` property to the Hub that can be assigned a writable object that will receive errors (this can wrap a logger in the same way that pywsgi allows). In addition, it's always been possible to assign to `Hub.handle_error`, `print_exception`, etc, to override-in-place. 

Note that this was added because FileObjectThread can't be used in the Hub, a situation that was already arising for some users who monkey-patched stderr. So it's dangerous to mess with.

I don't plan to widely advertise this functionality because of the safety and blocking concerns.

**Comment by anentropic** [comment]
is there a way to just turn off logging of tracebacks?
