### ISSUE TITLE
KeyError: 'CONTENT_LENGTH' when running with Flask app

### ISSUE THREAD

**Issue by jt28340** [gevent/gevent#831]
* gevent version: 1.0.1
* Python version: 2.7.8
* Operating System: Windows 7 x64bits

### Description:
I was trying to access a Flask app wrapped by Gevent. It was running I think. However, I encountered "Internal Server Error" when i open it in Chrome browser by typing "localhost:5002". Therefore, i looked into the cmd screen and found the below error. If I run the flask app without gevent wrapped, it can prompt me the login page which is the expected result.
```
Traceback (most recent call last):
  File "Q:\lib\site-packages\gevent\pywsgi.py", line 508,
in handle_one_response
    self.run_application()
  File "Q:\lib\site-packages\gevent\pywsgi.py", line 495,
in run_application
    self.process_result()
  File "Q:\lib\site-packages\gevent\pywsgi.py", line 484,
in process_result
    for data in self.result:
  File "C:\AlWeb\webapp\webapp.py", line 41,
in __call__
    int(environ['CONTENT_LENGTH'] or 0))
KeyError: 'CONTENT_LENGTH'
{'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/web
p,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': 'session=eyJ1c2VyIjoyfQ.CmjhHw.f81C9mUJUmUZIt1GpxxbyXrRVTI',
 'HTTP_HOST': 'localhost:5002',
 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHT
ML, like Gecko) Chrome/51.0.2704.63 Safari/537.36',
 'PATH_INFO': '/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '54275',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'jeff.net',
 'SERVER_PORT': '5002',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x0000000001D42150>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x000000000A5A8550>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with KeyError
```

### What I've run:
In webapp.py:
```python
...
app = Flask(__name__)

@app.route('/')
def main():
    return render_template('index.html')

if __name__ == "__main__":
    app.run()
```
In gevent_server.py:
```python
from gevent.wsgi import WSGIServer
from gevent import monkey
from webapp import app

monkey.patch_all()

if __name__ == "__main__":
    http_server = WSGIServer(('', 5002), app)
    http_server.serve_forever()
```
Then I run the command "python gevent_server.py" in cmd

**Comment by jamadden** [comment]
This is a bug in `webapp.py`:
```python
  File "C:\AlWeb\webapp\webapp.py", line 41,
in __call__
    int(environ['CONTENT_LENGTH'] or 0))
```

It assumes that `CONTENT_LENGTH` is available, but according to [the WSGI spec](https://www.python.org/dev/peps/pep-3333/#environ-variables) that key "[m]ay be empty or absent" if the client didn't send one. Different servers are free to handle that as they choose.

The portable way to handle this is to write `environ.get('CONTENT_LENGTH', 0)`.

**Comment by jamadden** [comment]
(Also, please consider upgrading to gevent 1.1. It has a much cleaner pywsgi implementation that fixes several security bugs.)

**Comment by jt28340** [comment]
Where to add "environ.get('CONTENT_LENGTH', 0)"? I have tried to add in webapp.py & gevent_server.py main or even in the main page route. All failed and received "Internal Server Error".

**Comment by jamadden** [comment]
The exact line that's causing the problem is webapp.py line 41, according to the traceback:
```python
  File "C:\AlWeb\webapp\webapp.py", line 41,
in __call__
    int(environ['CONTENT_LENGTH'] or 0))
```

That should be:
```python
    int(environ.get('CONTENT_LENGTH', 0))
```
