### ISSUE TITLE
Gevent WSGI server. "Too many open files"

### ISSUE THREAD

**Issue by smetj** [gevent/gevent#832]
* gevent version: 1.1.0
* Python version: 2.7.5
* Operating System: CentOS Linux release 7.2.1511 (Core)

### Description:

I'm running a Gevent WSGI server with ssl which after serving content for a long time starts to refuse to handle further requests and generates stacktraces for every request referring to "Too many open files".

When raising the "allowed open filehandles" we postpone the problem and not solve it.  I just takes longer to reach the point.

### What I've run:

```
Traceback (most recent call last):
File "/usr/lib64/python2.7/site-packages/gevent/baseserver.py", line 186, in _do_read
args = self.do_read()
File "/usr/lib64/python2.7/site-packages/gevent/server.py", line 111, in do_read
client_socket, address = self.socket.accept()
File "/usr/lib64/python2.7/site-packages/gevent/_socket2.py", line 188, in accept
client_socket, address = sock.accept()
error: [Errno 24] Too many open files
<WSGIServer at 0x25f1710 fileno=6 address=0.0.0.0:4000> failed with error
Traceback (most recent call last):
File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 534, in run
result = self._run(*self.args, **self.kwargs)
File "/usr/lib64/python2.7/site-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
return handle(*args_tuple)
File "/usr/lib64/python2.7/site-packages/gevent/server.py", line 126, in wrap_socket_and_handle
ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
File "/usr/lib64/python2.7/site-packages/gevent/_sslgte279.py", line 691, in wrap_socket
ciphers=ciphers)
File "/usr/lib64/python2.7/site-packages/gevent/_sslgte279.py", line 199, in __init__
self._context.load_cert_chain(certfile, keyfile)
IOError: [Errno 24] Too many open files
<Greenlet at 0x100dc370: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x13159dd0 fileno=[Errno 9] Bad file d)> failed with IOError
```

**Comment by jamadden** [comment]
Can you please provide a minimum example that demonstrates the leak?

**Comment by smetj** [comment]
When investigating this I came to the conclusion that my application was building up large quantities of connections in FIN_WAIT2 state (other side sometimes abruptly disconnects) consuming all available file descriptors for the user running the application hence it was not able to open the ssl certs anymore (no more fds available) for new incoming requests yielding the above error.

In other words, it's not a bug or problem in Gevent wsgi ...

For reference, as it might be useful to other people, the solution in my case was to explicitly enable _keepalive_  on the socket:

```python
self.socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
self.socket.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)
self.socket.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPIDLE, 1)
self.socket.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPINTVL, 3)
self.socket.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPCNT, 5)
```
