### ISSUE TITLE
What is the difference between pool and threadpool

### ISSUE THREAD

**Issue by Jackyele** [gevent/gevent#833]
I am newbie to Gevent. I wonder what is the difference between `pool` and `threadpool`, and when to use them?

And what is the difference between `Greenlet` and `threading.Thread` which has been patched?

**Comment by jamadden** [comment]
One tracks greenlets, the other deals with native threads (regardless of monkey-patching).

A Thread has a specific API that is different than a Greenlet, monkey-patched or not.

Note that this is not really the appropriate forum to ask generic questions.
