### ISSUE TITLE
patch_select fails to patch selectors on 3.5, if executed via patch_all

### ISSUE THREAD

**Issue by codepainters** [gevent/gevent#835]
* gevent version: 1.1.1
* Python version: 3.5

It seems that `patch_all()` fails to patch `selectors` module, if executed like this:
```python
from gevent.monkey import patch_all
patch_all()

import selectors
s = selectors.SelectSelector()
print (s._select)
# <built-in function select>
```

However, it works if executed on its own:
```python
from gevent.monkey import patch_select
patch_select()

import selectors
s = selectors.SelectSelector()
print (s._select)
# <bound method patch_select.<locals>._select of <selectors.SelectSelector object at 0x10e5ebcc0>>
```
The problem is caused by `patch_select` expecting the `selectors` module not to be imported yet.
```python
    if sys.version_info[:2] >= (3, 4):
        # Python 3 wants to use `select.select` as a member function,
        # leading to this error in selectors.py (because gevent.select.select is
        # not a builtin and doesn't get the magic auto-static that they do)
        #    r, w, _ = self._select(self._readers, self._writers, [], timeout)
        #    TypeError: select() takes from 3 to 4 positional arguments but 5 were given
        select = __import__('select')
        selectors = __import__('selectors')
        if selectors.SelectSelector._select is select.select:
            def _select(self, *args, **kwargs): # pylint:disable=unused-argument
                return select.select(*args, **kwargs)
            selectors.SelectSelector._select = _select
```
When the second `if` statement executes:
 * `select` is already patched
 * if `selectors` module was imported before, its `selectors.SelectSelector._select` refers to original unpatched function. The condition is false and no patching ever happens.

Why is `selectors` already imported, then? A call to `patch_socket` inside `patch_all()` imports `gevent.socket`:
```python
    if socket:
        patch_socket(dns=dns, aggressive=aggressive)
    if select:
        patch_select(aggressive=aggressive)
```
This in turn imports `_socket3`, which imports `_socketcommon` which in turn import Python's `socket` module, which pulls `selectors`.

**Comment by codepainters** [comment]
Not sure, which is better:

 * patch `select` before `socket`
 * let `patch_socket()` compare `selectors.SelectSelector._select` against unpatched `select.select()`

**Comment by jamadden** [comment]
Thanks for the report.

**Comment by codepainters** [comment]
Thanks for a lightning fast fix! :)

BTW, I'm wondering if `selectors` module should be prepared for patched `selec.select()` (and thus require no extra patching from `gevent`)? I encountered this issue with `selectors34` first - see discussion here: https://github.com/berkerpeksag/selectors34/pull/4#issuecomment-234245856

Do you think it would make sense to make `selector` module accept patched `select`? It's a hack anyway, so I'm not sure if it would be ever accepted upstream.

**Comment by jamadden** [comment]
> Do you think it would make sense to make selector module accept patched select? It's a hack anyway, so I'm not sure if it would be ever accepted upstream.

That might be nice, but I highly doubt upstream would accept it. Monkey-patching aside, it's a private implementation detail we're messing with (`_select`).

**Comment by codepainters** [comment]
Well, `selectors` accepting patched `select` would actually save us from patching private stuff. Let's try, we'll see.

**Comment by codepainters** [comment]
Just for record - as expected, http://bugs.python.org/issue27634 was rejected.
