### ISSUE TITLE
data is silently not sent into socket in python3

### ISSUE THREAD

**Issue by zeevt** [gevent/gevent#837]
* gevent version: 1.1.2
* Python version: 3.4
* Operating System: amazon linux

### Description:
AWS EC2 server running Amazon linux  4.1.7-15.23.amzn1.x86_64

two virtualenvs with today's latest pip, setuptools, six and gevent
one with this python:
Python 3.4.3 (default, Jul 20 2016, 21:31:36)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux

another with this python:
Python 2.7.10 (default, Jul 20 2016, 20:53:27)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2

A very simple test script that moves 1 million bytes over an internet socket from one greenlet to another in the same python process.

On python 2.7 it successfully moves 1000000 bytes as expected.
On python 3.4 it doesn't. Instead, it moves a different number each time: 995408, 996216, 997904, 996104, 995736, 996400 silently corrupting data.

```python
from __future__ import print_function
import socket
import six
import gevent
from gevent.monkey import patch_all
patch_all()

def server():
    serversocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    serversocket.bind(('0.0.0.0', 15000))
    serversocket.listen(1)
    clientsocket, address = serversocket.accept()
    total_received = 0
    while True:
        chunk = clientsocket.recv(1024)
        if not len(chunk):
            break
        total_received += len(chunk)
    print("total_received", total_received)
    serversocket.close()

def client():
    data_packets = []
    for i in range(1000):
        data_packets.append(six.int2byte(i % 256) * 1000)
    sock = socket.create_connection(('my external ip', 15000))
    conn = sock.makefile("rwb", 0)
    for data_packet in data_packets:
        conn.write(data_packet)
    sock.shutdown(socket.SHUT_RDWR)
    sock.close()

jobs = []

job1 = gevent.spawn(server)
job1.start()
jobs.append(job1)

job2 = gevent.spawn(client)
job2.start()
jobs.append(job2)

gevent.joinall(jobs)
```

**Comment by jamadden** [comment]
I cannot reproduce this using either 'localhost' or explicit IP addresses. Tested in these environments:

- Debian 15.10 (Linux 4.2.0)/ Python 3.4.3+
- Raspbian (Linux 4.4.9)/Python 3.4.2
- Mac OS 10.11.6/Python 3.4.5

**Comment by jamadden** [comment]
Note that the given code has a bug in it:
```python
    for data_packet in data_packets:
        conn.write(data_packet)
```

It ignores the return value of `write` and assumes it all got sent. But `write` on the file-like object returned by [`makefile`](https://docs.python.org/3/library/socket.html#socket.socket.makefile) is [allowed to send fewer bytes than requested](https://docs.python.org/3/library/io.html#io.RawIOBase.write). It is up to the caller to check how many bytes it wrote and send the remainder if necessary.

I suspect this is more likely to be a problem on slower systems/networks such as one might find in a virtualized environment.
