### ISSUE TITLE
FileObjectPosix does not support unbuffered IO

### ISSUE THREAD

**Issue by ekimekim** [gevent/gevent#840]
* gevent version: 1.1.2
* Python version: 2.7.12
* Operating System: linux (specifically archlinux, kernel version `4.6.4-1-ARCH`)

### Description:

The `FileObjectPosix` class converts a passed in bufsize of 0 to 1.
This behaviour is documented, so this is not a bug.
However, it's a missing feature - to have unbuffered gevent-friendly blocking IO on arbitrary file-like objects (in my specific use-case, i'm writing a single byte to a pipe).

### What I've run:

```python
from gevent.subprocess import Popen, PIPE
cat = Popen(['cat'], stdin=PIPE, stdout=PIPE, bufsize=0)
cat.stdin.write('x')
assert cat.stdout.read(1) == 'x'
```
Expected output:
```
done!
```
Actual output:
Process hangs.
After sending a SIGINT to get a traceback:
```
^CKeyboardInterrupt
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    assert cat.stdout.read(1) == 'x'
  File "/usr/lib/python2.7/site-packages/gevent/_fileobjectposix.py", line 274, in read
    return self.io.read(size)
  File "/usr/lib/python2.7/site-packages/gevent/_fileobjectposix.py", line 112, in readinto
    data = self.__read(len(b))
  File "/usr/lib/python2.7/site-packages/gevent/_fileobjectposix.py", line 100, in __read
    self.hub.wait(self._read_event)
  File "/usr/lib/python2.7/site-packages/gevent/hub.py", line 630, in wait
    result = waiter.get()
  File "/usr/lib/python2.7/site-packages/gevent/hub.py", line 878, in get
    return self.hub.switch()
  File "/usr/lib/python2.7/site-packages/gevent/hub.py", line 609, in switch
    return greenlet.switch(self)
KeyboardInterrupt
```
An `strace` confirms that the byte was not written to `cat.stdin`.

**Comment by jamadden** [comment]
If buffering is a concern, you probably need to be working at a lower level; I suggest [`nb_read` and `nb_write`](http://www.gevent.org/gevent.os.html#posix-functions). You could also try using `GreenFileDescriptorIO` directly, but keep in mind it's an implementation class subject to change or deletion at any time.

**Comment by jceel** [comment]
How about implementing read1() for unbuffered reads?

**Comment by jamadden** [comment]
We can and probably should add a `read1()` in most cases,  but I don't see how that *necessarily* leads to unbuffered reads. If the underlying `BufferedReader` has at least one byte buffered, [only buffered bytes are returned](https://docs.python.org/2/library/io.html#io.BufferedReader.read1).

**Comment by jamadden** [comment]
In this case, simply calling `cat.stdin.flush()` resolves the hang. Does that solve your actual usecase?

**Comment by ekimekim** [comment]
This is great, thank you!
And yes, my interim solution was a manual flush after every call.
