### ISSUE TITLE
BlockingIOError raised by socket.connect_ex after monkey patch on python3.5

### ISSUE THREAD

**Issue by dpkp** [gevent/gevent#841]
* gevent version: 1.1.2
* Python version: 3.5.0
* Operating System: mac os

### Description:

In non-blocking mode, `socket.connect_ex` is expected to return an errno and not raise an exception (except socket.gaierror caused by hostname / dns lookup failures).

On python3.5 gevent raises `BlockingIOError: [Errno 115] Operation now in progress` when it should simply return the errno, 115.

### What I've run:

```
from gevent import monkey
monkey.patch_all()

import socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setblocking(False)
ret = s.connect_ex(("www.google.com", 80))
print(ret)
```

It appears that gevent is attempting to return the error code here:
https://github.com/gevent/gevent/blob/b550598753d3cf4763cb47ba3bf804bfb9db26b0/src/gevent/_socket3.py#L305-L314 specifically, L312

But the `type(ex) is error` check is not sufficient. here, type(ex) is `BlockingIOError` while socket.error is `OSError`

**Comment by jamadden** [comment]
Thanks for the report. Is that expected behaviour specific to (new/changed) in Python 3.5 or should it be the same all the way back to Python 3.3?

**Comment by dpkp** [comment]
I think connect_ex semantics are unchanged between python2 and python3. The difference is that the socket exception classes were refactored in 3.3, so while python2 socket.connect() raises socket.error, python3 raises different exception types (all subclassed from OSError, I believe)

**Comment by jamadden** [comment]
I'm surprised, then, that the stdlib tests (in greentest/3.x/test_socket.py, probably) don't contain a check for this...I wonder if there's a different stdlib test file we need to include.

**Comment by dpkp** [comment]
Do you have a link to the source of the stdlib tests?

**Comment by jamadden** [comment]
There's a good mirror at https://github.com/python/cpython
