### ISSUE TITLE
Update Python 3.4 tests

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#844]
test_httplib.py is failing on Appveyor now; previously (the last good build) it was with 3.4.3, which is the version of the tests. Now Appveyor is giving us 3.4.4 and we're getting certificate validation failures.

**Comment by tarekziade** [comment]
Thanks!

**Comment by jamadden** [comment]
Hi! Can you provide some more context for your comment? Is this affecting you? I didn't realize it was more than an isolated test issue.
