### ISSUE TITLE
_socket3.py has invalid signature for makefile method

### ISSUE THREAD

**Issue by wkv** [gevent/gevent#845]
* gevent version: 1.1.2 (and 1.1.1)
* Python version: 2.7.3
* Operating System: Ubuntu 12.04

### Description:
 Installing shows this error message and there is a bare "*", does not seem necessary.
```
SyntaxError: ('invalid syntax', ('venv/lib/python2.7/site-packages/gevent/_socket3.py', 183, 51, '    def makefile(self, mode="r", buffering=None, *,\n'))
```

**Comment by jamadden** [comment]
Thank you for your report. That is indeed correct and is not a problem for Python 2; it is not even reported with a modern pip version. See e.g., #601 and several others.
