### ISSUE TITLE
Pool.imap should honor greenlet_class

### ISSUE THREAD

**Issue by kerrick-lyft** [gevent/gevent#849]
* gevent version: 1.0.1
* Python version: 2.7.6
* Operating System: Ubuntu 14.04.4

(Note: I know my gevent / Python versions are out-of-date, but I read the source code at master and this bug is still present).

### Description:

I created a Greenlet subclass that preserves the Flask context, and created a Pool subclass:
```
from gevent.pool import Pool
class MyPool(Pool):
    greenlet_class = FlaskContextPreservingGreenlet
```
However, when I call `MyPool(10).imap(my_func, my_data)`, the Flask context is not propagated down to `my_func`, because [`imap` spawns an `IMap` instance](https://github.com/gevent/gevent/blob/90472cab964250e48bd5f9062cbea0ae3608b28f/src/gevent/pool.py#L358), and [`IMap` inherits from vanilla `Greenlet`](https://github.com/gevent/gevent/blob/90472cab964250e48bd5f9062cbea0ae3608b28f/src/gevent/pool.py#L33).

One solution would be to dynamically generate the IMap class:
```
def get_imap_unordered_class(greenlet_class):
    class IMapUnordered(greenlet_class):
    """
    An iterator of map results.
    """
    [...]

    return IMapUnordered

def get_imap_class(greenlet_class):
    class IMap(get_imap_unordered_class(greenlet_class)):
    [...]

    return IMap
```

**Comment by kerrick-lyft** [comment]
I've created a PR to fix this: https://github.com/gevent/gevent/pull/850

**Comment by jamadden** [comment]
`Pool.imap` *does* honor the `greenlet_class`:

```
>>> from gevent import pool, Greenlet
>>> from gevent import getcurrent
>>> class MyGreenlet(Greenlet): pass
...
>>> pool = pool.Group()
>>> pool.greenlet_class = MyGreenlet
>>> def func(i):
...   print("Running in", getcurrent())
...
>>> list(pool.imap(func, (1, 2)))
Running in <MyGreenlet at 0x102890af8: func(1)>
Running in <MyGreenlet at 0x102890b90: func(2)>
```

The fact that there's an intermediate greenlet used to implement part of that functionality is an undocumented implementation detail.

As the zen states, "Explicit is better than implicit." Rather than relying on internal details about how greenlets are structured, perhaps you can pass your context as an explicit argument.

**Comment by kerrick-lyft** [comment]
Libraries that interoperate with Flask expect the Flask context to be available under the global variable `flask.request`, which under the covers uses a Greenlet-local variable to ensure each request gets its own context. If I'm explicitly passing the context around, I can't use code that assumes the context is available at `flask.request`, or I have to do extra work to ensure that `flask.request` is updated appropriately every time I use `Pool`.

Moreover, I think it's surprising that my Greenlet subclass works as expected in nearly all cases but breaks with Pool.imap, and libraries like gevent should try to minimize surprises.

I updated the PR to memoize the return value of get_imap_class and get_imap_unordered_class. That way, only one class object is created for each Greenlet class that the user code defines. It doesn't leak memory now (although the build still fails on Windows with Python 3.4, not sure why).

It might be cleaner to keep a reference to the greenlet in IMap instead of dynamically inheriting from the greenlet subclass (composition instead of inheritance). Should I write up a PR to do it this way?

**Comment by jamadden** [comment]
Thank you for your comments. 

Pyramid also has a threadlocal (or greenlet local) `request` property. To access it in foreign threads, it is important to properly set it up when that thread begins running. I know of projects that do this when using `Pool`, and it is not a burden; Python provides several ways to make that easy to do. In fact, the extra clarity of being sure exactly what request is being used when the code is running has benefits for code readability and testing, to mention only a few. I do not see how `flask.request` should be any different.

It seems your Greenlet subclass is making assumptions about the manner in which it is used, namely that the threadlocal has already been set up. If it is used outside that assumption, things break. This is not surprising. Hidden assumptions are prone to that sort of problem, hence "explicit is better than implicit." It is easy to imagine a future refactoring of `Greenlet.spawn_later,` for example, breaking this in the same way.

I appreciate your efforts, but I do not expect to merge #850 or another PR that changes the way in which IMap spawns child greenlets; I do not want to encourage implicit assumptions about greenlet relationships and context.

**Comment by jamadden** [comment]
Thanks again for your interest in this. Even though the outcome wasn't mergeable pull requests, I hope the rationale clear and the alternatives are helpful.
