### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by bootsmann** [gevent/gevent#864]
* gevent version: 1.1.2
* Python version: 2.7.10
* Operating System: Raspbian GNU/Linux 8.0 (jessie) & Windows 8.1 x64

### Description:

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 126, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 691, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 271, in __init__
    raise x
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:581)
<Greenlet at 0x751e8490: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x751ec350 fileno=[Errno 9] Bad file d)> failed with SSLError`

### What I've run:

https://github.com/gevent/gevent/blob/master/examples/wsgiserver_ssl.py
Cert and key created with openssl:
`openssl req -newkey rsa:2048 -nodes -keyout domain.key -x509 -days 365 -out domain.crt`

**Comment by jamadden** [comment]
That error message is actually being produced by the *client* you're connecting with sending a plain HTTP request, not an HTTPS request. You need to use an `https://` URL in a browser or tool, or `ssl.wrap_socket` in Python code.

Note that this certificate is not valid and won't be accepted by default in most tools, even when they connect with HTTPS. The excellent [httpie](https://httpie.org) client produces this error on the server by default: `SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590)`, while the client produces this error `http: error: SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed while doing GET request to URL: https://localhost:8443/`. To make it work, you can tell it to ignore invalid certificates:
```
$ http --verify no https://localhost:8443
HTTP/1.1 200 OK
Content-Length: 18
Content-Type: text/html
Date: Wed, 21 Sep 2016 13:37:28 GMT

<b>hello world</b>
```

Another way of seeing how clients may react to your certificates is with `openssl s_client -connect localhost:8443 -verify 2`.

Note that the Python `ssl.wrap_socket` API doesn't verify the certificate chain by default.

**Comment by bootsmann** [comment]
Thx very much. I found the mistake:
instead of `wss://10.0.2.112:8443/web_socket'` I had written `ws://`
