### ISSUE TITLE
should i lock/release share obj while using gevent threadpool ?

### ISSUE THREAD

**Issue by 4ever911** [gevent/gevent#865]
* gevent version: 1.1.1
* Python version: Python 2.7.11 :: Anaconda 4.1.0 (64-bit)
* Operating System: Ubuntu 16.04 xenial 64bit

### Description:

I want to fetch a large number of pages from one website,  so i was trying to use gevent ThreadPool. 

The problem is that the code runs like multiple threads when I tried to print some text to the console. You can see the output of the second function, they are all mixed together.

I think the output debug strings should be listed one after another, no matter which methods i use.
Is there anything wrong?

```
import gevent.monkey
gevent.monkey.patch_socket()

import gevent
import requests
from gevent.threadpool import ThreadPool


def fetch(pid):
    r = requests.get('http://www.baidu.com')
    
    print 'Process', pid, ':', len(r.text)

def asynchronous():
    threads = []
    for i in range(1,10):
        threads.append(gevent.spawn(fetch, i))
    gevent.joinall(threads)

def asynchronousPool():
    pool = ThreadPool(10)
    for i in range(1,10):
        pool.spawn(fetch, i)      
    gevent.wait()

print('----------Asynchronous----------')
asynchronous()

print('----------POOL----------')
asynchronousPool()
```

### What I've got:

```
----------Asynchronous----------
Process 1 : 2381
Process 4 : 2381
Process 6 : 2381
Process 2 : 2381
Process 3 : 2381
Process 8 : 2381
Process 7 : 2381
Process 5 : 2381
Process 9 : 2381
----------POOL----------
ProcessProcessProcess  ProcessProcess Process25ProcessProcess  3     69 8::41  :     :: :2381:2381:  2381 
 
 23812381
238123812381
Process 7 : 2381
```

Does it mean that while using gevent threadpool, I need to lock/release share resource? If so, why do i use gevent thread instead of the default python threads library.

**Comment by jamadden** [comment]
A ThreadPool uses native threads, so you have exactly the same concerns that you'd have with *any* use of native threads.

You probably don't want to use a ThreadPool here anyway, I doubt it's going to gain you any additional concurrency over what gevent already provides.

**Comment by 4ever911** [comment]
Thanks for your reply. So i guess i need to come up with my own task queue manager, in order to control the number of simultaneous greenlets.

**Comment by jamadden** [comment]
You can probably get what you want with a [regular gevent.pool.Pool](http://www.gevent.org/gevent.pool.html#gevent.pool.Pool).
