### ISSUE TITLE
Gevent 1.1.2 + PyPy3 brings up threading error when monkey patching

### ISSUE THREAD

**Issue by btegs** [gevent/gevent#866]
I installed a local version of PyPy3 to my /opt directory and after installing setuptools and pip, I installed gevent 1.1.2 from pip and this is what happened from simply starting pypy3 and doing a gevent import and monkey patching it:

> brian@teg1:/opt/pypy3/bin$ ./pip3 install gevent
> Collecting gevent
>   Using cached gevent-1.1.2.tar.gz
> Building wheels for collected packages: gevent
>   Building wheel for gevent failed: [Errno 13] Permission denied: '/home/brian/.cache/pip/wheels/cb'
> Failed to build gevent
> Installing collected packages: gevent
>   Running setup.py install for gevent ... done
> Successfully installed gevent-1.1.2

and after starting up pypy3 with gevent installed...

> brian@teg1:/opt/pypy3/bin$ ./pypy3
> Python 3.3.5 (40497617ae91, May 30 2016, 05:15:23)
> [PyPy 5.2.0-alpha0 with GCC 4.8.2] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> And now for something completely different: ``running tests is essential for
> developing pypy -- uh? did I break the test? (fijal)''
>  from gevent.monkey import patch_all; patch_all()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/opt/pypy3/site-packages/gevent/monkey.py", line 577, in patch_all
>     patch_thread(Event=Event)
>   File "/opt/pypy3/site-packages/gevent/monkey.py", line 327, in patch_thread
>     patch_module('thread')
>   File "/opt/pypy3/site-packages/gevent/monkey.py", line 155, in patch_module
>     gevent_module = getattr(__import__('gevent.' + name), name)
>   File "/opt/pypy3/site-packages/gevent/thread.py", line 35, in <module>
>     from gevent.lock import BoundedSemaphore
>   File "/opt/pypy3/site-packages/gevent/lock.py", line 20, in <module>
>     from thread import allocate_lock as _allocate_lock
> ImportError: No module named 'thread'

**Comment by jamadden** [comment]
Thanks for the report and your interest in PyPy3. As you know, PyPy3 is in alpha state. It's not currently supported in our build matrix and has known test failures. It's not a high priority for me personally but might move up when it hits beta. cf #826.

**Comment by btegs** [comment]
Thanks for the response. I've used PyPy2 + gevent in the past with no issues and decided to give PyPy3 a shot in one of my scripts and the threading errors kept coming up. So I went back and launched pypy3 manually in Ubuntu and just typing "from gevent.monkey import patch_all; patch_all()" threw up errors after one line.

I think gevent is a great library and its unfortunate that Python 3 support is still having issues when its solid in Python 2 and its variants. I know there are others like guv and uvloop, but having both Python 2 and 3 unified under gevent would be nice. :-)

**Comment by jamadden** [comment]
> Python 3 support is still having issues

I wouldn't consider that to be an accurate characterization. On *released* Python 3.3+, gevent works fine and is supported as much as Python 2 is. But PyPy3 with 3.3 support isn't released yet, it's barely an alpha. I don't have the time or motivation to chase PyPy3-alpha specific bugs that are just as likely to be in PyPy3 itself as they are to be anywhere else, and as such are likely to change as PyPy3 matures.
