### ISSUE TITLE
websocket example issue,

### ISSUE THREAD

**Issue by penolove** [gevent/gevent#870]
* gevent version: 
* Python version: 2.7.6
* Operating System: ubuntu 14.04

pip with 8.12
### Description:
while runing the websocket example, on chrome will see
![image](https://cloud.githubusercontent.com/assets/9348557/19178853/b8753c1a-8c89-11e6-8c94-cc675906c716.png)
and don't know how to extact data from the Blob

### What I've run:
on shell:
cd gevent/examples
python websocket.py

on chrome ,url= http://localhost:7000

**Comment by jamadden** [comment]
gevent doesn't contain any file called `websocket.py`. Could you be more specific?

**Comment by penolove** [comment]
Sorry , I'm wrong , it's issue in the eventlet library.
