### ISSUE TITLE
SSLEOFError with Flask-SocketIO and gevent

### ISSUE THREAD

**Issue by eoswald** [gevent/gevent#875]
* gevent version: 1.1.2
* Python version: 2.7.12
* Operating System: Arch Linux/Raspbian/Ubuntu

### Description:

Using Flask 0.11 and Flask-SocketIO 2.7.1 with gevent, every client connection yields an SSLEOFError. This example reproduces the issue every single time:

### What I've run:

    from flask import Flask
    from flask_socketio import SocketIO
    
    from gevent import monkey
    monkey.patch_all()
    
    import ssl

    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret'

    socketio = SocketIO(app, async_mode='gevent')
    
    @app.route('/')
    def index():
        return "Hello World!"
    
    @socketio.on('connect')
    def handle_connect_event():
        print('Client connected')
    
    if __name__ == '__main__':
        socketio.run(app, host='127.0.0.1', port=8443,
                     certfile='ssl/server/server.cer', keyfile='ssl/server/server.key',
                     ca_certs='ssl/server/ca.cer', cert_reqs=ssl.CERT_REQUIRED,
                     ssl_version=ssl.PROTOCOL_TLSv1_2)

Which produces this error upon client connection:

    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
        result = self._run(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 25, in     _handle_and_close_when_done
        return handle(*args_tuple)
      File "/usr/lib/python2.7/site-packages/gevent/server.py", line 126, in wrap_socket_and_handle
        ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
      File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 691, in wrap_socket
        ciphers=ciphers)
      File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 271, in __init__
        raise x
    SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)
    <Greenlet at 0x7fda74ab04b0: _handle_and_close_when_done(<bound method     WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a,     (<socket at 0x7fda747dc590 fileno=[Errno 9] Bad fi)> failed with SSLEOFError

I access the page via `https://localhost:8443` and generate the certs using this script: 
https://github.com/NYU-Hyperloop/Secure-Telemetry-Server/blob/master/ssl/initial_setup.sh

I'm also using OpenSSL version 1.0.2.j if that helps. This issue was also brought up with Flask-SocketIO but I think they determined it was a bug in gevent. https://github.com/miguelgrinberg/Flask-SocketIO/issues/88

**Comment by jamadden** [comment]
Can you simplify the example to not include third-party frameworks?

**Comment by eoswald** [comment]
Yeah, I removed Flask-SocketIO and just use Flask as the WSGI application to the WSGIServer:

    from flask import Flask
    
    from gevent import monkey
    from gevent import pywsgi
    from geventwebsocket.handler import WebSocketHandler
    monkey.patch_all()
    
    import ssl
    
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret'
    
    
    @app.route('/')
    def index():
        return "Hello World!"
    
    if __name__ == '__main__':
        test_kwargs = {'certfile': 'ssl/server/server.cer', 'keyfile': 'ssl/server/server.key',
                       'ca_certs': 'ssl/server/ca.cer', 'cert_reqs': ssl.CERT_REQUIRED,
                       'ssl_version': ssl.PROTOCOL_TLSv1_2}
    
        wsgi_server = pywsgi.WSGIServer(
            ('127.0.0.1', 8443), app, handler_class=WebSocketHandler,
            log=None, **test_kwargs)
    
        wsgi_server.serve_forever()

And this is the error I got upon connection. Looks the same:

    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
        result = self._run(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 25, in     _handle_and_close_when_done
        return handle(*args_tuple)
      File "/usr/lib/python2.7/site-packages/gevent/server.py", line 126, in wrap_socket_and_handle
        ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
      File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 691, in wrap_socket
        ciphers=ciphers)
      File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 271, in __init__
        raise x
    SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)
    <Greenlet at 0x7f5ed51fd050: _handle_and_close_when_done(<bound method     WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a,     (<socket at 0x7f5ed51f3f50 fileno=[Errno 9] Bad fi)> failed with SSLEOFError

I know I still use Flask in this test but I tried looking in test__pywsgi.py to see if there was some kind of testing WSGI application used but unless I'm mistaken it seems like `None` is passed in for all the tests.

**Comment by eoswald** [comment]
Actually that's funny. Even if you pass `None` instead of `app` to `WSGIServer` it still produces the same error. Maybe there's a problem with my key generation?

**Comment by jamadden** [comment]
> I know I still use Flask in this test but I tried looking in test__pywsgi.py to see if there was some kind of testing WSGI application used but unless I'm mistaken it seems like None is passed in for all the tests.

`application` is [usually defined as a staticmethod](https://github.com/gevent/gevent/blob/master/src/greentest/test__pywsgi.py#L400) in the test class, and accessed as [`self.application`](https://github.com/gevent/gevent/blob/master/src/greentest/test__pywsgi.py#L256). It's also done [via subclassing](https://github.com/gevent/gevent/blob/master/src/greentest/test__server_pywsgi.py#L29). 

> Maybe there's a problem with my key generation?

Possibly. Or maybe it's setting `cert_reqs` to `CERT_REQUIRED`. That requires a *client* certificate to be presented. Which not all HTTP clients know how to do.

**Comment by eoswald** [comment]
> Or maybe it's setting cert_reqs to CERT_REQUIRED. That requires a client certificate to be presented. Which not all HTTP clients know how to do.

Hmm, I didn't even think of that. I've tried this on Chrome, Chromium, and Firefox with the same problem so I assume it's not a client issue.

**Comment by jamadden** [comment]
Were you prompted to choose a certificate to present? If not, that's just the client hanging up because it doesn't know what to do.

**Comment by eoswald** [comment]
Yes. And selecting it loads the webpage fine. I'm just seeing if it's possible to suppress the error because when the page reloads and multiple clients connect this exception will get raised several times per connection.

**Comment by jamadden** [comment]
So this doesn't seem to be a bug with gevent, it's SSL behaving as SSL behaves when requiring client certificates (a pretty rare thing to do outside of specific environments).
