### ISSUE TITLE
gevent 1.1.2 group map_async(self, func, iterable, callback=None) can not call func with many args?

### ISSUE THREAD

**Issue by xmdevops** [gevent/gevent#876]
* gevent version:
1.1.2
* Python version:
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
* Operating System:
windows

### Description:

```
Traceback (most recent call last):
  File "C:\Program Files\Python27\lib\site-packages\gevent\greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
TypeError: show_data() takes exactly 2 arguments (1 given)
<Greenlet at 0x2964930L: show_data((0, 0))> failed with TypeError
```

### What I've run:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
#
# Authors: limanman
# OsChina: http://xmdevops.blog.51cto.com/
# Purpose:
#
"""
# 说明: 导入公共模块
import gevent
import itertools
from gevent.pool import Group
from gevent.queue import Queue
# 说明: 导入其它模块


def add_worker(name, q):
    while not q.empty():
        task = q.get()
        print 'found notice: worker(%s:%s) got task(%s)' % (name, gevent.getcurrent(), task)
        gevent.sleep(0)


if __name__ == '__main__':
    q = Queue()
    g = Group()
    # 添加任务
    for _ in xrange(100):
        q.put_nowait(_)

    # 通用方法
    # for worker in ('langlang', 'fengfeng', 'shuishui'):
    #     g.add(gevent.spawn(add_worker, worker, q))
    # g.join()


    def show_data(x, y):
        print x, y

    res = zip(xrange(10), xrange(10))
    # 快速方法
    print g.map_async(show_data, res).get()
```

**Comment by jamadden** [comment]
That is correct. The `TypeError` is expected and documented. `map_async` calls `map` which ["appl[ies] the func to each element of the iterable."](http://www.gevent.org/gevent.pool.html#gevent.pool.Group.map).

There is no syntax to indicate that you somehow expect gevent to unpack elements of the `iterable` for you.

There are many alternatives, however, including simply unpacking the argument yourself, using varargs and assignment to have *Python* unpack the elements for you (the deprecated unpacking-a-single argument-inline form might work for you under Python 2), a lambda function that unpacks and forwards, etc, etc,
