### ISSUE TITLE
test_backdoor hangs on OpenBSD

### ISSUE THREAD

**Issue by czarkoff** [gevent/gevent#886]
* gevent version: 1.2a1
* Python version: 2.7.12
* Operating System: OpenBSD

### Description:
Test just hangs and sits there indefinitely.  CPU load is low, python does not respond to signals.

### What I've run:

```sh
cd src/greentest && python2.7 ./testrunner.py --config known_failures.py
```

**Comment by jamadden** [comment]
I can't reproduce a hang in `test__backdoor.py` on a brand new bare-bones OpenBSD VM:

```
# python --version
Python 2.7.12
# uname -a
OpenBSD openbsd 6.0 GENERIC.MP#2319 amd64
# python ./test__backdoor.py -v
test_banner (__main__.Test) ... ok
test_builtins (__main__.Test) ... ok
test_multi (__main__.Test) ... ok
test_quit (__main__.Test) ... ok
test_switch_exc (__main__.Test) ... ok
test_sys_exit (__main__.Test) ... ok

----------------------------------------------------------------------
Ran 6 tests in 0.262s
```

**Comment by jamadden** [comment]
If I purposefully misconfigure my DNS server, I can obtain a hang similar to what you're describing in test__socket.py:TestTCP.test_connect_ex_gaierror. A ktrace indicates that the event loop is entering a `poll` with a one minute timeout. Apparently `poll` is not interruptible under OpenBSD....

**Comment by jamadden** [comment]
Since this was not reproducible and there have been no updates in a month, I'm going to go ahead and close it. Please feel free to reopen if there are updates.

**Comment by czarkoff** [comment]
Sorry for taking so long to respond, but I keep getting the same issue over and over again.  `python2.7 -u test__backdoor.py` just sits there stopped.  If I wake it up with `kill -CONT pid`, I get the following:
```
| /usr/local/bin/python2.7 -u test__backdoor.py                
  ....Got Empty                                                
  switching out          
  Traceback (most recent call last):
    File "<console>", line 1, in <module>                      
    File "test__backdoor.py", line 119, in bad
      gevent.sleep(0.1)   
    File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 194, in sleep
      hub.wait(loop.timer(seconds, ref=ref))
    File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 630, in wait
      result = waiter.get()
    File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 878, in get
      return self.hub.switch()
    File "/home/czarkoff/tmp/obj/pobj/py-gevent-1.2.0/gevent-1.2.0/src/greentest/greentest.py", line 472, in switch
      return _original_Hub.switch(self, *args)
    File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 608, in switch
      switch_out()                                             
    File "/usr/local/lib/python2.7/site-packages/gevent/backdoor.py", line 46, in switch_out
      sys.stdin, sys.stderr, sys.stdout = self.saved
  TypeError: 'NoneType' object is not iterable
  >>>                   
                       
! /usr/local/bin/python2.7 -u test__backdoor.py [code TIMEOUT] [took 559.7s]
```

**Comment by czarkoff** [comment]
@jamadden, is there any additional info I could provide that would help debugging the issue?

**Comment by jamadden** [comment]
I haven't had a chance to try to reproduce it again myself, hopefully within a few days.

The most important things to know is if this is the stock gevent .tar.gz from PyPI, built to use its own embedded libraries, or if there are any patches or external (system) libraries in use. Unfortunately if I'm reading the test log correctly it looks like you're trying to use system libraries. That makes things much more difficult because now the variables of how those libraries were configured and built, what version they are, patches applied, etc come into play. If you *don't* link to system libraries and let gevent use its embedded copy do the tests pass?

**Comment by czarkoff** [comment]
This was a log with system cares and libev.  [Some tests pass with bundled libraries](http://termbin.com/tyu9), and there is no hang. Still, I am only interested in using gevent with system libraries, as otherwise high maintenance burden and associated security risk are unacceptable to us.

**Comment by jamadden** [comment]
I cannot reproduce this, even using the system libev (4.22) on OpenBSD 6.0 with 64-bit python 2.7.12.

Very roughly, the steps I took were these (and yes, I'm running as root [in a virtual machine] because I couldn't be bothered to create a user):
```
## instal system deps
# pkg_add libev
# pkg_add python-tests
## install pip and virtualenv; make and activate a virtualenv
## clone 1.2.1
# git clone https://github.com/gevent/gevent 
# cd gevent
# pip install -r dev-requirements.txt
# Build non-embedded
# CPPFLAGS=-I/usr/local/include LIBEV_EMBED=0 MAKE=gmake python ./setup.py  develop
## verify
# ldd src/gevent/libev/corecext.so
src/gevent/libev/corecext.so:
        Start            End              Type Open Ref GrpRef Name
        00001069933d3000 0000106993831000 dlib 2    0   0      /home/root/gevent/src/gevent/libev/corecext.so
        0000106a1bce5000 0000106a1c0f2000 rlib 0    1   0      /usr/local/lib/libev.so.3.1
        00001069ec8b5000 00001069ece8b000 rlib 0    1   0      /usr/local/lib/libpython2.7.so.0.0
        00001069487fd000 0000106948c0b000 rlib 0    2   0      /usr/lib/libpthread.so.22.0
        0000106a20548000 0000106a20970000 rlib 0    2   0      /usr/lib/libm.so.9.0
        000010699bf1d000 000010699c329000 rlib 0    1   0      /usr/lib/libutil.so.12.1
## test
# cd src/greentest
# python testrunner.py --config ./known_failures.py
```

I get failures, but test_backdoor.py isn't among them, it works smoothly.
```
Longest-running tests:
180.0 seconds: /root/.virtualenvs/gevent27/bin/python -u test__doctests.py
120.1 seconds: /root/.virtualenvs/gevent27/bin/python -u -m monkey_test --Event test_threading_local.py
120.0 seconds: /root/.virtualenvs/gevent27/bin/python -u -m monkey_test --Event test_urllib2.py
120.0 seconds: /root/.virtualenvs/gevent27/bin/python -u -m monkey_test test_urllib2.py
120.0 seconds: /root/.virtualenvs/gevent27/bin/python -u -m monkey_test test_threading_local.py

18/150 tests failed in 07:42

18/150 unexpected failures
 - /root/.virtualenvs/gevent27/bin/python -u test__socket_dns.py
 - /root/.virtualenvs/gevent27/bin/python -u -m monkey_test test_threading.py
 - /root/.virtualenvs/gevent27/bin/python -u -m monkey_test test_urllib2.py
 - /root/.virtualenvs/gevent27/bin/python -u test__doctests.py
 - /root/.virtualenvs/gevent27/bin/python -u -m monkey_test test_ssl.py
 - /root/.virtualenvs/gevent27/bin/python -u -m monkey_test --Event test_socket.py
 - /root/.virtualenvs/gevent27/bin/python -u -m monkey_test --Event test_urllib2.py
 - /root/.virtualenvs/gevent27/bin/python -u -m monkey_test --Event test_threading.py
 - /root/.virtualenvs/gevent27/bin/python -u test__timeout.py
 - /root/.virtualenvs/gevent27/bin/python -u test__socket_dns6.py
 - /root/.virtualenvs/gevent27/bin/python -u test__ssl.py
 - /root/.virtualenvs/gevent27/bin/python -u -m monkey_test test_threading_local.py
 - /root/.virtualenvs/gevent27/bin/python -u test__socket.py
 - /root/.virtualenvs/gevent27/bin/python -u test___example_servers.py
 - /root/.virtualenvs/gevent27/bin/python -u -m monkey_test --Event test_ssl.py
 - /root/.virtualenvs/gevent27/bin/python -u -m monkey_test --Event test_threading_local.py
 - /root/.virtualenvs/gevent27/bin/python -u test__pywsgi.py
 - /root/.virtualenvs/gevent27/bin/python -u -m monkey_test test_socket.py
```

```
+ /root/.virtualenvs/gevent27/bin/python -u test__backdoor.py
| /root/.virtualenvs/gevent27/bin/python -u test__backdoor.py
  ......
  ----------------------------------------------------------------------
  Ran 6 tests in 0.270s

  OK

- /root/.virtualenvs/gevent27/bin/python -u test__backdoor.py [took 0.4s]
```

(There are a few test timeouts; test_threading_local and test_doctest I've seen timeout before but only in a Python 2.7 virtualenv under OS X; I've never bothered to investigate any closer because it heisenbugs and goes away when you look. Most of the remaining failures are network related, many of them caused by the lack of dual IPv6/IPv4 sockets where the test binds to '' but connects to 127.0.0.1 or vice versa.)

This is a pretty bare-bones VM that I've spun up just to test this issue. There's nothing weird in my environment:
```
# env | sort
HOME=/root
LOGNAME=root
MAIL=/var/mail/root
PATH=/root/.virtualenvs/gevent27/bin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/X11R6/bin:/usr/local/sbin:/usr/local/bin
PKG_PATH=http://mirror.esc7.net/pub/OpenBSD/6.0/packages/amd64
PS1=(gevent27) #
SHELL=/bin/ksh
SSH_CLIENT=192.168.1.82 55430 22
SSH_CONNECTION=192.168.1.82 55430 192.168.1.158 22
SSH_TTY=/dev/ttyp0
TERM=linux
USER=root
VIRTUAL_ENV=/root/.virtualenvs/gevent27
_=/usr/bin/env
```

**Comment by czarkoff** [comment]
I am lost in the complexity of this setup.  I am trying to update a port, and I can't use pip due to requirement of being able to build ports offline.  Consequently I can't use virtualenv.  With ports-specific stuff filtered out, what I am doing is:
```
$ /usr/bin/env -i CARES_EMBED=0 LIBEV_EMBED=0 /usr/local/bin/python2.7 ./setup.py egg_info || true
$ /usr/bin/env -i CARES_EMBED=0 LIBEV_EMBED=0 /usr/local/bin/python2.7 ./setup.py build --build-base=`pwd`
$ /usr/bin/env -i CARES_EMBED=0 LIBEV_EMBED=0 PYTHONPATH="`pwd`/src"  /usr/local/bin/python2.7 ./setup.py test
```
(Irrelevant noise from ports infrastructure is redacted.  All instances of (`pwd`) are actually real paths, just did not want to litter. `env -i` insures that no piece of my environment leaks to the python processes.)

And with 1.2.1 [this](http://termbin.com/4nl5) is what I get.  Now, I am not even sure what I am supposed to work around to make this (pretty standard for all I know) workflow produce reasonable results.  Pretty much the same thing happens when I do `cd src/greentest && python2.7 testrunner.py --config ./known_failures.py` instead of the last step above.

Any suggestions?

**Comment by jamadden** [comment]
From the log above, all those import errors mean that the build failed, or that PYTHONPATH is wrong, or that the runtime shared objects (e.g., libev) can't be found. Since we know this process works when done in the usual way, something about the way your packaging worklow is set up is doing things wrong. I don't know enough about what all that does to be able to do any more than hazard a guess (which would be that since the list of dependencies it prints is different for the "run regression" step, it's isolating this build too much).

**Comment by czarkoff** [comment]
As a matter of fact the shared objects were being placed into wrong localtion. I found out the set of knobs that makes thing work. Still, the commands above are the commands that are used to build nearly every other python port in our tree, so the fact that gevent is cannot be built and tested this way hints that there **might be** some issue with gevent's build system setup.

Anyway, now with things working again I don't have the issue with test_backdoor anymore, so I am closing this issue.  @jamadden, I sincerely thank you for your support which helped me move the port forward, and I am sorry for wasting excessive amounts of your time.
