### ISSUE TITLE
queue.get can raise both deque.IndexError and Empty for empty gevent.queue

### ISSUE THREAD

**Issue by rudy-6-4** [gevent/gevent#894]
* gevent version: any
* Python version: any
* Operating System: any

### Description:

a = gevent.queue.Queue()
a.get() # can raise IndexError instead of Empty in multi-threaded code

Even if code is not guaranteed thread safe, it could be good to have the same exception.

### Code
```python
def get(...):
    if self.qsize():
        if self.putters:
            self._schedule_unlock()
        return self._get()
    return self.__get_or_peek(...)
```
could be replaced by:
```python
def get(...):
    if self.qsize():
        if self.putters:
            self._schedule_unlock()
         try:
             return self._get()
         except IndexError:
             pass  # let's continue with _get_or_peek
    return self.__get_or_peek(...)
```
?

**Comment by jamadden** [comment]
The code is *explicitly* not thread safe. That's sort of the point. If it was trying to deal with threads in any way it would need to use threaded locks, and it doesn't. The code is *greenlet* safe only.

**Comment by rudy-6-4** [comment]
True, I am not asking for it to be thread-safe or even to be modified. Globally the code is not thread safe, however some usages are. In that case I think it's still better to not surprise the user with an undocumented exception.

**Comment by jamadden** [comment]
I'm afraid I don't understand the argument you're making. The code is not thread safe, therefore using it in a threaded fashion by definition has undefined consequences (subject to change at any time).

**Comment by rudy-6-4** [comment]
Ok, I understand your point. Let's say it is not an issue.

**Comment by jamadden** [comment]
Thanks for the report!
