### ISSUE TITLE
No documentation in gevent servers about SO_REUSEPORT

### ISSUE THREAD

**Issue by thestick613** [gevent/gevent#895]
I've recently read about using SO_REUSEPORT on linux socket servers and i want to try it on a gevent-based datagram server. on my macbook i get this error when i try to bind the second time:

```
Traceback (most recent call last):
  File "some_datagram_server.py", line 21, in <module>
    srv.start()
  File "/usr/local/lib/python2.7/site-packages/gevent/baseserver.py", line 304, in start
    self.init_socket()
  File "/usr/local/lib/python2.7/site-packages/gevent/server.py", line 148, in init_socket
    self.socket = self.get_listener(self.address, self.family)
  File "/usr/local/lib/python2.7/site-packages/gevent/server.py", line 158, in get_listener
    return _udp_socket(address, reuse_addr=cls.reuse_addr, family=family)
  File "/usr/local/lib/python2.7/site-packages/gevent/server.py", line 203, in _udp_socket
    sock.bind(address)
  File "<string>", line 1, in bind
socket.error: [Errno 48] Address already in use: ('0.0.0.0', 10000)
```

but i've tried the same code on a recent linux system and it seems to work. both processes manage to bind on `0.0.0.0:10000`, and they both seem to respond. The requests coming from my laptop only went to the first process, but after i closed it, they were forwarded automatically to the second one.

My question is why isn't this documented in gevent? I've grepped the whole source code tree for SO_REUSEPORT and i haven't found any mention. How is this working then? Thanks!

**Comment by jamadden** [comment]
Whether and how `SO_REUSEPORT` works has nothing to do with gevent, that's up to the underlying system. gevent can't do anything that the underlying system can't do.

**Comment by thestick613** [comment]
You need to `setsockopt(socket.SOL_SOCKET,socket.SO_REUSEPORT,1)` on the socket before you start accepting connections. The `DatagramServer` has access to the _socket object inside but it needs to be activated before.
