### ISSUE TITLE
TypeError: memoryview: str object does not have the buffer interface (python 3.4)

### ISSUE THREAD

**Issue by PiRune** [gevent/gevent#898]
* gevent version: (latest as per 30 nov 2016)
* Python version: 3.4
* Operating System: Raspbian (latest as per 30 nov 2016)

### Description: 

I get the following error:

```
File "/usr/local/lib/python3.4/dist-packages/gevent/_socket3.py", line 35, in _get_memory
    mv = memoryview(data)
TypeError: memoryview: str object does not have the buffer interface
Wed Nov 30 14:55:04 2016 {'REMOTE_PORT': '3887', 'REMOTE_ADDR': '::ffff:192.168.3.24', 'HTTP_HOST': '192.168.3.6:8402', (hidden keys: 22)} failed with TypeError

```
How can I avoid this error?

### What I've run:

```
#!/usr/bin/env /usr/bin/python3
# -*- coding: utf-8 -*-

import RPi.GPIO as GPIO

import time

import datetime

import os

from ouimeaux.environment import Environment

def on_switch(switch):
        print("Switch found!", switch.name)

env = Environment(on_switch)

try:
        env.start()

        env.discover()

        env.list_switches()

except (RuntimeError, TypeError, NameError):
        print('Der skete en fejl (WeMo): {:%Y-%m-%d %H:%M:%S}'.format(datetime.datetime.now()))  

switch = env.get_switch('WeMo')

switch.basicevent.SetBinaryState(BinaryState=0)
switch.basicevent.SetBinaryState(BinaryState=1)

```
...which gives the abovementioned error.

I have installed and reinstalled ouimeaux and gevent using pip3 install.

**Comment by jamadden** [comment]
On Python 3, `socket.write` only accepts `bytes` objects (or `bytebuffer` objects). Specifically, they *do not* accept `str` objects. If you're trying to send a literal, you need to use the `b"syntax"`. 

The rest of the traceback should give a better indication of where the str is coming from.

**Comment by PiRune** [comment]
thank you for your swift reply, jamadden. Here is the rest of the traceback:

```
Switch found! WeMo
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gevent/pywsgi.py", line 936, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.4/dist-packages/gevent/pywsgi.py", line 910, in run_application
    self.process_result()
  File "/usr/local/lib/python3.4/dist-packages/gevent/pywsgi.py", line 896, in process_result
    self.write(data)
  File "/usr/local/lib/python3.4/dist-packages/gevent/pywsgi.py", line 742, in write
    self._write_with_headers(data)
  File "/usr/local/lib/python3.4/dist-packages/gevent/pywsgi.py", line 764, in _write_with_headers
    self._write(data)
  File "/usr/local/lib/python3.4/dist-packages/gevent/pywsgi.py", line 727, in _write
    self._sendall(data)
  File "/usr/local/lib/python3.4/dist-packages/gevent/pywsgi.py", line 702, in _sendall
    self.socket.sendall(data)
  File "/usr/local/lib/python3.4/dist-packages/gevent/_socket3.py", line 408, in sendall
    data_memory = _get_memory(data)
  File "/usr/local/lib/python3.4/dist-packages/gevent/_socket3.py", line 35, in _get_memory
    mv = memoryview(data)
TypeError: memoryview: str object does not have the buffer interface
Wed Nov 30 14:55:04 2016 {'REMOTE_PORT': '3887', 'REMOTE_ADDR': '::ffff:192.168.3.24', 'HTTP_HOST': '192.168.3.6:8402', (hidden keys: 22)} failed with TypeError
```

I figured it was a bytes / string problem, but I'm not sure how to solve it (what to edit and where)

**Comment by jamadden** [comment]
The traceback tells us that it's the results of the WSGI callable (the WSGI application) that's bad. That is, whatever is calling `start_response` is then proceeding to return a `str` instead of `bytes`.

**Comment by jamadden** [comment]
I see that ouimeaux has a dependency on gevent-socketio. Last I knew, gevent-socketio wasn't Python 3 compatible (there are outstanding pull requests for that).

**Comment by PiRune** [comment]
once again, thank you for your swift response. Being a noob, I want to make sure I understand. Nothing needs to be changed in the `_socket3.py` file? Can I correct something in the `pywgi.py` file to avoid the error?

How can I see from the traceback that gevent-socketio is the problem? Can I fix that or does that require gevent-socketio to be fully Python 3 compatible?

**Comment by jamadden** [comment]
This is almost certainly not a gevent bug. There is nothing to change in gevent. Even if you did try to edit `_socket3.py` to avoid this, you would still get an error from Python itself when the `str` was passed to the Python socket.

This is a bug somewhere inside (presumably) outmeaux or one of the libraries it uses. I do not know where or what library. 

You could try to use a debugger to set a breakpoint in `run_application` and step into the WSGI application and see what it returns (and how it gets it)---that's the bug.

Other than that, you could use Python 2.7, which is still fully supported and in some cases like this potentially less troublesome.

**Comment by PiRune** [comment]
I considered using Python 2.7 (tried it and it works), but I wanted to integrate my script into a big Python 3 script which I have spent a lot of time on. That's why I'm trying to get it to work with Python 3.

But thank you once again. Very helpful. Hopefully Ouimeaux can find a solution. They say that it is Python 3 compatible, but apparently their dependencies are not.

**Comment by jamadden** [comment]
Since this seems to be a problem elsewhere I'm going to go ahead and close this.

**Comment by vnarasimhan** [comment]
The real problem appears to be in ouimeaux. The WSGIServer handler in subscription.py returns a str object instead of bytes object. One possible fix is below:

```
diff --git a/ouimeaux/subscribe.py b/ouimeaux/subscribe.py
index 1efff46..1e57d21 100644
--- a/ouimeaux/subscribe.py
+++ b/ouimeaux/subscribe.py
@@ -19,6 +19,7 @@ log = logging.getLogger(__name__)
 
 NS = "{urn:schemas-upnp-org:event-1-0}"
 SUCCESS = '<html><body><h1>200 OK</h1></body></html>'
+SUCCESS_BINARY = SUCCESS.encode()
 
 
 class SubscriptionRegistry(object):
@@ -81,7 +82,7 @@ class SubscriptionRegistry(object):
             ('Content-Length', str(len(SUCCESS))),
             ('Connection', 'close')
         ])
-        yield SUCCESS
+        yield SUCCESS_BINARY
 
     def _event(self, device, type_, value):
         for t, callback in self._callbacks.get(device, ()):
```
