### ISSUE TITLE
[Question]Possibility of adding asyncio custom event loop work with gevent

### ISSUE THREAD

**Issue by sideffect0** [gevent/gevent#900]
i like gevent api , not checked gevent internal structure, but is it possible in python3+gevent with asyncio custom event loop ?

**Comment by jamadden** [comment]
See #641 for a discussion, if I understand what you're asking.

**Comment by jamadden** [comment]
Otherwise, note that gevent does work perfectly on Python 3 as is.

**Comment by jamadden** [comment]
Closing in favor of the more in-depth discussion in #982.

**Comment by 3ddi** [comment]
You didn't close @jamadden :)
