### ISSUE TITLE
Add SSLContext to StreamServer et al

### ISSUE THREAD

**Issue by arcivanov** [gevent/gevent#901]
* gevent version: 1.2
* Python version: 3.5+
* Operating System: Any

### Description:

Currently StreamServer and descendants take a whole bunch of SSL-related args but do not accept SSLConxext and gevent's wrap_socket does not accept it either even though both SSLSocket and SSLContext fully support both.

I'll be interested adding this myself if the commit will be accepted.

### What I've run:

I don't care what name it is, but I presume `context` would work as an addition to `**ssl_args` with appropriate changes here https://github.com/gevent/gevent/blob/master/src/gevent/server.py#L25 and further down the call stack.

**Comment by jamadden** [comment]
I wouldn't necessarily be opposed to such a change, but it may be somewhat difficult and ugly because gevent still supports versions of Python that don't have an SSLContext.

**Comment by arcivanov** [comment]
Well, if SSLContext is not available in Python before 2.7.9 with gevent having scrapped support of 2.6. Which means that the affected people will be everyone who still uses 2.7.8 and below only, with current versions in stock distros being at least 2.7.11 mostly. People below 2.7.8 won't be able to provide a sensible object anyway for `context`/`ssl_context` argument and the interpretation using standard ssl_args will be available.

What arg name would you prefer?
