### ISSUE TITLE
Backport HTTP Response Splitting fix to gevent 1.1.x

### ISSUE THREAD

**Issue by aelse** [gevent/gevent#902]
* gevent version: 1.1.x
* Python version: 2.7.12 / 3.5.2
* Operating System:

### Description:

```
A fix for HTTP Response Splitting detailed in #775 has been applied to gevent 1.2 branch (available in 1.2a1). This fix should make it to 1.1.x with a release published to PyPI.
```

### What I've run:

```
I'm happy to backport the HTTP Response Splitting fix to 1.1.x so that a release can be pushed out for the benefit of everyone on gevent 1.1.x. I just want to confirm that an acceptable patch would be merged in and published.

Notably, gevent 1.1.0 was published on March 5, 2016. The last 1.1.x release was 1.1.2 on July 21, 2016 (see https://github.com/gevent/gevent/blob/master/changelog.rst). Users really need greater longevity between releases introducing breaking changes, in particular for security related bugfixes.

Let me know what you think :)
```

**Comment by aelse** [comment]
Relates to issue #775

**Comment by jamadden** [comment]
gevent 1.2 is intended to be the next security/bugfix release of gevent, building on gevent 1.1. I know of an organization that has successfully moved a large production code base from gevent 1.0 through the 1.1 series to 1.2a1 with no gevent-related changes, so I wouldn't expect that to be difficult for anyone to do.

**Comment by aelse** [comment]
This is about stability, not difficulty. Bugfix versions usually don't make breaking changes to APIs or substantially change functionality. In 1.2 python runtimes have been deprecated and added, and there have been a bunch of behavioural changes. There's a cost to evaluating how these things affect us and risk involved in moving to a new release with changes encompassing a wide surface area.

We're happy to move to the next version once the feature set has stablised (alpha), seen some real use under a beta release and then 1.2.0 published so we know there will be no surprises. It'd be really great to have the relatively small list of security fixes (3 changes noted in the changelog) applied to the current stable branch. It's a better interim measure than recommending people move to an alpha candidate for the next feature branch.

If you'll accept help making that happen we can work on it with you (the wsgi environment disclosure report came in from my colleague). Reopen the issue and let me know.
