### ISSUE TITLE
Using gevent with an alternate implementation of Greenlet

### ISSUE THREAD

**Issue by tbodt** [gevent/gevent#906]
I've made a fork of Greenlet called [Greenstack](https://github.com/tbodt/greenstack) that uses an alternative approach to stack switching. It allocates a separate stack for each greenstack, instead of using the same stack for each greenlet and copying things back and forth. The reason I did it is for compatibility with V8, but switching between greenstacks is also somewhat faster than switching between greenlets. Creating greenstacks is slower because it has to allocate some memory for the stack, but I've implemented a cache of stacks so this won't matter in a long-running program.

There's different tradeoffs between using greenlet and greenstack, so I'm not suggesting gevent should completely convert to using greenstack. Instead, I think there should be some way to choose. What would be a good way of adding that to the gevent API?

**Comment by jamadden** [comment]
That's some very interesting work! Does it work under PyPy? I'm not interested in adding support for anything that reduces the number of platforms gevent works on, and I'm not interested in complicating the support for what it already does. So I guess the short answer is, make it importable with, and provide the same API as, existing greenlet--then people can choose what to install.

**Comment by tbodt** [comment]
The API for it right now is the same as greenlet, except you import things from greenstack instead of greenlet. I'm not sure about pypy support, but it probably does work. I'll look into that.

**Comment by tbodt** [comment]
Hmm, looks like PyPy includes greenlets implemented in its own way, so greenstack would be irrelevant there. 

I'm going to check if PyPI allows multiple packages to expose the same module. If so, that's probably the answer.

**Comment by tbodt** [comment]
I've created an additional package called `greenstack-greenlet` that defines a `greenlet` module that imports everything from greenstack. Since it's a Python package instead of an extension module, it takes precedence in the Python importer. If you just install greenstack-greenlet gevent will automatically start using greenstack.

Could there be a setuptools extra for greenstack? Something like this:

```python
extras_require={
    'greenstack': ['greenstack-greenlet'],
}
```

So then you could do `pip install gevent[greenstack]` if you wanted greenstack.

**Comment by jamadden** [comment]
Couldn't one just do that in a `requirements.txt`, etc? Rather than try to modify gevent itself? dstufts [post](https://caremad.io/posts/2013/07/setup-vs-requirement/) seems relevant.

**Comment by jamadden** [comment]
This seems to basically be solved by the third-party packages which a user can choose to install if desired (on supported platforms) so I'll go ahead and close it.
