### ISSUE TITLE
blog.gevent.org unavailable

### ISSUE THREAD

**Issue by FelixSchwarz** [gevent/gevent#911]
When I try to access http://blog.gevent.org/2010/02/27/why-gevent I just see an error page saying:

> Warning! Domain mapping upgrade for this domain not found. Please log in and go to the Domains Upgrades page of your blog to use this domain.

**Comment by jamadden** [comment]
@denik Any thoughts?
@FelixSchwarz This link should work: https://gevent.wordpress.com/2010/02/27/why-gevent/

**Comment by FelixSchwarz** [comment]
This works now.
