### ISSUE TITLE
Will WebSocket Support?

### ISSUE THREAD

**Issue by wwqgtxx** [gevent/gevent#912]
We all know gevent is a great Python networking library.
And the WebSocket protocol is a good protocol to let the web program work better.
So I went here to ask will websocket support with gevent official.
It will give us a very big help to develop the websocket application

**Comment by jamadden** [comment]
Check PyPI, there are a few websocket implementations available (e.g., https://github.com/karellen/karellen-geventws). They aren't, and probably won't be, part of the gevent distribution.
