### ISSUE TITLE
monkey.patch_os() affect multiprocessing.Process.is_alive()

### ISSUE THREAD

**Issue by 0wu** [gevent/gevent#914]
* gevent version: 1.1.2
* Python version: 2.7.12
* Operating System: 
   Linux 4.4.0-53-generic inside docker container (Ubuntu 16.04) and Darwin Kernel Version 14.5.0

### Description:

Process().is_alive() should return False after the process is killed or exited. 
In other words, the following code should not be infinite loop. 

A few workaround was found.
* removal of monkey_patch, the code then behaves as expected.
* add pr.join() after the start, pr.join(0) doesn't work.
* add time.sleep(0.1) inside the loop.

The problem was discovered when trying to use https://github.com/kennethreitz/grequests/blob/master/grequests.py#L21
in a multiprocessing environment.

### What I've run:

```
from gevent import monkey
monkey.patch_os()
import os
from multiprocessing import Process

pr =  Process()
pr.start()
while pr.is_alive():
        os.kill(pr.pid, 9)
```

**Comment by jamadden** [comment]
The problem in this example is that you're not yielding to gevent, so it can never know when the process has finished. To fix the problem, use `patch_all()` instead of `patch_os()` (or add `patch_time()`, but using `patch_all()` is *highly* recommended in all cases).

**Comment by 0wu** [comment]
@jamadden thanks for fast response. I tried with `patch_all()` instead of `patch_os`. The problem still occurs.

**Comment by jamadden** [comment]
I'm sorry, if you're in a tight loop, you're still not yielding to the event loop. You need to yield. The most explicit way is with a  `gevent.sleep`, but you can also use a `time.sleep` if you've `patched_all`.

```python
import gevent
from gevent import monkey
monkey.patch_all()

import os
import time
from multiprocessing import Process

pr =  Process(target=lambda: time.sleep(10000))
pr.start()

while pr.is_alive():
	os.kill(pr.pid, 9)
	gevent.sleep()
print("Killed")
```

**Comment by 0wu** [comment]
Thanks. It worked. 

Just for reference, it took exactly 1001 gevent.sleep() that is_alive() returns the correct value. The following code would print 1001 with monkey_patch and 0 without.
```
import gevent
from gevent import monkey
monkey.patch_all()
import time
import os
from multiprocessing import Process

pr =  Process(target=lambda :time.sleep(999999))
pr.start()
os.kill(pr.pid, 9)
count=0
while pr.is_alive():
    time.sleep(0)
    count+=1
print(count)
```
It appears the "eventhandler" in gevent is not invoked everytime when gevent.sleep() is called

**Comment by jamadden** [comment]
That's an unfortunate but [documented](http://www.gevent.org/gevent.html#gevent.sleep) consequence of the way sleep works (and it's why `waitpid` doesn't sleep for you).
