### ISSUE TITLE
CI: Update to Python 3.6 final

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#915]
- [x] Update travis to 3.6.0 final
- [x] Update appveyor to 3.6.0 final (we may have to install it ourself?)
- [x] Update manylinux to 3.6.0 final once pypa/manylinux#82 is resolved

Ideally we would upload manylinux and appveyor wheels for 3.6

**Comment by njsmith** [comment]
manylinux docker images now have 3.6

**Comment by jamadden** [comment]
Thanks! I've built and uploaded a 3.6 wheel.

**Comment by jamadden** [comment]
Fixed in #922 and #923
