### ISSUE TITLE
landscape is broken

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#927]
Master builds of landscape aren't working, and haven't been for awhile. They did work once, after some tweaking. Can we figure out why they aren't working now?

Our own lint checks are still running and working as expected, but we're missing the reports and feedback.

**Comment by jamadden** [comment]
Asked for help in https://github.com/landscapeio/landscape-issues/issues/268

**Comment by thedrow** [comment]
Try re-enabling it. The service has suffered a period of stagnancy due to a bike accident the founder had.

**Comment by jamadden** [comment]
I'm giving up on this.
