### ISSUE TITLE
Gevent.spawn, ctypes callbacks and thread safety

### ISSUE THREAD

**Issue by arcivanov** [gevent/gevent#931]
When using ctypes callbacks the documentation is as follows:

https://docs.python.org/3/library/ctypes.html#callback-functions

> Also, note that if the callback function is called in a thread created outside of Python’s control (e.g. by the foreign code that calls the callback), ctypes creates a new dummy Python thread on every invocation. This behavior is correct for most purposes, but it means that values stored with threading.local will not survive across different callbacks, even when those calls are made from the same C thread.

I need to schedule the execution of the code inside the callback. The execution should happen in the Hub with which the callback has been created in the first place. The "dummy thread" however, is an actual physical pseudo-Python thread, even if Gevent monkey-patched the threading module beforehand.

When registering a callback I can capture the `hub` from the current gevent thread.

Is there a safe way to inject a Greenlet into a hub i.e. something like `gevent.spawn()` whilst passing the Hub to the spawn from a different physical thread the same way as `loop.call_soon_threadsafe` works in asyncio? (https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.call_soon_threadsafe)?

**Comment by jamadden** [comment]
If I understand what you're asking (and I'm not entirely sure that I do) then you want this:
```python
def spawn_raw_in_hub(function, hub):
    from greenlet import greenlet as RawGreenlet
    g = RawGreenlet(function, hub)
    hub.loop.run_callback(g.switch)
```

That's basically just `gevent.spawn_raw`; you need a plain-Jane greenlet because the `gevent.Greenlet` class does its own capturing of the hub to be its parent (it is crucial that the hub that's the parent of the greenlet be the hub in which it runs).

Note that the neither the hub not its loop are thread safe, though, so if you're running in a different thread than the one that created the hub, this might fail in mysterious ways. (In practice, the GIL will probably keep you safe.)

**Comment by arcivanov** [comment]
@jamadden Thanks! That said, if `hub.loop` has been created in physical Thread-1 and `hub.loop.run_callback` is called from physical Thread-2, is it safe?

**Comment by arcivanov** [comment]
To give it more context: SQLite has an update hook that notifies a callback of data change. It runs in a separate physical thread. I need to unblock a monkey-patched `threading.Event` in the main thread, which necessarily requires it happening from a separate physical thread that enters Python from SQLite backend through CFFI.

**Comment by jamadden** [comment]
In principle, no. No methods of a hub are meant to be called from a different thread. There is no locking of any kind done. So mutating the callback list from two different threads could corrupt the datastructure.

In practice, because you're running Python code, the GIL will be held preventing any other Python code from running. `run_callback` doesn't release the GIL (I think) and nothing else in the loop releases the GIL and manipulates the internal datastructure (I think), so in practice it should be safe.

**Comment by jamadden** [comment]
A pipe (or probably better, an async watcher) may be a safer option then. See https://github.com/gevent/gevent/issues/891

**Comment by arcivanov** [comment]
Let me take a look at how asyncio does it. I suspect they have a synchronized queue of callbacks to add to the loop that is checked before a switch and is consumed there.

**Comment by arcivanov** [comment]
Ok, asyncio thread-safe vs not only differs by the fact that "_threadsafe" methods wake up the loop via "_write_to_self" which is pipe write to unblock the loop.

The internal handle structure is a deque that is per spec thread safe.

**Comment by jamadden** [comment]
That's pretty much what async watchers and the callback queue are.

**Comment by arcivanov** [comment]
Two questions then:

1) Is callback queue a deque or equivalent?
2) Will `hub.loop.run_callback(g.switch)` wake the loop up?

**Comment by jamadden** [comment]
An async watcher send will wake the loop up (trigger the polling call to return) but their exact ordering is not specified.

**Comment by arcivanov** [comment]
Ordering is irrelevant, since this is coming from the other thread.

I guess this means that this is a thread-safe approach if callback queue is a thread-safe deque.

**Comment by jamadden** [comment]
Threads and threadsafety and callback queue don't enter into the question at all once you're using an async watcher beyond the fact that an async watcher is guaranteed to be thread and signal safe (that's its purpose). It encapsulates the reading and writing of a pipe.

```python
# Untested pseude-code
# thread 1
thread_1_event = threading.Event()
def on_wakeup_from_other_thread():
   thread_1_event.set() # cascade the wakeup. Or whatever
watcher = get_hub().loop.async().start(on_wakeup_from_other_thread)


# thread 2
def sqlite_callback():
  # wake up thread 1 to execute its callback
  watcher.send()
```

**Comment by arcivanov** [comment]
1) I have monkeypatched code, so the thread 1 uses
```
event.wait()
event.clear()
```
from the normally blocking code. I can't introduce an async watcher as it's all transparent.

`run_callback` is a good approach as is in sync with what asyncio does.

**Comment by jamadden** [comment]
Note that that will not cause the loop to wakeup. You still need to use some other watcher to do that.

However, I don't see why you can't use an async watcher if you have access to the event at all (which you should, otherwise how would it get set?). It should be roughly this simple:
```
# thread 1
watcher = get_hub().loop.async().start(event.set)

# thread 2 as before
```

**Comment by arcivanov** [comment]
@jamadden Doesn't `self.ref()` in  https://github.com/gevent/gevent/blob/master/src/gevent/libev/corecffi.py#L620 wake up the loop?

**Comment by jamadden** [comment]
No, `ev_ref` is simply an internal reference counter.

**Comment by arcivanov** [comment]
I think this also speaks of #347

**Comment by jamadden** [comment]
Yes, it seems similar. It's a rarely used pattern but not that hard to write.

**Comment by arcivanov** [comment]
So assuming we implement a `callback_threadsafe` and/or `wakeup` mentioned in #347 would you accept a PR?

**Comment by jamadden** [comment]
I'm not sure there's a need for it in gevent core or that it's hard to write as needed. An async watcher is about as basic as it gets, and that follows the pattern of other existing watchers.

**Comment by arcivanov** [comment]
`get_hub().loop.async().start(Event().set)` returns None

**Comment by jamadden** [comment]
As I said, untested pseudo-code. Watchers are init'd and then started currently. But having `start` return the watcher might not be a bad idea...
```python
watcher = async()
watcher.start(callback_func)
```

**Comment by arcivanov** [comment]
@jamadden Thanks for your help. I thought that notification wasn't properly running in the correct Hub but it seems something else is afoot.

Under what circumstances would `gevent.hub.sleep(0)` raise 
```
Exception ignored in: <module 'threading' from '/home/arcivanov/.pyenv/versions/3.6.0/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/home/arcivanov/.pyenv/versions/3.6.0/lib/python3.6/threading.py", line 1290, in _shutdown
    t.join()
  File "/home/arcivanov/.pyenv/versions/karellen-env/lib/python3.6/site-packages/gevent/threading.py", line 202, in join
    self._greenlet.join(timeout=timeout)
  File "/home/arcivanov/.pyenv/versions/karellen-env/lib/python3.6/site-packages/gevent/greenlet.py", line 496, in join
    result = self.parent.switch()
  File "/home/arcivanov/.pyenv/versions/karellen-env/lib/python3.6/site-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x7f15d4b87af8 epoll default pending=0 ref=0 fileno=5 resolver=<gevent.resolver_thread.Resolver at 0x7f15cab2d4e0 pool=<ThreadPool at 0x7f15cb525c88 0/2/100>> threadpool=<ThreadPool at 0x7f15cb525c88 0/2/100>>)
```
in
```python
        waiter = Waiter()
        loop.run_callback(waiter.switch)
        waiter.get()
```

**Comment by jamadden** [comment]
I don't see a call to sleep in your code, so I can't say. I thought this solution was rejected though.

A LoopExit is pretty much what it says on the tin: there's no other greenlet to switch to.

**Comment by arcivanov** [comment]
Ok, I think there might be a bug somewhere:

1. Register a callback from server thread

<StandaloneServer(StandaloneServer, started 140077256007304)>

<Hub at 0x7f66508b8930 epoll default pending=0 ref=0 fileno=5 threadpool=<ThreadPool at 0x7f6647053550 0/1/10>>

<loop at 0x7f6650870488 epoll default pending=0 ref=0 fileno=5>

```python
    def _make_hook_adapter(self, hook):
        hub = gevent.get_hub()
        return partial(gevent_hook_adapter, hook, self, hub)
```

2. Callback is called from inside of CFFI

<_DummyThread(DummyThread-1, started daemon 140077245072192)>

<Hub at 0x7f66508b8930 epoll default pending=0 ref=1 fileno=5 resolver=
<gevent.resolver_thread.Resolver at 0x7f66467cef98 pool=<ThreadPool at 0x7f6647053550 1/1/10>> threadpool=<ThreadPool at 0x7f6647053550 1/1/10>>

<loop at 0x7f6650870488 epoll default pending=0 ref=1 fileno=5>

```python
def gevent_hook_adapter(hook, conn, hub, _, op, db_name, table_name, rowid):
    waiter = hub.loop.async(lambda: None)
    g = RawGreenlet(_sqlite.hook_adapter, hub)  # This goes into monkey-patched regular code
    hub.loop.run_callback(g.switch, hook, conn, None, op, db_name, table_name, rowid)
    waiter.send()
```

So far so good, right?

3. In the `_sqlite_hook_adapter`

**<_DummyThread(DummyThread-2, started daemon 140077245073864)>** - **WHAT?!?!?!?**

_Passed:_ <Hub at 0x7f66508b8930 epoll default pending=0 ref=1 fileno=5 resolver=<gevent.resolver_thread.Resolver at 0x7f66467cef98 pool=<ThreadPool at 0x7f6647053550 1/1/10>> threadpool=<ThreadPool at 0x7f6647053550 1/1/10>>

_Passed:_ <loop at 0x7f6650870488 epoll default pending=0 ref=1 fileno=5>

In the debugger I can definitely see that the [1] and [3] are the same Python thread, while [2] is a CFFI dummy Python thread (Dummy-6). 

But why is there a dummy Gevent thread in [3] instead of <StandaloneServer(StandaloneServer, started 140077256007304)> and what else is missing in that new dummy Gevent thread?

**Comment by arcivanov** [comment]
Ok, I figured that there is no "Thread" when the greenlet [3] is running. In the debugger I can see the Event wake up from the wait and switch itself into the loop. But it never actually comes back until all other greenlets die even if those greenlets gevent.sleep.

**Comment by arcivanov** [comment]
Ah, it's my screwup, found the issue - assume wrong object model, there is a race to consume the Event and a wrong greenlet consumes it.

Thanks for all your help.
