### ISSUE TITLE
Socks5 proxy and gevent error AttributeError: 'super' object has no attribute 'getpeername'

### ISSUE THREAD

**Issue by masolit** [gevent/gevent#937]
# same problem after update

# urllib
```python
from gevent import monkey
monkey.patch_all()

import urllib.request
import socks
from sockshandler import SocksiPyHandler

request = urllib.request.Request('http://myip.dnsomatic.com')
opener = urllib.request.build_opener(SocksiPyHandler(socks.SOCKS5, '127.0.0.1', 9050))
urllib.request.install_opener(opener)

handle = urllib.request.urlopen(request, timeout=60)
print(handle.read())
```
```
Traceback (most recent call last):
  File "/home/masolit/IdeaProjects/Python/scraping/tor_reqests2.py", line 28, in <module>
    handle = urllib.request.urlopen(request, timeout=60)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/sockshandler.py", line 62, in http_open
    return self.do_open(build, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/sockshandler.py", line 35, in connect
    self.sock.settimeout(self.timeout)
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/socks.py", line 288, in settimeout
    peer = self.get_proxy_peername()
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/socks.py", line 429, in get_proxy_peername
    return super(socksocket, self).getpeername()
AttributeError: 'super' object has no attribute 'getpeername'
```

https://github.com/Anorov/PySocks/issues/65

**Comment by jamadden** [comment]
Ah, hmm. This appears to be a limitation of [`super`](https://docs.python.org/3/library/functions.html#super) that I hadn't really thought about/encountered before:

> Note that super() is implemented as part of the binding process for explicit dotted attribute lookups such as super().__getitem__(name). It does so by implementing its own __getattribute__() method for searching classes in a predictable order that supports cooperative multiple inheritance. Accordingly, super() is undefined for implicit lookups using statements or operators such as super()[name].

The implication being that if the *class* also defines a `__getattr__` or `__getattribute__`, then `super` won't work as expected. :/


Without having given it much thought, my next suggestion would be for PySocks to avoid subclassing the socket and delegate to it instead, much like gevent does. There are a bunch of workarounds in PySocks to make subclassing a socket work, but it's not clear that socket objects are really *meant* to be subclassed (indeed, the documentation only refers to [`socket.socket` as a function, not a class](https://docs.python.org/3/library/socket.html#socket.socket). (In fact at one time gevent did subclass the socket, but that had so many portability issues that delegation turned out to be the better---only---option, IIRC)

It's not clear to me that there's anything gevent can or should do here.

**Comment by ianchen06** [comment]
I also encountered this problem, and I really want to use gevent with PySocks so I looked into the problem a bit. Here are my findings...

1. The error only occurs with HTTP urls, not HTTPS

2. `_BaseSocket` class from PySocks inherited from socket.socket, which is monkey patched by gevent(?) and it is missing the `getpeername()` method which exists on the original `socket` class in the standard library.

I got PySocks to work with gevent by making the following changes in PySocks

```
    def get_proxy_peername(self):
        """
        Returns the IP and port number of the proxy.
        """
        # return super(socksocket, self).getpeername()
        return self.getpeername()
```

I am not too sure if this has other side effects or maybe this is the wrong way to fix the problem..

**Comment by metashock** [comment]
@ianchen06 Would you mind to create a PR to PySocks?

**Comment by metashock** [comment]
@jamadden How to proceed here?

**Comment by jamadden** [comment]
AFAICS changes need to be made in pysocks (note that this change can easily be applied by users with their own monkey-patch). I don't see gevent manually copying wrappers for every stdlib function into its class; we only do that when necessary for gevent functionality as its a maintenance burden.

**Comment by metashock** [comment]
@jamadden Can you elaborate on the changes that should be applied to PySocks? Sorry, if this is a stupid question. I'm confused by this thread which points to PySocks and related threads in PySocks which claim that it is *not* a PySocks issue.

**Comment by jamadden** [comment]
Upstream has fixed this in https://github.com/Anorov/PySocks/pull/88 and closed the original issue.
