### ISSUE TITLE
python 2.7 doesn't support empty star as parameter

### ISSUE THREAD

**Issue by fyears** [gevent/gevent#940]
* gevent version: 1.2.1
* Python version: python 2.7
* Operating System: Ubuntu

### Description:

Installing via `pip install gevent`, see some error:

```
      File ".../lib/python2.7/site-packages/gevent/_socket3.py", line 196
        def makefile(self, mode="r", buffering=None, *,
                                                      ^
    SyntaxError: invalid syntax
```

### What I've run:

```
pip install gevent
```

### Result:

Still able to `import gevent`

### Possible Fix

Pretty obvious, python 2.7 doesn't support star as parameter for the function in https://github.com/gevent/gevent/blob/master/src/gevent/_socket3.py#L196

**Comment by jamadden** [comment]
Thanks, but that file isn't used on Python 2 and this isn't a problem. Newer versions of pip don't even report that.

**Comment by Ponyboy47** [comment]
I'm trying to package this into an rpm for CentOS 7 and I too am seeing this error while building event for python 2.7.

**Comment by jamadden** [comment]
If you search you'll find that there's a setting that can be added to the spec file to prevent bytecode compilation (or something) that other people have used when building RPMs.

**Comment by Ponyboy47** [comment]
Thank you, I'll see what I can find
