### ISSUE TITLE
Some question about gevent Pool  make me confuse

### ISSUE THREAD

**Issue by 631068264** [gevent/gevent#952]
I use gevent 1.2.1 and Python 2.7

```
pool=gevent.pool.Pool(10)

for i in range(300):
    pool.add(gevent.spawn(func,i))

pool.join()
```
```
jobs = []
pool=gevent.pool.Pool(10)
for i in range(300):
    jobs.append(p.spawn(func, i))
gevent.joinall(jobs)
```

What is the difference between this two code ? And If I want to get the result from the func  return how can I do ?

**Comment by jamadden** [comment]
I don't understand your question.

I assume if you run the code you can see the difference, if any. 

Please look at the [pool documentation](http://www.gevent.org/gevent.pool.html) for how to use it and get results from what you spawn.

**Comment by jamadden** [comment]
There's been no further feedback so I'm going to close this.
