### ISSUE TITLE
monkey_patching socket for use with raw python ping and gevent.pool of pings results are the same IP address even with mulitple 

### ISSUE THREAD

**Issue by steelliberty** [gevent/gevent#956]
* gevent version: 1.21
* Python version: 2.7 (pypy latest)
* Operating System: ubuntu 16

### Description:

I appologize if this has already been addressed or is clearly a result of imperfect understanding of the gevent coroutine module. 

I built a module based on grequests only for pings.  Using Matthew Dixon Cowles' python ping as the ping engine.  When I run the module without monkey_patch (Socket =True) It fails to work properly, when I comment out the monkey_patch it works as I think it should but likely without and possible speed advantages.   

With the patch, the code runs, but ping results are all from the first ping ip -- even though the rest of the ping-requests appear to run -- apparently the socket ip never changes between calls to the new ip .. 

### What I've run:

I am attempting to start multiple pings in a pool of worker threads in this fashion
```python
urls = ['microsoft.com','yahoo.com']
pingrequests = (pingone(p) for p in urls)
results = map(pingrequests,size=4,exception_handler=errorHandler)
print results 
```
The map function looks like this : 
```python
def map(prequests, stream=False, size=None, exception_handler=errorHandler, gtimeout=None):

    prequests = list(prequests)
    for x in prequests:
        print x.domain

    pool = Pool(size) if size else None
    jobs = [send(r, pool, stream=stream) for r in prequests]
    gevent.joinall(jobs, timeout=gtimeout)
```
pingone is  a wrapper class around the following functionality :
```python
def send(self):
        try:
            #generate the list now in order to propagate any exceptions otherwise they are lost
            self.response = list(ping.quiet_ping(self.domain,timeout=1000,count = self.count))
        except Exception as e:
            self.response = None
            self.exception = e
            self.traceback = traceback.format_exc()

```

**Comment by jamadden** [comment]
I'm afraid I don't understand what you're describing when you say "apparently the socket ip never changes between calls to the new ip " and there's not enough for me here to try to reproduce. I can't find a current version of "python ping" that matches your usage, for example.

Can you create a [short, self-contained example](http://sscce.org), (that is, one without any third-party dependencies and as simple as possible) that you can show here that demonstrates exactly what the problem appears to be? Often the process of removing *all* the extraneous code and stripping the example to its fundamentals can reveal the problem...

**Comment by jamadden** [comment]
It's been three months without any further information, I'm going to close this.

**Comment by steelliberty** [comment]
I am sorry -- I have been lost in a project - that issue still exists -- I
will repost again ..

**Comment by jamadden** [comment]
Feel free to re-open this issue, but please provide more information as requested if you do.

**Comment by steelliberty** [comment]
yes sir.
