### ISSUE TITLE
gevent - hub.loop.reinit() does not work after fork

### ISSUE THREAD

**Issue by Jackyele** [gevent/gevent#957]
The `do_magic` function would be called twice in the following example, both in parent and child process.

My confusion is the `os.fork` has been replaced with `gevent.fork`, and `hub.loop.reinit()` would be called in child process. If so, why `do_magic` still be called in child process?

```python
    import gevent
    
    from gevent import monkey
    monkey.patch_all()
    
    import os, time
    
    
    def do_magic():
        print 'magic...'
    
    
    def main():
        g = gevent.spawn_later(1, do_magic)
    
        pid = os.fork()
        if pid != 0:  # parent
            g.join()
        else:
            gevent.get_hub().loop.reinit()
            time.sleep(3)
    
    
    main()
```

**Comment by jgehrcke** [comment]
You might want to look into how [gipc](https://gehrcke.de/gipc/) solves that. The "child cleanup code", in particular:

https://bitbucket.org/jgehrcke/gipc/src/ad6ba71c8ff053bafb6783d0b3bf067d6ef877b0/gipc/gipc.py?at=default&fileviewer=file-view-default#gipc.py-311

(it's neither trivial nor super clean).

**Comment by Jackyele** [comment]
@jgehrcke  does it mean `hub.loop.reinit()` does not work well, needed to fix?

**Comment by jamadden** [comment]
No, it's not in need of a fix. greenlets surviving fork can be considered a feature, not a bug; I know of systems that rely on that property. If that were to change, that would have to be either (1) optional or (2) in a major release.

**Comment by jgehrcke** [comment]
>  does it mean hub.loop.reinit() not work well, needed to fix?

Which piece of documentation makes you think so? :-) AFAIK it is not documented to magically wipe state that has been inherited from the parent (which is what fork _naturally_ does). So, no. You might also be interested in these conversations:

* https://groups.google.com/forum/#!topic/gevent/gb200hLAKW4
* https://github.com/gevent/gevent/issues/200

> greenlets surviving fork can be considered a feature, not a bug

:+1: 

@Jackyele If you'd like to spawn child processes within your gevent-driven application and not worry much / be ignorant about the order of spawning greenlets and spawning processes then [gipc](https://gehrcke.de) should make this a no-brainer (that's what it has been built for). Note that you can mix and match this with `os.fork`, `gevent.fork`, `multiprocessing.Process`, etc (in those cases you need to take _precise_ control however).

**Comment by Jackyele** [comment]
@jgehrcke  The first impression of `reinit` is to hope it could reinit the event loop as the hub first initialized cleanly, without any events, callback, watchers...  Just hope it similar to sqlalchemy's [Engine.dispose](http://docs.sqlalchemy.org/en/latest/core/pooling.html#using-connection-pools-with-multiprocessing), give us an empty connection pool in child process

In above example, `do_magic`'s greenlet could still alive in child process, it is okay; but we hope the event loop in child process does not switch to it.

I think this is the expected behavior in most cases. :-)

**Comment by Jackyele** [comment]
It would be better to give a documentation of what would be inherited from parent and what not after fork + reinit()

**Comment by jamadden** [comment]
This is very clearly documented. Here's just on example: http://www.gevent.org/gevent.os.html#child-processes
