### ISSUE TITLE
I don't want to mention the port 5000 explicitly in a flask based gevent app.

### ISSUE THREAD

**Issue by Prithiraj** [gevent/gevent#968]
* gevent version: 1.2.1
* Python version: Python 2.7.12
* Operating System: Ubuntu 16.04.1 LTS
* Gunicorn version: 19.6.0
* nginx version: nginx/1.10.0 (Ubuntu)

### Description:

I am dealing with a project, where I have used Server Side Event to get real-time data.

I implemented the below line at the top of my _project_.py. I didn't had to make any further changes and it's working great without the development mode's threaded = True.

`from gevent import monkey; monkey.patch_socket()`

It's working great in the server and the local dev machine alike without any issues.

To get it rolling with gunicorn I created a systemd script and have the following line:

`gunicorn -k gevent --worker-connections 1001 -w 5 --bind 0.0.0.0:5000 wsgi:app`

```
An nginx server is setup for reverse proxy, to direct port 80 standard requests to the 5000.
Below is the part of nginx cofiguration from /etc/nginx/sites-enabled/:

server {
    listen 80;
    server_name project.com;

    location / {
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   Host      $http_host;
        proxy_pass         http://127.0.0.1:5000;
    }
}

```

### What I've run:

Testing _project_.com
```
The page loads successfully, but the gevent is clearly not working as I don't get real-time test updates from the server.
```

Testing _project_.com:5000
```
The gevent works well in this scenario, I get the real-time updates successfully. 
```

### What I need to do:

I don't want to add the additional port number 5000 in an URL. I want to visit _project_.com with no additional port numbers and able to catch the real-time updates.

Regards,
Prith

**Comment by jamadden** [comment]
What makes you think this is a gevent bug? And not, for instance, a configuration problem ?

**Comment by Prithiraj** [comment]
Hi Jamadden,

Thank you for responding. Honestly, I don't know, if it's a gevent bug or a configuration problem. I feel it's the later one.

I believe whatever route I take with or without mentioning the port 5000 in the URL, it should have given me the result executed at 127.0.0.1:5000 as per the given configuration.

Regards,
Prith

**Comment by jamadden** [comment]
Was this configuration "given" in the gevent documentation or somewhere else?

If somewhere else, I'm struggling to understand what this has to do with gevent. It doesn't seem to have *anything* to do with gevent as far as I can see.

**Comment by Prithiraj** [comment]
Dear Jason,

The problem I was facing is now resolved. Server Sent Event returns event-streams. The response headers should have `X-Accel-Buffering: 'no'`.

In the server I have updated the code as follows.
```
response =  Response(eventStream(data), mimetype="text/event-stream")

# Added the line below:
response.headers['X-Accel-Buffering'] = 'no' 
return response
```

Here is the configuration explanation in details specifically for Server Sent Events:
[https://serverfault.com/questions/801628/for-server-sent-events-sse-what-nginx-proxy-configuration-is-appropriate](url)

Thank you,
Prith
