### ISSUE TITLE
allow SO_REUSEPORT besides SO_REUSEADDR in StreamServer

### ISSUE THREAD

**Issue by thestick613** [gevent/gevent#970]
* gevent version: 1.2.1
* Python version: 3.6.1
* Operating System: Mac OS

### Description:

We should be able to create socket servers in gevent that create sockets with SO_REUSEPORT. This allows applications to spawn multiple identical processes which bind on the same address and port without getting the "address in use" error. There is a base for a similar functionality in TCP Servers [here](https://github.com/gevent/gevent/blob/master/src/gevent/server.py#L227) and UDP servers [here](https://github.com/gevent/gevent/blob/master/src/gevent/server.py#L247), but that is for setting SO_REUSEADDR.

### What I've run:

I've been monkey patching these two functions when necessary, and it works just fine.

**Comment by jamadden** [comment]
If you'll be using multiple processes at the same time, I strongly suggest using a layer on top of gevent to handle that, such as gunicorn which already provides that. gevent is a base for servers, but it's not a fully fledged server itself.

Alternatively for very simple cases, simply bind and start the server before forking.

**Comment by thestick613** [comment]
I've used haproxy before, but it's very difficult to proxy the real ip address doing the request to your application logic. I've been using a monkey patch to `_tcp_listener` without any issue for a few months now. I'm not forking, i'm just starting multiple processes that do the same thing in order to scale on multiple CPUs. Is there any reason for your suggestion?

**Comment by jamadden** [comment]
haproxy is not at all the same thing as gunicorn. gunicorn specifically runs a python webserver in multiple processes. haproxy is just a routing proxy and load balancer and leaves the server to you.

There are numerous reasons for using it as opposed to a roll-your-own solution, starting with the fact that it will watch the child processes and restart them if necessary and going from there.

My typical deployment has haproxy at the front tier, pointing to multiple machines, each of which is running gunicorn and multiple gevent processes.

**Comment by thestick613** [comment]
I'm not running a HTTP server, just some generic TCP servers.

**Comment by jamadden** [comment]
I would probably still build on gunicorn. It would require some custom subclasses of Application and possibly Worker, but I suspect it could be done. 

That said, if you don't want to do that, there should be no need to monkey patch. You can just create the socket ahead of time and pass it to the `StreamServer` constructor after you've set whatever options on it you want to; servers accept both sockets and addresses in the constructor *Or* subclass the server and override `get_listener` to set whatever flags you want.

**Comment by thestick613** [comment]
Yes, that's it - i can create the socket and pass it to the listener. Thank you.
