### ISSUE TITLE
gevent.pywsgi.WSGIServer not logging the correct IP address when using a load balancer

### ISSUE THREAD

**Issue by Code-ReaQtor** [gevent/gevent#972]
* gevent version: 1.2.1
* Python version: 3.4
* Operating System: Amazon Linux

### Description:

[gevent.pywsgi.WSGIServer](http://www.gevent.org/gevent.pywsgi.html#gevent.pywsgi.WSGIServer) does not log the correct IP address when using a load balancer (HAProxy). IP address should be taken from the **X-Forwarded-For** header

### What I've run:

Used HAProxy as load balancer.

### Additional notes:

Logging follows a hard-coded format (I checked the source code). If there are other ways to change the format, that should be great!

Cheers!

**Comment by jamadden** [comment]
If you want proper support for forwarded IPs, I suggest using gunicorn's gevent worker. There are security concerns that require configuration and gunicorn handles that. 

It als implements the high-performance proxy protocol haproxy defines, so it's a double win.

**Comment by Code-ReaQtor** [comment]
@jamadden thanks! Any link to an example (googling it doesn't seem to produce a correct article)?

Right now, I monkey-patched the pywsgi.WSGIHandler to extract the correct client IP address.

**Comment by jamadden** [comment]
The [gunicorn docs](http://gunicorn.org) are pretty good in my experience. Here's [the specific part](http://docs.gunicorn.org/en/latest/settings.html#forwarded-allow-ips) where it talks about extracting forwarded IPs.

Here's a (lightly edited) complete `gunicorn.conf.py` for a local development instance of a production service I had sitting around:
```python
import multiprocessing

# Let true and false be synonyms for ease of
# the templaters
true = True
false = False

proxy_protocol = True
# Listen on all addresses to this port, and locally on this file
bind = [":8081", "unix:/.../.buildout/var/dataserver.sock"]
# Calculate worker number automatically if not
# specified. We specify 1 in development for ease of debuging.
workers = "1" or multiprocessing.cpu_count() * 2 + 1

# Most people won't need a worker subclass.
worker_class =  "path.to.our.subclass.GeventApplicationWorker"

# Log to stdout; we daemonize with supervisor and it handles log files
# for us.
accesslog = "-"

timeout = 1800

# Set to False in development for ease of debugging, but True in 
# production for improved performance.
preload_app = False

# We're fully firewalled and unreachable except from our frontend
# process, which is carefully configured to strip values of this header
# before adding its own.
forwarded_allow_ips = "" or "*"

# The maximum number of requests a worker will process before
# restarting. Any value greater than zero will limit the number of
# requests a work will process before automatically restarting. This
# is a simple method to help limit the damage of memory leaks. If this
# is set to zero (the default) then the automatic worker restarts are
# disabled.
max_requests = 0

# The maximum number of simultaneous clients. This setting only
# affects the Eventlet and Gevent worker types.
worker_connections = 1000
```

**Comment by Code-ReaQtor** [comment]
Thanks @jamadden.

**Comment by zhangaoqi** [comment]
> @jamadden thanks! Any link to an example (googling it doesn't seem to produce a correct article)?
> 
> Right now, I monkey-patched the pywsgi.WSGIHandler to extract the correct client IP address.

How did you monkey-patched the pywsgi.WSGIHandler to extract the correct client IP address?

**Comment by roniemartinez** [comment]
@zhangaoqi I don't have the code now since I did not commit it to my repo.

I only modified the client_address [here](https://github.com/gevent/gevent/blob/master/src/gevent/pywsgi.py#L885) replacing it with the last IP in `X-Forwarded-For` header if it exists.

Note that `X-Forwared-For` may contain several IP address separated by a comma

**Comment by zhangaoqi** [comment]
@roniemartinez Thx.

**Comment by zhangaoqi** [comment]
@roniemartinez Thx.
