### ISSUE TITLE
Installation issues on macOS Sierra 

### ISSUE THREAD

**Issue by jayasi** [gevent/gevent#974]
* gevent version: 0.13.8
* Python version: 2.7.10
* Operating System: macOS Sierra

### Description:

```
I am trying to install the 0.13.8 version of gevent on my Mac. However, I am running into an issue related to ev_flags. I have libevent-2.1.8 installed. 
```

### What I've run:
sudo pip install gevent==0.13.8

```
 gevent/core.c:2750:47: error: no member named 'ev_flags' in 'struct event'
      __pyx_t_1 = PyInt_FromLong(__pyx_v_self->ev.ev_flags); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 213; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                 ~~~~~~~~~~~~~~~~ ^
    gevent/core.c:2830:36: error: no member named 'ev_flags' in 'struct event'
      __pyx_v_flags = __pyx_v_self->ev.ev_flags;
                      ~~~~~~~~~~~~~~~~ ^
    gevent/core.c:6525:34: error: use of undeclared identifier '_EVENT_VERSION'
      __pyx_t_1 = PyBytes_FromString(_EVENT_VERSION); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 432; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
```

Not sure what I'm missing. Will greatly appreciate your help!

**Comment by jamadden** [comment]
gevent 0.13.8 is no longer supported. Please use gevent 1.2.1.

**Comment by jayasi** [comment]
Yes, the current version builds perfectly fine. Another project that I am trying to build had a dependency on the 0.13.8 version of gevent, which is why I was trying the older version to work. 

Thank you for your quick response.

**Comment by jamadden** [comment]
1.x should *very nearly* be a drop-in replacement for 0.13.8. At least I don't remember needing to make many gevent changes upgrading my apps.

**Comment by jayasi** [comment]
I tried, but it doesn't work. 

```     
from gevent.coros import Semaphore
ImportError: No module named coros 
``` 

This is where the current version fails.

**Comment by jamadden** [comment]
`gevent.lock` has been the home of `Semaphore` for quite some time, with coros a BWC location. (I can't remember exactly when that was, probably an early 1.0 alpha).

**Comment by jayasi** [comment]
Thanks so much! That really helped! 😄
