### ISSUE TITLE
Where was socket patched? is_module_patched always returns true

### ISSUE THREAD

**Issue by abarik1981** [gevent/gevent#976]
* gevent version: 1.1.2
* Python version: 2.7
* Operating System: Redhat 5.3

### Description:
I am trying to see where was the socket patched? 

I a blank python cli, I see is_module_patched always returns true, where i call patch_all or not

```

from gevent import monkey
import gevent
print gevent.__version__
print 'IS SOCKET PATCHED', monkey.is_module_patched('socket')

# Output
1.1.2
IS SOCKET PATCHED True
```

With patch_all

```

>>> import gevent.monkey
>>> gevent.monkey.patch_all()
>>>
>>> print 'IS SOCKET PATCHED',gevent.monkey.is_module_patched('socket')
IS SOCKET PATCHED True
>>>
```

**Comment by jamadden** [comment]
I don't reproduce this locally:
```
$ python
Python 3.4.6 (default, Apr 23 2017, 17:16:17)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent.monkey
>>> gevent.monkey.is_module_patched('socket')
```
```
$ python
Python 2.7.13 (default, May  5 2017, 09:16:47)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent.monkey
>>> gevent.monkey.is_module_patched('socket')
False
```

Perhaps you have PYTHONSTARTUP set, or have code in sitecustomize.py or another hook. I suggest you set a breakpoint (`import pdb; pdb.set_trace()`) in `gevent.monkey.patch_socket()` so see what's calling it.

**Comment by abarik1981** [comment]
sorry for the trouble, you are absolutely right. that is what was happening.

I would really like to know if there is a way to unpatch_all()?

**Comment by jamadden** [comment]
> I would really like to know if there is a way to unpatch_all()?

There is not. It's really not feasible, as described at length elsewhere. As a quick example of the kind of things that break, consider:
```
import socket
class MySocket(socket.socket):
  ...
```

**Comment by abarik1981** [comment]
Thank you so much once again :)
