### ISSUE TITLE
question: How can I block the event loop/hub ?

### ISSUE THREAD

**Issue by amigrave** [gevent/gevent#977]
For debugging purpose, in some conditions I'd like to prevent a given greenlet to switch, hence blocking the event loop. How can I do that ?

I first tried to use the original `time.sleep()` until I remembered it was using `select()`'s timeout. So I tried to use the original `select.select()` instead but I still see other greenlets running on the way.

Here's what I'm currently trying:

```python
        if DEBUG:
            print("Do your manual stuff for debugging purpose")
            while True:
                try:
                    # in debug mode the IO dependency is resolved manually
                    do_stuff_with_io_dependency()
                    break
                except IOError:
                    select = monkey.get_original('select', 'select')
                    select([], [], [], 1)  
```
So basically I'd like to pause for an amount of time while preventing the greenlet to switch.
I'm trying the hackish way and I hope there's a simpler way to achieve that.

**Comment by jamadden** [comment]
You seem to want to stop the entire process from making progress. It's very counterintuitive to me why you would want to do that (maybe I'm misunderstanding) but I know of no simpler way to achieve that than making a process-wide blocking call.

**Comment by amigrave** [comment]
Silly me, I was using the original `select.select` but not the original `os.stat`.
My goal was to block the event loop until a machine slice exists in cgroupfs (as manually triggered in debug mode).

I'm really sorry to have bothered you with that, anyway I will take the opportunity to tell you that I love your work on gevent. It's so much easier than having to deal with asyncio.

Have a nice day !
