### ISSUE TITLE
KeyError in threading._shutdown() when importing gevent.threading on PyPy

### ISSUE THREAD

**Issue by sublee** [gevent/gevent#984]
* gevent version: 1.2.2
* Python version: PyPy 5.8.0 (Python 2.7.13)
* Operating System: Ubuntu 14.04, 16.04

### Description:

When I import `gevent.threadig` on PyPy, `KeyError` in `threading._shutdown()` always occurs at the exit.  It does not fail on CPython.  It's not a harmful bug.  But it's annoying when we need to parse stdout output from a Python code.

There's a similar issue: https://github.com/gevent/gevent/issues/534

And I read this reply: https://stackoverflow.com/questions/8774958/keyerror-in-module-threading-after-a-successful-py-test-run

### What I've run:

PyPy:

```console
$ pypy --version
Python 2.7.13 (c925e7381036, Jun 05 2017, 21:20:51)
[PyPy 5.8.0 with GCC 6.2.0 20160901]
$ pypy -c 'import gevent.threading'
Exception KeyError: KeyError(140692800006016,) in threading._shutdown() ignored
$
```

CPython:

```console
$ python --version
Python 2.7.12
$ python -c 'import gevent.threading'
$
```

**Comment by jamadden** [comment]
That's a known issue. There's a specific block of code that addresses that for CPython, but [a comment indicates](https://github.com/gevent/gevent/blob/master/src/gevent/threading.py#L153) it wasn't possible on PyPy.

However, it also indicated that perhaps newer versions of PyPy do not have this problem. Can you test with all versions of PyPy you use to see whether it is?

**Comment by jamadden** [comment]
(Regardless of the above, it would be nice if we weren't doing what we're doing to the stdlib's `threading._active` until we're monkey-patched, as the comment suggests. I should revisit that.)

**Comment by sublee** [comment]
I tested it on only PyPy 5.8.0 but it is the latest version of PyPy.  Do you want me to test it on the previous versions?  If you think it is meaningful, I'll help you.

I just tested same condition with small change: `if not PYPY` to `if True` at the block you mentioned.  Then the error has gone!  I think it is important on PyPy 5.8.0 also.

**Comment by jamadden** [comment]
Another question: What's your use case for directly importing `gevent.threading`? The [documentation says not to do that](http://www.gevent.org/gevent.threading.html):

>  This module is a helper for gevent.monkey and is not intended to be used directly.

If done the intended way, I don't see the `KeyError` (note that I'm printing its value from sys.modules to prove it was imported):
```
pypy -c "import gevent.monkey, sys; gevent.monkey.patch_all(); print(sys.modules['gevent.threading'])"
<module 'gevent.threading' from '//src/gevent/threading.pyc'>
```

**Comment by sublee** [comment]
I don't import `gevent.threading` myself.  But `logbook` does.  My application imports only `logbook` directly.  I just digged into the bug and I found that point.

So you will see the same error with `import logbook`: (Logbook-1.0.0)

```console
$ pypy -c 'import logbook'
Exception KeyError: KeyError(140592628664192,) in threading._shutdown() ignored
```

I didn't think it is a Logbook's bug.  Because there's no problem on CPython.

**Comment by sublee** [comment]
@jamadden I really appreciate to you.  Your cool responses (here and #981) are impressive for me.  Thank you so much again!
