### ISSUE TITLE
Gevent and multiprocessing

### ISSUE THREAD

**Issue by mdomans** [gevent/gevent#993]
* gevent version: 1.2.2
* Python version: Python 2.7.6
* Operating System: Ubuntu 14.04

### Description:

Tried running gevent based and multiprocessing based workers on the same codebase. The multiprocessing based worker blocks at start, probably related to this https://github.com/gevent/gevent/blob/master/src/gevent/monkey.py#L319-L340

### What I've run:

```
./manage.py celeryd -l debug -P gevent -c 100 --purge 
./manage.py celeryd -l debug -P processes -c 10 --purge 
```

Question: is this an issue being worked upon or should I just hack it through some global variables?

**Comment by jamadden** [comment]
To my knowledge there is nothing actively being done to change that situation.

**Comment by arcivanov** [comment]
I might be fixing this, albeit no ETA.

**Comment by arcivanov** [comment]
Apparently it's actually much easier to monkey-patch the MP that it seems.
Fork and Spawn appear to be working now. Forkserver still gets locked up. No Windows support yet, but it's definitely possible the same way as with Linux.

Methodology:

1. Mpatched threading is not an issue.
2. _ConnectionBase, PipeConnection, Connection etc are easily patchable by making FDs non-blocking and substituting read/recv and write/send with respective gevent.os.nb_read/nb_write.
3. Native semaphore is easily made non-blocking with hub's TP (performance hit?) in SemLock with subclass rebasing.

On Windows non-blocking IO will be similarly replaced with TPed IO.

Issues to fix:
When spawning via fork the gevent mpatch stays and everything is normal. Spawn and forkserver are different - they spawn a fresh new Python process and therefore NB fds passed to the spawns will be non-blocking as well. Either need to patch the bootstrap code to mpatch the children or make passed sockets non-blocking in pickling based on the gevent-specific mp context setting. Probably both.

**Comment by arcivanov** [comment]
Curious finding while testing: https://bugs.python.org/issue33196

**Comment by arcivanov** [comment]
@mdomans FYI `celery` isn't using Python multiprocessing but a fork thereof called `billiard`, so fixing MP support in Python won't help wrt Celery at all, unless we specifically apply the same patches for billiard as well.

**Comment by arcivanov** [comment]
All spawn contexts work in Python 3.6.4. Queues (and respectively Connections) can now be passed to children. Socket reduction/passing wasn't tested and will probably fail but easily rectified with additional reduction/module substitution magic.

**Comment by arcivanov** [comment]
This should be closed. Per discussion in gevent/gevent#1158 the work has been moved to https://github.com/karellen/geventmp
